import { ClientEvent } from '@public/shared/event/client';

import { Job, JobPermission, JobPermissionData, JobType } from '../job';
import { BoxZone } from '../polyzone/box.zone';

const BasePermissions: Partial<Record<JobPermission, JobPermissionData>> = {
    [JobPermission.Enrollment]: { label: 'Gestion des recrutements' },
    [JobPermission.ManageGrade]: { label: 'Gestion des grades' },
    [JobPermission.SocietyBankAccount]: { label: 'Accès au compte société' },
    [JobPermission.SocietyBankInvoices]: { label: 'Accès aux outils de facturation société' },
    [JobPermission.SocietyPrivateStorage]: { label: 'Accès au stockage patron' },
    [JobPermission.SocietyGeneralStorage]: { label: 'Accès aux stockages standards' },
    [JobPermission.SocietyMoneyStorage]: { label: 'Accès au coffre-fort de société' },
    [JobPermission.SocietyDealershipVehicle]: { label: 'Accès aux concessionnaires de véhicules' },
    [JobPermission.SocietyTakeOutPound]: { label: 'Sortir les véhicules de la fourrière' },
    [JobPermission.SocietyPublicGarage]: {
        label: 'Ranger/sortir les véhicules des garages publics',
    },
    [JobPermission.SocietyPrivateGarage]: {
        label: 'Ranger/sortir les véhicules des garages privés',
    },
    [JobPermission.SocietyPublicPort]: { label: 'Ranger/sortir les véhicules des ports publics' },
    [JobPermission.SocietyPrivatePort]: { label: 'Ranger/sortir les véhicules des ports privés' },
    [JobPermission.SocietyShop]: { label: 'Accès aux magasins de société' },
    [JobPermission.OnDutyView]: { label: 'Voir les employé(e)s en service' },
    [JobPermission.SocietyViewCompanyPanel]: { label: 'Accès au panel patron' },
};

export const JobRegistry: Record<JobType, Omit<Job, 'id'>> = {
    [JobType.Unemployed]: {
        label: 'Sans emploi',
        permissions: {},
        canReceiveSocietyInvoice: false,
    },
    [JobType.Adsl]: {
        label: 'ADSL',
        platePrefix: 'ADSL',
        permissions: {},
        canReceiveSocietyInvoice: false,
    },
    [JobType.Delivery]: {
        label: 'Fougère Prime',
        platePrefix: 'FOUG',
        permissions: {},
        canReceiveSocietyInvoice: false,
    },
    [JobType.Religious]: {
        label: 'InfoChat',
        platePrefix: 'INFO',
        permissions: {},
        canReceiveSocietyInvoice: false,
    },
    [JobType.Scrapper]: {
        label: 'OldMetal',
        platePrefix: 'OMC',
        permissions: {},
        canReceiveSocietyInvoice: false,
    },
    [JobType.FBI]: {
        label: 'Federal Bureau of Investigation',
        platePrefix: 'FBI ',
        menuCallback: ClientEvent.JOBS_POLICE_OPEN_SOCIETY_MENU,
        permissions: {
            [JobPermission.SocietyDealershipVehicle]: { label: 'Accès aux concessionnaires de véhicules' },
        },
        phone: '555-FBI',
        canReceiveSocietyInvoice: true,
    },
    [JobType.LSPD]: {
        label: 'Los Santos Police Department',
        platePrefix: 'LSPD',
        menuCallback: ClientEvent.JOBS_POLICE_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.CriminalRecord]: { label: 'Accès aux casiers judiciaires' },
            [JobPermission.VehicleRegistrar]: { label: 'Accès au registre des véhicules' },
            [JobPermission.VehicleTransfert]: { label: 'Accès aux transferts de véhicules' },
            [JobPermission.Investigation]: { label: 'Accès aux enquêtes' },
            [JobPermission.ManageInvestigation]: { label: 'Gérer les enquêtes' },
            [JobPermission.AssignCertification]: { label: 'Assigner des certifications aux agents' },
            [JobPermission.ManageCertification]: { label: 'Gérer les certifications' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos/matricules dans les effectifs panel' },
            [JobPermission.FDOFedPound]: { label: 'Mise en fourrière fédérale' },
        },
        bossZones: [
            {
                center: [626.23, -24.0, 90.51],
                length: 16.2,
                width: 16.4,
                heading: 340,
                minZ: 89.51,
                maxZ: 92.51,
            },
        ],
        phone: '555-LSPD',
        canReceiveSocietyInvoice: true,
    },
    [JobType.BCSO]: {
        label: 'Blaine County Sheriff Office',
        platePrefix: 'BCSO',
        menuCallback: ClientEvent.JOBS_POLICE_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.CriminalRecord]: { label: 'Accès aux casiers judiciaires' },
            [JobPermission.VehicleRegistrar]: { label: 'Accès au registre des véhicules' },
            [JobPermission.VehicleTransfert]: { label: 'Accès aux transferts de véhicules' },
            [JobPermission.Investigation]: { label: 'Accès aux enquêtes' },
            [JobPermission.ManageInvestigation]: { label: 'Gérer les enquêtes' },
            [JobPermission.AssignCertification]: { label: 'Assigner des certifications aux agents' },
            [JobPermission.ManageCertification]: { label: 'Gérer les certifications' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos/matricules dans les effectifs panel' },
            [JobPermission.FDOFedPound]: { label: 'Mise en fourrière fédérale' },
        },
        bossZones: [
            {
                center: [1855.38, 3689.22, 38.07],
                length: 3.8,
                width: 6.8,
                heading: 30,
                minZ: 37.07,
                maxZ: 41.01,
            },
        ],
        phone: '555-BCSO',
        canReceiveSocietyInvoice: true,
    },
    [JobType.LSCS]: {
        label: 'Los Santos County Sheriff',
        platePrefix: 'LSCS',
        menuCallback: 'soz-jobs:client:police:OpenSocietyMenu',
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.CriminalRecord]: { label: 'Accès aux casiers judiciaires' },
            [JobPermission.VehicleRegistrar]: { label: 'Accès au registre des véhicules' },
            [JobPermission.VehicleTransfert]: { label: 'Accès aux transferts de véhicules' },
            [JobPermission.Investigation]: { label: 'Accès aux enquêtes' },
            [JobPermission.ManageInvestigation]: { label: 'Gérer les enquêtes' },
            [JobPermission.AssignCertification]: { label: 'Assigner des certifications aux agents' },
            [JobPermission.ManageCertification]: { label: 'Gérer les certifications' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos/matricules dans les effectifs panel' },
            [JobPermission.FDOFedPound]: { label: 'Mise en fourrière fédérale' },
        },
        bossZones: [
            {
                center: [447.71, -977.18, 30.69],
                length: 12.4,
                width: 10.0,
                heading: 89.94,
                minZ: 29.69,
                maxZ: 31.69,
            },
        ],
        phone: '555-LCCS',
        canReceiveSocietyInvoice: true,
    },
    [JobType.LSMC]: {
        label: 'Los Santos Medical Center',
        platePrefix: 'LSMC',
        menuCallback: ClientEvent.JOBS_LSMC_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.ManageRoster]: { label: 'Gérer les photos/matricules dans les effectifs panel' },
            [JobPermission.AssignCertification]: { label: 'Assigner des certifications aux médecins' },
            [JobPermission.ManageCertification]: { label: 'Gérer les certifications' },
            [JobPermission.MedicalPatientAccess]: { label: 'Accéder aux dossiers patients panel' },
            [JobPermission.MedicalPatientEdit]: { label: 'Editer les dossiers patients panel' },
            [JobPermission.MedicalPatientDelete]: { label: 'Supprimer les dossiers patients panel' },
            [JobPermission.MedicalPatientHistoryAccess]: { label: 'Accéder à la liste des interventions panel' },
            [JobPermission.MedicalPatientHistoryEdit]: { label: 'Créer / Editer une intervention panel' },
            [JobPermission.MedicalPatientHistoryDelete]: { label: 'Supprimer une intervention panel' },
        },
        bossZones: [
            new BoxZone([383.87, -1411.63, 37.99], 21.0, 25.6, {
                heading: 50.09,
                minZ: 36.99,
                maxZ: 38.99,
            }),
        ],
        phone: '555-LSMC',
        canReceiveSocietyInvoice: true,
    },
    [JobType.Taxi]: {
        label: 'Carl Jr Services',
        platePrefix: 'CARL',
        menuCallback: ClientEvent.JOBS_TAXI_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        bossZones: [
            {
                center: [907.35, -152.04, 74.17],
                length: 8.4,
                width: 4.2,
                heading: 58,
                minZ: 73.17,
                maxZ: 77.17,
            },
        ],
        phone: '555-CARLJR',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['taxi', 'safe_taxi'],
    },
    [JobType.Food]: {
        label: 'Château Marius',
        platePrefix: 'CHAT',
        menuCallback: ClientEvent.JOBS_FOOD_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.Harvest]: { label: 'Récolter des ingrédients' },
            [JobPermission.Craft]: { label: 'Cuisiner' },
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        resell: {
            coords: [-57.01, -2448.4, 7.24, 145.77],
            ZoneName: 'Resell:LSPort:Food',
            SourceAccount: 'farm_food',
            TargetAccount: 'safe_food',
        },
        bossZones: [
            {
                center: [-1874.49, 2055.03, 154.49],
                length: 6.0,
                width: 5.8,
                heading: 159.29,
                minZ: 153.49,
                maxZ: 155.49,
            },
        ],
        phone: '555-MARIUS',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['food', 'safe_food'],
    },
    [JobType.News]: {
        label: 'Twitch News',
        platePrefix: 'NEWS',
        menuCallback: ClientEvent.JOBS_TWITCH_NEWS_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.NewsManageArticle]: { label: 'Gérer les articles sur le panel' },
            [JobPermission.NewsManageBillboards]: { label: 'Gérer les panneaux sur le panel' },
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        bossZones: [
            {
                center: [-576.17, -937.34, 28.82],
                length: 5.8,
                width: 10.8,
                heading: 0,
                minZ: 27.82,
                maxZ: 31.82,
            },
        ],
        phone: '555-NEWS',
        canReceiveSocietyInvoice: true,
    },
    [JobType.YouNews]: {
        label: 'You News',
        platePrefix: 'YOUN',
        menuCallback: ClientEvent.JOBS_YOU_NEWS_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.NewsManageArticle]: { label: 'Gérer les articles sur le panel' },
            [JobPermission.NewsManageBillboards]: { label: 'Gérer les panneaux sur le panel' },
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        bossZones: [
            { center: [-1054.43, -232.09, 44.02], length: 6.2, width: 5.8, heading: 116.65, minZ: 43.02, maxZ: 45.02 },
        ],
        phone: '555-YOUN',
        canReceiveSocietyInvoice: true,
    },
    [JobType.Garbage]: {
        label: 'BlueBird',
        platePrefix: 'BLUE',
        menuCallback: ClientEvent.JOBS_GARBAGE_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
        },
        bossZones: [
            {
                center: [-620.23, -1620.86, 33.01],
                length: 8.0,
                width: 11.8,
                heading: 355,
                minZ: 32.01,
                maxZ: 36.01,
            },
        ],
        phone: '555-BLUEBIRD',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['garbage', 'safe_garbage'],
    },
    [JobType.Oil]: {
        label: 'Michel Transport Petrol',
        platePrefix: 'MITP',
        menuCallback: ClientEvent.JOBS_OIL_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.FuelerChangePrice]: { label: 'Changer le prix des stations publiques' },
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        bossZones: [
            {
                center: [-242.74, 6070.52, 40.61],
                length: 13.4,
                width: 4.6,
                heading: 315,
                minZ: 39.61,
                maxZ: 42.61,
            },
        ],
        phone: '555-MTP',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['oil', 'safe_oil'],
    },
    [JobType.CashTransfer]: {
        label: 'STONK Security',
        platePrefix: 'STNK',
        menuCallback: ClientEvent.JOBS_STONK_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.CashTransfer_CollectSecure]: { label: 'Collecte des containers sécurisés' },
            [JobPermission.CashTransfer_CollectBags]: { label: "Collecte sacs d'argent" },
            [JobPermission.CashTransfer_ResaleBags]: { label: "Déposer sacs d'argent" },
            [JobPermission.CashTransfer_FillIn]: { label: 'Remplir banque / ATM' },
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        bossZones: [
            {
                center: [-17.97, -705.88, 46.02],
                length: 7.8,
                width: 4.4,
                heading: 25,
                minZ: 45.02,
                maxZ: 49.02,
            },
        ],
        phone: '555-STONK',
        canReceiveSocietyInvoice: true,
    },
    [JobType.Bennys]: {
        label: 'New Gahray',
        platePrefix: 'NEWG',
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.BennysEstimate]: { label: 'Estimer les véhicules' },
            [JobPermission.Order]: { label: "Commander un véhicule d'essai" },
            [JobPermission.BennysResell]: { label: 'Revendre un véhicule' },
            [JobPermission.BennysPitStopPrice]: { label: 'Changer le prix du Pit Stop' },
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        bossZones: [
            {
                center: [-204.51, -1336.96, 34.89],
                length: 15.8,
                width: 3.4,
                heading: 0,
                minZ: 33.89,
                maxZ: 37.89,
            },
            new BoxZone([1908.1, 3086.76, 51.75], 18.4, 9.2, {
                heading: 61.21,
                minZ: 50.75,
                maxZ: 52.75,
            }),
        ],
        phone: '555-NEWGAHRAY',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['bennys', 'safe_bennys'],
    },
    [JobType.Upw]: {
        label: 'Unexpected Power & Water',
        platePrefix: 'UPW',
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.Order]: { label: 'Commander des véhicules éléctriques' },
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        bossZones: [
            {
                center: [604.3, 2765.85, 47.76],
                length: 11.2,
                width: 11.8,
                heading: 4,
                minZ: 46.76,
                maxZ: 50.76,
            },
        ],
        phone: '555-UPW',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['upw', 'safe_upw'],
    },
    [JobType.Pawl]: {
        label: 'Pipe And Wooden Leg',
        platePrefix: 'PAWL',
        menuCallback: 'pawl:client:OpenSocietyMenu',
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        resell: {
            primary: {
                coords: [-272.22, -2496.57, 7.3, 186.72],
                ZoneName: 'Resell:LSPort:Pawl',
                SourceAccount: 'farm_pawl',
                TargetAccount: 'safe_pawl',
            },
            secondary: { ZoneName: 'Resell:Zkea', SourceAccount: 'farm_pawl', TargetAccount: 'safe_pawl' },
        },
        bossZones: [
            {
                center: [-539.85, 5300.99, 76.37],
                length: 9.4,
                width: 10.8,
                heading: 341,
                minZ: 75.37,
                maxZ: 79.37,
            },
        ],
        phone: '555-PAWL',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['pawl', 'safe_pawl'],
    },
    [JobType.Baun]: {
        label: 'Bahama Unicorn',
        platePrefix: 'BAUN',
        menuCallback: ClientEvent.JOBS_BAUN_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.Harvest]: { label: 'Récolter des ingrédients' },
            [JobPermission.Restock]: { label: 'Réapprovisionner le matériel' },
            [JobPermission.Craft]: { label: 'Fabriquer un cocktail' },
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        bossZones: [
            {
                center: [96.11, -1292.08, 29.27],
                length: 7.2,
                width: 6.2,
                heading: 300,
                minZ: 28.27,
                maxZ: 32.27,
            },
            {
                center: [-1387.87, -631.19, 30.81],
                length: 5.4,
                width: 6.4,
                heading: 303,
                minZ: 29.81,
                maxZ: 33.81,
            },
        ],
        phone: '555-BAUN',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['baun', 'safe_baun'],
    },
    [JobType.Ffs]: {
        label: 'Fight For Style',
        platePrefix: 'FFS',
        menuCallback: ClientEvent.JOBS_FFS_OPEN_SOCIETY_MENU,
        canInvoice: true,
        permissions: {
            ...BasePermissions,
            [JobPermission.Harvest]: { label: 'Récolter des matériaux' },
            [JobPermission.Restock]: { label: "Réapprovisionner l'atelier" },
            [JobPermission.Craft]: { label: 'Coudre un vêtement' },
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        bossZones: [
            {
                center: [706.83, -965.59, 30.41],
                length: 6.0,
                width: 6.0,
                heading: 0,
                minZ: 29.41,
                maxZ: 33.41,
            },
        ],
        phone: '555-FFS',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['ffs', 'safe_ffs'],
    },
    [JobType.MDR]: {
        label: 'Mandatory',
        platePrefix: 'MDR',
        menuCallback: ClientEvent.JOBS_MDR_OPEN_SOCIETY_MENU,
        permissions: {
            ...BasePermissions,
            [JobPermission.VehicleRegistrar]: { label: 'Accès aux registre des véhicules' },
            [JobPermission.Investigation]: { label: 'Accès aux enquêtes' },
            [JobPermission.ManageInvestigation]: { label: 'Gérer les enquêtes' },
            [JobPermission.MdrViewCitizenData]: { label: 'Accès aux casiers judiciaires' },
            [JobPermission.InvestigationLawyer]: { label: 'Avocat dans les enquêtes' },
            [JobPermission.InvestigationProsecutor]: { label: 'Prosecutor dans les enquètes' },
            [JobPermission.MdrViewOtherJobs]: { label: 'Accès aux infos des entreprises' },
            [JobPermission.MdrMarkedMoneyCleaning]: { label: 'Accès à la réhabilitation des billets' },
        },
        bossZones: [
            {
                center: [-546.36, -201.78, 47.66],
                length: 8.0,
                width: 17.0,
                heading: 30.0,
                minZ: 46.66,
                maxZ: 49.66,
            },
        ],
        canInvoice: true,
        phone: '555-MDR',
        canReceiveSocietyInvoice: true,
    },
    [JobType.Gouv]: {
        label: 'Gouvernement',
        platePrefix: 'GOUV',
        menuCallback: ClientEvent.JOBS_GOUV_OPEN_SOCIETY_MENU,
        permissions: {
            ...BasePermissions,
            [JobPermission.GouvUpdateTax]: { label: 'Mettre à jour les taxes' },
            [JobPermission.GouvManageRadar]: { label: 'Permet de gérer les radars' },
            [JobPermission.GouvManageFine]: { label: 'Ajouter, mettre à jour et supprimer les amendes' },
            [JobPermission.VehicleRegistrar]: { label: 'Accès au registre des véhicules sur le panel' },
            [JobPermission.VehicleTransfert]: { label: 'Accès aux transferts de véhicules sur le panel' },
            [JobPermission.MdrViewCitizenData]: { label: 'Accès aux casiers judiciaires' },
        },
        bossZones: [
            {
                center: [-526.8, -597.0, 34.68],
                length: 8.8,
                width: 17.6,
                heading: 90.0,
                minZ: 33.68,
                maxZ: 35.68,
            },
        ],
        canInvoice: true,
        phone: '555-GOUV',
        canReceiveSocietyInvoice: true,
    },
    [JobType.SASP]: {
        label: 'San Andreas State Police',
        platePrefix: 'SASP',
        menuCallback: ClientEvent.JOBS_POLICE_OPEN_SOCIETY_MENU,
        permissions: {
            ...BasePermissions,
            [JobPermission.CriminalRecord]: { label: 'Accès aux casiers judiciaires' },
            [JobPermission.VehicleRegistrar]: { label: 'Accès au registre des véhicules' },
            [JobPermission.VehicleTransfert]: { label: 'Accès aux transferts de véhicules' },
            [JobPermission.Investigation]: { label: 'Accès aux enquêtes' },
            [JobPermission.ManageInvestigation]: { label: 'Gérer les enquêtes' },
            [JobPermission.AssignCertification]: { label: 'Assigner des certifications aux agents' },
            [JobPermission.ManageCertification]: { label: 'Gérer les certifications' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos/matricules dans les effectifs panel' },
            [JobPermission.FDOFedPound]: { label: 'Mise en fourrière fédérale' },
        },
        bossZones: [
            {
                center: [-584.16, -593.97, 34.68],
                length: 8.4,
                width: 11.6,
                heading: 90.0,
                minZ: 33.68,
                maxZ: 35.68,
            },
        ],
        canInvoice: true,
        phone: '555-SASP',
        canReceiveSocietyInvoice: true,
    },
    [JobType.FDF]: {
        label: 'Ferme de Fou',
        platePrefix: 'FDF',
        menuCallback: ClientEvent.JOBS_FDF_OPEN_SOCIETY_MENU,
        permissions: {
            ...BasePermissions,
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        bossZones: [
            {
                center: [2443.96, 4974.61, 47.39],
                length: 23.2,
                width: 47.8,
                heading: 226.09,
                minZ: 44.39,
                maxZ: 55.39,
            },
        ],
        canInvoice: true,
        phone: '555-FDF',
        canReceiveSocietyInvoice: true,
        taxCollectAccounts: ['fdf', 'safe_fdf'],
    },
    [JobType.DMC]: {
        label: 'DeMetal Company',
        platePrefix: 'DMC',
        menuCallback: ClientEvent.JOBS_DMC_OPEN_SOCIETY_MENU,
        permissions: {
            ...BasePermissions,
            [JobPermission.NewCompanyPanelAccess]: { label: 'Accès au panel entreprise' },
            [JobPermission.EmployeesListRead]: { label: 'Accès aux données employés sur le panel entreprise' },
            [JobPermission.EmployeesListWrite]: { label: 'Editer les données employés sur le panel entreprise' },
            [JobPermission.PricingRead]: { label: 'Accès aux devis sur le panel entreprise' },
            [JobPermission.PricingManage]: { label: 'Gestion des données des devis sur le panel entreprise' },
            [JobPermission.ReadDocumentation]: { label: 'Lecture de la documentation sur le panel entreprise' },
            [JobPermission.WriteDocumentation]: { label: 'Edition de la documentation sur le panel entreprise' },
            [JobPermission.ManageDocumentation]: { label: 'Gestion de la documentation sur le panel entreprise' },
            [JobPermission.AssignCertification]: { label: 'Assigner des formations sur le panel' },
            [JobPermission.ManageCertification]: { label: 'Gérer les formations sur le panel' },
            [JobPermission.ManageRoster]: { label: 'Gérer les photos dans les effectifs panel' },
        },
        bossZones: [
            {
                center: [1077.99, -1979.487, 31.37],
                length: 7.8,
                width: 4.2,
                heading: 235.7,
                minZ: 30.37,
                maxZ: 32.97,
            },
        ],
        canInvoice: true,
        phone: '555-DMC',
        canReceiveSocietyInvoice: true,
        resell: {
            primary: {
                //coords: [-132.7, -2383.92, 6.0, 174.18],
                coords: [-334.31, -1314.83, 31.4, 87.04],
                ZoneName: 'Resell:LSPort:Dmc',
                SourceAccount: 'farm_dmc',
                TargetAccount: 'safe_dmc',
            },
            secondary: { ZoneName: 'Resell:LSCustom', SourceAccount: 'farm_dmc', TargetAccount: 'safe_dmc' },
        },
        taxCollectAccounts: ['dmc', 'safe_dmc'],
    },
};
