import { WardrobeConfig } from '../cloth';

export const NewsCloakroom: WardrobeConfig = {
    [GetHashKey('mp_m_freemode_01')]: {
        ['Tenue habillée']: {
            Components: {
                [3]: { Drawable: 1, Texture: 0, Palette: 0 },
                [4]: { Drawable: 24, Texture: 5, Palette: 0 },
                [6]: { Drawable: 104, Texture: 1, Palette: 0 },
                [7]: { Drawable: 22, Texture: 8, Palette: 0 },
                [8]: { Drawable: 26, Texture: 2, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 23, Texture: 3, Palette: 0 },
            },
            Props: {},
        },
        ['Tenue formelle']: {
            Components: {
                [3]: { Drawable: 11, Texture: 0, Palette: 0 },
                [4]: { Drawable: 22, Texture: 2, Palette: 0 },
                [6]: { Drawable: 104, Texture: 1, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 0, Texture: 20, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 95, Texture: 1, Palette: 0 },
            },
            Props: {},
        },
        ['Tenue terrain']: {
            Components: {
                [3]: { Drawable: 11, Texture: 0, Palette: 0 },
                [4]: { Drawable: 0, Texture: 12, Palette: 0 },
                [6]: { Drawable: 22, Texture: 4, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 9, Texture: 7, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 338, Texture: 2, Palette: 0 },
            },
            Props: {},
        },
        ['Tenue décontractée']: {
            Components: {
                [3]: { Drawable: 11, Texture: 0, Palette: 0 },
                [4]: { Drawable: 15, Texture: 8, Palette: 0 },
                [6]: { Drawable: 1, Texture: 0, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 0, Texture: 2, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 346, Texture: 4, Palette: 0 },
            },
            Props: {},
        },
        ['Tenue hélico']: {
            Components: {
                [3]: { Drawable: 17, Texture: 0, Palette: 0 },
                [4]: { Drawable: 41, Texture: 0, Palette: 0 },
                [6]: { Drawable: 25, Texture: 0, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 15, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 54, Texture: 0, Palette: 0 },
            },
            Props: { [0]: { Drawable: 19, Texture: 0, Palette: 0 } },
        },
    },
    [GetHashKey('mp_f_freemode_01')]: {
        ['Tenue habillée']: {
            Components: {
                [3]: { Drawable: 5, Texture: 0, Palette: 0 },
                [4]: { Drawable: 133, Texture: 3, Palette: 0 },
                [6]: { Drawable: 108, Texture: 1, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 23, Texture: 4, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 24, Texture: 0, Palette: 0 },
            },
            Props: {},
        },
        ['Tenue formelle']: {
            Components: {
                [3]: { Drawable: 9, Texture: 0, Palette: 0 },
                [4]: { Drawable: 34, Texture: 0, Palette: 0 },
                [6]: { Drawable: 108, Texture: 1, Palette: 0 },
                [7]: { Drawable: 22, Texture: 4, Palette: 0 },
                [8]: { Drawable: 7, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 333, Texture: 0, Palette: 0 },
            },
            Props: {},
        },
        ['Tenue décontractée']: {
            Components: {
                [3]: { Drawable: 0, Texture: 0, Palette: 0 },
                [4]: { Drawable: 153, Texture: 0, Palette: 0 },
                [6]: { Drawable: 3, Texture: 4, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 15, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 428, Texture: 24, Palette: 0 },
            },
            Props: {},
        },
        ['Tenue terrain']: {
            Components: {
                [3]: { Drawable: 9, Texture: 0, Palette: 0 },
                [4]: { Drawable: 0, Texture: 0, Palette: 0 },
                [6]: { Drawable: 103, Texture: 1, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 151, Texture: 11, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 8, Texture: 2, Palette: 0 },
            },
            Props: {},
        },
        ['Tenue hélico']: {
            Components: {
                [3]: { Drawable: 18, Texture: 0, Palette: 0 },
                [4]: { Drawable: 42, Texture: 0, Palette: 0 },
                [6]: { Drawable: 25, Texture: 0, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 15, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 47, Texture: 0, Palette: 0 },
            },
            Props: { [0]: { Drawable: 19, Texture: 0, Palette: 0 } },
        },
    },
};
