import { WardrobeConfig } from '../cloth';

export const NewsCloakroom: WardrobeConfig = {
    [GetHashKey('mp_m_freemode_01')]: {
        ['Costume Talk Show']: {
            Components: {
                [3]: { Drawable: 1, Texture: 0, Palette: 0 },
                [4]: { Drawable: 10, Texture: 1, Palette: 0 },
                [6]: { Drawable: 10, Texture: 0, Palette: 0 },
                [7]: { Drawable: 38, Texture: 4, Palette: 0 },
                [8]: { Drawable: 31, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 99, Texture: 1, Palette: 0 },
            },
            Props: {},
        },
        ['Costume Terrain']: {
            Components: {
                [3]: { Drawable: 11, Texture: 0, Palette: 0 },
                [4]: { Drawable: 22, Texture: 2, Palette: 0 },
                [6]: { Drawable: 1, Texture: 0, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 0, Texture: 20, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 348, Texture: 0, Palette: 0 },
            },
            Props: {},
        },
        ["Costume Terrain d'été"]: {
            Components: {
                [3]: { Drawable: 11, Texture: 0, Palette: 0 },
                [4]: { Drawable: 15, Texture: 8, Palette: 0 },
                [6]: { Drawable: 1, Texture: 0, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 0, Texture: 20, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 234, Texture: 4, Palette: 0 },
            },
            Props: {},
        },
        ["Costume Terrain d'hiver"]: {
            Components: {
                [3]: { Drawable: 22, Texture: 0, Palette: 0 },
                [4]: { Drawable: 20, Texture: 0, Palette: 0 },
                [6]: { Drawable: 10, Texture: 0, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 15, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 139, Texture: 6, Palette: 0 },
            },
            Props: {},
        },
        ['Costume Hélico']: {
            Components: {
                [3]: { Drawable: 17, Texture: 0, Palette: 0 },
                [4]: { Drawable: 41, Texture: 0, Palette: 0 },
                [6]: { Drawable: 25, Texture: 0, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 15, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 54, Texture: 0, Palette: 0 },
            },
            Props: { [0]: { Clear: true } },
        },
    },
    [GetHashKey('mp_f_freemode_01')]: {
        ['Costume Talk Show']: {
            Components: {
                [3]: { Drawable: 6, Texture: 0, Palette: 0 },
                [4]: { Drawable: 133, Texture: 5, Palette: 0 },
                [6]: { Drawable: 42, Texture: 2, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 215, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 25, Texture: 5, Palette: 0 },
            },
            Props: {},
        },
        ['Costume Terrain']: {
            Components: {
                [3]: { Drawable: 9, Texture: 0, Palette: 0 },
                [4]: { Drawable: 0, Texture: 0, Palette: 0 },
                [6]: { Drawable: 103, Texture: 1, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 151, Texture: 11, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 8, Texture: 2, Palette: 0 },
            },
            Props: {},
        },
        ["Costume Terrain d'été"]: {
            Components: {
                [3]: { Drawable: 15, Texture: 0, Palette: 0 },
                [4]: { Drawable: 14, Texture: 8, Palette: 0 },
                [6]: { Drawable: 0, Texture: 2, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 15, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 26, Texture: 4, Palette: 0 },
            },
            Props: {},
        },
        ["Costume Terrain d'hiver"]: {
            Components: {
                [3]: { Drawable: 23, Texture: 0, Palette: 0 },
                [4]: { Drawable: 133, Texture: 3, Palette: 0 },
                [6]: { Drawable: 29, Texture: 0, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 14, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 136, Texture: 6, Palette: 0 },
            },
            Props: {},
        },
        ['Costume Hélico']: {
            Components: {
                [3]: { Drawable: 18, Texture: 0, Palette: 0 },
                [4]: { Drawable: 42, Texture: 0, Palette: 0 },
                [6]: { Drawable: 25, Texture: 0, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 15, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 47, Texture: 0, Palette: 0 },
            },
            Props: { [0]: { Clear: true } },
        },
    },
};
