import { WardrobeConfig } from '../cloth';

export const OilCloakroom: WardrobeConfig = {
    [GetHashKey('mp_m_freemode_01')]: {
        ["Tenue de pompiste d'été"]: {
            Components: {
                [3]: { Drawable: 21, Texture: 0, Palette: 0 },
                [4]: { Drawable: 98, Texture: 16, Palette: 0 },
                [5]: { Drawable: 86, Texture: 18, Palette: 0 },
                [6]: { Drawable: 71, Texture: 16, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 15, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 247, Texture: 15, Palette: 0 },
            },
            Props: {},
        },
        ["Tenue de pompiste d'hiver"]: {
            Components: {
                [3]: { Drawable: 24, Texture: 0, Palette: 0 },
                [4]: { Drawable: 98, Texture: 16, Palette: 0 },
                [5]: { Drawable: 86, Texture: 18, Palette: 0 },
                [6]: { Drawable: 71, Texture: 16, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 44, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 244, Texture: 18, Palette: 0 },
            },
            Props: {},
        },
        ["Tenue de responsable d'été"]: {
            Components: {
                [3]: { Drawable: 19, Texture: 0, Palette: 0 },
                [4]: { Drawable: 97, Texture: 16, Palette: 0 },
                [5]: { Drawable: 86, Texture: 18, Palette: 0 },
                [6]: { Drawable: 70, Texture: 16, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 15, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 345, Texture: 0, Palette: 0 },
            },
            Props: {},
        },
        ["Tenue de responsable d'hiver"]: {
            Components: {
                [3]: { Drawable: 20, Texture: 0, Palette: 0 },
                [4]: { Drawable: 97, Texture: 16, Palette: 0 },
                [5]: { Drawable: 86, Texture: 18, Palette: 0 },
                [6]: { Drawable: 70, Texture: 16, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 44, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 251, Texture: 16, Palette: 0 },
            },
            Props: {},
        },
    },
    [GetHashKey('mp_f_freemode_01')]: {
        ["Tenue de pompiste d'été"]: {
            Components: {
                [3]: { Drawable: 24, Texture: 0, Palette: 0 },
                [4]: { Drawable: 101, Texture: 16, Palette: 0 },
                [5]: { Drawable: 86, Texture: 18, Palette: 0 },
                [6]: { Drawable: 74, Texture: 16, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 0, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 255, Texture: 15, Palette: 0 },
            },
            Props: {},
        },
        ["Tenue de pompiste d'hiver"]: {
            Components: {
                [3]: { Drawable: 21, Texture: 0, Palette: 0 },
                [4]: { Drawable: 101, Texture: 16, Palette: 0 },
                [5]: { Drawable: 86, Texture: 18, Palette: 0 },
                [6]: { Drawable: 74, Texture: 16, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 0, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 252, Texture: 18, Palette: 0 },
            },
            Props: {},
        },
        ["Tenue de responsable d'été"]: {
            Components: {
                [3]: { Drawable: 31, Texture: 0, Palette: 0 },
                [4]: { Drawable: 100, Texture: 16, Palette: 0 },
                [5]: { Drawable: 86, Texture: 18, Palette: 0 },
                [6]: { Drawable: 75, Texture: 18, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 0, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 141, Texture: 2, Palette: 0 },
            },
            Props: {},
        },
        ["Tenue de responsable d'hiver"]: {
            Components: {
                [3]: { Drawable: 23, Texture: 0, Palette: 0 },
                [4]: { Drawable: 100, Texture: 16, Palette: 0 },
                [5]: { Drawable: 86, Texture: 18, Palette: 0 },
                [6]: { Drawable: 75, Texture: 18, Palette: 0 },
                [7]: { Drawable: 0, Texture: 0, Palette: 0 },
                [8]: { Drawable: 0, Texture: 0, Palette: 0 },
                [9]: { Drawable: 0, Texture: 0, Palette: 0 },
                [10]: { Drawable: 0, Texture: 0, Palette: 0 },
                [11]: { Drawable: 259, Texture: 16, Palette: 0 },
            },
            Props: {},
        },
    },
};
