import { Component, Prop, WardrobeConfig } from '../cloth';

export const UpwCloakroom: WardrobeConfig = {
    [GetHashKey('mp_m_freemode_01')]: {
        ["Tenue d'apprenti pour été"]: {
            Components: {
                [Component.Torso]: { Palette: 0, Drawable: 41, Texture: 0 },
                [Component.Legs]: { Palette: 0, Drawable: 98, Texture: 19 },
                [Component.Shoes]: { Palette: 0, Drawable: 12, Texture: 5 },
                [Component.Accessories]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Undershirt]: { Palette: 0, Drawable: 15, Texture: 0 },
                [Component.BodyArmor]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Decals]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Tops]: { Palette: 0, Drawable: 146, Texture: 6 },
            },
            Props: { [Prop.Hat]: { Drawable: 145, Texture: 0, Palette: 0 } },
        },
        ["Tenue d'apprenti pour hiver"]: {
            Components: {
                [Component.Torso]: { Palette: 0, Drawable: 42, Texture: 0 },
                [Component.Legs]: { Palette: 0, Drawable: 98, Texture: 19 },
                [Component.Shoes]: { Palette: 0, Drawable: 12, Texture: 5 },
                [Component.Accessories]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Undershirt]: { Palette: 0, Drawable: 2, Texture: 2 },
                [Component.BodyArmor]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Decals]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Tops]: { Palette: 0, Drawable: 244, Texture: 4 },
            },
            Props: { [Prop.Hat]: { Drawable: 145, Texture: 0, Palette: 0 } },
        },
        ["Tenue d'électricien pour été"]: {
            Components: {
                [Component.Torso]: { Palette: 0, Drawable: 41, Texture: 0 },
                [Component.Legs]: { Palette: 0, Drawable: 98, Texture: 19 },
                [Component.Shoes]: { Palette: 0, Drawable: 12, Texture: 5 },
                [Component.Accessories]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Undershirt]: { Palette: 0, Drawable: 15, Texture: 0 },
                [Component.BodyArmor]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Decals]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Tops]: { Palette: 0, Drawable: 22, Texture: 1 },
            },
            Props: { [Prop.Hat]: { Drawable: 145, Texture: 1, Palette: 0 } },
        },
        ["Tenue d'électricien pour hiver"]: {
            Components: {
                [Component.Torso]: { Palette: 0, Drawable: 42, Texture: 0 },
                [Component.Legs]: { Palette: 0, Drawable: 98, Texture: 19 },
                [Component.Shoes]: { Palette: 0, Drawable: 12, Texture: 5 },
                [Component.Accessories]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Undershirt]: { Palette: 0, Drawable: 2, Texture: 2 },
                [Component.BodyArmor]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Decals]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Tops]: { Palette: 0, Drawable: 244, Texture: 6 },
            },
            Props: { [Prop.Hat]: { Drawable: 145, Texture: 1, Palette: 0 } },
        },
        ['Tenue de chef électricien pour été']: {
            Components: {
                [Component.Torso]: { Palette: 0, Drawable: 41, Texture: 0 },
                [Component.Legs]: { Palette: 0, Drawable: 98, Texture: 19 },
                [Component.Shoes]: { Palette: 0, Drawable: 12, Texture: 5 },
                [Component.Accessories]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Undershirt]: { Palette: 0, Drawable: 15, Texture: 0 },
                [Component.BodyArmor]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Decals]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Tops]: { Palette: 0, Drawable: 241, Texture: 2 },
            },
            Props: { [Prop.Hat]: { Drawable: 145, Texture: 2, Palette: 0 } },
        },
        ['Tenue de chef électricien pour hiver']: {
            Components: {
                [Component.Torso]: { Palette: 0, Drawable: 42, Texture: 0 },
                [Component.Legs]: { Palette: 0, Drawable: 98, Texture: 19 },
                [Component.Shoes]: { Palette: 0, Drawable: 12, Texture: 5 },
                [Component.Accessories]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Undershirt]: { Palette: 0, Drawable: 2, Texture: 2 },
                [Component.BodyArmor]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Decals]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Tops]: { Palette: 0, Drawable: 244, Texture: 7 },
            },
            Props: { [Prop.Hat]: { Drawable: 145, Texture: 2, Palette: 0 } },
        },
        ['Tenue de la Direction']: {
            Components: {
                [Component.Torso]: { Palette: 0, Drawable: 1, Texture: 0 },
                [Component.Legs]: { Palette: 0, Drawable: 25, Texture: 0 },
                [Component.Shoes]: { Palette: 0, Drawable: 56, Texture: 1 },
                [Component.Accessories]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Undershirt]: { Palette: 0, Drawable: 32, Texture: 0 },
                [Component.BodyArmor]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Decals]: { Palette: 0, Drawable: 0, Texture: 0 },
                [Component.Tops]: { Palette: 0, Drawable: 294, Texture: 7 },
            },
            Props: { [Prop.Hat]: { Drawable: 145, Texture: 3, Palette: 0 } },
        },
    },
    [GetHashKey('mp_f_freemode_01')]: {
        ["Tenue d'apprentie pour été"]: {
            Components: {
                [Component.Torso]: { Texture: 0, Palette: 0, Drawable: 57 },
                [Component.Legs]: { Texture: 19, Palette: 0, Drawable: 101 },
                [Component.Shoes]: { Texture: 2, Palette: 0, Drawable: 60 },
                [Component.Accessories]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Undershirt]: { Texture: 9, Palette: 0, Drawable: 101 },
                [Component.BodyArmor]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Decals]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Tops]: { Texture: 1, Palette: 0, Drawable: 141 },
            },
            Props: { [Prop.Hat]: { Drawable: 144, Texture: 0, Palette: 0 } },
        },
        ["Tenue d'apprentie pour hiver"]: {
            Components: {
                [Component.Torso]: { Texture: 0, Palette: 0, Drawable: 46 },
                [Component.Legs]: { Texture: 19, Palette: 0, Drawable: 101 },
                [Component.Shoes]: { Texture: 2, Palette: 0, Drawable: 60 },
                [Component.Accessories]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Undershirt]: { Texture: 5, Palette: 0, Drawable: 213 },
                [Component.BodyArmor]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Decals]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Tops]: { Texture: 4, Palette: 0, Drawable: 252 },
            },
            Props: { [Prop.Hat]: { Drawable: 144, Texture: 0, Palette: 0 } },
        },
        ["Tenue d'électricienne pour été"]: {
            Components: {
                [Component.Torso]: { Texture: 0, Palette: 0, Drawable: 57 },
                [Component.Legs]: { Texture: 19, Palette: 0, Drawable: 101 },
                [Component.Shoes]: { Texture: 2, Palette: 0, Drawable: 60 },
                [Component.Accessories]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Undershirt]: { Texture: 9, Palette: 0, Drawable: 101 },
                [Component.BodyArmor]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Decals]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Tops]: { Texture: 1, Palette: 0, Drawable: 286 },
            },
            Props: { [Prop.Hat]: { Drawable: 144, Texture: 1, Palette: 0 } },
        },
        ["Tenue d'électricienne pour hiver"]: {
            Components: {
                [Component.Torso]: { Texture: 0, Palette: 0, Drawable: 46 },
                [Component.Legs]: { Texture: 19, Palette: 0, Drawable: 101 },
                [Component.Shoes]: { Texture: 2, Palette: 0, Drawable: 60 },
                [Component.Accessories]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Undershirt]: { Texture: 5, Palette: 0, Drawable: 213 },
                [Component.BodyArmor]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Decals]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Tops]: { Texture: 6, Palette: 0, Drawable: 252 },
            },
            Props: { [Prop.Hat]: { Drawable: 144, Texture: 1, Palette: 0 } },
        },
        ['Tenue de cheffe électricienne pour été']: {
            Components: {
                [Component.Torso]: { Texture: 0, Palette: 0, Drawable: 57 },
                [Component.Legs]: { Texture: 19, Palette: 0, Drawable: 101 },
                [Component.Shoes]: { Texture: 2, Palette: 0, Drawable: 60 },
                [Component.Accessories]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Undershirt]: { Texture: 9, Palette: 0, Drawable: 101 },
                [Component.BodyArmor]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Decals]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Tops]: { Texture: 2, Palette: 0, Drawable: 249 },
            },
            Props: { [Prop.Hat]: { Drawable: 144, Texture: 2, Palette: 0 } },
        },
        ['Tenue de cheffe électricienne pour hiver']: {
            Components: {
                [Component.Torso]: { Texture: 0, Palette: 0, Drawable: 46 },
                [Component.Legs]: { Texture: 19, Palette: 0, Drawable: 101 },
                [Component.Shoes]: { Texture: 2, Palette: 0, Drawable: 60 },
                [Component.Accessories]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Undershirt]: { Texture: 5, Palette: 0, Drawable: 213 },
                [Component.BodyArmor]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Decals]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Tops]: { Texture: 7, Palette: 0, Drawable: 252 },
            },
            Props: { [Prop.Hat]: { Drawable: 144, Texture: 2, Palette: 0 } },
        },
        ['Tenue de la Direction']: {
            Components: {
                [Component.Torso]: { Texture: 0, Palette: 0, Drawable: 5 },
                [Component.Legs]: { Texture: 0, Palette: 0, Drawable: 133 },
                [Component.Shoes]: { Texture: 0, Palette: 0, Drawable: 27 },
                [Component.Accessories]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Undershirt]: { Texture: 6, Palette: 0, Drawable: 217 },
                [Component.BodyArmor]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Decals]: { Texture: 0, Palette: 0, Drawable: 0 },
                [Component.Tops]: { Texture: 2, Palette: 0, Drawable: 6 },
            },
            Props: { [Prop.Hat]: { Drawable: 144, Texture: 3, Palette: 0 } },
        },
    },
};
