import { Forecast } from '../../shared/weather';

export const SpringAutumn: Forecast = {
    EXTRASUNNY: { CLEARING: 15, OVERCAST: 15 },
    CLEAR: { CLEARING: 15, OVERCAST: 15, SMOG: 100, FOGGY: 100 },
    NEUTRAL: {},
    SMOG: { CLEARING: 15, OVERCAST: 15 },
    FOGGY: { CLEARING: 15, OVERCAST: 15 },
    OVERCAST: { CLEAR: 85, CLOUDS: 85, EXTRASUNNY: 85 },
    CLOUDS: { CLEARING: 15, OVERCAST: 15 },
    CLEARING: { CLEAR: 15, CLOUDS: 15, EXTRASUNNY: 15, THUNDER: 100, RAIN: 100 },
    RAIN: { CLEARING: 5, OVERCAST: 5 },
    THUNDER: {},
    SNOW: {},
    BLIZZARD: {},
    SNOWLIGHT: {},
    XMAS: {},
    HALLOWEEN: {},
    LIGHT_SNOW: {},
};

export const Winter: Forecast = {
    EXTRASUNNY: { CLEARING: 15, OVERCAST: 15 },
    CLEAR: { CLEARING: 15, OVERCAST: 15, SMOG: 100, FOGGY: 100 },
    NEUTRAL: {},
    SMOG: { CLEARING: 15, OVERCAST: 15 },
    FOGGY: { CLEARING: 15, OVERCAST: 15 },
    OVERCAST: { CLEAR: 85, CLOUDS: 85, EXTRASUNNY: 85, SNOW: 50 },
    CLOUDS: { CLEARING: 15, OVERCAST: 15 },
    CLEARING: { CLEAR: 15, CLOUDS: 15, EXTRASUNNY: 15, THUNDER: 100, RAIN: 100 },
    RAIN: { CLEARING: 5, OVERCAST: 5 },
    THUNDER: {},
    SNOW: { CLEARING: 5, OVERCAST: 5 },
    BLIZZARD: {},
    SNOWLIGHT: { CLEARING: 5, OVERCAST: 5 },
    XMAS: { SNOW: 100 },
    HALLOWEEN: {},
    LIGHT_SNOW: {},
};

export const Summer: Forecast = {
    EXTRASUNNY: { CLOUDS: 10, OVERCAST: 90 },
    CLEAR: {},
    NEUTRAL: {},
    SMOG: {},
    FOGGY: {},
    OVERCAST: { CLOUDS: 5, EXTRASUNNY: 95 },
    CLOUDS: { OVERCAST: 50, EXTRASUNNY: 50 },
    CLEARING: {},
    RAIN: {},
    THUNDER: {},
    SNOW: {},
    BLIZZARD: {},
    SNOWLIGHT: {},
    XMAS: {},
    HALLOWEEN: {},
    LIGHT_SNOW: {},
};

export const Polluted: Forecast = {
    EXTRASUNNY: { SMOG: 80, FOGGY: 20 },
    CLEAR: { SMOG: 80, FOGGY: 20 },
    NEUTRAL: { SMOG: 80, FOGGY: 20 },
    SMOG: { SMOG: 80, FOGGY: 20 },
    FOGGY: { SMOG: 80, FOGGY: 20 },
    OVERCAST: { SMOG: 80, FOGGY: 20 },
    CLOUDS: { SMOG: 80, FOGGY: 20 },
    CLEARING: { SMOG: 80, FOGGY: 20 },
    RAIN: { SMOG: 80, FOGGY: 20 },
    THUNDER: { SMOG: 80, FOGGY: 20 },
    SNOW: { SMOG: 80, FOGGY: 20 },
    BLIZZARD: { SMOG: 80, FOGGY: 20 },
    SNOWLIGHT: { SMOG: 80, FOGGY: 20 },
    XMAS: { SMOG: 80, FOGGY: 20 },
    HALLOWEEN: { SMOG: 80, FOGGY: 20 },
    LIGHT_SNOW: { SMOG: 80, FOGGY: 20 },
};
