fx_version "cerulean"
game "gta5"

data_file 'DLC_ITYP_REQUEST' 'stream/apa_int_mp_h_01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/apa_int_mp_h_04.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/apa_int_mp_h_05.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bkr_biker_dlc_int_01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/h4_dlc_int_04_h4.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/int_club.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/int_corporate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/int_industrial.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/int_medical.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/int_residential.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/int_services.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/m23_2_mp2023_02_dlc_int_5.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/m24_1_prop_m24_1_accs_02.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sf_dlc_int_01_sec.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/soz_assets_v_int_3.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/soz_assets_v_int_9.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/soz_assets_v_int_16.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/soz_assets_v_int_19.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/soz_assets_v_int_57.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/soz_assets_v_int_61.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/tr_dlc_int_01_tr.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vw_vwdlc_int_02.ytyp'