-- local function GetComponentDataFromHash(hash, type)
--    print(hash, type)
--
--    local blob = string.rep('\0\0\0\0\0\0\0\0', 9 + 16)
--    if not Citizen.InvokeNative(0x74C0E2A57EC66760, hash, blob) then
--        print("not working for " .. type)
--        return nil
--    end
--
--    -- adapted from: https://gist.github.com/root-cause/3b80234367b0c856d60bf5cb4b826f86
--    local lockHash = string.unpack('<i4', blob, 1)
--    local hash = string.unpack('<i4', blob, 9)
--    local locate = string.unpack('<i4', blob, 17)
--    local drawable = string.unpack('<i4', blob, 25)
--    local texture = string.unpack('<i4', blob, 33)
--    local field5 = string.unpack('<i4', blob, 41)
--    local component = string.unpack('<i4', blob, 49)
--    local field7 = string.unpack('<i4', blob, 57)
--    local field8 = string.unpack('<i4', blob, 65)
--    local gxt = string.unpack('c64', blob, 73)
--
--    --print(lockHash)
--    --print(hash)
--    --print(locate)
--    --print(drawable)
--    --print(texture)
--    --print(field5)
--    --print(component)
--    --print(field7)
--    --print(field8)
--    --print(gxt)
--
--    local label = GetLabelText(gxt)
--
--    print(label)
--
--    return component, drawable, texture, gxt, field5, field7, field8
-- end
-- local function TestComponent(ped, clothSkin)
--    local hash = GetHashNameForComponent(ped, ComponentType.Torso, clothSkin.Torso.Type, clothSkin.Torso.Variation)
--    local numForcedComponent = GetShopPedApparelForcedComponentCount(hash)
--
--    print("Hash : " .. hash)
--    print("Forced component : " .. numForcedComponent)
--
--    for i = 0, numForcedComponent - 1, 1 do
--        local nameHash, enumValue, componentType = GetForcedComponent(hash, i)
--        print("Forced component : ", i, nameHash, enumValue, componentType)
--
--        print(GetComponentDataFromHash(nameHash, componentType))
--    end
-- end
