export enum RpcServerEvent {
    ADMIN_GET_PLAYERS = 'soz-core:admin:get-players',
    ADMIN_GET_PLAYER_PET = 'soz-core:admin:get-player-pet',
    ADMIN_GET_JOB_PETS = 'soz-core:admin:get-job-pets',
    ADMIN_GET_CHARACTERS = 'soz-core:admin:get-characters',
    ADMIN_GET_FULL_PLAYERS = 'soz-core:admin:get-full-players',
    ADMIN_GET_LIGHT_PLAYERS = 'soz-core:admin:get-light-players',
    ADMIN_GET_VEHICLES = 'soz-core:admin:get-vehicles',
    ADMIN_IS_ALLOWED = 'soz-core:admin:is-allowed',
    ADMIN_GET_REPUTATION = 'soz-core:admin:get-reputation',
    ADMIN_MAPPER_SET_APARTMENT_PRICE = 'soz-core:admin:mapper:set-apartment-price',
    ADMIN_MAPPER_SET_APARTMENT_NAME = 'soz-core:admin:mapper:set-apartment-name',
    ADMIN_MAPPER_SET_APARTMENT_IDENTIFIER = 'soz-core:admin:mapper:set-apartment-identifier',
    ADMIN_MAPPER_UPDATE_APARTMENT_ZONE = 'soz-core:admin:mapper:update-apartment-zone',
    ADMIN_MAPPER_UPDATE_PROPERTY_ZONE = 'soz-core:admin:mapper:update-property-zone',
    ADMIN_MAPPER_ADD_APARTMENT = 'soz-core:admin:mapper:add-apartment',
    ADMIN_MAPPER_ADD_PROPERTY = 'soz-core:admin:mapper:add-property',
    ADMIN_MAPPER_ADD_PROPERTY_CULLING = 'soz-core:admin:mapper:add-property-culling',
    ADMIN_MAPPER_REMOVE_PROPERTY_CULLING = 'soz-core:admin:mapper:remove-property-culling',
    ADMIN_MAPPER_REMOVE_PROPERTY = 'soz-core:admin:mapper:remove-property',
    ADMIN_MAPPER_REMOVE_APARTMENT = 'soz-core:admin:mapper:remove-apartment',
    ADMIN_MAPPER_SET_SENATE_PARTY = 'soz-core:admin:mapper:set-senate-party',
    ADMIN_MAPPER_SET_OWNER = 'soz-core:admin:mapper:set-owner',
    ADMIN_MAPPER_CLEAR_OWNER = 'soz-core:admin:mapper:clear-owner',
    ADMIN_MAPPER_SET_APARTMENT_TIER = 'soz-core:admin:mapper:set-apartment-tier',
    ADMIN_MAPPER_SET_APARTMENT_TAXE = 'soz-core:admin:mapper:set-apartment-taxe',
    ADMIN_OCEAN = 'soz-core:admin:ocean',
    ADMIN_METEOR_STATE = 'soz-core:admin:meteor:state',

    BENNYS_GET_ORDERS = 'soz-core:server:job:bennys:get-orders',
    BENNYS_CANCEL_ORDER = 'soz-core:server:job:bennys:cancel-order',
    BENNYS_ORDER_VEHICLE = 'soz-core:server:job:bennys:order-vehicle',

    CRIMI_CAN_USE_CLOAKROOM = 'soz-core:server:crimi:can-use-cloakroom',
    CRIMI_IS_NAKED = 'soz-core:server:crimi:is-naked',
    CRIMI_SIPHON_CHECK = 'soz-core:server:crimi:siphon-check',

    DRIVING_SCHOOL_SPAWN_VEHICLE = 'soz-core:server:driving-school:spawn-vehicle',
    DRIVING_SCHOOL_CHECK_REMAINING_SLOTS = 'soz-core:server:driving-school:check-vehicle-slots',

    DMC_GET_CONVERTER_STATE = 'soz-core:server:job:dmc:get-converter-state',

    INVENTORY_SELF_FETCH = 'soz-core:inventory:self-fetch',
    INVENTORY_TRANSFER_MONEY = 'soz-core:inventory:transfer-money',
    INVENTORY_GET_ITEM_COUNT = 'soz-core:inventory:search',
    INVENTORY_SHOP_VALIDATE_CART = 'soz-core:inventory:shop-validate-cart',
    INVENTORY_GANG_SMUGGLING_BLACK_MARKET_VALIDATE_CART = 'soz-core:inventory:gang:smuggling:black-market-validate-cart',

    HOUSING_GET_TEMPORARY_ACCESS = 'soz-core:server:housing:get-temporary-access',
    HOUSING_GET_FOURNITURE = 'soz-core:server:housing:get-fourniture',
    HOUSING_GET_LIGHTS = 'soz-core:server:housing:get-lights',
    HOUSING_EDIT_FOURNITURE = 'soz-core:server:housing:edit-fourniture',
    HOUSING_SET_SHELL = 'soz-core:server:housing:set-shell',

    JOBS_USE_WORK_CLOTHES = 'soz-core:server:job:use-work-clothes',

    OIL_GET_STATION = 'soz-core:job:oil:get-station',
    OIL_GET_STATION_PRICES = 'soz-core:job:oil:get-station-prices',
    OIL_LOCK_TANKER = 'soz-core:job:oil:lock-tanker',

    PLAYER_GET_CLIENT_STATE = 'soz-core:player:get-client-state',
    PLAYER_GET_LIST_STATE = 'soz-core:player:get-list-state',
    PLAYER_GET_SERVER_STATE = 'soz-core:player:get-server-state',
    PLAYER_GET_JWT_TOKEN = 'soz-core:player:get-jwt-token',
    PLAYER_GET_LICENCES = 'soz-core:player:get-licences',
    PLAYER_TELEPORT = 'soz-core:player:teleport',
    PLAYER_GET_JOB = 'soz-core:player:get-job',

    CRAFTING_GET_RECIPES = 'soz-core:crafting:get-recipes',
    CRAFTING_DO_CRAFT = 'soz-core:crafting:do-craft',
    CRAFTING_DO_SALVAGE = 'soz-core:crafting:do-salvage',

    CLOTHING_GET_WARM_SCORE = 'soz-core:clothing:gwarm-score',
    CLOTHING_GET_SHOP = 'soz-core:clothing:get-shop',

    SCENE_GET_LOADED = 'soz-core:rpc:scene:get-loaded-scenes',

    STORY_HALLOWEEN_SCENARIO1 = 'soz-story:server:halloween1',
    STORY_HALLOWEEN_SCENARIO2 = 'soz-story:server:halloween2',
    STORY_HALLOWEEN_SCENARIO3 = 'soz-story:server:halloween3',
    STORY_HALLOWEEN_SCENARIO4 = 'soz-story:server:halloween4',

    HALLOWEEN_HUNTCHECK = 'soz-story:server:halloween-check',

    REPOSITORY_GET_DATA = 'soz-core:repository:get-data',
    REPOSITORY_GET_DATA_2 = 'soz-core:repository:get-data-2',

    GET_DISABLE_NPC = 'soz-core:utils:get-disable-npc',

    GET_FORECASTS = 'soz-core:weather:get-forecasts',
    GET_STORM_ALERT = 'soz-core:weather:get-storm-alert',

    VEHICLE_CUSTOM_GET_MODS = 'soz-core:vehicle:custom:get-mods',
    VEHICLE_CUSTOM_SET_MODS = 'soz-core:vehicle:custom:set-mods',
    VEHICLE_DEALERSHIP_AUCTION_BID = 'soz-core:vehicle:dealership:auction:bid',
    VEHICLE_DEALERSHIP_GET_AUCTIONS = 'soz-core:vehicle:dealership:get-auctions',
    VEHICLE_DEALERSHIP_GET_LIST = 'soz-core:vehicle:dealership:get-list',
    VEHICLE_DEALERSHIP_GET_LIST_JOB = 'soz-core:vehicle:dealership:get-list-job',
    VEHICLE_DEALERSHIP_BUY = 'soz-core:vehicle:dealership:buy',
    VEHICLE_GARAGE_GET_VEHICLES = 'soz-core:vehicle:garage:get-vehicles',
    VEHICLE_GARAGE_GET_PLACES = 'soz-core:vehicle:garage:get-places',
    VEHICLE_GARAGE_GET_PROPERTY_PLACES = 'soz-core:vehicle:garage:get-property-places',
    VEHICLE_GARAGE_GET_MAX_PLACES = 'soz-core:vehicle:garage:get-max-places',
    VEHICLE_HAS_KEY = 'soz-core:vehicle:has-key',
    VEHICLE_GET_STATE = 'soz-core:rpc:vehicle:get-state',
    VEHICLE_GET_CONFIGURATION = 'soz-core:rpc:vehicle:get-configuration',
    VEHICLE_GET_CONDITION = 'soz-core:rpc:vehicle:get-condition',
    VEHICLE_GET_MUTED_SIRENS = 'soz-core:rpc:vehicle:get-muted-sirens',
    VEHICLE_GET_OPENED = 'soz-core:rpc:vehicle:get-opened',
    VEHICLE_FDO_GET_POSTIONS = 'soz-core:rpc:vehicle:fdo-get-positions',
    VEHICLE_PITSTOP_DATA = 'soz-core:rpc:vehicle:pitstop:data',
    VEHICLE_PITSTOP_PRICES = 'soz-core:rpc:vehicle:pitstop:price',
    VEHICLE_PITSTOP_PRICES_UPDATE = 'soz-core:rpc:vehicle:pitstop:price-update',
    VEHICLE_SPAWN_JOB_TEMPORARY = 'soz-core:rpc:vehicle:spawn-job-temporary',
    VEHICLE_SPAWN_TEMPORARY = 'soz-core:rpc:vehicle:spawn-temporary',

    VEHICLE_ORDER_GET = 'soz-core:vehicle:orders-get',
    VEHICLE_ORDER_CANCEL = 'soz-core:server:vehicle:cancel-order',
    VEHICLE_ORDER_DO = 'soz-core:server:vehicle:order-do',

    VEHICLE_GRAB_CAR = 'soz-core:server:vehicle:grab-car',
    VEHICLE_GRAB_STEERING_WHEEL = 'soz-core:server:vehicle:grab-steering-wheel',

    VOIP_SET_MUTE = 'soz-core:voip:set-mute',
    VOIP_IS_MUTED = 'soz-core:voip:is-muted',
    VOIP_GET_MEGAPHONE_PLAYERS = 'soz-core:voip:get-megaphone-players',
    VOIP_GET_ROBOT_PLAYERS = 'soz-core:voip:get-robot-players',
    VOIP_VOICE_START_TRANSMITTING = 'soz-core:server:voip:voice-start-transmitting',
    VOIP_VOICE_STOP_TRANSMITTING = 'soz-core:server:voip:voice-stop-transmitting',

    INVENTORY_GET_ITEM_BY_SHORTCUT = 'soz-core:inventory:get-item-by-shortcut',

    UPW_GET_FACILITIES = 'soz-core:job:upw:get-facilities',
    UPW_GET_STORAGE_CAPACITY = 'soz-core:job:upw:get-capacity',
    UPW_GET_STATION = 'soz-core:server:job:upw:get-station',

    WEAPON_USE_AMMO = 'soz-core:server:weapon:useAmmo',
    WEAPON_SET_LABEL = 'soz-core:server:weapon:setLabel',
    WEAPON_REPAIR = 'soz-core:server:weapon:repair',
    WEAPON_SET_TINT = 'soz-core:server:weapon:setTint',
    WEAPON_SET_ATTACHMENTS = 'soz-core:server:weapon:setAttachments',

    VANDALISM_LOAD = 'soz-core:server:vandalism:load',
    VANDALISM_CHECK = 'soz-core:server:vandalism:check',
    VANDALISM_ALERT_CHECK = 'soz-core:server:vandalism:alert-check',

    HEIST_CHECK = 'soz-core:server:heist:check',
    HEIST_JEWELRY_IS_ZONE_UNLOCK = 'soz-core:server:heist:jewelry-check-unlock',
    HEIST_JEWELRY_CHECK_ROBBERY = 'soz-core:server:heist:jewelry-check-robbery',
    HEIST_JEWELRY_START_ROBBERY = 'soz-core:server:heist:jewelry-start-robbery',

    LSMC_GET_DAMAGE = 'soz-core:server:lsmc:get-damage',
    LSMC_CAN_REMOVE_ITT = 'soz-core:server:lsmc:can-remove-itt',
    LSMC_CAN_SET_ITT = 'soz-core:server:lsmc:can-set-itt',
    LSMC_PLAYER_PLASTER = 'soz-core:server:lsmc:get-plaster',
    LSMC_STRETCHER_AMBULANCE_STATUS = 'soz-core:server:lsmc:ambulance-stretcher-status',

    TALENT_TREE_UNLOCK = 'soz-core:server:talent:unlock',
    TALENT_TREE_RESET = 'soz-core:server:talent:reset',
    TALENT_TREE_ENABLE_CRIMI = 'soz-core:server:talent:enable-crimi',

    HELICO_INIT_LIGHT = 'soz-core:server:helico:init-spotlight',

    PAWL_IS_PROCESSING_ENABLED = 'soz-core:server:pawl:is-processing-enabled',
    PAWL_HARVEST_TREE = 'soz-core:server:pawl:harvest-tree',
    PAWL_HARVEST_TREE_SAP = 'soz-core:server:pawl:harvest-tree-sap',

    POLICE_ALCOOLLEVEL = 'soz-core:server:police:alcool-level',
    POLICE_DRUGLEVEL_AND_TYPE = 'soz-core:server:police:drug-level',
    POLICE_K9_FIND_DRUG_ON_PLAYER = 'soz-core:server:police:k9-find-drug-on-player',
    POLICE_K9_FIND_DRUG_ON_CAR = 'soz-core:server:police:k9-find-drug-on-car',
    POLICE_GET_WANTED_PLAYERS = 'soz-core:server:police:get-wanted-players',
    POLICE_DELETE_WANTED_PLAYER = 'soz-core:server:police:delete-wanted-player',
    POLICE_GET_MARKED_MONEY = 'soz-core:server:police:get-marked-money',
    POLICE_GET_CLUES_IN_AREA = 'soz-core:server:police:get-clues-in-area',
    POLICE_GET_ALL_IDENTIFIED_CLUES = 'soz-core:server:police:get-all-identified-clues',
    POLICE_LICENSE_HAS_RECUER = 'soz-core:server:police:has-recuer-license',
    POLICE_SYNC_SHIELD_ANIMATION_OVERRIDE = 'soz-core:server:police-sync-shield-animation-override',
    POLICE_SECRET_CHECK = 'soz-core:server:police:secret-check',

    HUB_EXIT_TIME = 'soz-core:server:hub:exit-time',
    HUB_ENTRY_FETCH_ALL = 'soz-core:server:hub:fetch-all',
    HUB_ENTRY_FETCH_ACTIVE = 'soz-core:server:hub:fetch-active',

    BIN_IS_NOT_LOCKED = 'soz-core:server:bin:is-locked',

    LSMC_GET_CURRENT_ORGAN = 'soz-core:server:lsmc:get-organ',

    RACKET_COOP_CHECK_CRIMI = 'soz-core:server:racket:check-crimi',
    RACKET_LOCK_PED = 'soz-core:server:racket:lock-ped',

    DRUGS_GET_GARDEN_INFO = 'soz-core:server:drugs:garden-info',
    DRUGS_GARDEN_ENTER = 'soz-core:server:drugs:garden-enter',
    DRUGS_GARDEN_EXIT = 'soz-core:server:drugs:garden-exit',
    DRUGS_GET_RECIPES = 'soz-core:server:drugs:recipes-get',
    DRUG_DO_TRANSFORM = 'soz-core:server:drugs:recipes-transform',
    DRUGS_PAY_LOCATION = 'soz-core:server:drugs:location-pay',
    DRUGS_FIELD_HEALTH = 'soz-core:server:drugs:field-health',
    DRUGS_CAN_CONTRACT = 'soz-core:server:drugs:can-contract',

    SOZEDEX_CLAIM_REWARD = 'soz-core:server:sozedex:claim-reward',

    RACE_SERVER_START = 'soz-core:server:race:start',
    RACE_SERVER_EXIT = 'soz-core:server:race:exit',
    RACE_GET_RANKING = 'soz-core:server:race:get-ranking',
    RACE_GET_SPLITS = 'soz-core:server:race:get-splits',

    OBJECT_GET_LIST = 'soz-core:server:object:get-list',

    PLAYER_IS_ZOMBIE = 'soz-core:server:player:is-zombie',

    CRAFT_GET_RECIPES = 'soz-core:server:craft:get-recipes',
    CRAFT_DO_RECIPES = 'soz-core:server:craft:do-recipes',

    FDF_TREE_HARVEST = 'soz-core:server:fdf:tree-harvest',
    FDF_TREE_GET = 'soz-core:server:fdf:tree-get',
    FDF_CROP_GET = 'soz-core:server:fdf:crop-get',
    FDF_FIELD_ISPLOW = 'soz-core:server:fdf:field-isplow',
    FDF_GET_CROP_TO_TRACTOR_HARVEST = 'soz-core:server:fdf:get-crops-to-harvest',
    FDF_CROP_WITH_TRACTOR = 'soz-core:server:fdf:crop-with-tractor',
    FDF_PLOW_STATUS = 'soz-core:server:fdf:get-plow-status',

    CURRENT_PLAYERS = 'soz-core:server:utils:getnbplayers',

    FOOD_HUNT_INIT = 'soz-core:server:food:hunt-init',

    METEOR_OCEAN = 'soz-core:meteor:ocean',

    BANK_GET_ACCOUNT = 'soz-core:server:bank:safe:get-account',
    BANK_GET_ACCOUNT_MONEY = 'soz-core:server:bank:get-account-money',
    BANK_GET_ACCOUNT_UI = 'soz-core:server:bank:get-account-ui',
    BANK_GET_STATEMENTS = 'soz-core:server:bank:get-statements',
    BANK_GET_CONTACTS = 'soz-core:server:bank:get-contacts',
    BANK_TRANSFER_ACTION = 'soz-core:server:bank:transfer-action',
    BANK_CASH_TRANSFER_ACTION = 'soz-core:server:bank:safe:transfer-action',
    BANK_CREATE_OFFSHORE_ACCOUNT = 'soz-core:server:bank:create-offshore-account',
    BANK_CONTACT_ADD = 'soz-core:server:bank:contact:add',
    BANK_CONTACT_REMOVE = 'soz-core:server:bank:contact:remove',

    BANK_ATM_REMOVE_LIQUIDITY = 'soz-core:server:bank:atm:remove-liquidity',
    BANK_ATM_GET_ACCOUNT_UI = 'soz-core:server:bank:atm:get-account-ui',
    BANK_ATM_GET_ACCOUNT = 'soz-core:server:bank:atm:get-account',
    BANK_ATM_GET_MONEY = 'soz-core:server:bank:atm:get-money',

    BANK_GET_INVOICES = 'soz-core:server:bank:get-invoices',
    BANK_CREATE_INVOICE = 'soz-core:server:bank:create-invoice',
    BANK_PAY_INVOICE = 'soz-core:server:bank:pay-invoice',
    BANK_REJECT_INVOICE = 'soz-core:server:bank:reject-invoice',

    GANG_VEHBIZ_LIST = 'soz-core:server:gang:vehbiz:list',
    GANG_VEHBIZ_REFRESH_LIST = 'soz-core:server:gang:vehbiz:refresh-list',
    GANG_VEHBIZ_COMMAND = 'soz-core:server:gang:veh:command',
    GANG_VEHBIZ_UNIQUE_GET = 'soz-core:server:gang:veh:unique-get',
    GANG_VEHBIZ_UNIQUE_ADD = 'soz-core:server:gang:veh:unique-add',
    GANG_VEHBIZ_UNIQUE_DELETE = 'soz-core:server:gang:veh:unique-delete',
    GANG_VEHBIZ_UNIQUE_PRICE = 'soz-core:server:gang:veh:unique-price',
    GANG_VEHBIZ_UNIQUE_NAME = 'soz-core:server:gang:veh:unique-name',
    GANG_VEHBIZ_RESELL_CHECK = 'soz-core:server:gang:veh:resell-check',
    GANG_INFLUENCE_ZONE_GET = 'soz-core:server:gang:inflence:get',
    GANG_MEMBER_FETCH = 'soz-core:server:gang:member:get',
    GANG_MEMBER_ADD = 'soz-core:server:gang:member:add',
    GANG_MEMBER_UPDATE = 'soz-core:server:gang:member:update',
    GANG_CAN_CRIMI = 'soz-core:server:gang:can-crimi',
    GANG_SMUGGLING_BLACK_MARKET_CONTENT = 'soz-core:server:gang:smuggling:blackmarket-content',
    GANG_SMUGGLING_BLACK_MARKET_OWNERS = 'soz-core:server:gang:smuggling:blackmarket-owners',
    GANG_SMUGGLING_CONTAINER_ORDER_GET = 'soz-core:server:gang:smuggling:container-get',
    GANG_SMUGGLING_CONTAINER_ORDER_CANCEL = 'soz-core:server:gang:smuggling:container-cancel',
    GANG_SMUGGLING_CONTAINER_ORDER_NEW = 'soz-core:server:gang:smuggling:container-new',
    GANG_SMUGGLING_CONTAINER_CHECK = 'soz-core:server:gang:smuggling:container-check',
    GANG_SMUGGLING_HARVEST_ZONE_GET = 'soz-core:server:gang:smuggling:harvest:get',
    GANG_SMUGGLING_HARVEST_ZONE_CREATE = 'soz-core:server:gang:smuggling:harvest:create',
    GANG_SMUGGLING_HARVEST_ZONE_DELETE = 'soz-core:server:gang:smuggling:harvest:delete',
    GANG_SMUGGLING_HARVEST_ZONE_RENAME = 'soz-core:server:gang:smuggling:harvest:rename',
    GANG_SMUGGLING_HARVEST_ZONE_LOCATION_ADD = 'soz-core:server:gang:smuggling:harvest:location-add',
    GANG_SMUGGLING_HARVEST_ZONE_LOCATION_REMOVE = 'soz-core:server:gang:smuggling:harvest:location-remove',
    GANG_SMUGGLING_HARVEST_ZONE_LOCATION_UPDATE = 'soz-core:server:gang:smuggling:harvest:location-update',
    GANG_SMUGGLING_HARVEST_LOCATION = 'soz-core:server:gang:smuggling:harvest:location',
    GANG_SMUGGLING_CONVOY_INIT = 'soz-core:server:gang:smuggling:convoy:init',
    GANG_SMUGGLING_GET_OPENED_RESALERS = 'soz-core:server:gang:smuggling:resalers:opened',
    GANG_SMUGGLING_ELECTRONIC_LOCATIONS = 'soz-core:server:gang:smuggling:electronics:locations',
    GANG_SMUGGLING_WAREHOUSE_ENTER = 'soz-core:server:gang:smuggling:warehouse-enter',
    GANG_CYBER_CRYPTO_WASH = 'soz-core:server:gang:cyber:crypto-wash',
    GANG_CYBER_CRYPTO_DEPOSIT = 'soz-core:server:gang:cyber:crypto-deposit',
    GANG_CYBER_CRYPTO_WITHDRAW = 'soz-core:server:gang:cyber:crypto-withdraw',
    GANG_CYBER_BLACKOUT = 'soz-core:server:gang:cyber:blackout',
    GANG_CYBER_DB_SEARCH = 'soz-core:server:gang:cyber:db-search',
    GANG_CYBER_DB_SEARCH_DELETE = 'soz-core:server:gang:cyber:db-search-delete',
    GANG_CYBER_DB_SEARCH_PRINT = 'soz-core:server:gang:cyber:db-search-print',
    GANG_CYBER_DB_ERASE = 'soz-core:server:gang:cyber:db-erase',
    GANG_CYBER_DB_REMOVE = 'soz-core:server:gang:cyber:db-remove',
    GANG_CYBER_CRYPTO_MARKET_BUY = 'soz-core:server:gang:cyber:market-buy',
    GANG_CYBER_CRYPTO_ACTIVATE = 'soz-core:server:gang:cyber:activate',
    GANG_CYBER_CRYPTO_HARVEST = 'soz-core:server:gang:cyber:harvest',
    GANG_CYBER_HACK_ENERGY_CHECK = 'soz-core:server:gang:cyber:energy-check',
    GANG_CYBER_HEIST_START = 'soz-core:server:gang:cyber:heist-start',
    GANG_CYBER_ENTRER_HEIST = 'soz-core:server:gang:cyber:heist-enter',

    WORLD_EVENT_GET_INFO = 'soz-core:server:world-event:get-info',
    WORLD_EVENT_START = 'soz-core:server:world-event:start',

    DRONE_GET = 'soz-core:server:drone-get',
    MINESWEEPER_ROBOT_NEW = 'soz-core:server:minesweeper:robot-new',
    MINESWEEPER_ROBOT_TAKE_CONTROL = 'soz-core:server:minesweeper:robot-take-control',

    WEATHER_GET_FORECASTS = 'soz-core:server:weather:get-forecasts',

    ADMIN_HALLOWEEN_GAME_STATE = 'soz-core:server:admin:halloween:vampire-game-state',

    STRESS_UPDATE = 'soz-core:server:stress:update',

    XMAS_GET_SCENE_STATE = 'soz-core:server:xmas:get-scene-state',

    PHONE_LIGHT_ADD_PHONE = 'soz-core:server:phone:light:add-phone',
    PHONE_LIGHT_REMOVE_PHONE = 'soz-core:server:phone:light:remove-phone',
    PHONE_LIGHT_SET_FLASHLIGHT = 'soz-core:server:phone:light:set-flashlight',
    PHONE_SIMCARD_RESET = 'soz-core:server:phone:simcard:reset',
    PHONE_SIMCARD_GET_AVATAR = 'soz-core:server:phone:simcard:get-avatar',
    PHONE_SIMCARD_UPDATE_AVATAR = 'soz-core:server:phone:simcard:update-avatar',
    PHONE_SIMCARD_CALLS_HISTORY_GET = 'soz-core:server:phone:simcard:calls-history:get',
    PHONE_SIMCARD_CALLS_INIT = 'soz-core:server:phone:simcard:calls:init',
    PHONE_SIMCARD_CALLS_ACCEPT = 'soz-core:server:phone:simcard:calls:accept',
    PHONE_SIMCARD_CALLS_DECLINE = 'soz-core:server:phone:simcard:calls:decline',
    PHONE_SIMCARD_CALLS_MUTE = 'soz-core:server:phone:simcard:calls:mute',
    PHONE_SIMCARD_CALLS_END = 'soz-core:server:phone:simcard:calls:end',
    PHONE_SIMCARD_MESSAGES_CONVERSATION_GET = 'soz-core:server:phone:simcard:messages:conversation:get',
    PHONE_SIMCARD_MESSAGES_CONVERSATION_ADD = 'soz-core:server:phone:simcard:messages:conversation:add',
    PHONE_SIMCARD_MESSAGES_CONVERSATION_SET_READ = 'soz-core:server:phone:simcard:messages:conversation:set-read',
    PHONE_SIMCARD_MESSAGES_CONVERSATION_ARCHIVE = 'soz-core:server:phone:simcard:messages:conversation:archive',
    PHONE_SIMCARD_MESSAGES_GET = 'soz-core:server:phone:simcard:messages:get',
    PHONE_SIMCARD_MESSAGES_SEND = 'soz-core:server:phone:simcard:messages:send',
    PHONE_SIMCARD_CONTACTS_GET = 'soz-core:server:phone:simcard:contacts:get',
    PHONE_SIMCARD_CONTACTS_ADD = 'soz-core:server:phone:simcard:contacts:add',
    PHONE_SIMCARD_CONTACTS_UPDATE = 'soz-core:server:phone:simcard:contacts:update',
    PHONE_SIMCARD_CONTACTS_REMOVE = 'soz-core:server:phone:simcard:contacts:remove',
    PHONE_APP_SOCIETY_GET = 'soz-core:server:phone:app:society:get',
    PHONE_APP_SOCIETY_SEND_MESSAGE = 'soz-core:server:phone:app:society:send-message',
    PHONE_APP_SOCIETY_UPDATE_MESSAGE = 'soz-core:server:phone:app:society:update-message',
    PHONE_APP_DARKWEB_GET_CONVERSATIONS = 'soz-core:server:phone:app:darkweb:get-conversations',
    PHONE_APP_DARKWEB_CREATE_CONVERSATION = 'soz-core:server:phone:app:darkweb:create-conversation',
    PHONE_APP_DARKWEB_UPDATE_CONVERSATION = 'soz-core:server:phone:app:darkweb:update-conversation',
    PHONE_APP_DARKWEB_UPDATE_PARTICIPANT_ROLE = 'soz-core:server:phone:app:darkweb:update-participant-role',
    PHONE_APP_DARKWEB_UPDATE_PARTICIPANT_NOTIFICATION = 'soz-core:server:phone:app:darkweb:update-participant-notification',
    PHONE_APP_DARKWEB_SET_CONVERSATION_AS_READ = 'soz-core:server:phone:app:darkweb:set-conversation-as-read',
    PHONE_APP_DARKWEB_GET_PARTICIPANTS = 'soz-core:server:phone:app:darkweb:get-participants',
    PHONE_APP_DARKWEB_GET_MESSAGES = 'soz-core:server:phone:app:darkweb:get-messages',
    PHONE_APP_DARKWEB_SEND_MESSAGE = 'soz-core:server:phone:app:darkweb:send-message',
    PHONE_APP_PHOTOS_GET = 'soz-core:server:phone:app:photos:get',
    PHONE_APP_PHOTOS_UPLOAD = 'soz-core:server:phone:app:photos:upload',
    PHONE_APP_PHOTOS_DELETE = 'soz-core:server:phone:app:photos:delete',
    PHONE_APP_NOTES_GET = 'soz-core:server:phone:app:notes:get',
    PHONE_APP_NOTES_ADD = 'soz-core:server:phone:app:notes:add',
    PHONE_APP_NOTES_UPDATE = 'soz-core:server:phone:app:notes:update',
    PHONE_APP_NOTES_DELETE = 'soz-core:server:phone:app:notes:delete',
    PHONE_APP_NEWS_GET = 'soz-core:server:phone:app:news:get',
    PHONE_APP_NEWS_CREATE = 'soz-core:server:phone:app:news:create',
    PHONE_APP_TETRIS_ADD_SCORE = 'soz-core:server:phone:app:tetris:add-score',
    PHONE_APP_SNAKE_ADD_SCORE = 'soz-core:server:phone:app:snake:add-score',

    LASER_GAME_GET_INFO_AS_STAFF = 'soz-core:server:phone:app:laser-game:get-info-as-staff',
    LASER_GAME_CREATE = 'soz-core:server:phone:app:laser-game:create',
    LASER_GAME_GET_DATA = 'soz-core:server:phone:app:laser-game:get-data',
    LASER_GAME_GET_AS_CLIENT = 'soz-core:server:phone:app:laser-game:get-as-client',
    LASER_GAME_ACTION_PLAYER = 'soz-core:server:phone:app:laser-game:action-player',
    LASER_GAME_GET_PLAYER_NAME = 'soz-core:server:phone:app:laser-game:get-player-name',
    LASER_GAME_GET_BUCKET = 'soz-core:server:phone:app:laser-game:get-bucket',

    ADMIN_CASINO_UPDATE_HOUSE_EDGE = 'soz-core:server:admin:casino:house-edge:update',
    ADMIN_CASINO_UPDATE_HOUSE_EDGE_CONFIG = 'soz-core:server:admin:casino:house-edge:config:update',
    ADMIN_CASINO_POKER_RESET = 'soz-core:server:admin:casino:poker:reset',
    ADMIN_CASINO_BLACKJACK_RESET = 'soz-core:server:admin:casino:blackjack:reset',
    ADMIN_CASINO_ROULETTE_RESET = 'soz-core:server:admin:casino:roulette:reset',
    ADMIN_CASINO_INSIDE_TRACK_RUN = 'soz-core:server:admin:casino:inside-track:run',
    ADMIN_CASINO_INSIDE_TRACK_RESET = 'soz-core:server:admin:casino:inside-track:reset',
    ADMIN_CASINO_LUCKY_WHEEL_CLEAN_VEHICLE = 'soz-core:server:admin:casino:lucky-wheel:clean-vehicle',
    ADMIN_CASINO_LUCKY_WHEEL_RESET_VEHICLE = 'soz-core:server:admin:casino:lucky-wheel:reset-vehicle',
    CASINO_LUCKY_WHEEL_JOIN = 'soz-core:server:casino:licky-wheel:join',
    CASINO_LUCKY_WHEEL_USE = 'soz-core:server:casino:licky-wheel:use',
    CASINO_LUCKY_WHEEL_LEAVE = 'soz-core:server:casino:licky-wheel:leave',
    CASINO_SLOT_MACHINE_USE = 'soz-core:server:casino:slot-machine-use',
    CASINO_SLOT_MACHINE_SPIN = 'soz-core:server:casino:slot-machine-spin',
    CASINO_SLOT_MACHINE_LEAVE = 'soz-core:server:casino:slot-machine-leave',
    CASINO_POKER_JOIN_TABLE = 'soz-core:server:casino:poker-join-table',
    CASINO_POKER_PLACE_BET = 'soz-core:server:casino:poker-place-bet',
    CASINO_POKER_FOLD = 'soz-core:server:casino:poker-fold',
    CASINO_POKER_LEAVE_TABLE = 'soz-core:server:casino:poker-leave-table',
    CASINO_BLACKJACK_JOIN_TABLE = 'soz-core:server:casino:blackjack-join-table',
    CASINO_BLACKJACK_PLACE_BET = 'soz-core:server:casino:blackjack-place-bet',
    CASINO_BLACKJACK_SPLIT_HAND = 'soz-core:server:casino:blackjack-split-hand',
    CASINO_BLACKJACK_DOUBLE_DOWN = 'soz-core:server:casino:blackjack-double-down',
    CASINO_BLACKJACK_HIT = 'soz-core:server:casino:blackjack-hit',
    CASINO_BLACKJACK_STAND = 'soz-core:server:casino:blackjack-stand',
    CASINO_BLACKJACK_LEAVE_TABLE = 'soz-core:server:casino:blackjack-leave-table',
    CASINO_ROULETTE_JOIN_TABLE = 'soz-core:server:casino:roulette-join-table',
    CASINO_ROULETTE_PLACE_BET = 'soz-core:server:casino:roulette-place-bet',
    CASINO_ROULETTE_LEAVE_TABLE = 'soz-core:server:casino:roulette-leave-table',
    CASINO_INSIDE_TRACK_JOIN = 'soz-core:server:casino:inside-track-join',
    CASINO_INSIDE_TRACK_BET = 'soz-core:server:casino:inside-track-bet',
    CASINO_INSIDE_TRACK_LEAVE = 'soz-core:server:casino:inside-track-leave',
    CASINO_INSIDE_TRACK_HAS_PENDING_GAINS = 'soz-core:server:casino:inside-track-has-pending-gains',
    CASINO_VIP_REWARD_TAKEN = 'soz-core:server:casino:vip-reward-taken',

    FIRE_GET_FIRE_PIT_PROPAGATION = 'soz-core:server:fire:get-fire-pit-propagation',
    FIRE_GET_ALL_PITS = 'soz-core:server:fire:get-all-pits',
    FIRE_EXTINGUISHED = 'soz-core:server:fire:extinguished',
    FIRE_GET_LOCKED_FIRETRUCK = 'soz-core:server:fire:get-locked-firetruck',
    FIRE_LOCK_FIRETRUCK = 'soz-core:server:fire:loke-firetruck',
    FIRE_UNLOCK_FIRETRUCK = 'soz-core:server:fire:unlock-firetruck',

    WHAT_IF_PLAYER_GET_CITIZEN_ID = 'soz-core:server:what-if:player:get-citizen-id',

    WHAT_IF_GET_HAMMER_PROPS = 'soz-core:server:what-if:hammer:get-props',
    WHAT_IF_HAMMER_CREATE = 'soz-core:server:what-if:hammer-create',
    WHAT_IF_HAMMER_UPDATE = 'soz-core:server:what-if:hammer-update',
    WHAT_IF_HAMMER_DELETE = 'soz-core:server:what-if:hammer-delete',
    WHAT_IF_LOOT_INVENTORY = 'soz-core:server:what-if:loot-inventory',
    WHAT_IF_VEHICLE_DEALERSHIP_GET_LIST = 'soz-core:server:what-if:vehicle-dealership:get-list',

    PET_GET_ANIMAL = 'soz-core:server:pet:get-animal',
    PET_GET_JOB_ANIMAL = 'soz-core:server:pet:get-job-animal',
    PET_CONSUME_BALL = 'soz-core:server:pet:consume-ball',
    PET_LIST_JOB_ANIMALS = 'soz-core:server:pet:list-job-animals',
    PET_SHOULD_PLAYER_BE_ATTACKED = 'soz-core:server:pet:should-player-be-attacked',

    PLAYER_CLOTHES_UPDATE = 'soz-core:server:player:clothes:update',
}

export enum RpcClientEvent {
    VEHICLE_GET_TYPE = 'soz-core:rpc:client:vehicle:get-type',
    VEHICLE_GET_NAME = 'soz-core:rpc:client:vehicle:get-name',
    VEHICLE_SPAWN = 'soz-core:rpc:client:vehicle:spawn',
    GET_LAST_VEHICLE_SPAWN = 'soz-core:rpc:client:vehicle:get-last-spawn',
    DELETE_LAST_VEHICLE_SPAWN = 'soz-core:rpc:client:vehicle:delete-last-spawn',
    VEHICLE_SPAWN_FROM_SERVER = 'soz-core:rpc:client:vehicle:spawn-from-server',
    VEHICLE_DELETE = 'soz-core:rpc:client:vehicle:delete',
    MONITOR_GET_TRACES = 'soz-core:rpc:client:monitor:get-traces',
    DRUG_CHECK_ZONE = 'soz-core:rpc:client:drug:check-zone',
    FDF_CHECK_ZONE = 'soz-core:rpc:client:fdf:check-zone',
    CHECK_WEARING_GLOVES = 'soz-core:rpc:client:check-wearing-gloves',
    OBJECT_GET_GROUND_POSITION = 'soz-core:rpc:client:object:get-ground-position',
    GANG_SMUGGLING_CHECK_ZONE = 'soz-core:rpc:client:gang:smuggling:check-zone',
    BATTERY_IS_RELOADING = 'soz-core:rpc:client:battery:i-reloading',
    GET_CLOTHES = 'soz-core:clothing:get-clothes',
    CLOTH_FILTER_GEN9 = 'soz-core:clothing:isgen9',
    CLOTH_TEXTURE_COUNT = 'soz-core:clothing:texture-count',
    FIRE_GET_WIND_DATA = 'soz-core:fire:get-wind-data',
    FIRE_GET_Z = 'soz-core:fire:get-z',
    WHAT_IF_SPAWN_PEDS = 'soz-core:what-if:spawn-peds',
}
