---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Pablo1610.
--- DateTime: 23/01/2022 20:20
---

---@class VoicePlayer
---@field public applicationKey string
---@field public debug boolean
VoicePlayer = {}

---new
---@return VoicePlayer
---@public
function VoicePlayer:new(_src)
    local object = {}
    setmetatable(object, self)
    self.__index = self
    self.debug = (debug or false)
    self.applicationKey = applicationKey
    return self
end