QBCore = exports["qb-core"]:GetCoreObject()

ComponentType = {
    Head = 0,
    Mask = 1,
    Hair = 2,
    Torso = 3,
    Legs = 4,
    Hands = 5,
    Foot = 6,
    Unknown = 7,
    Accessories1 = 8,
    Accessories2 = 9,
    Decals = 10,
    Auxiliary = 11,
}

HeadOverlayType = {
    Blemishes = 0,
    FacialHair = 1,
    Eyebrows = 2,
    Ageing = 3,
    Makeup = 4,
    Blush = 5,
    Complexion = 6,
    SunDamage = 7,
    Lipstick = 8,
    Moles = 9,
    ChestHair = 10,
    BodyBlemishes = 11,
    AddBodyBlemishes = 12,
}

FaceFeatureType = {
    NoseWidth = 0,
    NosePeakHeight = 1,
    NosePeakLength = 2,
    NoseBoneHigh = 3,
    NosePeakLowering = 4,
    NoseBoneTwist = 5,
    EyebrowHigh = 6,
    EyebrowForward = 7,
    CheeksBoneHigh = 8,
    CheeksBoneWidth = 9,
    CheeksWidth = 10,
    EyesOpening = 11,
    LipsThickness = 12,
    JawBoneWidth = 13,
    JawBoneBackLength = 14,
    ChimpBoneLowering = 15,
    ChimpBoneLength = 16,
    ChimpBoneWidth = 17,
    ChimpHole = 18,
    NeckThickness = 19,
}

-- Labels for listing options
Labels = {
    Eye = {
        { value = -1, label = GetLabelText("NONE") },
        { value = 0, label = GetLabelText("FACE_E_C_0") },
        { value = 1, label = GetLabelText("FACE_E_C_1") },
        { value = 2, label = GetLabelText("FACE_E_C_2") },
        { value = 3, label = GetLabelText("FACE_E_C_3") },
        { value = 4, label = GetLabelText("FACE_E_C_4") },
        { value = 5, label = GetLabelText("FACE_E_C_5") },
        { value = 6, label = GetLabelText("FACE_E_C_6") },
        { value = 7, label = GetLabelText("FACE_E_C_7") },
        { value = 8, label = GetLabelText("FACE_E_C_8") },
        { value = 9, label = GetLabelText("FACE_E_C_9") },
        { value = 10, label = GetLabelText("FACE_E_C_10") },
        { value = 11, label = GetLabelText("FACE_E_C_11") },
        { value = 12, label = GetLabelText("FACE_E_C_12") },
        { value = 13, label = GetLabelText("FACE_E_C_13") },
        { value = 14, label = GetLabelText("FACE_E_C_14") },
        { value = 15, label = GetLabelText("FACE_E_C_15") },
        { value = 16, label = GetLabelText("FACE_E_C_16") },
        { value = 17, label = GetLabelText("FACE_E_C_17") },
        { value = 18, label = GetLabelText("FACE_E_C_18") },
        { value = 19, label = GetLabelText("FACE_E_C_19") },
        { value = 20, label = GetLabelText("FACE_E_C_20") },
        { value = 21, label = GetLabelText("FACE_E_C_21") },
        { value = 22, label = GetLabelText("FACE_E_C_22") },
        { value = 23, label = GetLabelText("FACE_E_C_23") },
        { value = 24, label = GetLabelText("FACE_E_C_24") },
        { value = 25, label = GetLabelText("FACE_E_C_25") },
        { value = 26, label = GetLabelText("FACE_E_C_26") },
        { value = 27, label = GetLabelText("FACE_E_C_27") },
        { value = 28, label = GetLabelText("FACE_E_C_28") },
        { value = 29, label = GetLabelText("FACE_E_C_29") },
        { value = 30, label = GetLabelText("FACE_E_C_30") },
        { value = 31, label = GetLabelText("FACE_E_C_31") },
    },
    Blemish = {
        { value = -1, label =  GetLabelText("NONE") },
        { value = 0, label = "0" },
        { value = 1, label = "1" },
        { value = 2, label = "2" },
        { value = 3, label = "3" },
        { value = 4, label = "4" },
        { value = 5, label = "5" },
        { value = 6, label = "6" },
        { value = 7, label = "7" },
        { value = 8, label = "8" },
        { value = 9, label = "9" },
        { value = 10, label = "10" },
        { value = 11, label = "11" },
        { value = 12, label = "12" },
        { value = 13, label = "13" },
        { value = 14, label = "14" },
        { value = 15, label = "15" },
        { value = 16, label = "16" },
        { value = 17, label = "17" },
        { value = 18, label = "18" },
        { value = 19, label = "19" },
        { value = 20, label = "20" },
        { value = 21, label = "21" },
        { value = 22, label = "22" },
        { value = 23, label = "23" },
    },
    Ageing = {
        { value = -1, label =  GetLabelText("NONE") },
        { value = 0, label = "0" },
        { value = 1, label = "1" },
        { value = 2, label = "2" },
        { value = 3, label = "3" },
        { value = 4, label = "4" },
        { value = 5, label = "5" },
        { value = 6, label = "6" },
        { value = 7, label = "7" },
        { value = 8, label = "8" },
        { value = 9, label = "9" },
        { value = 10, label = "10" },
        { value = 11, label = "11" },
        { value = 12, label = "12" },
        { value = 13, label = "13" },
        { value = 14, label = "14" },
        { value = 15, label = "15" },
    },
    Complexion = {
        { value = -1, label =  GetLabelText("NONE") },
        { value = 0, label = "0" },
        { value = 1, label = "1" },
        { value = 2, label = "2" },
        { value = 3, label = "3" },
        { value = 4, label = "4" },
        { value = 5, label = "5" },
        { value = 6, label = "6" },
        { value = 7, label = "7" },
        { value = 8, label = "8" },
        { value = 9, label = "9" },
        { value = 10, label = "10" },
        { value = 11, label = "11" },
    },
    Moles = {
        { value = -1, label =  GetLabelText("NONE") },
        { value = 0, label = "0" },
        { value = 1, label = "1" },
        { value = 2, label = "2" },
        { value = 3, label = "3" },
        { value = 4, label = "4" },
        { value = 5, label = "5" },
        { value = 6, label = "6" },
        { value = 7, label = "7" },
        { value = 8, label = "8" },
        { value = 9, label = "9" },
        { value = 10, label = "10" },
        { value = 11, label = "11" },
        { value = 12, label = "12" },
        { value = 13, label = "13" },
        { value = 14, label = "14" },
        { value = 15, label = "15" },
        { value = 16, label = "16" },
        { value = 17, label = "17" },
    },
    BodyBlemishes = {
        { value = -1, label =  GetLabelText("NONE") },
        { value = 0, label = "0" },
        { value = 1, label = "1" },
        { value = 2, label = "2" },
        { value = 3, label = "3" },
        { value = 4, label = "4" },
        { value = 5, label = "5" },
        { value = 6, label = "6" },
        { value = 7, label = "7" },
        { value = 8, label = "8" },
        { value = 9, label = "9" },
        { value = 10, label = "10" },
        { value = 11, label = "11" },
    },
    AddBodyBlemishes = {
        { value = -1, label =  GetLabelText("NONE") },
        { value = 0, label = "0" },
        { value = 1, label = "1" },
    },
    HairMale = {
        { value = 0, label = GetLabelText("CC_M_HS_0") },
        { value = 1, label = GetLabelText("CC_M_HS_1") },
        { value = 2, label = GetLabelText("CC_M_HS_2") },
        { value = 3, label = GetLabelText("CC_M_HS_3") },
        { value = 4, label = GetLabelText("CC_M_HS_4") },
        { value = 5, label = GetLabelText("CC_M_HS_5") },
        { value = 6, label = GetLabelText("CC_M_HS_6") },
        { value = 7, label = GetLabelText("CC_M_HS_7") },
        { value = 8, label = GetLabelText("CC_M_HS_8") },
        { value = 9, label = GetLabelText("CC_M_HS_9") },
        { value = 10, label = GetLabelText("CC_M_HS_10") },
        { value = 11, label = GetLabelText("CC_M_HS_11") },
        { value = 12, label = GetLabelText("CC_M_HS_12") },
        { value = 13, label = GetLabelText("CC_M_HS_13") },
        { value = 14, label = GetLabelText("CC_M_HS_14") },
        { value = 15, label = GetLabelText("CC_M_HS_15") },
        { value = 16, label = GetLabelText("CC_M_HS_16") },
        { value = 17, label = GetLabelText("CC_M_HS_17") },
        { value = 18, label = GetLabelText("CC_M_HS_18") },
        { value = 19, label = GetLabelText("CC_M_HS_19") },
        { value = 20, label = GetLabelText("CC_M_HS_20") },
        { value = 21, label = GetLabelText("CC_M_HS_21") },
        { value = 24, label = GetLabelText("CLO_S1M_H_0_0") },
        { value = 25, label = GetLabelText("CLO_S1M_H_1_0") },
        { value = 26, label = GetLabelText("CLO_S1M_H_2_0") },
        { value = 27, label = GetLabelText("CLO_S1M_H_3_0") },
        { value = 28, label = GetLabelText("CLO_S2M_H_0_0") },
        { value = 29, label = GetLabelText("CLO_S2M_H_1_0") },
        { value = 30, label = GetLabelText("CLO_S2M_H_2_0") },
        { value = 31, label = GetLabelText("CLO_BIM_H_0_0") },
        { value = 32, label = GetLabelText("CLO_BIM_H_1_0") },
        { value = 33, label = GetLabelText("CLO_BIM_H_2_0") },
        { value = 34, label = GetLabelText("CLO_BIM_H_3_0") },
        { value = 35, label = GetLabelText("CLO_BIM_H_4_0") },
        { value = 36, label = GetLabelText("CLO_BIM_H_5_0") },
    },
    HairFemale = {
        { value = 0, label = GetLabelText("CC_F_HS_0") },
        { value = 1, label = GetLabelText("CC_F_HS_1") },
        { value = 2, label = GetLabelText("CC_F_HS_2") },
        { value = 3, label = GetLabelText("CC_F_HS_3") },
        { value = 4, label = GetLabelText("CC_F_HS_4") },
        { value = 5, label = GetLabelText("CC_F_HS_5") },
        { value = 6, label = GetLabelText("CC_F_HS_6") },
        { value = 7, label = GetLabelText("CC_F_HS_7") },
        { value = 8, label = GetLabelText("CC_F_HS_8") },
        { value = 9, label = GetLabelText("CC_F_HS_9") },
        { value = 10, label = GetLabelText("CC_F_HS_10") },
        { value = 11, label = GetLabelText("CC_F_HS_11") },
        { value = 12, label = GetLabelText("CC_F_HS_12") },
        { value = 13, label = GetLabelText("CC_F_HS_13") },
        { value = 14, label = GetLabelText("CC_F_HS_14") },
        { value = 15, label = GetLabelText("CC_F_HS_15") },
        { value = 16, label = GetLabelText("CC_F_HS_16") },
        { value = 17, label = GetLabelText("CC_F_HS_17") },
        { value = 18, label = GetLabelText("CC_F_HS_18") },
        { value = 19, label = GetLabelText("CC_F_HS_19") },
        { value = 20, label = GetLabelText("CC_F_HS_23") },
        { value = 21, label = GetLabelText("CC_F_HS_20") },
        { value = 22, label = GetLabelText("CC_F_HS_21") },
        { value = 23, label = GetLabelText("CC_F_HS_22") },
    },
    BeardMale = {
        { value = -1, label = GetLabelText("BERD_P0_0_0") },
        { value = 0, label = GetLabelText("BERD_P0_1_0") },
        { value = 1, label = GetLabelText("BERD_P0_2_0") },
        { value = 2, label = GetLabelText("BERD_P0_3_0") },
        { value = 3, label = GetLabelText("BERD_P0_4_0") },
        { value = 4, label = GetLabelText("BERD_P2_0_0") },
        { value = 5, label = GetLabelText("BERD_P2_1_0") },
        { value = 6, label = GetLabelText("BERD_P2_2_0") },
        { value = 7, label = GetLabelText("HAIR_BEARD7") },
        { value = 8, label = GetLabelText("HAIR_BEARD8") },
        { value = 9, label = GetLabelText("HAIR_BEARD9") },
        { value = 10, label = GetLabelText("HAIR_BEARD10") },
        { value = 11, label = GetLabelText("HAIR_BEARD11") },
        { value = 12, label = GetLabelText("HAIR_BEARD12") },
        { value = 13, label = GetLabelText("HAIR_BEARD13") },
        { value = 14, label = GetLabelText("HAIR_BEARD14") },
        { value = 15, label = GetLabelText("HAIR_BEARD15") },
        { value = 16, label = GetLabelText("HAIR_BEARD16") },
        { value = 17, label = GetLabelText("HAIR_BEARD17") },
        { value = 18, label = GetLabelText("HAIR_BEARD18") },
        { value = 19, label = GetLabelText("BRD_HP_0") },
        { value = 20, label = GetLabelText("BRD_HP_1") },
        { value = 21, label = GetLabelText("BRD_HP_2") },
        { value = 23, label = GetLabelText("BRD_HP_3") },
        { value = 24, label = GetLabelText("BRD_HP_4") },
        { value = 25, label = GetLabelText("BRD_HP_5") },
        { value = 26, label = GetLabelText("BRD_HP_6") },
        { value = 27, label = GetLabelText("BRD_HP_7") },
        { value = 28, label = GetLabelText("BRD_HP_8") },
        { value = 29, label = GetLabelText("BRD_HP_9") },
    },
    Eyebrow = {
        { value = -1, label = GetLabelText("NONE") },
        { value = 0, label = GetLabelText("CC_EYEBRW_0") },
        { value = 1, label = GetLabelText("CC_EYEBRW_1") },
        { value = 2, label = GetLabelText("CC_EYEBRW_2") },
        { value = 3, label = GetLabelText("CC_EYEBRW_3") },
        { value = 4, label = GetLabelText("CC_EYEBRW_4") },
        { value = 5, label = GetLabelText("CC_EYEBRW_5") },
        { value = 6, label = GetLabelText("CC_EYEBRW_6") },
        { value = 7, label = GetLabelText("CC_EYEBRW_7") },
        { value = 8, label = GetLabelText("CC_EYEBRW_8") },
        { value = 9, label = GetLabelText("CC_EYEBRW_9") },
        { value = 10, label = GetLabelText("CC_EYEBRW_10") },
        { value = 11, label = GetLabelText("CC_EYEBRW_11") },
        { value = 12, label = GetLabelText("CC_EYEBRW_12") },
        { value = 13, label = GetLabelText("CC_EYEBRW_13") },
        { value = 14, label = GetLabelText("CC_EYEBRW_14") },
        { value = 15, label = GetLabelText("CC_EYEBRW_15") },
        { value = 16, label = GetLabelText("CC_EYEBRW_16") },
        { value = 17, label = GetLabelText("CC_EYEBRW_17") },
        { value = 18, label = GetLabelText("CC_EYEBRW_18") },
        { value = 19, label = GetLabelText("CC_EYEBRW_19") },
        { value = 20, label = GetLabelText("CC_EYEBRW_20") },
        { value = 21, label = GetLabelText("CC_EYEBRW_21") },
        { value = 22, label = GetLabelText("CC_EYEBRW_22") },
        { value = 23, label = GetLabelText("CC_EYEBRW_23") },
        { value = 24, label = GetLabelText("CC_EYEBRW_24") },
        { value = 25, label = GetLabelText("CC_EYEBRW_25") },
        { value = 26, label = GetLabelText("CC_EYEBRW_26") },
        { value = 27, label = GetLabelText("CC_EYEBRW_27") },
        { value = 28, label = GetLabelText("CC_EYEBRW_28") },
        { value = 29, label = GetLabelText("CC_EYEBRW_29") },
        { value = 30, label = GetLabelText("CC_EYEBRW_30") },
        { value = 31, label = GetLabelText("CC_EYEBRW_31") },
        { value = 32, label = GetLabelText("CC_EYEBRW_32") },
        { value = 33, label = GetLabelText("CC_EYEBRW_33") },
    },
    ChestHair = {
        { value = -1, label = GetLabelText("CC_BODY_1_0") },
        { value = 0, label = GetLabelText("CC_BODY_1_1") },
        { value = 1, label = GetLabelText("CC_BODY_1_2") },
        { value = 2, label = GetLabelText("CC_BODY_1_3") },
        { value = 3, label = GetLabelText("CC_BODY_1_4") },
        { value = 4, label = GetLabelText("CC_BODY_1_5") },
        { value = 5, label = GetLabelText("CC_BODY_1_6") },
        { value = 6, label = GetLabelText("CC_BODY_1_7") },
        { value = 7, label = GetLabelText("CC_BODY_1_8") },
        { value = 8, label = GetLabelText("CC_BODY_1_9") },
        { value = 9, label = GetLabelText("CC_BODY_1_10") },
        { value = 10, label = GetLabelText("CC_BODY_1_11") },
        { value = 11, label = GetLabelText("CC_BODY_1_12") },
        { value = 12, label = GetLabelText("CC_BODY_1_13") },
        { value = 13, label = GetLabelText("CC_BODY_1_14") },
        { value = 14, label = GetLabelText("CC_BODY_1_15") },
        { value = 15, label = GetLabelText("CC_BODY_1_16") },
        { value = 16, label = GetLabelText("CC_BODY_1_17") },
    },
    Blush = {
        { value = -1, label = GetLabelText("NONE") },
        { value = 0, label = GetLabelText("CC_BLUSH_0") },
        { value = 1, label = GetLabelText("CC_BLUSH_1") },
        { value = 2, label = GetLabelText("CC_BLUSH_2") },
        { value = 3, label = GetLabelText("CC_BLUSH_3") },
        { value = 4, label = GetLabelText("CC_BLUSH_4") },
        { value = 5, label = GetLabelText("CC_BLUSH_5") },
        { value = 6, label = GetLabelText("CC_BLUSH_6") },
        { value = 7, label = GetLabelText("CC_BLUSH_7") },
        { value = 8, label = GetLabelText("CC_BLUSH_8") },
        { value = 9, label = GetLabelText("CC_BLUSH_9") },
        { value = 10, label = GetLabelText("CC_BLUSH_10") },
        { value = 11, label = GetLabelText("CC_BLUSH_11") },
        { value = 12, label = GetLabelText("CC_BLUSH_12") },
        { value = 13, label = GetLabelText("CC_BLUSH_13") },
        { value = 14, label = GetLabelText("CC_BLUSH_14") },
        { value = 15, label = GetLabelText("CC_BLUSH_15") },
        { value = 16, label = GetLabelText("CC_BLUSH_16") },
        { value = 17, label = GetLabelText("CC_BLUSH_17") },
        { value = 18, label = GetLabelText("CC_BLUSH_18") },
        { value = 19, label = GetLabelText("CC_BLUSH_19") },
        { value = 20, label = GetLabelText("CC_BLUSH_20") },
        { value = 21, label = GetLabelText("CC_BLUSH_21") },
        { value = 22, label = GetLabelText("CC_BLUSH_22") },
        { value = 23, label = GetLabelText("CC_BLUSH_23") },
        { value = 24, label = GetLabelText("CC_BLUSH_24") },
        { value = 25, label = GetLabelText("CC_BLUSH_25") },
        { value = 26, label = GetLabelText("CC_BLUSH_26") },
        { value = 27, label = GetLabelText("CC_BLUSH_27") },
        { value = 28, label = GetLabelText("CC_BLUSH_28") },
        { value = 29, label = GetLabelText("CC_BLUSH_29") },
        { value = 30, label = GetLabelText("CC_BLUSH_30") },
        { value = 31, label = GetLabelText("CC_BLUSH_31") },
        { value = 32, label = GetLabelText("CC_BLUSH_32") },
    },
    Lipstick = {
        { value = -1, label = GetLabelText("NONE") },
        { value = 0, label = GetLabelText("CC_LIPSTICK_0") },
        { value = 1, label = GetLabelText("CC_LIPSTICK_1") },
        { value = 2, label = GetLabelText("CC_LIPSTICK_2") },
        { value = 3, label = GetLabelText("CC_LIPSTICK_3") },
        { value = 4, label = GetLabelText("CC_LIPSTICK_4") },
        { value = 5, label = GetLabelText("CC_LIPSTICK_5") },
        { value = 6, label = GetLabelText("CC_LIPSTICK_6") },
        { value = 7, label = GetLabelText("CC_LIPSTICK_7") },
        { value = 8, label = GetLabelText("CC_LIPSTICK_8") },
        { value = 9, label = GetLabelText("CC_LIPSTICK_9") },
    },
}

Colors = {
    Hair = {},
    Makeup = {},
}

Citizen.CreateThread(function()
    local numHairColors = GetNumHairColors();
    local numMakeupColors = GetNumMakeupColors();

    for i = 0, numHairColors - 1 do
        local r, g, b = GetHairRgbColor(i);

        table.insert(Colors.Hair, { value = i, label = "HAIR_COLOR_" .. i, r = r, g = g, b = b });
    end

    for i = 0, numMakeupColors - 1 do
        local r, g, b = GetMakeupRgbColor(i);

        table.insert(Colors.Makeup, { value = i, label = "MAKEUP_COLOR_" .. i, r = r, g = g, b = b });
    end
end)
