import { SocietyContact } from '../../../../../shared/phone/apps/society';

export const societyContacts: SocietyContact[] = [
    {
        display: 'FIB',
        number: '555-FBI',
        avatar: 'fbi.webp',
        type: 'public',
        order: 7,
    },
    {
        display: 'LSPD',
        number: '555-LSPD',
        avatar: 'lspd.webp',
        type: 'public',
        order: 1,
        anonymousCallAllowed: true,
    },
    {
        display: 'LSMC',
        number: '555-LSMC',
        avatar: 'lsmc.webp',
        type: 'public',
        order: 0,
        anonymousCallAllowed: true,
    },
    {
        display: 'BCSO',
        number: '555-BCSO',
        avatar: 'bcso.webp',
        type: 'public',
        order: 2,
        anonymousCallAllowed: true,
    },
    {
        display: 'Twitch News',
        number: '555-NEWS',
        avatar: 'news.webp',
        type: 'private',
    },
    {
        display: 'BlueBird',
        number: '555-BLUEBIRD',
        avatar: 'garbage.webp',
        type: 'private',
    },
    {
        display: 'Carl Jr Services',
        number: '555-CARLJR',
        avatar: 'taxi.webp',
        type: 'private',
    },
    {
        display: 'Château Marius',
        number: '555-MARIUS',
        avatar: 'food.webp',
        type: 'private',
    },
    {
        display: 'Michel Transport Petrol',
        number: '555-MTP',
        avatar: 'oil.webp',
        type: 'private',
    },
    {
        display: 'STONK Security',
        number: '555-STONK',
        avatar: 'cash-transfer.webp',
        type: 'public',
        order: 4,
    },
    {
        display: 'New Gahray',
        number: '555-NEWGAHRAY',
        avatar: 'bennys.webp',
        type: 'private',
    },
    {
        display: 'UPW',
        number: '555-UPW',
        avatar: 'upw.webp',
        type: 'private',
    },
    {
        display: 'PAWL',
        number: '555-PAWL',
        avatar: 'pawl.webp',
        type: 'private',
    },
    {
        display: 'Bahama Unicorn',
        number: '555-BAUN',
        avatar: 'baun.webp',
        type: 'private',
    },
    {
        display: 'Fight For Style',
        number: '555-FFS',
        avatar: 'ffs.webp',
        type: 'private',
    },
    {
        display: 'Mandatory',
        number: '555-MDR',
        avatar: 'mdr.webp',
        type: 'public',
        order: 5,
    },
    {
        display: "Force de l'ordre",
        number: '555-POLICE',
        avatar: 'fdo.webp',
        type: 'urgence',
        anonymousCallAllowed: true,
    },
    {
        display: 'SASP',
        number: '555-SASP',
        avatar: 'sasp.webp',
        type: 'public',
        order: 3,
        anonymousCallAllowed: true,
    },
    {
        display: 'Gouvernement',
        number: '555-GOUV',
        avatar: 'gouv.webp',
        type: 'public',
        order: 6,
    },
    {
        display: 'Ferme de Fou',
        number: '555-FDF',
        avatar: 'fdf.webp',
        type: 'private',
    },
    {
        display: 'YouNews',
        number: '555-YOUN',
        avatar: 'you-news.webp',
        type: 'private',
    },
    {
        display: 'DeMetal Company',
        number: '555-DMC',
        avatar: 'dmc.webp',
        type: 'private',
    },
];
