export default {
  MESSAGES: 'MESSAGES',
  NOTES: 'NOTES',
  MARKETPLACE: 'MARKETPLACE',
  CONTACTS: 'CONTACTS',
  CAMERA: 'CAMERA',
  SOCIETIES: 'SOCIETIES',
  SOCIETY_MESSAGES: 'SOCIETY_MESSAGES',
  TWITCH_NEWS: 'TWITCH_NEWS',
};
