table.insert(migrations, {
    name = "reset-msb-metadata-2",
    queries = {
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.fiber', 0) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.lipid', 0) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.sugar', 0) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.protein', 0) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.max_stamina', 100) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.strength', 100) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.stress_level', 0) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.health_level', 100) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.health_book_health_level', null) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.health_book_max_stamina', null) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.health_book_strength', null) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.health_book_stress_level', null) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.health_book_sugar', null) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.health_book_fiber', null) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.health_book_lipid', null) ]],
        [[ UPDATE player SET metadata = JSON_SET(metadata, '$.health_book_protein', null) ]],
    },
})
