table.insert(migrations, {
    name = "add-stock-for-new-vehicles",
    queries = {
        [[
            INSERT INTO concess_storage (model, stock, category) VALUES
                ('issi7', 6, 'Compacts'),
                ('asbo', 6, 'Compacts'),
                ('kanjo', 6, 'Compacts'),
                ('issi3', 6, 'Compacts'),
                ('sentinel3', 6, 'Coupes'),
                ('gauntlet3', 6, 'Muscle'),
                ('gauntlet4', 6, 'Muscle'),
                ('gasser', 6, 'Muscle'),
                ('ellie', 6, 'Muscle'),
                ('dominator3', 6, 'Muscle'),
                ('impaler', 6, 'Muscle'),
                ('clique', 6, 'Muscle'),
                ('tulip', 6, 'Muscle'),
                ('deviant', 6, 'Muscle'),
                ('virgo2', 6, 'Muscle'),
                ('virgo3', 6, 'Muscle'),
                ('faction3', 6, 'Muscle'),
                ('ruiner', 6, 'Muscle'),
                ('ruiner2', 6, 'Muscle'),
                ('novak', 6, 'Suvs'),
                ('rebla', 6, 'Suvs'),
                ('patriot2', 6, 'Suvs'),
                ('toros', 6, 'Suvs'),
                ('caracara2', 6, 'Off-road'),
                ('hellion', 6, 'Off-road'),
                ('everon', 6, 'Off-road'),
                ('vagrant', 6, 'Off-road'),
                ('outlaw', 6, 'Off-road'),
                ('freecrawler', 6, 'Off-road'),
                ('stafford', 6, 'Sedans'),
                ('stryder', 6, 'Motorcycles'),
                ('diablous', 6, 'Motorcycles'),
                ('diablous2', 6, 'Motorcycles'),
                ('fcr', 6, 'Motorcycles'),
                ('fcr2', 6, 'Motorcycles'),
                ('speedo4', 6, 'Vans'),
                ('speedo', 6, 'Vans'),
                ('minivan2', 6, 'Vans')
            ;
        ]],
    },
})
