table.insert(migrations, {
    name = "add-vehicles-table",
    queries = {
        [[
            CREATE TABLE IF NOT EXISTS `vehicles` (
                 `model` varchar(50) NOT NULL,
                 `name` varchar(255) NOT NULL,
                 `price` int(11) NOT NULL,
                 `category` varchar(50) DEFAULT NULL,
                 `dealership_id` varchar(10) DEFAULT NULL,
                 `required_licence` varchar(10) DEFAULT NULL,
                 `size` int(1) DEFAULT 1,
                 `job_name` TEXT DEFAULT NULL,
                 INDEX `vehicles_dealership_idx`(`dealership_id`),
                 INDEX `vehicles_category_idx`(`category`),
                 PRIMARY KEY (`model`)
               ) ENGINE=InnoDB AUTO_INCREMENT=1;
        ]],
        [[
            INSERT INTO vehicles (model, name, price, category, dealership_id, required_licence) VALUES
                ('asbo', 'Asbo', 4000, 'Compacts', 'pdm', 'car'),
                ('blista', 'Blista', 10080, 'Compacts', 'pdm', 'car'),
                ('blista2', 'Blista Compact', 18950, 'Compacts', 'pdm', 'car'),
                ('blista3', 'Blista Go Go Monkey', 15000, 'Compacts', 'pdm', 'car'),
                ('brioso', 'Brioso R/A', 21060, 'Compacts', 'pdm', 'car'),
                ('club', 'Club', 8000, 'Compacts', 'pdm', 'car'),
                ('dilettante', 'Dilettante', 9000, 'Compacts', 'pdm', 'car'),
                ('dilettante2', 'Dilettante Patrol', 12000, 'Compacts', 'pdm', 'car'),
                ('kanjo', 'Blista Kanjo', 12000, 'Compacts', 'pdm', 'car'),
                ('issi7', 'Issi Sport', 100000, 'Compacts', 'pdm', 'car'),
                ('issi2', 'Issi', 20250, 'Compacts', 'pdm', 'car'),
                ('issi3', 'Issi Classic', 5000, 'Compacts', 'pdm', 'car'),
                ('issi4', 'Issi Arena', 80000, 'Compacts', 'pdm', 'car'),
                ('issi5', 'Issi Arena', 80000, 'Compacts', 'pdm', 'car'),
                ('issi6', 'Issi Arena', 80000, 'Compacts', 'pdm', 'car'),
                ('panto', 'Panto', 13140, 'Compacts', 'pdm', 'car'),
                ('prairie', 'Prairie', 11160, 'Compacts', 'pdm', 'car'),
                ('rhapsody', 'Rhapsody', 10000, 'Compacts', 'pdm', 'car'),
                ('brioso2', 'Brioso 300', 12000, 'Compacts', 'pdm', 'car'),
                ('weevil', 'Weevil', 9000, 'Compacts', 'pdm', 'car'),
                ('cogcabrio', 'Cognoscenti Cabrio', 40500, 'Coupes', 'pdm', 'car'),
                ('examplar', 'Exemplar', 134910, 'Coupes', 'pdm', 'car'),
                ('f620', 'F620', 75870, 'Coupes', 'pdm', 'car'),
                ('felon', 'Felon', 101160, 'Coupes', 'pdm', 'car'),
                ('felon2', 'Felon GT', 84330, 'Coupes', 'pdm', 'car'),
                ('futo', 'Futo', 17500, 'Coupes', 'pdm', 'car'),
                ('jackal', 'Jackal', 123660, 'Coupes', 'pdm', 'car'),
                ('oracle', 'Oracle', 22000, 'Coupes', 'pdm', 'car'),
                ('oracle2', 'Oracle XS', 134910, 'Coupes', 'pdm', 'car'),
                ('sentinel', 'Sentinel', 84330, 'Coupes', 'pdm', 'car'),
                ('sentinel2', 'Sentinel XS', 98370, 'Coupes', 'pdm', 'car'),
                ('sentinel3', 'Sentinel Classic', 70000, 'Coupes', 'pdm', 'car'),
                ('windsor', 'Windsor', 134910, 'Coupes', 'pdm', 'car'),
                ('windsor2', 'Windsor Drop', 202320, 'Coupes', 'pdm', 'car'),
                ('zion', 'Zion', 91350, 'Coupes', 'pdm', 'car'),
                ('zion2', 'Zion Cabrio', 109620, 'Coupes', 'pdm', 'car'),
                ('previon', 'Previon', 149000, 'Coupes', 'pdm', 'car'),
                ('champion', 'Champion', 205000, 'Super', 'luxury', 'car'),
                ('ignus', 'Ignus', 1120000, 'Super', 'luxury', 'car'),
                ('zeno', 'Zeno', 1350000, 'Super', 'luxury', 'car'),
                ('bmx', 'BMX', 850, 'Cycles', 'cycle', NULL),
                ('cruiser', 'Cruiser', 450, 'Cycles', 'cycle', NULL),
                ('fixter', 'Fixter', 600, 'Cycles', 'cycle', NULL),
                ('scorcher', 'Scorcher', 450, 'Cycles', 'cycle', NULL),
                ('tribike', 'Tri Bike', 600, 'Cycles', 'cycle', NULL),
                ('tribike2', 'Tri Bike 2', 600, 'Cycles', 'cycle', NULL),
                ('tribike3', 'Tri Bike 3', 600, 'Cycles', 'cycle', NULL),
                ('akuma', 'Akuma', 55000, 'Motorcycles', 'moto', 'moto'),
                ('avarus', 'Avarus', 150030, 'Motorcycles', 'moto', 'moto'),
                ('bagger', 'Bagger', 54000, 'Motorcycles', 'moto', 'moto'),
                ('bati', 'Bati 801', 143370, 'Motorcycles', 'moto', 'moto'),
                ('bati2', 'Bati 801RR', 114660, 'Motorcycles', 'moto', 'moto'),
                ('bf400', 'BF400', 370890, 'Motorcycles', 'moto', 'moto'),
                ('carbon', 'Carbon RS', 134910, 'Motorcycles', 'moto', 'moto'),
                ('chimera', 'Chimera', 54000, 'Motorcycles', 'moto', 'moto'),
                ('cliffhanger', 'Cliffhanger', 259650, 'Motorcycles', 'moto', 'moto'),
                ('daemon', 'Daemon', 124740, 'Motorcycles', 'moto', 'moto'),
                ('daemon2', 'Daemon Custom', 99810, 'Motorcycles', 'moto', 'moto'),
                ('defiler', 'Defiler', 43200, 'Motorcycles', 'moto', 'moto'),
                ('deathbike', 'Apocalypse Deathbike', 30000, 'Motorcycles', 'moto', 'moto'),
                ('deathbike2', 'Future Shock Deathbike', 30000, 'Motorcycles', 'moto', 'moto'),
                ('deathbike3', 'Nightmare Deathbike', 30000, 'Motorcycles', 'moto', 'moto'),
                ('diablous', 'Diablous', 30000, 'Motorcycles', 'moto', 'moto'),
                ('diablous2', 'Diablous Custom', 30000, 'Motorcycles', 'moto', 'moto'),
                ('double', 'Double-T', 194220, 'Motorcycles', 'moto', 'moto'),
                ('enduro', 'Enduro', 78192, 'Motorcycles', 'moto', 'moto'),
                ('esskey', 'Esskey', 40500, 'Motorcycles', 'moto', 'moto'),
                ('faggio', 'Faggio Sport', 16920, 'Motorcycles', 'moto', 'moto'),
                ('faggio2', 'Faggio', 25380, 'Motorcycles', 'moto', 'moto'),
                ('faggio3', 'Faggio Mod', 2500, 'Motorcycles', 'moto', 'moto'),
                ('fcr', 'FCR 1000', 5000, 'Motorcycles', 'moto', 'moto'),
                ('fcr2', 'FCR 1000 Custom', 19000, 'Motorcycles', 'moto', 'moto'),
                ('gargoyle', 'Gargoyle', 408060, 'Motorcycles', 'moto', 'moto'),
                ('hakuchou', 'Hakuchou', 184140, 'Motorcycles', 'moto', 'moto'),
                ('hakuchou2', 'Hakuchou Drag', 184140, 'Motorcycles', 'moto', 'moto'),
                ('hexer', 'Hexer', 59310, 'Motorcycles', 'moto', 'moto'),
                ('innovation', 'Innovation', 148410, 'Motorcycles', 'moto', 'moto'),
                ('lectro', 'Lectro', 28000, 'Motorcycles', 'moto', 'moto'),
                ('manchez', 'Manchez', 119340, 'Motorcycles', 'moto', 'moto'),
                ('nemesis', 'Nemesis', 33750, 'Motorcycles', 'moto', 'moto'),
                ('nightblade', 'Nightblade', 333900, 'Motorcycles', 'moto', 'moto'),
                ('oppressor', 'Oppressor', 9999999, 'Super', 'luxury', 'moto'),
                ('pcj', 'PCJ-600', 33750, 'Motorcycles', 'moto', 'moto'),
                ('ratbike', 'Rat Bike', 3000, 'Motorcycles', 'moto', 'moto'),
                ('ruffian', 'Ruffian', 50220, 'Motorcycles', 'moto', 'moto'),
                ('sanchez01', 'Sanchez Livery', 67410, 'Motorcycles', 'moto', 'moto'),
                ('sanchez02', 'Sanchez', 84420, 'Motorcycles', 'moto', 'moto'),
                ('sanctus', 'Sanctus', 394560, 'Motorcycles', 'moto', 'moto'),
                ('shotaro', 'Shotaro Concept', 320000, 'Motorcycles', 'moto', 'moto'),
                ('sovereign', 'Sovereign', 45360, 'Motorcycles', 'moto', 'moto'),
                ('stryder', 'Stryder', 50000, 'Motorcycles', 'moto', 'moto'),
                ('thrust', 'Thrust', 46440, 'Motorcycles', 'moto', 'moto'),
                ('vader', 'Vader', 49140, 'Motorcycles', 'moto', 'moto'),
                ('vindicator', 'Vindicator', 19000, 'Motorcycles', 'moto', 'moto'),
                ('vortex', 'Vortex', 121410, 'Motorcycles', 'moto', 'moto'),
                ('wolfsbane', 'Wolfsbane', 150030, 'Motorcycles', 'moto', 'moto'),
                ('zombiea', 'Zombie Bobber', 242820, 'Motorcycles', 'moto', 'moto'),
                ('zombieb', 'Zombie Chopper', 223380, 'Motorcycles', 'moto', 'moto'),
                ('manchez2', 'Manchez', 14000, 'Motorcycles', 'moto', 'moto'),
                ('shinobi', 'Shinobi', 25000, 'Motorcycles', 'moto', 'moto'),
                ('reever', 'Reever', 25000, 'Motorcycles', 'moto', 'moto'),
                ('blade', 'Blade', 168570, 'Muscle', 'pdm', 'car'),
                ('buccaneer', 'Buccaneer', 54810, 'Muscle', 'pdm', 'car'),
                ('buccaneer2', 'Buccaneer Rider', 140490, 'Muscle', 'pdm', 'car'),
                ('chino', 'Chino', 54810, 'Muscle', 'pdm', 'car'),
                ('chino2', 'Chino Luxe', 126450, 'Muscle', 'pdm', 'car'),
                ('clique', 'Clique', 20000, 'Muscle', 'pdm', 'car'),
                ('coquette3', 'Coquette BlackFin', 309060, 'Muscle', 'pdm', 'car'),
                ('deviant', 'Deviant', 70000, 'Muscle', 'pdm', 'car'),
                ('dominator', 'Dominator', 179820, 'Muscle', 'pdm', 'car'),
                ('dominator2', 'Pißwasser Dominator', 50000, 'Muscle', 'pdm', 'car'),
                ('dominator3', 'Dominator GTX', 70000, 'Muscle', 'pdm', 'car'),
                ('dominator4', 'Dominator Arena', 200000, 'Muscle', 'pdm', 'car'),
                ('dominator7', 'Dominator ASP', 110000, 'Muscle', 'pdm', 'car'),
                ('dominator8', 'Dominator GTT', 80000, 'Muscle', 'pdm', 'car'),
                ('dukes', 'Dukes', 157320, 'Muscle', 'pdm', 'car'),
                ('dukes2', 'Dukes Nightrider', 60000, 'Muscle', 'pdm', 'car'),
                ('dukes3', 'Beater Dukes', 45000, 'Muscle', 'pdm', 'car'),
                ('faction', 'Faction', 58410, 'Muscle', 'pdm', 'car'),
                ('faction2', 'Faction Rider', 109620, 'Muscle', 'pdm', 'car'),
                ('faction3', 'Faction Custom Donk', 35000, 'Muscle', 'pdm', 'car'),
                ('ellie', 'Ellie', 42250, 'Muscle', 'pdm', 'car'),
                ('gauntlet', 'Gauntlet', 280980, 'Muscle', 'pdm', 'car'),
                ('gauntlet2', 'Redwood Gauntlet', 70000, 'Muscle', 'pdm', 'car'),
                ('gauntlet3', 'Classic Gauntlet', 75000, 'Muscle', 'pdm', 'car'),
                ('gauntlet4', 'Gauntlet Hellfire', 80000, 'Muscle', 'pdm', 'car'),
                ('gauntlet5', 'Gauntlet Classic Custom', 120000, 'Muscle', 'pdm', 'car'),
                ('hermes', 'Hermes', 347040, 'Muscle', 'pdm', 'car'),
                ('hotknife', 'Hotknife', 154530, 'Muscle', 'pdm', 'car'),
                ('hustler', 'Hustler', 168570, 'Muscle', 'pdm', 'car'),
                ('impaler', 'Impaler', 95000, 'Muscle', 'pdm', 'car'),
                ('impaler2', 'Apocalypse Impaler', 95000, 'Muscle', 'pdm', 'car'),
                ('impaler3', 'Future Shock Impaler', 95000, 'Muscle', 'pdm', 'car'),
                ('impaler4', 'Nightmare Impaler', 95000, 'Muscle', 'pdm', 'car'),
                ('imperator', 'Apocalypse Imperator', 95000, 'Muscle', 'pdm', 'car'),
                ('imperator2', 'Future Shock Imperator', 95000, 'Muscle', 'pdm', 'car'),
                ('imperator3', 'Nightmare Imperator', 95000, 'Muscle', 'pdm', 'car'),
                ('lurcher', 'Lurcher', 21000, 'Muscle', 'pdm', 'car'),
                ('manana', 'Manana', 12800, 'Muscle', 'pdm', 'car'),
                ('manana2', 'Manana Custom', 24000, 'Muscle', 'pdm', 'car'),
                ('moonbeam', 'Moonbeam', 16470, 'Vans', 'pdm', 'car'),
                ('moonbeam2', 'Moonbeam Custom', 40770, 'Vans', 'pdm', 'car'),
                ('nightshade', 'Nightshade', 213570, 'Muscle', 'pdm', 'car'),
                ('peyote2', 'Peyote Gasser', 40000, 'Muscle', 'pdm', 'car'),
                ('phoenix', 'Phoenix', 224820, 'Muscle', 'pdm', 'car'),
                ('picador', 'Picador', 62100, 'Muscle', 'pdm', 'car'),
                ('ratloader2', 'Rat-Truck', 20000, 'Muscle', 'pdm', 'car'),
                ('ruiner', 'Ruiner', 29000, 'Muscle', 'pdm', 'car'),
                ('ruiner2', 'Ruiner 2000', 50000, 'Muscle', 'pdm', 'car'),
                ('sabregt', 'Sabre Turbo', 168570, 'Muscle', 'pdm', 'car'),
                ('sabregt2', 'Sabre GT', 222570, 'Muscle', 'pdm', 'car'),
                ('slamtruck', 'Slam Truck', 100000, 'Muscle', 'pdm', 'car'),
                ('slamvan', 'Slam Van', 30000, 'Muscle', 'pdm', 'car'),
                ('slamvan2', 'Lost Slam Van', 90000, 'Muscle', 'pdm', 'car'),
                ('slamvan3', 'Slam Van Custom', 235980, 'Muscle', 'pdm', 'car'),
                ('stalion', 'Stallion', 33000, 'Muscle', 'pdm', 'car'),
                ('stalion2', 'Stallion Burgershot', 40000, 'Muscle', 'pdm', 'car'),
                ('tampa', 'Tampa', 202320, 'Muscle', 'pdm', 'car'),
                ('tampa2', 'Drift Tampa', 80000, 'Muscle', 'pdm', 'car'),
                ('tulip', 'Tulip', 80000, 'Muscle', 'pdm', 'car'),
                ('vamos', 'Vamos', 30000, 'Muscle', 'pdm', 'car'),
                ('vigero', 'Vigero', 143280, 'Muscle', 'pdm', 'car'),
                ('virgo', 'Virgo', 73080, 'Muscle', 'pdm', 'car'),
                ('virgo2', 'Virgo Classic Custom', 21000, 'Muscle', 'pdm', 'car'),
                ('virgo3', 'Virgo Classic', 21000, 'Muscle', 'pdm', 'car'),
                ('voodoo2', 'Voodoo', 150300, 'Muscle', 'pdm', 'car'),
                ('yosemite', 'Yosemite', 325980, 'Muscle', 'pdm', 'car'),
                ('yosemite2', 'Yosemite Drift', 55000, 'Muscle', 'pdm', 'car'),
                ('yosemite3', 'Yosemite Rancher', 425000, 'Off-road', 'pdm', 'car'),
                ('buffalo4', 'Buffalo STX', 345000, 'Muscle', 'pdm', 'car'),
                ('bfinject', 'Bf Injection', 161820, 'Off-road', 'pdm', 'car'),
                ('bifta', 'Bifta', 157320, 'Off-road', 'pdm', 'car'),
                ('blazer', 'Blazer', 32850, 'Off-road', 'pdm', 'car'),
                ('blazer2', 'Blazer Lifeguard', 7000, 'Off-road', 'pdm', 'car'),
                ('blazer3', 'Blazer Hot Rod', 7000, 'Off-road', 'pdm', 'car'),
                ('blazer4', 'Blazer Sport', 37890, 'Off-road', 'pdm', 'car'),
                ('blazer5', 'Blazer Aqua', 40000, 'Off-road', 'pdm', 'car'),
                ('brawler', 'Brawler', 425000, 'Off-road', 'pdm', 'car'),
                ('caracara', 'Caracara', 60000, 'Off-road', 'pdm', 'car'),
                ('caracara2', 'Caracara 4x4', 80000, 'Off-road', 'pdm', 'car'),
                ('dubsta3', 'Dubsta 6x6', 323100, 'Off-road', 'pdm', 'car'),
                ('dune', 'Dune Buggy', 140490, 'Off-road', 'pdm', 'car'),
                ('everon', 'Everon', 60000, 'Off-road', 'pdm', 'car'),
                ('freecrawler', 'Freecrawler', 24000, 'Off-road', 'pdm', 'car'),
                ('hellion', 'Hellion', 38000, 'Off-road', 'pdm', 'car'),
                ('kalahari', 'Kalahari', 14000, 'Off-road', 'pdm', 'car'),
                ('kamacho', 'Kamacho', 449550, 'Off-road', 'pdm', 'car'),
                ('mesa3', 'Mesa Merryweather', 400000, 'Off-road', 'pdm', 'car'),
                ('outlaw', 'Outlaw', 15000, 'Off-road', 'pdm', 'car'),
                ('rancherxl', 'Rancher XL', 24000, 'Off-road', 'pdm', 'car'),
                ('rebel2', 'Rebel', 22230, 'Off-road', 'pdm', 'car'),
                ('riata', 'Riata', 365310, 'Off-road', 'pdm', 'car'),
                ('sandking', 'Sandking', 146700, 'Off-road', 'pdm', 'car'),
                ('sandking2', 'Sandking SWB', 38000, 'Off-road', 'pdm', 'car'),
                ('trophytruck', 'Trophy Truck', 60000, 'Off-road', 'pdm', 'car'),
                ('trophytruck2', 'Trophy Truck Limited', 80000, 'Off-road', 'pdm', 'car'),
                ('vagrant', 'Vagrant', 50000, 'Off-road', 'pdm', 'car'),
                ('verus', 'Verus', 20000, 'Off-road', 'pdm', 'car'),
                ('winky', 'Winky', 10000, 'Off-road', 'pdm', 'car'),
                ('baller', 'Baller', 43020, 'Suvs', 'pdm', 'car'),
                ('baller2', 'Baller II', 117990, 'Suvs', 'pdm', 'car'),
                ('baller3', 'Baller LE', 15000, 'Suvs', 'pdm', 'car'),
                ('baller4', 'Baller LE LWB', 29000, 'Suvs', 'pdm', 'car'),
                ('baller5', 'Baller LE Blindé', 78000, 'Suvs', 'pdm', 'car'),
                ('baller6', 'Baller LE LWB Blindé', 82000, 'Suvs', 'pdm', 'car'),
                ('bjxl', 'BeeJay XL', 19000, 'Suvs', 'pdm', 'car'),
                ('cavalcade', 'Cavalcade', 14000, 'Suvs', 'pdm', 'car'),
                ('cavalcade2', 'Cavalcade II', 44280, 'Suvs', 'pdm', 'car'),
                ('contender', 'Contender', 365310, 'Suvs', 'pdm', 'car'),
                ('dubsta', 'Dubsta', 168570, 'Suvs', 'pdm', 'car'),
                ('dubsta2', 'Dubsta Luxuary', 185490, 'Suvs', 'pdm', 'car'),
                ('fq2', 'FQ2', 17190, 'Suvs', 'pdm', 'car'),
                ('gresley', 'Gresley', 43470, 'Suvs', 'pdm', 'car'),
                ('habanero', 'Habanero', 43470, 'Suvs', 'pdm', 'car'),
                ('huntley', 'Huntley S', 43470, 'Suvs', 'pdm', 'car'),
                ('landstalker', 'Landstalker', 43740, 'Suvs', 'pdm', 'car'),
                ('landstalker2', 'Landstalker XL', 26000, 'Suvs', 'pdm', 'car'),
                ('mesa', 'Mesa', 63540, 'Suvs', 'pdm', 'car'),
                ('novak', 'Novak', 70000, 'Suvs', 'pdm', 'car'),
                ('patriot', 'Patriot', 120780, 'Suvs', 'pdm', 'car'),
                ('radi', 'Radius', 17280, 'Suvs', 'pdm', 'car'),
                ('rebla', 'Rebla GTS', 21000, 'Suvs', 'pdm', 'car'),
                ('rocoto', 'Rocoto', 148320, 'Suvs', 'pdm', 'car'),
                ('seminole', 'Seminole', 18180, 'Suvs', 'pdm', 'car'),
                ('seminole2', 'Seminole Frontier', 13000, 'Suvs', 'pdm', 'car'),
                ('serrano', 'Serrano', 48000, 'Suvs', 'pdm', 'car'),
                ('toros', 'Toros', 65000, 'Suvs', 'pdm', 'car'),
                ('xls', 'XLS', 165240, 'Suvs', 'pdm', 'car'),
                ('granger2', 'Granger 3600LX', 221000, 'Suvs', 'pdm', 'car'),
                ('asea', 'Asea', 25290, 'Sedans', 'pdm', 'car'),
                ('asterope', 'Asterope', 11000, 'Sedans', 'pdm', 'car'),
                ('cog55', 'Cognoscenti 55', 22000, 'Sedans', 'pdm', 'car'),
                ('cognoscenti', 'Cognoscenti', 134910, 'Sedans', 'pdm', 'car'),
                ('emperor', 'Emperor', 10080, 'Sedans', 'pdm', 'car'),
                ('fugitive', 'Fugitive', 119430, 'Sedans', 'pdm', 'car'),
                ('glendale', 'Glendale', 112410, 'Sedans', 'pdm', 'car'),
                ('glendale2', 'Glendale II', 12000, 'Sedans', 'pdm', 'car'),
                ('ingot', 'Ingot', 4999, 'Sedans', 'pdm', 'car'),
                ('intruder', 'Intruder', 119430, 'Sedans', 'pdm', 'car'),
                ('premier', 'Premier', 11160, 'Sedans', 'pdm', 'car'),
                ('primo', 'Primo', 5000, 'Sedans', 'pdm', 'car'),
                ('primo2', 'Primo Custom', 105390, 'Sedans', 'pdm', 'car'),
                ('regina', 'Regina', 13140, 'Sedans', 'pdm', 'car'),
                ('stafford', 'Stafford', 30000, 'Sedans', 'pdm', 'car'),
                ('stanier', 'Stanier', 19000, 'Sedans', 'pdm', 'car'),
                ('stratum', 'Stratum', 15000, 'Sedans', 'pdm', 'car'),
                ('stretch', 'Stretch', 211410, 'Sedans', 'pdm', 'car'),
                ('superd', 'Super Diamond', 150030, 'Sedans', 'pdm', 'car'),
                ('surge', 'Surge', 20000, 'Sedans', 'pdm', 'car'),
                ('tailgater', 'Tailgater', 109620, 'Sedans', 'pdm', 'car'),
                ('warrener', 'Warrener', 112410, 'Sedans', 'pdm', 'car'),
                ('washington', 'Washington', 73100, 'Sedans', 'pdm', 'car'),
                ('tailgater2', 'Tailgater S', 51000, 'Sedans', 'pdm', 'car'),
                ('cinquemila', 'Cinquemila', 125000, 'Sedans', 'luxury', 'car'),
                ('iwagen', 'I-Wagen', 225000, 'Sedans', 'luxury', 'car'),
                ('astron', 'Astron', 150000, 'Sedans', 'luxury', 'car'),
                ('baller7', 'Baller ST', 145000, 'Sedans', 'luxury', 'car'),
                ('comet7', 'Comet S2 Cabrio', 150000, 'Coupes', 'luxury', 'car'),
                ('deity', 'Deity', 505000, 'Sedans', 'luxury', 'car'),
                ('jubilee', 'Jubilee', 485000, 'Sedans', 'luxury', 'car'),
                ('patriot3', 'Patriot', 270000, 'Sedans', 'luxury', 'car'),
                ('alpha', 'Alpha', 53000, 'Sports', 'luxury', 'car'),
                ('banshee', 'Banshee', 56000, 'Sports', 'luxury', 'car'),
                ('bestiagts', 'Bestia GTS', 37000, 'Sports', 'luxury', 'car'),
                ('buffalo', 'Buffalo', 18750, 'Sedans', 'Sports', 'car'),
                ('buffalo2', 'Buffalo S', 24500, 'Sedans', 'Sports', 'car'),
                ('carbonizzare', 'Carbonizzare', 155000, 'Sports', 'luxury', 'car'),
                ('comet2', 'Comet', 130000, 'Sports', 'luxury', 'car'),
                ('comet3', 'Comet Retro Custom', 175000, 'Sports', 'luxury', 'car'),
                ('comet4', 'Comet Safari', 110000, 'Sports', 'luxury', 'car'),
                ('comet5', 'Comet SR', 155000, 'Sports', 'luxury', 'car'),
                ('coquette', 'Coquette', 145000, 'Sports', 'luxury', 'car'),
                ('coquette2', 'Coquette Classic', 165000, 'Sports', 'luxury', 'car'),
                ('coquette4', 'Coquette D10', 220000, 'Sports', 'luxury', 'car'),
                ('drafter', '8F Drafter', 80000, 'Sports', 'luxury', 'car'),
                ('deveste', 'Deveste', 234000, 'Sports', 'luxury', 'car'),
                ('elegy', 'Elegy Retro Custom', 145000, 'Sports', 'luxury', 'car'),
                ('elegy2', 'Elegy RH8', 150000, 'Sports', 'luxury', 'car'),
                ('feltzer2', 'Feltzer', 97000, 'Sports', 'luxury', 'car'),
                ('flashgt', 'Flash GT', 48000, 'Sports', 'luxury', 'car'),
                ('furoregt', 'Furore GT', 78000, 'Sports', 'luxury', 'car'),
                ('gb200', 'GB 200', 140000, 'Sports', 'luxury', 'car'),
                ('komoda', 'Komoda', 55000, 'Sports', 'luxury', 'car'),
                ('imorgon', 'Imorgon', 120000, 'Sports', 'luxury', 'car'),
                ('italigto', 'Itali GTO', 260000, 'Sports', 'luxury', 'car'),
                ('jugular', 'Jugular', 80000, 'Sports', 'luxury', 'car'),
                ('jester', 'Jester', 132250, 'Sports', 'luxury', 'car'),
                ('jester2', 'Jester Racecar', 210000, 'Sports', 'luxury', 'car'),
                ('jester3', 'Jester Classic', 85000, 'Sports', 'luxury', 'car'),
                ('khamelion', 'Khamelion', 90000, 'Sports', 'luxury', 'car'),
                ('kuruma', 'Kuruma', 72000, 'Sports', 'luxury', 'car'),
                ('kuruma2', 'Kuruma Blindé', 72000, 'Sports', 'luxury', 'car'),
                ('locust', 'Locust', 200000, 'Sports', 'luxury', 'car'),
                ('lynx', 'Lynx', 150000, 'Sports', 'luxury', 'car'),
                ('massacro', 'Massacro', 110000, 'Sports', 'luxury', 'car'),
                ('massacro2', 'Massacro Racecar', 80000, 'Sports', 'luxury', 'car'),
                ('neo', 'Neo', 230000, 'Sports', 'luxury', 'car'),
                ('neon', 'Neon', 220000, 'Sports', 'luxury', 'car'),
                ('ninef', '9F', 95000, 'Sports', 'luxury', 'car'),
                ('ninef2', '9F Cabrio', 105000, 'Sports', 'luxury', 'car'),
                ('omnis', 'Omnis', 90000, 'Sports', 'luxury', 'car'),
                ('paragon', 'Paragon', 60000, 'Sports', 'luxury', 'car'),
                ('pariah', 'Pariah', 90000, 'Sports', 'luxury', 'car'),
                ('penumbra', 'Penumbra', 22000, 'Sports', 'luxury', 'car'),
                ('penumbra2', 'Penumbra FF', 30000, 'Sports', 'luxury', 'car'),
                ('rapidgt', 'Rapid GT', 86000, 'Sports', 'luxury', 'car'),
                ('rapidgt2', 'Rapid GT Convertible', 92000, 'Sports', 'luxury', 'car'),
                ('raptor', 'Raptor', 90000, 'Sports', 'luxury', 'car'),
                ('revolter', 'Revolter', 95000, 'Sports', 'luxury', 'car'),
                ('ruston', 'Ruston', 130000, 'Sports', 'luxury', 'car'),
                ('schafter', 'Schafter', 179800, 'Sports', 'luxury', 'car'),
                ('schafter3', 'Schafter V12', 35000, 'Sports', 'luxury', 'car'),
                ('schafter4', 'Schafter LWB', 21000, 'Sports', 'luxury', 'car'),
                ('schlagen', 'Schlagen GT', 160000, 'Sports', 'luxury', 'car'),
                ('schwarzer', 'Schwartzer', 47000, 'Sports', 'luxury', 'car'),
                ('seven70', 'Seven-70', 140000, 'Sports', 'luxury', 'car'),
                ('specter', 'Specter', 160000, 'Sports', 'luxury', 'car'),
                ('sugoi', 'Sugoi', 85000, 'Sports', 'luxury', 'car'),
                ('sultan', 'Sultan', 50000, 'Sports', 'luxury', 'car'),
                ('sultan2', 'Sultan Custom', 55000, 'Sports', 'luxury', 'car'),
                ('surano', 'Surano', 80000, 'Sports', 'luxury', 'car'),
                ('tropos', 'Tropos Rallye', 65000, 'Sports', 'luxury', 'car'),
                ('verlierer2', 'Verlierer', 90500, 'Sports', 'luxury', 'car'),
                ('vstr', 'V-STR', 80000, 'Sports', 'luxury', 'car'),
                ('italirsx', 'Itali RSX', 260000, 'Sports', 'luxury', 'car'),
                ('zr350', 'ZR350', 38000, 'Sports', 'luxury', 'car'),
                ('calico', 'Calico GTF', 39000, 'Sports', 'luxury', 'car'),
                ('futo2', 'Futo GTX', 39000, 'Sports', 'luxury', 'car'),
                ('euros', 'Euros', 80000, 'Sports', 'luxury', 'car'),
                ('jester4', 'Jester RR', 240000, 'Sports', 'luxury', 'car'),
                ('remus', 'Remus', 48000, 'Sports', 'luxury', 'car'),
                ('comet6', 'Comet S2', 230000, 'Sports', 'luxury', 'car'),
                ('growler', 'Growler', 205000, 'Sports', 'luxury', 'car'),
                ('vectre', 'Emperor Vectre', 80000, 'Sports', 'luxury', 'car'),
                ('cypher', 'Cypher', 155000, 'Sports', 'luxury', 'car'),
                ('sultan3', 'Sultan Classic Custom', 56000, 'Sports', 'luxury', 'car'),
                ('rt3000', 'RT3000', 65000, 'Sports', 'luxury', 'car'),
                ('ardent', 'Ardent', 30000, 'Sportsclassics', 'pdm', 'car'),
                ('btype', 'Roosevelt', 75000, 'Sportsclassics', 'pdm', 'car'),
                ('btype2', 'Franken Stange', 87000, 'Sportsclassics', 'pdm', 'car'),
                ('btype3', 'Roosevelt Valor', 63000, 'Sportsclassics', 'pdm', 'car'),
                ('casco', 'Casco', 100000, 'Sportsclassics', 'pdm', 'car'),
                ('cheetah2', 'Cheetah Classic', 195000, 'Sportsclassics', 'luxury', 'car'),
                ('deluxo', 'Deluxo', 55000, 'Sportsclassics', 'pdm', 'car'),
                ('dynasty', 'Dynasty', 25000, 'Sportsclassics', 'pdm', 'car'),
                ('fagaloa', 'Fagaloa', 13000, 'Sportsclassics', 'pdm', 'car'),
                ('feltzer3', 'Stirling GT', 115000, 'Sportsclassics', 'pdm', 'car'),
                ('gt500', 'GT500', 130000, 'Sportsclassics', 'pdm', 'car'),
                ('infernus2', 'Infernus Classic', 245000, 'Sportsclassics', 'pdm', 'car'),
                ('jb700', 'JB 700', 240000, 'Sportsclassics', 'pdm', 'car'),
                ('jb7002', 'JB 700W', 40000, 'Sportsclassics', 'pdm', 'car'),
                ('mamba', 'Mamba', 140000, 'Sportsclassics', 'pdm', 'car'),
                ('michelli', 'Michelli GT', 30000, 'Sportsclassics', 'pdm', 'car'),
                ('monroe', 'Monroe', 115000, 'Sportsclassics', 'pdm', 'car'),
                ('nebula', 'Nebula', 22000, 'Sportsclassics', 'pdm', 'car'),
                ('peyote', 'Peyote', 23500, 'Sportsclassics', 'pdm', 'car'),
                ('peyote3', 'Peyote Custom', 48000, 'Sportsclassics', 'pdm', 'car'),
                ('pigalle', 'Pigalle', 92000, 'Sportsclassics', 'pdm', 'car'),
                ('rapidgt3', 'Rapid GT', 90000, 'Sportsclassics', 'pdm', 'car'),
                ('retinue', 'Retinue', 32000, 'Sportsclassics', 'pdm', 'car'),
                ('retinue2', 'Retinue MKII', 38000, 'Sportsclassics', 'pdm', 'car'),
                ('savestra', 'Savestra', 67000, 'Sportsclassics', 'pdm', 'car'),
                ('stinger', 'Stinger', 39500, 'Sportsclassics', 'pdm', 'car'),
                ('stingergt', 'Stinger GT', 70000, 'Sportsclassics', 'pdm', 'car'),
                ('stromberg', 'Stromberg', 80000, 'Sportsclassics', 'pdm', 'car'),
                ('swinger', 'Swinger', 221000, 'Sportsclassics', 'pdm', 'car'),
                ('torero', 'Torero', 84000, 'Sportsclassics', 'pdm', 'car'),
                ('tornado', 'Tornado', 21000, 'Sportsclassics', 'pdm', 'car'),
                ('tornado2', 'Tornado Gang', 22000, 'Sportsclassics', 'pdm', 'car'),
                ('tornado5', 'Tornado Custom', 22000, 'Sportsclassics', 'pdm', 'car'),
                ('turismo2', 'Turismo Classic', 170000, 'Sportsclassics', 'pdm', 'car'),
                ('viseris', 'Viseris', 210000, 'Sportsclassics', 'pdm', 'car'),
                ('z190', 'Z190', 78000, 'Sportsclassics', 'pdm', 'car'),
                ('ztype', 'Z-Type', 270000, 'Sportsclassics', 'pdm', 'car'),
                ('zion3', 'Zion Classic', 45000, 'Sportsclassics', 'pdm', 'car'),
                ('cheburek', 'Cheburek', 7000, 'Sportsclassics', 'pdm', 'car'),
                ('toreador', 'Toreador', 50000, 'Sportsclassics', 'pdm', 'car'),
                ('adder', 'Adder', 280000, 'Super', 'luxury', 'car'),
                ('autarch', 'Autarch', 224000, 'Super', 'luxury', 'car'),
                ('banshee2', 'Banshee 900R', 120000, 'Super', 'luxury', 'car'),
                ('bullet', 'Bullet', 120000, 'Super', 'luxury', 'car'),
                ('cheetah', 'Cheetah', 214000, 'Super', 'luxury', 'car'),
                ('cyclone', 'Cyclone', 300000, 'Super', 'luxury', 'car'),
                ('entity2', 'Entity XXR', 164000, 'Super', 'luxury', 'car'),
                ('entityxf', 'Entity XF', 180000, 'Super', 'luxury', 'car'),
                ('emerus', 'Emerus', 220000, 'Super', 'luxury', 'car'),
                ('fmj', 'FMJ', 125000, 'Super', 'luxury', 'car'),
                ('furia', 'Furia', 230000, 'Super', 'luxury', 'car'),
                ('infernus', 'Infernus', 235000, 'Super', 'luxury', 'car'),
                ('italigtb', 'Itali GTB', 170000, 'Super', 'luxury', 'car'),
                ('italigtb2', 'Itali GTB Custom', 250000, 'Super', 'luxury', 'car'),
                ('krieger', 'Krieger', 222000, 'Super', 'luxury', 'car'),
                ('le7b', 'RE-7B', 260000, 'Super', 'luxury', 'car'),
                ('nero', 'Nero', 200000, 'Super', 'luxury', 'car'),
                ('nero2', 'Nero Custom', 260000, 'Super', 'luxury', 'car'),
                ('osiris', 'Osiris', 220000, 'Super', 'luxury', 'car'),
                ('penetrator', 'Penetrator', 130000, 'Super', 'luxury', 'car'),
                ('prototipo', 'X80 Proto', 235000, 'Super', 'luxury', 'car'),
                ('reaper', 'Reaper', 100000, 'Super', 'luxury', 'car'),
                ('s80', 'S80RR', 205000, 'Super', 'luxury', 'car'),
                ('sc1', 'SC1', 90000, 'Super', 'luxury', 'car'),
                ('sheava', 'ETR1', 220000, 'Super', 'luxury', 'car'),
                ('sultanrs', 'Sultan RS', 76500, 'Super', 'luxury', 'car'),
                ('t20', 'T20', 1650000, 'Super', 'luxury', 'car'),
                ('taipan', 'Taipan', 1850000, 'Super', 'luxury', 'car'),
                ('tempesta', 'Tempesta', 120000, 'Super', 'luxury', 'car'),
                ('tezeract', 'Tezeract', 220000, 'Super', 'luxury', 'car'),
                ('thrax', 'Thrax', 180000, 'Super', 'luxury', 'car'),
                ('tigon', 'Tigon', 240000, 'Super', 'luxury', 'car'),
                ('turismor', 'Turismo R', 140000, 'Super', 'luxury', 'car'),
                ('tyrant', 'Tyrant', 2100000, 'Super', 'luxury', 'car'),
                ('tyrus', 'Tyrus', 230000, 'Super', 'luxury', 'car'),
                ('vacca', 'Vacca', 105000, 'Super', 'luxury', 'car'),
                ('vagner', 'Vagner', 1660000, 'Super', 'luxury', 'car'),
                ('visione', 'Visione', 750000, 'Super', 'luxury', 'car'),
                ('voltic', 'Voltic', 120000, 'Super', 'luxury', 'car'),
                ('voltic2', 'Rocket Voltic', 9830400, 'Super', 'luxury', 'car'),
                ('xa21', 'XA-21', 180000, 'Super', 'luxury', 'car'),
                ('zentorno', 'Zentorno', 340000, 'Super', 'luxury', 'car'),
                ('zorrusso', 'Zorrusso', 277000, 'Super', 'luxury', 'car'),
                ('bison', 'Bison', 33750, 'Vans', 'pdm', 'car'),
                ('bobcatxl', 'Bobcat XL Open', 26280, 'Vans', 'pdm', 'car'),
                ('burrito', 'Burrito', 23760, 'Vans', 'pdm', 'car'),
                ('gburrito2', 'Burrito Custom', 50580, 'Vans', 'pdm', 'car'),
                ('rumpo', 'Rumpo', 9000, 'Vans', 'pdm', 'car'),
                ('journey', 'Journey', 6500, 'Vans', 'pdm', 'car'),
                ('minivan', 'Minivan', 11160, 'Vans', 'pdm', 'car'),
                ('minivan2', 'Minivan Custom', 10000, 'Vans', 'pdm', 'car'),
                ('paradise', 'Paradise', 18990, 'Vans', 'pdm', 'car'),
                ('rumpo3', 'Rumpo Custom', 19500, 'Vans', 'pdm', 'car'),
                ('speedo', 'Speedo', 10000, 'Vans', 'pdm', 'car'),
                ('speedo4', 'Speedo Custom', 15000, 'Vans', 'pdm', 'car'),
                ('surfer', 'Surfer', 22680, 'Vans', 'pdm', 'car'),
                ('youga3', 'Youga Classic 4x4', 15000, 'Vans', 'pdm', 'car'),
                ('youga', 'Youga', 25290, 'Vans', 'pdm', 'car'),
                ('youga2', 'Youga Classic', 52290, 'Vans', 'pdm', 'car'),
                ('youga4', 'Youga', 85000, 'Vans', 'pdm', 'car'),
                ('mule5', 'Mule', 221000, 'Vans', 'pdm', 'car'),
                ('sadler', 'Sadler', 20000, 'Off-road', 'pdm', 'car'),
                ('guardian', 'Guardian', 21000, 'Off-road', 'pdm', 'car'),
                ('warrener2', 'Warrener HKR', 30000, 'Sedans', 'pdm', 'car'),
                ('ambcar', 'Granger', 35000, 'Suvs', NULL, 'car'),
                ('firetruk', 'Camion de pompier', 35000, 'Suvs', NULL, 'truck'),
                ('police5', 'STX', 35000, 'Muscle', NULL, 'car'),
                ('police6', 'Scout', 45000, 'Suvs', NULL, 'car'),
                ('sheriff3', 'Charger', 35000, 'Muscle', NULL, 'car'),
                ('sheriff4', 'Tahoe', 45000, 'Suvs', NULL, 'car'),
                ('sheriffb', 'Moto Sheriff', 25000, 'Motorcycles', NULL, 'moto'),
                ('paragonfbi', 'Paragon FBI', 60000, 'Sports', NULL, 'car'),
                ('cogfbi', 'Cognoscenti FBI', 22000, 'Sedans', NULL, 'car'),
                ('dynasty2', 'Dynasty', 24000, 'Sportsclassics', NULL, 'car'),
                ('burrito6', 'Burrito', 26000, 'Vans', NULL, 'car'),
                ('baller8', 'Baller ST', 45000, 'Sedans', NULL, 'car'),
                ('flatbed3', 'Flatbed', 45000, 'Industrial', NULL, 'truck'),
                ('mule6', 'Mule', 26000, 'Vans', NULL, 'car'),
                ('newsvan', 'Rumpo', 26000, 'Vans', NULL, 'car'),
                ('packer2', 'Packer', 27000, 'Industrial', NULL, 'truck'),
                ('tanker', 'Trailer', 10000, 'Industrial', NULL, 'truck'),
                ('stockade', 'Securicar', 30000, 'Commercial', NULL, 'car'),
                ('utillitruck4', 'Utility Truck', 20000, 'Utility', NULL, 'truck'),
                ('polmav', 'Maverick', 65000, 'Emergency', NULL, 'air'),
                ('ambulance', 'Ambulance', 25000, 'Emergency', NULL, 'car'),
                ('frogger3', 'Frogger', 65000, 'Emergency', NULL, 'air'),
                ('trash', 'Trashmaster', 18000, 'Utility', NULL, 'truck'),
                ('maverick2', 'Maverick', 65000, 'Emergency', NULL, 'air'),
                ('policeb', 'Moto de Police', 25000, 'Emergency', NULL, 'moto'),
                ('buzzard2', 'Buzzard', 100000, 'Helicopters', 'air', 'heli'),
                ('seasparrow', 'Sea Sparrow', 115000, 'Helicopters', 'air', 'heli'),
                ('supervolito', 'SuperVolito', 260000, 'Helicopters', 'air', 'heli'),
                ('supervolito1', 'SuperVolito', 65000, 'Helicopters', NULL, 'heli'),
                ('supervolito2', 'SuperVolito Carbon', 340000, 'Helicopters', 'air', 'heli'),
                ('swift', 'Swift', 450000, 'Helicopters', 'air', 'heli'),
                ('swift2', 'Swift Deluxe', 520000, 'Helicopters', 'air', 'heli'),
                ('volatus', 'Volatus', 600000, 'Helicopters', 'air', 'heli'),
                ('cargobob2', 'Cargobob', 65000, 'Helicopters', NULL, 'air'),
                ('sadler1', 'Sadler', 25000, 'Utility', NULL, 'car'),
                ('hauler1', 'Hauler', 25000, 'Commercial', NULL, 'truck'),
                ('trailerlogs', 'Remorque', 25000, 'Utility', NULL, 'truck'),
                ('brickade1', 'Brickade', 35000, 'Utility', NULL, 'truck'),
                ('boxville', 'Boxville', 24000, 'Utility', NULL, 'truck'),
                ('dinghy', 'Dinghy 4 Places', 50000, 'Boats', 'boat', 'boat'),
                ('dinghy2', 'Dinghy 2 Places', 50000, 'Boats', NULL, 'boat'),
                ('dinghy3', 'Dinghy', 50000, 'Boats', NULL, 'boat'),
                ('dinghy4', 'Dinghy Deluxe', 50000, 'Boats', NULL, 'boat'),
                ('jetmax', 'Jetmax', 60000, 'Boats', 'boat', 'boat'),
                ('marquis', 'Marquis', 120000, 'Boats', 'boat', 'boat'),
                ('seashark', 'Seashark', 15000, 'Boats', 'boat', 'boat'),
                ('seashark2', 'Seashark Deluxe', 20000, 'Boats', NULL, 'boat'),
                ('speeder', 'Speeder', 65000, 'Boats', 'boat', 'boat'),
                ('speeder2', 'Speeder Deluxe', 65000, 'Boats', 'boat', 'boat'),
                ('squalo', 'Squalo', 135000, 'Boats', 'boat', 'boat'),
                ('submersible', 'Submersible', 200000, 'Boats', NULL, 'boat'),
                ('submersible2', 'Kraken', 230000, 'Boats', NULL, 'boat'),
                ('avisa', 'Avisa', 290000, 'Boats', NULL, 'boat'),
                ('suntrap', 'Suntrap', 80000, 'Boats', 'boat', 'boat'),
                ('toro', 'Toro', 165000, 'Boats', 'boat', 'boat'),
                ('toro2', 'Toro Deluxe', 165000, 'Boats', 'boat', 'boat'),
                ('tropic', 'Tropic', 125000, 'Boats', 'boat', 'boat'),
                ('tropic2', 'Tropic Deluxe', 135000, 'Boats', 'boat', 'boat'),
                ('longfin', 'Longfin', 260000, 'Boats', 'boat', 'boat'),
                ('openwheel1', 'BR8', 666666, 'Openwheel', NULL, 'car'),
                ('openwheel2', 'DR1', 666666, 'Openwheel', NULL, 'car'),
                ('formula', 'PR4', 666666, 'Openwheel', NULL, 'car'),
                ('formula2', 'R88', 666666, 'Openwheel', NULL, 'car')
            ;
        ]],
        [[
            UPDATE vehicles SET size = 3 WHERE model IN ('firetruk', 'tanker');
        ]],
        [[
            UPDATE vehicles SET job_name = '{"lspd": "Police Polmav", "lsmc": "Ambulance Polmav"}' WHERE model = 'polmav';
        ]],
    },
});
