local function CreateItemsWithTextures(componentType, drawableId, textures)
    local items = {}
    for _, texture in pairs(textures) do
        local item = {
            Name = texture.Name,
            ApplyComponents = {[componentType] = {Drawable = drawableId, Texture = texture.Id, Palette = 0}},
        }

        table.insert(items, item)
    end
    return items
end

Config.Products["ponsonbys"] = {
    [GetHashKey("mp_m_freemode_01")] = {
        [1] = {
            Name = "Haut",
            Collections = {
                [1] = {
                    Name = "T-shirts & Polos",
                    Price = 50,
                    Items = table.unpack({
                        CreateItemsWithTextures(11, 9, {
                            {Name = GetLabelText("U_FMM_9_0"), Id = 0},
                            {Name = GetLabelText("U_FMM_9_1"), Id = 1},
                            {Name = GetLabelText("U_FMM_9_2"), Id = 2},
                            {Name = GetLabelText("U_FMM_9_3"), Id = 3},
                            {Name = GetLabelText("U_FMM_9_4"), Id = 4},
                            {Name = GetLabelText("U_FMM_9_5"), Id = 5},
                            {Name = GetLabelText("U_FMM_9_6"), Id = 6},
                            {Name = GetLabelText("U_FMM_9_7"), Id = 7},
                            {Name = GetLabelText("U_FMM_9_10"), Id = 10},
                            {Name = GetLabelText("U_FMM_9_11"), Id = 11},
                            {Name = GetLabelText("U_FMM_9_12"), Id = 12},
                            {Name = GetLabelText("U_FMM_9_13"), Id = 13},
                            {Name = GetLabelText("U_FMM_9_14"), Id = 14},
                            {Name = GetLabelText("U_FMM_9_15"), Id = 15},
                        }),
                        CreateItemsWithTextures(11, 73, {
                            {Name = GetLabelText("CLO_LXM_U_5_0"), Id = 0},
                            {Name = GetLabelText("CLO_LXM_U_5_1"), Id = 1},
                            {Name = GetLabelText("CLO_LXM_U_5_2"), Id = 2},
                            {Name = GetLabelText("CLO_LXM_U_5_3"), Id = 3},
                        }),
                        CreateItemsWithTextures(11, 82, {
                            {Name = GetLabelText("CLO_S1M_U_2_0"), Id = 0},
                            {Name = GetLabelText("CLO_S1M_U_2_1"), Id = 1},
                            {Name = GetLabelText("CLO_S1M_U_2_2"), Id = 2},
                            {Name = GetLabelText("CLO_S1M_U_2_3"), Id = 3},
                            {Name = GetLabelText("CLO_S1M_U_2_4"), Id = 4},
                            {Name = GetLabelText("CLO_S1M_U_2_5"), Id = 5},
                            {Name = GetLabelText("CLO_S1M_U_2_6"), Id = 6},
                            {Name = GetLabelText("CLO_S1M_U_2_7"), Id = 7},
                            {Name = GetLabelText("CLO_S1M_U_2_8"), Id = 8},
                            {Name = GetLabelText("CLO_S1M_U_2_9"), Id = 9},
                            {Name = GetLabelText("CLO_S1M_U_2_10"), Id = 10},
                            {Name = GetLabelText("CLO_S1M_U_2_11"), Id = 11},
                            {Name = GetLabelText("CLO_S1M_U_2_12"), Id = 12},
                            {Name = GetLabelText("CLO_S1M_U_2_13"), Id = 13},
                            {Name = GetLabelText("CLO_S1M_U_2_14"), Id = 14},
                            {Name = GetLabelText("CLO_S1M_U_2_15"), Id = 15},
                        }),
                        CreateItemsWithTextures(11, 93, {
                            {Name = GetLabelText("CLO_EXM_AU_2_0"), Id = 0},
                            {Name = GetLabelText("CLO_EXM_AU_2_1"), Id = 1},
                            {Name = GetLabelText("CLO_EXM_AU_2_2"), Id = 2},
                        }),
                        CreateItemsWithTextures(11, 94, {
                            {Name = GetLabelText("CLO_EXM_AU_3_0"), Id = 0},
                            {Name = GetLabelText("CLO_EXM_AU_3_1"), Id = 1},
                            {Name = GetLabelText("CLO_EXM_AU_3_2"), Id = 2},
                        }),
                        CreateItemsWithTextures(11, 111, {
                            {Name = "(DEBUG) 111_0", Id = 0},
                            {Name = "(DEBUG) 111_1", Id = 1},
                            {Name = "(DEBUG) 111_2", Id = 2},
                            {Name = "(DEBUG) 111_3", Id = 3},
                            {Name = "(DEBUG) 111_4", Id = 4},
                            {Name = "(DEBUG) 111_5", Id = 5},
                        }),
                        CreateItemsWithTextures(11, 131, {
                            {Name = GetLabelText("CLO_EXM_EU_2_0"), Id = 0},
                        }),
                        CreateItemsWithTextures(11, 132, {
                            {Name = GetLabelText("CLO_EXM_EU_3_0"), Id = 0},
                        }),
                        CreateItemsWithTextures(11, 133, {
                            {Name = GetLabelText("CLO_EXM_EU_4_0"), Id = 0},
                        }),
                        CreateItemsWithTextures(11, 199, {
                            {Name = GetLabelText("CLO_X4M_U_13_0"), Id = 0},
                            {Name = GetLabelText("CLO_X4M_U_13_1"), Id = 1},
                            {Name = GetLabelText("CLO_X4M_U_13_2"), Id = 2},
                            {Name = GetLabelText("CLO_X4M_U_13_3"), Id = 3},
                            {Name = GetLabelText("CLO_X4M_U_13_4"), Id = 4},
                            {Name = GetLabelText("CLO_X4M_U_13_5"), Id = 5},
                            {Name = GetLabelText("CLO_X4M_U_13_6"), Id = 6},
                            {Name = GetLabelText("CLO_X4M_U_13_7"), Id = 7},
                        }),
                        CreateItemsWithTextures(11, 235, {
                            {Name = GetLabelText("CLO_SMM_U_3_0"), Id = 0},
                            {Name = GetLabelText("CLO_SMM_U_3_1"), Id = 1},
                            {Name = GetLabelText("CLO_SMM_U_3_2"), Id = 2},
                            {Name = GetLabelText("CLO_SMM_U_3_3"), Id = 3},
                            {Name = GetLabelText("CLO_SMM_U_3_4"), Id = 4},
                            {Name = GetLabelText("CLO_SMM_U_3_5"), Id = 5},
                            {Name = GetLabelText("CLO_SMM_U_3_6"), Id = 6},
                            {Name = GetLabelText("CLO_SMM_U_3_7"), Id = 7},
                            {Name = GetLabelText("CLO_SMM_U_3_8"), Id = 8},
                            {Name = GetLabelText("CLO_SMM_U_3_9"), Id = 9},
                            {Name = GetLabelText("CLO_SMM_U_3_10"), Id = 10},
                            {Name = GetLabelText("CLO_SMM_U_3_11"), Id = 11},
                        }),
                        CreateItemsWithTextures(11, 236, {
                            {Name = GetLabelText("CLO_SMM_U_4_0"), Id = 0},
                            {Name = GetLabelText("CLO_SMM_U_4_1"), Id = 1},
                            {Name = GetLabelText("CLO_SMM_U_4_2"), Id = 2},
                            {Name = GetLabelText("CLO_SMM_U_4_3"), Id = 3},
                            {Name = GetLabelText("CLO_SMM_U_4_4"), Id = 4},
                            {Name = GetLabelText("CLO_SMM_U_4_5"), Id = 5},
                            {Name = GetLabelText("CLO_SMM_U_4_6"), Id = 6},
                            {Name = GetLabelText("CLO_SMM_U_4_7"), Id = 7},
                            {Name = GetLabelText("CLO_SMM_U_4_8"), Id = 8},
                            {Name = GetLabelText("CLO_SMM_U_4_9"), Id = 9},
                            {Name = GetLabelText("CLO_SMM_U_4_10"), Id = 10},
                            {Name = GetLabelText("CLO_SMM_U_4_11"), Id = 11},
                        }),
                        CreateItemsWithTextures(11, 241, {
                            {Name = "(DEBUG) 241_0", Id = 0},
                            {Name = "(DEBUG) 241_1", Id = 1},
                            {Name = "(DEBUG) 241_2", Id = 2},
                            {Name = "(DEBUG) 241_3", Id = 3},
                            {Name = "(DEBUG) 241_4", Id = 4},
                            {Name = "(DEBUG) 241_5", Id = 5},
                        }),
                        CreateItemsWithTextures(11, 318, {
                            {Name = GetLabelText("CLO_H3M_U_4_0"), Id = 0},
                            {Name = GetLabelText("CLO_H3M_U_4_1"), Id = 1},
                            {Name = GetLabelText("CLO_H3M_U_4_2"), Id = 2},
                            {Name = GetLabelText("CLO_H3M_U_4_3"), Id = 3},
                            {Name = GetLabelText("CLO_H3M_U_4_4"), Id = 4},
                            {Name = GetLabelText("CLO_H3M_U_4_5"), Id = 5},
                            {Name = GetLabelText("CLO_H3M_U_4_6"), Id = 6},
                            {Name = GetLabelText("CLO_H3M_U_4_7"), Id = 7},
                            {Name = GetLabelText("CLO_H3M_U_4_7"), Id = 8},
                        }),
                        CreateItemsWithTextures(11, 319, {
                            {Name = GetLabelText("CLO_H3M_U_5_0"), Id = 0},
                            {Name = GetLabelText("CLO_H3M_U_5_1"), Id = 1},
                            {Name = GetLabelText("CLO_H3M_U_5_2"), Id = 2},
                            {Name = GetLabelText("CLO_H3M_U_5_3"), Id = 3},
                            {Name = GetLabelText("CLO_H3M_U_5_4"), Id = 4},
                            {Name = GetLabelText("CLO_H3M_U_5_5"), Id = 5},
                            {Name = GetLabelText("CLO_H3M_U_5_6"), Id = 6},
                            {Name = GetLabelText("CLO_H3M_U_5_7"), Id = 7},
                            {Name = GetLabelText("CLO_H3M_U_5_7"), Id = 8},
                        }),
                        CreateItemsWithTextures(11, 336, {
                            {Name = GetLabelText("CLO_SUM_U_4_0"), Id = 0},
                            {Name = GetLabelText("CLO_SUM_U_4_1"), Id = 1},
                            {Name = GetLabelText("CLO_SUM_U_4_2"), Id = 2},
                            {Name = GetLabelText("CLO_SUM_U_4_3"), Id = 3},
                            {Name = GetLabelText("CLO_SUM_U_4_4"), Id = 4},
                            {Name = GetLabelText("CLO_SUM_U_4_5"), Id = 5},
                            {Name = GetLabelText("CLO_SUM_U_4_6"), Id = 6},
                            {Name = GetLabelText("CLO_SUM_U_4_7"), Id = 7},
                            {Name = GetLabelText("CLO_SUM_U_4_7"), Id = 8},
                        }),
                        CreateItemsWithTextures(11, 354, {
                            {Name = GetLabelText("CLO_H4M_U_3_0"), Id = 0},
                            {Name = GetLabelText("CLO_H4M_U_3_1"), Id = 1},
                            {Name = GetLabelText("CLO_H4M_U_3_2"), Id = 2},
                            {Name = GetLabelText("CLO_H4M_U_3_3"), Id = 3},
                            {Name = GetLabelText("CLO_H4M_U_3_4"), Id = 4},
                            {Name = GetLabelText("CLO_H4M_U_3_5"), Id = 5},
                            {Name = GetLabelText("CLO_H4M_U_3_6"), Id = 6},
                            {Name = GetLabelText("CLO_H4M_U_3_7"), Id = 7},
                            {Name = GetLabelText("CLO_H4M_U_3_8"), Id = 8},
                            {Name = GetLabelText("CLO_H4M_U_3_9"), Id = 9},
                            {Name = GetLabelText("CLO_H4M_U_3_10"), Id = 10},
                            {Name = GetLabelText("CLO_H4M_U_3_11"), Id = 11},
                            {Name = GetLabelText("CLO_H4M_U_3_12"), Id = 12},
                            {Name = GetLabelText("CLO_H4M_U_3_13"), Id = 13},
                            {Name = GetLabelText("CLO_H4M_U_3_14"), Id = 14},
                            {Name = GetLabelText("CLO_H4M_U_3_15"), Id = 15},
                            {Name = GetLabelText("CLO_H4M_U_3_16"), Id = 16},
                            {Name = GetLabelText("CLO_H4M_U_3_17"), Id = 17},
                            {Name = GetLabelText("CLO_H4M_U_3_18"), Id = 18},
                            {Name = GetLabelText("CLO_H4M_U_3_19"), Id = 19},
                            {Name = GetLabelText("CLO_H4M_U_3_20"), Id = 20},
                            {Name = GetLabelText("CLO_H4M_U_3_21"), Id = 21},
                            {Name = GetLabelText("CLO_H4M_U_3_22"), Id = 22},
                            {Name = GetLabelText("CLO_H4M_U_3_23"), Id = 23},
                            {Name = GetLabelText("CLO_H4M_U_3_24"), Id = 24},
                            {Name = GetLabelText("CLO_H4M_U_3_25"), Id = 25},
                        }),
                        CreateItemsWithTextures(11, 355, {
                            {Name = GetLabelText("CLO_H4M_U_3_0"), Id = 0},
                            {Name = GetLabelText("CLO_H4M_U_3_1"), Id = 1},
                            {Name = GetLabelText("CLO_H4M_U_3_2"), Id = 2},
                            {Name = GetLabelText("CLO_H4M_U_3_3"), Id = 3},
                            {Name = GetLabelText("CLO_H4M_U_3_4"), Id = 4},
                            {Name = GetLabelText("CLO_H4M_U_3_5"), Id = 5},
                            {Name = GetLabelText("CLO_H4M_U_3_6"), Id = 6},
                            {Name = GetLabelText("CLO_H4M_U_3_7"), Id = 7},
                            {Name = GetLabelText("CLO_H4M_U_3_8"), Id = 8},
                            {Name = GetLabelText("CLO_H4M_U_3_9"), Id = 9},
                            {Name = GetLabelText("CLO_H4M_U_3_10"), Id = 10},
                            {Name = GetLabelText("CLO_H4M_U_3_11"), Id = 11},
                            {Name = GetLabelText("CLO_H4M_U_3_12"), Id = 12},
                            {Name = GetLabelText("CLO_H4M_U_3_13"), Id = 13},
                            {Name = GetLabelText("CLO_H4M_U_3_14"), Id = 14},
                            {Name = GetLabelText("CLO_H4M_U_3_15"), Id = 15},
                            {Name = GetLabelText("CLO_H4M_U_3_16"), Id = 16},
                            {Name = GetLabelText("CLO_H4M_U_3_17"), Id = 17},
                            {Name = GetLabelText("CLO_H4M_U_3_18"), Id = 18},
                            {Name = GetLabelText("CLO_H4M_U_3_19"), Id = 19},
                            {Name = GetLabelText("CLO_H4M_U_3_20"), Id = 20},
                            {Name = GetLabelText("CLO_H4M_U_3_21"), Id = 21},
                            {Name = GetLabelText("CLO_H4M_U_3_22"), Id = 22},
                            {Name = GetLabelText("CLO_H4M_U_3_23"), Id = 23},
                            {Name = GetLabelText("CLO_H4M_U_3_24"), Id = 24},
                            {Name = GetLabelText("CLO_H4M_U_3_25"), Id = 25},
                        }),
                        CreateItemsWithTextures(11, 382, {
                            {Name = GetLabelText("CLO_FXM_U_0_0"), Id = 0},
                            {Name = GetLabelText("CLO_FXM_U_0_1"), Id = 1},
                            {Name = GetLabelText("CLO_FXM_U_0_2"), Id = 2},
                            {Name = GetLabelText("CLO_FXM_U_0_3"), Id = 3},
                            {Name = GetLabelText("CLO_FXM_U_0_4"), Id = 4},
                            {Name = GetLabelText("CLO_FXM_U_0_5"), Id = 5},
                            {Name = GetLabelText("CLO_FXM_U_0_6"), Id = 6},
                            {Name = GetLabelText("CLO_FXM_U_0_7"), Id = 7},
                        }),
                        CreateItemsWithTextures(11, 383, {
                            {Name = GetLabelText("CLO_FXM_U_1_0"), Id = 0},
                            {Name = GetLabelText("CLO_FXM_U_1_1"), Id = 1},
                            {Name = GetLabelText("CLO_FXM_U_1_2"), Id = 2},
                            {Name = GetLabelText("CLO_FXM_U_1_3"), Id = 3},
                            {Name = GetLabelText("CLO_FXM_U_1_4"), Id = 4},
                            {Name = GetLabelText("CLO_FXM_U_1_5"), Id = 5},
                            {Name = GetLabelText("CLO_FXM_U_1_6"), Id = 6},
                            {Name = GetLabelText("CLO_FXM_U_1_7"), Id = 7},
                        }),
                        CreateItemsWithTextures(11, 392, {
                            {Name = GetLabelText("CLO_FXM_U_10_0"), Id = 0},
                            {Name = GetLabelText("CLO_FXM_U_10_1"), Id = 1},
                            {Name = GetLabelText("CLO_FXM_U_10_2"), Id = 2},
                            {Name = GetLabelText("CLO_FXM_U_10_3"), Id = 3},
                            {Name = GetLabelText("CLO_FXM_U_10_4"), Id = 4},
                        }),
                    }),
                },
                [2] = {
                    Name = "Pulls & gilets",
                    Price = 50,
                    Items = table.unpack({
                        CreateItemsWithTextures(11, 11, {
                            {Name = GetLabelText("U_FMM_11_0"), Id = 0},
                            {Name = GetLabelText("U_FMM_11_1"), Id = 1},
                            {Name = GetLabelText("U_FMM_11_7"), Id = 7},
                            {Name = GetLabelText("U_FMM_11_14"), Id = 14},
                        }),
                        CreateItemsWithTextures(11, 40, {
                            {Name = GetLabelText("CLO_HP_U_7_0"), Id = 0},
                            {Name = GetLabelText("CLO_HP_U_7_1"), Id = 1},
                        }),
                        CreateItemsWithTextures(11, 45, {
                            {Name = GetLabelText("CLO_INDM_U_0_0"), Id = 0},
                            {Name = GetLabelText("CLO_INDM_U_0_1"), Id = 1},
                            {Name = GetLabelText("CLO_INDM_U_0_2"), Id = 2},
                        }),
                        CreateItemsWithTextures(11, 120, {
                            {Name = GetLabelText("CLO_V2M_U_1_11"), Id = 11},
                        }),
                        CreateItemsWithTextures(11, 139, {
                            {Name = GetLabelText("CLO_EXM_EU_10_0"), Id = 0},
                            {Name = GetLabelText("CLO_EXM_EU_10_1"), Id = 1},
                            {Name = GetLabelText("CLO_EXM_EU_10_2"), Id = 2},
                            {Name = GetLabelText("CLO_EXM_EU_10_3"), Id = 3},
                            {Name = GetLabelText("CLO_EXM_EU_10_4"), Id = 4},
                            {Name = GetLabelText("CLO_EXM_EU_10_5"), Id = 5},
                            {Name = GetLabelText("CLO_EXM_EU_10_6"), Id = 6},
                            {Name = GetLabelText("CLO_EXM_EU_10_7"), Id = 7},
                        }),
                        CreateItemsWithTextures(11, 198, {
                            {Name = GetLabelText("CLO_X4M_U_12_0"), Id = 0},
                            {Name = GetLabelText("CLO_X4M_U_12_1"), Id = 1},
                            {Name = GetLabelText("CLO_X4M_U_12_2"), Id = 2},
                            {Name = GetLabelText("CLO_X4M_U_12_3"), Id = 3},
                            {Name = GetLabelText("CLO_X4M_U_12_4"), Id = 4},
                            {Name = GetLabelText("CLO_X4M_U_12_5"), Id = 5},
                            {Name = GetLabelText("CLO_X4M_U_12_6"), Id = 6},
                            {Name = GetLabelText("CLO_X4M_U_12_7"), Id = 7},
                        }),
                        CreateItemsWithTextures(11, 201, {
                            {Name = "(DEBUG) 201_0", Id = 0},
                            {Name = "(DEBUG) 201_1", Id = 1},
                            {Name = "(DEBUG) 201_2", Id = 2},
                        }),
                        CreateItemsWithTextures(11, 242, {
                            {Name = "(DEBUG) 242_0", Id = 0},
                            {Name = "(DEBUG) 242_1", Id = 1},
                            {Name = "(DEBUG) 242_2", Id = 2},
                            {Name = "(DEBUG) 242_3", Id = 3},
                            {Name = "(DEBUG) 242_4", Id = 4},
                            {Name = "(DEBUG) 242_5", Id = 5},
                        }),
                        CreateItemsWithTextures(11, 258, {
                            {Name = GetLabelText("CLO_BHM_U_3_0"), Id = 0},
                            {Name = GetLabelText("CLO_BHM_U_3_1"), Id = 1},
                            {Name = GetLabelText("CLO_BHM_U_3_2"), Id = 2},
                            {Name = GetLabelText("CLO_BHM_U_3_3"), Id = 3},
                            {Name = GetLabelText("CLO_BHM_U_3_4"), Id = 4},
                            {Name = GetLabelText("CLO_BHM_U_3_5"), Id = 5},
                            {Name = GetLabelText("CLO_BHM_U_3_6"), Id = 6},
                            {Name = GetLabelText("CLO_BHM_U_3_7"), Id = 7},
                            {Name = GetLabelText("CLO_BHM_U_3_8"), Id = 8},
                            {Name = GetLabelText("CLO_BHM_U_3_9"), Id = 9},
                            {Name = GetLabelText("CLO_BHM_U_3_10"), Id = 10},
                            {Name = "(DEBUG) 258_11", Id = 11},
                            {Name = "(DEBUG) 258_12", Id = 12},
                            {Name = "(DEBUG) 258_13", Id = 13},
                            {Name = "(DEBUG) 258_14", Id = 14},
                        }),
                        CreateItemsWithTextures(11, 290, {
                            {Name = "(DEBUG) 290_0", Id = 0},
                        }),
                        CreateItemsWithTextures(11, 306, {
                            {Name = GetLabelText("CLO_VWM_U_15_0"), Id = 0},
                            {Name = GetLabelText("CLO_VWM_U_15_1"), Id = 1},
                            {Name = GetLabelText("CLO_VWM_U_15_3"), Id = 3},
                            {Name = GetLabelText("CLO_VWM_U_15_4"), Id = 4},
                            {Name = GetLabelText("CLO_VWM_U_15_6"), Id = 6},
                            {Name = GetLabelText("CLO_VWM_U_15_9"), Id = 9},
                        }),
                        CreateItemsWithTextures(11, 365, {
                            {Name = "(DEBUG) 265_0", Id = 0},
                        }),
                    }),
                },
                [3] = {
                    Name = "Sweats & Hoodies",
                    Price = 50,
                    Items = table.unpack({
                        CreateItemsWithTextures(11, 305, {
                            {Name = GetLabelText("CLO_VWM_U_15_0"), Id = 0},
                            {Name = GetLabelText("CLO_VWM_U_15_1"), Id = 1},
                            {Name = GetLabelText("CLO_VWM_U_15_3"), Id = 3},
                            {Name = GetLabelText("CLO_VWM_U_15_4"), Id = 4},
                            {Name = GetLabelText("CLO_VWM_U_15_6"), Id = 6},
                            {Name = GetLabelText("CLO_VWM_U_15_9"), Id = 9},
                        }),
                        CreateItemsWithTextures(11, 384, {
                            {Name = GetLabelText("CLO_FXM_U_2_0"), Id = 0},
                            {Name = GetLabelText("CLO_FXM_U_2_1"), Id = 1},
                            {Name = GetLabelText("CLO_FXM_U_2_2"), Id = 2},
                            {Name = GetLabelText("CLO_FXM_U_2_3"), Id = 3},
                            {Name = GetLabelText("CLO_FXM_U_2_4"), Id = 4},
                            {Name = GetLabelText("CLO_FXM_U_2_5"), Id = 5},
                            {Name = GetLabelText("CLO_FXM_U_2_6"), Id = 6},
                            {Name = GetLabelText("CLO_FXM_U_2_7"), Id = 7},
                            {Name = GetLabelText("CLO_FXM_U_2_8"), Id = 8},
                            {Name = GetLabelText("CLO_FXM_U_2_9"), Id = 9},
                            {Name = GetLabelText("CLO_FXM_U_2_10"), Id = 10},
                            {Name = GetLabelText("CLO_FXM_U_2_11"), Id = 11},
                            {Name = GetLabelText("CLO_FXM_U_2_12"), Id = 12},
                            {Name = GetLabelText("CLO_FXM_U_2_13"), Id = 13},
                            {Name = GetLabelText("CLO_FXM_U_2_14"), Id = 14},
                            {Name = GetLabelText("CLO_FXM_U_2_15"), Id = 15},
                            {Name = GetLabelText("CLO_FXM_U_2_16"), Id = 16},
                            {Name = GetLabelText("CLO_FXM_U_2_17"), Id = 17},
                            {Name = GetLabelText("CLO_FXM_U_2_18"), Id = 18},
                            {Name = GetLabelText("CLO_FXM_U_2_19"), Id = 19},
                            {Name = GetLabelText("CLO_FXM_U_2_20"), Id = 20},
                        }),
                        CreateItemsWithTextures(11, 385, {
                            {Name = GetLabelText("CLO_FXM_U_2_0"), Id = 0},
                            {Name = GetLabelText("CLO_FXM_U_2_1"), Id = 1},
                            {Name = GetLabelText("CLO_FXM_U_2_2"), Id = 2},
                            {Name = GetLabelText("CLO_FXM_U_2_3"), Id = 3},
                            {Name = GetLabelText("CLO_FXM_U_2_4"), Id = 4},
                            {Name = GetLabelText("CLO_FXM_U_2_5"), Id = 5},
                            {Name = GetLabelText("CLO_FXM_U_2_6"), Id = 6},
                            {Name = GetLabelText("CLO_FXM_U_2_7"), Id = 7},
                            {Name = GetLabelText("CLO_FXM_U_2_8"), Id = 8},
                            {Name = GetLabelText("CLO_FXM_U_2_9"), Id = 9},
                            {Name = GetLabelText("CLO_FXM_U_2_10"), Id = 10},
                            {Name = GetLabelText("CLO_FXM_U_2_11"), Id = 11},
                            {Name = GetLabelText("CLO_FXM_U_2_12"), Id = 12},
                            {Name = GetLabelText("CLO_FXM_U_2_13"), Id = 13},
                            {Name = GetLabelText("CLO_FXM_U_2_14"), Id = 14},
                            {Name = GetLabelText("CLO_FXM_U_2_15"), Id = 15},
                            {Name = GetLabelText("CLO_FXM_U_2_16"), Id = 16},
                            {Name = GetLabelText("CLO_FXM_U_2_17"), Id = 17},
                            {Name = GetLabelText("CLO_FXM_U_2_18"), Id = 18},
                            {Name = GetLabelText("CLO_FXM_U_2_19"), Id = 19},
                            {Name = GetLabelText("CLO_FXM_U_2_20"), Id = 20},
                        }),
                    }),
                },
                [4] = {
                    Name = "Chemises",
                    Price = 50,
                    Items = table.unpack({
                        CreateItemsWithTextures(11, 13, {
                            {Name = GetLabelText("U_FMM_13_0"), Id = 0},
                            {Name = GetLabelText("U_FMM_13_1"), Id = 1},
                            {Name = GetLabelText("U_FMM_13_2"), Id = 2},
                            {Name = GetLabelText("U_FMM_13_3"), Id = 3},
                            {Name = GetLabelText("U_FMM_13_5"), Id = 5},
                            {Name = GetLabelText("U_FMM_13_13"), Id = 13},
                        }),
                        CreateItemsWithTextures(11, 26, {
                            {Name = GetLabelText("CLO_BUSM_U_3_0"), Id = 0},
                            {Name = GetLabelText("CLO_BUSM_U_3_1"), Id = 1},
                            {Name = GetLabelText("CLO_BUSM_U_3_2"), Id = 2},
                            {Name = GetLabelText("CLO_BUSM_U_3_3"), Id = 3},
                            {Name = GetLabelText("CLO_BUSM_U_3_4"), Id = 4},
                            {Name = GetLabelText("CLO_BUSM_U_3_5"), Id = 5},
                            {Name = GetLabelText("CLO_BUSM_U_3_6"), Id = 6},
                            {Name = GetLabelText("CLO_BUSM_U_3_7"), Id = 7},
                            {Name = GetLabelText("CLO_BUSM_U_3_8"), Id = 8},
                            {Name = GetLabelText("CLO_BUSM_U_3_9"), Id = 9},
                        }),
                        CreateItemsWithTextures(11, 92, {
                            {Name = GetLabelText("CLO_APM_U_1_0"), Id = 0},
                            {Name = GetLabelText("CLO_APM_U_1_1"), Id = 1},
                            {Name = GetLabelText("CLO_APM_U_1_2"), Id = 2},
                            {Name = GetLabelText("CLO_APM_U_1_3"), Id = 3},
                            {Name = GetLabelText("CLO_APM_U_1_4"), Id = 4},
                            {Name = GetLabelText("CLO_APM_U_1_5"), Id = 5},
                            {Name = GetLabelText("CLO_APM_U_1_6"), Id = 6},
                        }),
                        CreateItemsWithTextures(11, 95, {
                            {Name = GetLabelText("CLO_EXM_AU_4_0"), Id = 0},
                            {Name = GetLabelText("CLO_EXM_AU_4_1"), Id = 1},
                            {Name = GetLabelText("CLO_EXM_AU_4_2"), Id = 2},
                        }),
                        CreateItemsWithTextures(11, 234, {
                            {Name = GetLabelText("CLO_SMM_U_2_0"), Id = 0},
                            {Name = GetLabelText("CLO_SMM_U_2_1"), Id = 1},
                            {Name = GetLabelText("CLO_SMM_U_2_2"), Id = 2},
                            {Name = GetLabelText("CLO_SMM_U_2_3"), Id = 3},
                            {Name = GetLabelText("CLO_SMM_U_2_4"), Id = 4},
                            {Name = GetLabelText("CLO_SMM_U_2_5"), Id = 5},
                            {Name = GetLabelText("CLO_SMM_U_2_6"), Id = 6},
                            {Name = GetLabelText("CLO_SMM_U_2_7"), Id = 7},
                            {Name = GetLabelText("CLO_SMM_U_2_8"), Id = 8},
                            {Name = GetLabelText("CLO_SMM_U_2_9"), Id = 9},
                            {Name = GetLabelText("CLO_SMM_U_2_10"), Id = 10},
                            {Name = GetLabelText("CLO_SMM_U_2_11"), Id = 11},
                            {Name = GetLabelText("CLO_SMM_U_2_12"), Id = 12},
                            {Name = GetLabelText("CLO_SMM_U_2_13"), Id = 13},
                            {Name = GetLabelText("CLO_SMM_U_2_14"), Id = 14},
                            {Name = GetLabelText("CLO_SMM_U_2_15"), Id = 15},
                            {Name = GetLabelText("CLO_SMM_U_2_16"), Id = 16},
                            {Name = GetLabelText("CLO_SMM_U_2_17"), Id = 17},
                            {Name = GetLabelText("CLO_SMM_U_2_18"), Id = 18},
                            {Name = GetLabelText("CLO_SMM_U_2_19"), Id = 19},
                            {Name = GetLabelText("CLO_SMM_U_2_20"), Id = 20},
                            {Name = GetLabelText("CLO_SMM_U_2_21"), Id = 21},
                            {Name = GetLabelText("CLO_SMM_U_2_22"), Id = 22},
                            {Name = GetLabelText("CLO_SMM_U_2_23"), Id = 23},
                            {Name = GetLabelText("CLO_SMM_U_2_24"), Id = 24},
                            {Name = GetLabelText("CLO_SMM_U_2_25"), Id = 25},
                        }),
                        CreateItemsWithTextures(11, 260, {
                            {Name = GetLabelText("CLO_BHM_U_5_0"), Id = 0},
                            {Name = GetLabelText("CLO_BHM_U_5_1"), Id = 1},
                            {Name = GetLabelText("CLO_BHM_U_5_2"), Id = 2},
                            {Name = GetLabelText("CLO_BHM_U_5_3"), Id = 3},
                            {Name = GetLabelText("CLO_BHM_U_5_4"), Id = 4},
                            {Name = GetLabelText("CLO_BHM_U_5_5"), Id = 5},
                            {Name = GetLabelText("CLO_BHM_U_5_6"), Id = 6},
                            {Name = GetLabelText("CLO_BHM_U_5_7"), Id = 7},
                            {Name = GetLabelText("CLO_BHM_U_5_8"), Id = 8},
                            {Name = GetLabelText("CLO_BHM_U_5_9"), Id = 9},
                            {Name = GetLabelText("CLO_BHM_U_5_10"), Id = 10},
                            {Name = GetLabelText("CLO_BHM_U_5_11"), Id = 11},
                            {Name = GetLabelText("CLO_BHM_U_5_12"), Id = 12},
                            {Name = GetLabelText("CLO_BHM_U_5_13"), Id = 13},
                            {Name = GetLabelText("CLO_BHM_U_5_14"), Id = 14},
                            {Name = GetLabelText("CLO_BHM_U_5_15"), Id = 15},
                            {Name = GetLabelText("CLO_BHM_U_5_16"), Id = 16},
                            {Name = GetLabelText("CLO_BHM_U_5_17"), Id = 17},
                            {Name = GetLabelText("CLO_BHM_U_5_18"), Id = 18},
                            {Name = GetLabelText("CLO_BHM_U_5_19"), Id = 19},
                            {Name = GetLabelText("CLO_BHM_U_5_20"), Id = 20},
                            {Name = GetLabelText("CLO_BHM_U_5_21"), Id = 21},
                        }),
                        CreateItemsWithTextures(11, 316, {
                            {Name = GetLabelText("CLO_H3M_U_2_0"), Id = 0},
                            {Name = GetLabelText("CLO_H3M_U_2_1"), Id = 1},
                            {Name = GetLabelText("CLO_H3M_U_2_2"), Id = 2},
                            {Name = GetLabelText("CLO_H3M_U_2_3"), Id = 3},
                            {Name = GetLabelText("CLO_H3M_U_2_4"), Id = 4},
                            {Name = GetLabelText("CLO_H3M_U_2_5"), Id = 5},
                            {Name = GetLabelText("CLO_H3M_U_2_6"), Id = 6},
                            {Name = GetLabelText("CLO_H3M_U_2_7"), Id = 7},
                            {Name = GetLabelText("CLO_H3M_U_2_8"), Id = 8},
                        }),
                        CreateItemsWithTextures(11, 317, {
                            {Name = GetLabelText("CLO_H3M_U_3_0"), Id = 0},
                            {Name = GetLabelText("CLO_H3M_U_3_1"), Id = 1},
                            {Name = GetLabelText("CLO_H3M_U_3_2"), Id = 2},
                            {Name = GetLabelText("CLO_H3M_U_3_3"), Id = 3},
                            {Name = GetLabelText("CLO_H3M_U_3_4"), Id = 4},
                            {Name = GetLabelText("CLO_H3M_U_3_5"), Id = 5},
                            {Name = GetLabelText("CLO_H3M_U_3_6"), Id = 6},
                            {Name = GetLabelText("CLO_H3M_U_3_7"), Id = 7},
                            {Name = GetLabelText("CLO_H3M_U_3_8"), Id = 8},
                        }),
                        CreateItemsWithTextures(11, 321, {
                            {Name = GetLabelText("CLO_H3M_U_7_0"), Id = 0},
                        }),
                        CreateItemsWithTextures(11, 322, {
                            {Name = GetLabelText("CLO_H3M_U_7_0"), Id = 0},
                        }),
                        CreateItemsWithTextures(11, 337, {
                            {Name = GetLabelText("CLO_SUM_U_5_0"), Id = 0},
                            {Name = GetLabelText("CLO_SUM_U_5_1"), Id = 1},
                            {Name = GetLabelText("CLO_SUM_U_5_2"), Id = 2},
                            {Name = GetLabelText("CLO_SUM_U_5_3"), Id = 3},
                            {Name = GetLabelText("CLO_SUM_U_5_4"), Id = 4},
                            {Name = GetLabelText("CLO_SUM_U_5_5"), Id = 5},
                            {Name = GetLabelText("CLO_SUM_U_5_6"), Id = 6},
                            {Name = GetLabelText("CLO_SUM_U_5_7"), Id = 7},
                            {Name = GetLabelText("CLO_SUM_U_5_8"), Id = 8},
                        }),
                        CreateItemsWithTextures(11, 348, {
                            {Name = GetLabelText("CLO_SUM_U_16_0"), Id = 0},
                            {Name = GetLabelText("CLO_SUM_U_16_1"), Id = 1},
                            {Name = GetLabelText("CLO_SUM_U_16_2"), Id = 2},
                            {Name = GetLabelText("CLO_SUM_U_16_3"), Id = 3},
                            {Name = GetLabelText("CLO_SUM_U_16_4"), Id = 4},
                            {Name = GetLabelText("CLO_SUM_U_16_5"), Id = 5},
                            {Name = GetLabelText("CLO_SUM_U_16_6"), Id = 6},
                            {Name = GetLabelText("CLO_SUM_U_16_7"), Id = 7},
                            {Name = GetLabelText("CLO_SUM_U_16_8"), Id = 8},
                            {Name = GetLabelText("CLO_SUM_U_16_9"), Id = 9},
                            {Name = GetLabelText("CLO_SUM_U_16_10"), Id = 10},
                            {Name = GetLabelText("CLO_SUM_U_16_11"), Id = 11},
                            {Name = GetLabelText("CLO_SUM_U_16_12"), Id = 12},
                            {Name = GetLabelText("CLO_SUM_U_16_13"), Id = 13},
                            {Name = GetLabelText("CLO_SUM_U_16_14"), Id = 14},
                            {Name = GetLabelText("CLO_SUM_U_16_15"), Id = 15},
                            {Name = GetLabelText("CLO_SUM_U_16_16"), Id = 16},
                            {Name = GetLabelText("CLO_SUM_U_16_17"), Id = 17},
                            {Name = GetLabelText("CLO_SUM_U_16_18"), Id = 18},
                            {Name = GetLabelText("CLO_SUM_U_16_19"), Id = 19},
                        }),
                        CreateItemsWithTextures(11, 349, {
                            {Name = GetLabelText("CLO_SUM_U_17_0"), Id = 0},
                            {Name = GetLabelText("CLO_SUM_U_17_1"), Id = 1},
                            {Name = GetLabelText("CLO_SUM_U_17_2"), Id = 2},
                            {Name = GetLabelText("CLO_SUM_U_17_3"), Id = 3},
                            {Name = GetLabelText("CLO_SUM_U_17_4"), Id = 4},
                            {Name = GetLabelText("CLO_SUM_U_17_5"), Id = 5},
                            {Name = GetLabelText("CLO_SUM_U_17_6"), Id = 6},
                            {Name = GetLabelText("CLO_SUM_U_17_7"), Id = 7},
                            {Name = GetLabelText("CLO_SUM_U_17_8"), Id = 8},
                            {Name = GetLabelText("CLO_SUM_U_17_9"), Id = 9},
                            {Name = GetLabelText("CLO_SUM_U_17_10"), Id = 10},
                            {Name = GetLabelText("CLO_SUM_U_17_11"), Id = 11},
                            {Name = GetLabelText("CLO_SUM_U_17_12"), Id = 12},
                            {Name = GetLabelText("CLO_SUM_U_17_13"), Id = 13},
                            {Name = GetLabelText("CLO_SUM_U_17_14"), Id = 14},
                            {Name = GetLabelText("CLO_SUM_U_17_15"), Id = 15},
                            {Name = GetLabelText("CLO_SUM_U_17_16"), Id = 16},
                            {Name = GetLabelText("CLO_SUM_U_17_17"), Id = 17},
                            {Name = GetLabelText("CLO_SUM_U_17_18"), Id = 18},
                            {Name = GetLabelText("CLO_SUM_U_17_19"), Id = 19},
                        }),
                        CreateItemsWithTextures(11, 388, {
                            {Name = GetLabelText("CLO_FXM_U_6_0"), Id = 0},
                            {Name = GetLabelText("CLO_FXM_U_6_1"), Id = 1},
                            {Name = GetLabelText("CLO_FXM_U_6_2"), Id = 2},
                            {Name = GetLabelText("CLO_FXM_U_6_3"), Id = 3},
                            {Name = GetLabelText("CLO_FXM_U_6_4"), Id = 4},
                            {Name = GetLabelText("CLO_FXM_U_6_5"), Id = 5},
                            {Name = GetLabelText("CLO_FXM_U_6_6"), Id = 6},
                            {Name = GetLabelText("CLO_FXM_U_6_7"), Id = 7},
                            {Name = GetLabelText("CLO_FXM_U_6_8"), Id = 8},
                            {Name = GetLabelText("CLO_FXM_U_6_9"), Id = 9},
                            {Name = GetLabelText("CLO_FXM_U_6_10"), Id = 10},
                            {Name = GetLabelText("CLO_FXM_U_6_11"), Id = 11},
                            {Name = GetLabelText("CLO_FXM_U_6_12"), Id = 12},
                            {Name = GetLabelText("CLO_FXM_U_6_13"), Id = 13},
                            {Name = GetLabelText("CLO_FXM_U_6_14"), Id = 14},
                            {Name = GetLabelText("CLO_FXM_U_6_15"), Id = 15},
                            {Name = GetLabelText("CLO_FXM_U_6_16"), Id = 16},
                            {Name = GetLabelText("CLO_FXM_U_6_17"), Id = 17},
                            {Name = GetLabelText("CLO_FXM_U_6_18"), Id = 18},
                            {Name = GetLabelText("CLO_FXM_U_6_19"), Id = 19},
                            {Name = GetLabelText("CLO_FXM_U_6_20"), Id = 20},
                            {Name = GetLabelText("CLO_FXM_U_6_21"), Id = 21},
                            {Name = GetLabelText("CLO_FXM_U_6_22"), Id = 22},
                            {Name = GetLabelText("CLO_FXM_U_6_23"), Id = 23},
                            {Name = GetLabelText("CLO_FXM_U_6_24"), Id = 24},
                            {Name = GetLabelText("CLO_FXM_U_6_25"), Id = 25},
                        }),
                        CreateItemsWithTextures(11, 389, {
                            {Name = GetLabelText("CLO_FXM_U_7_0"), Id = 0},
                            {Name = GetLabelText("CLO_FXM_U_7_1"), Id = 1},
                            {Name = GetLabelText("CLO_FXM_U_7_2"), Id = 2},
                        }),
                        CreateItemsWithTextures(11, 390, {
                            {Name = GetLabelText("CLO_FXM_U_6_0"), Id = 0},
                            {Name = GetLabelText("CLO_FXM_U_6_1"), Id = 1},
                            {Name = GetLabelText("CLO_FXM_U_6_2"), Id = 2},
                            {Name = GetLabelText("CLO_FXM_U_6_3"), Id = 3},
                            {Name = GetLabelText("CLO_FXM_U_6_4"), Id = 4},
                            {Name = GetLabelText("CLO_FXM_U_6_5"), Id = 5},
                            {Name = GetLabelText("CLO_FXM_U_6_6"), Id = 6},
                            {Name = GetLabelText("CLO_FXM_U_6_7"), Id = 7},
                            {Name = GetLabelText("CLO_FXM_U_6_8"), Id = 8},
                            {Name = GetLabelText("CLO_FXM_U_6_9"), Id = 9},
                            {Name = GetLabelText("CLO_FXM_U_6_10"), Id = 10},
                            {Name = GetLabelText("CLO_FXM_U_6_11"), Id = 11},
                            {Name = GetLabelText("CLO_FXM_U_6_12"), Id = 12},
                            {Name = GetLabelText("CLO_FXM_U_6_13"), Id = 13},
                            {Name = GetLabelText("CLO_FXM_U_6_14"), Id = 14},
                            {Name = GetLabelText("CLO_FXM_U_6_15"), Id = 15},
                            {Name = GetLabelText("CLO_FXM_U_6_16"), Id = 16},
                            {Name = GetLabelText("CLO_FXM_U_6_17"), Id = 17},
                            {Name = GetLabelText("CLO_FXM_U_6_18"), Id = 18},
                            {Name = GetLabelText("CLO_FXM_U_6_19"), Id = 19},
                            {Name = GetLabelText("CLO_FXM_U_6_20"), Id = 20},
                            {Name = GetLabelText("CLO_FXM_U_6_21"), Id = 21},
                            {Name = GetLabelText("CLO_FXM_U_6_22"), Id = 22},
                            {Name = GetLabelText("CLO_FXM_U_6_23"), Id = 23},
                            {Name = GetLabelText("CLO_FXM_U_6_24"), Id = 24},
                            {Name = GetLabelText("CLO_FXM_U_6_25"), Id = 25},
                        }),
                        CreateItemsWithTextures(11, 391, {
                            {Name = GetLabelText("CLO_FXM_U_7_0"), Id = 0},
                            {Name = GetLabelText("CLO_FXM_U_7_1"), Id = 1},
                            {Name = GetLabelText("CLO_FXM_U_7_2"), Id = 2},
                        }),
                    }),
                },
            },
        },
        [2] = {
            Name = "Pantalon",
            Collections = {
                [1] = {
                    Name = "Jeans",
                    Price = 50,
                    Items = table.unpack({
                        CreateItemsWithTextures(4, 4, {
                            {Name = GetLabelText("L_FMM_4_0"), Id = 0},
                            {Name = GetLabelText("L_FMM_4_1"), Id = 1},
                            {Name = GetLabelText("L_FMM_4_2"), Id = 2},
                            {Name = GetLabelText("L_FMM_4_4"), Id = 4},
                        }),
                    }),
                },
                [2] = {
                    Name = "Short & Bermudas",
                    Price = 50,
                    Items = table.unpack({
                        CreateItemsWithTextures(4, 6, {
                            {Name = GetLabelText("L_FMM_6_0"), Id = 0},
                            {Name = GetLabelText("L_FMM_6_1"), Id = 1},
                            {Name = GetLabelText("L_FMM_6_2"), Id = 2},
                            {Name = GetLabelText("L_FMM_6_10"), Id = 10},
                        }),
                        CreateItemsWithTextures(4, 14, {
                            {Name = GetLabelText("L_FMM_12_0"), Id = 0},
                            {Name = GetLabelText("L_FMM_12_4"), Id = 4},
                            {Name = GetLabelText("L_FMM_12_5"), Id = 5},
                            {Name = GetLabelText("L_FMM_12_7"), Id = 7},
                            {Name = GetLabelText("L_FMM_12_12"), Id = 12},
                        }),
                        CreateItemsWithTextures(4, 15, {
                            {Name = GetLabelText("L_FMM_15_0"), Id = 0},
                            {Name = GetLabelText("L_FMM_15_1"), Id = 1},
                            {Name = GetLabelText("L_FMM_15_2"), Id = 2},
                            {Name = GetLabelText("L_FMM_15_3"), Id = 3},
                            {Name = GetLabelText("L_FMM_15_4"), Id = 4},
                            {Name = GetLabelText("L_FMM_15_5"), Id = 5},
                            {Name = GetLabelText("L_FMM_15_6"), Id = 6},
                            {Name = GetLabelText("L_FMM_15_7"), Id = 7},
                            {Name = GetLabelText("L_FMM_15_8"), Id = 8},
                            {Name = GetLabelText("L_FMM_15_13"), Id = 13},
                            {Name = GetLabelText("L_FMM_15_14"), Id = 14},
                            {Name = GetLabelText("L_FMM_15_15"), Id = 15},
                        }),
                        CreateItemsWithTextures(4, 17, {
                            {Name = GetLabelText("CLO_BBM_L_1_0"), Id = 0},
                            {Name = GetLabelText("CLO_BBM_L_1_1"), Id = 1},
                            {Name = GetLabelText("CLO_BBM_L_1_2"), Id = 2},
                            {Name = GetLabelText("CLO_BBM_L_1_3"), Id = 3},
                            {Name = GetLabelText("CLO_BBM_L_1_4"), Id = 4},
                            {Name = GetLabelText("CLO_BBM_L_1_5"), Id = 5},
                            {Name = GetLabelText("CLO_BBM_L_1_6"), Id = 6},
                            {Name = GetLabelText("CLO_BBM_L_1_7"), Id = 7},
                            {Name = GetLabelText("CLO_BBM_L_1_8"), Id = 8},
                            {Name = GetLabelText("CLO_BBM_L_1_9"), Id = 9},
                            {Name = GetLabelText("CLO_BBM_L_1_10"), Id = 10},
                        }),
                    }),
                },
                [3] = {
                    Name = "Costume",
                    Price = 50,
                    Items = table.unpack({
                        CreateItemsWithTextures(4, 24, {
                            {Name = GetLabelText("CLO_HILF_L_0_0"), Id = 0},
                            {Name = GetLabelText("CLO_HILF_L_0_1"), Id = 1},
                            {Name = GetLabelText("CLO_HILF_L_0_2"), Id = 2},
                            {Name = GetLabelText("CLO_HILF_L_0_3"), Id = 3},
                            {Name = GetLabelText("CLO_HILF_L_0_4"), Id = 4},
                            {Name = GetLabelText("CLO_HILF_L_0_5"), Id = 5},
                            {Name = GetLabelText("CLO_HILF_L_0_6"), Id = 6},
                        }),
                        CreateItemsWithTextures(4, 10, {
                            {Name = GetLabelText("L_FMM_10_0"), Id = 0},
                            {Name = GetLabelText("L_FMM_10_1"), Id = 1},
                            {Name = GetLabelText("L_FMM_10_2"), Id = 2},
                        }),
                        CreateItemsWithTextures(4, 13, {
                            {Name = GetLabelText("L_FMM_13_0"), Id = 0},
                            {Name = GetLabelText("L_FMM_13_1"), Id = 1},
                            {Name = GetLabelText("L_FMM_13_2"), Id = 2},
                        }),
                        CreateItemsWithTextures(4, 19, {
                            {Name = GetLabelText("CLO_XMASM_L_0_0"), Id = 0},
                            {Name = GetLabelText("CLO_XMASM_L_0_1"), Id = 1},
                        }),
                        CreateItemsWithTextures(4, 20, {
                            {Name = GetLabelText("CLO_VALM_L_0_0"), Id = 0},
                            {Name = GetLabelText("CLO_VALM_L_0_1"), Id = 1},
                            {Name = GetLabelText("CLO_VALM_L_0_2"), Id = 2},
                            {Name = GetLabelText("CLO_VALM_L_0_3"), Id = 3},
                        }),
                        CreateItemsWithTextures(4, 22, {
                            {Name = GetLabelText("CLO_BUSM_L_0_0"), Id = 0},
                            {Name = GetLabelText("CLO_BUSM_L_0_1"), Id = 1},
                            {Name = GetLabelText("CLO_BUSM_L_0_2"), Id = 2},
                            {Name = GetLabelText("CLO_BUSM_L_0_3"), Id = 3},
                            {Name = GetLabelText("CLO_BUSM_L_0_4"), Id = 4},
                            {Name = GetLabelText("CLO_BUSM_L_0_5"), Id = 5},
                            {Name = GetLabelText("CLO_BUSM_L_0_6"), Id = 6},
                            {Name = GetLabelText("CLO_BUSM_L_0_7"), Id = 7},
                            {Name = GetLabelText("CLO_BUSM_L_0_8"), Id = 8},
                            {Name = GetLabelText("CLO_BUSM_L_0_9"), Id = 9},
                            {Name = GetLabelText("CLO_BUSM_L_0_10"), Id = 10},
                            {Name = GetLabelText("CLO_BUSM_L_0_11"), Id = 11},
                            {Name = GetLabelText("CLO_BUSM_L_0_12"), Id = 12},
                        }),
                        CreateItemsWithTextures(4, 23, {
                            {Name = GetLabelText("CLO_BUSM_L_1_0"), Id = 0},
                            {Name = GetLabelText("CLO_BUSM_L_1_1"), Id = 1},
                            {Name = GetLabelText("CLO_BUSM_L_1_2"), Id = 2},
                            {Name = GetLabelText("CLO_BUSM_L_1_3"), Id = 3},
                            {Name = GetLabelText("CLO_BUSM_L_1_4"), Id = 4},
                            {Name = GetLabelText("CLO_BUSM_L_1_5"), Id = 5},
                            {Name = GetLabelText("CLO_BUSM_L_1_6"), Id = 6},
                            {Name = GetLabelText("CLO_BUSM_L_1_7"), Id = 7},
                            {Name = GetLabelText("CLO_BUSM_L_1_8"), Id = 8},
                            {Name = GetLabelText("CLO_BUSM_L_1_9"), Id = 9},
                            {Name = GetLabelText("CLO_BUSM_L_1_10"), Id = 10},
                            {Name = GetLabelText("CLO_BUSM_L_1_11"), Id = 11},
                            {Name = GetLabelText("CLO_BUSM_L_1_12"), Id = 12},
                        }),
                        CreateItemsWithTextures(4, 25, {
                            {Name = GetLabelText("CLO_HILF_L_1_0"), Id = 0},
                            {Name = GetLabelText("CLO_HILF_L_1_1"), Id = 1},
                            {Name = GetLabelText("CLO_HILF_L_1_2"), Id = 2},
                            {Name = GetLabelText("CLO_HILF_L_1_3"), Id = 3},
                            {Name = GetLabelText("CLO_HILF_L_1_4"), Id = 4},
                            {Name = GetLabelText("CLO_HILF_L_1_5"), Id = 5},
                            {Name = GetLabelText("CLO_HILF_L_1_6"), Id = 6},
                        }),
                        CreateItemsWithTextures(4, 26, {
                            {Name = GetLabelText("CLO_HP_L_0_1"), Id = 1},
                            {Name = GetLabelText("CLO_HP_L_0_2"), Id = 2},
                            {Name = GetLabelText("CLO_HP_L_0_3"), Id = 3},
                            {Name = GetLabelText("CLO_HP_L_0_7"), Id = 7},
                            {Name = GetLabelText("CLO_HP_L_0_11"), Id = 11},
                        }),
                        CreateItemsWithTextures(4, 28, {
                            {Name = GetLabelText("CLO_HP_L_2_0"), Id = 0},
                            {Name = GetLabelText("CLO_HP_L_2_2"), Id = 2},
                            {Name = GetLabelText("CLO_HP_L_2_3"), Id = 3},
                            {Name = GetLabelText("CLO_HP_L_2_4"), Id = 4},
                            {Name = GetLabelText("CLO_HP_L_2_5"), Id = 5},
                            {Name = GetLabelText("CLO_HP_L_2_6"), Id = 6},
                            {Name = GetLabelText("CLO_HP_L_2_7"), Id = 7},
                            {Name = GetLabelText("CLO_HP_L_2_8"), Id = 8},
                            {Name = GetLabelText("CLO_HP_L_2_9"), Id = 9},
                            {Name = GetLabelText("CLO_HP_L_2_10"), Id = 10},
                            {Name = GetLabelText("CLO_HP_L_2_11"), Id = 11},
                            {Name = GetLabelText("CLO_HP_L_2_12"), Id = 12},
                            {Name = GetLabelText("CLO_HP_L_2_14"), Id = 14},
                        }),
                        CreateItemsWithTextures(4, 37, {
                            {Name = GetLabelText("CLO_HSTM_L_4_0"), Id = 0},
                            {Name = GetLabelText("CLO_HSTM_L_4_1"), Id = 1},
                            {Name = GetLabelText("CLO_HSTM_L_4_2"), Id = 2},
                            {Name = GetLabelText("CLO_HSTM_L_4_3"), Id = 3},
                        }),
                        CreateItemsWithTextures(4, 48, {
                            {Name = GetLabelText("CLO_EXM_AL_4_0"), Id = 0},
                            {Name = GetLabelText("CLO_EXM_AL_4_1"), Id = 1},
                            {Name = GetLabelText("CLO_EXM_AL_4_2"), Id = 2},
                            {Name = GetLabelText("CLO_EXM_AL_4_3"), Id = 3},
                            {Name = GetLabelText("CLO_EXM_AL_4_4"), Id = 4},
                        }),
                        CreateItemsWithTextures(4, 49, {
                            {Name = GetLabelText("CLO_EXM_AL_5_0"), Id = 0},
                            {Name = GetLabelText("CLO_EXM_AL_5_1"), Id = 1},
                            {Name = GetLabelText("CLO_EXM_AL_5_2"), Id = 2},
                            {Name = GetLabelText("CLO_EXM_AL_5_3"), Id = 3},
                            {Name = GetLabelText("CLO_EXM_AL_5_4"), Id = 4},
                        }),
                        CreateItemsWithTextures(4, 50, {
                            {Name = GetLabelText("CLO_EXM_AL_6_0"), Id = 0},
                            {Name = GetLabelText("CLO_EXM_AL_6_1"), Id = 1},
                            {Name = GetLabelText("CLO_EXM_AL_6_2"), Id = 2},
                            {Name = GetLabelText("CLO_EXM_AL_6_3"), Id = 3},
                        }),
                        CreateItemsWithTextures(4, 51, {
                            {Name = GetLabelText("CLO_EXM_AL_7_0"), Id = 0},
                        }),
                        CreateItemsWithTextures(4, 52, {
                            {Name = GetLabelText("CLO_EXM_AL_8_0"), Id = 0},
                            {Name = GetLabelText("CLO_EXM_AL_8_1"), Id = 1},
                            {Name = GetLabelText("CLO_EXM_AL_8_2"), Id = 2},
                            {Name = GetLabelText("CLO_EXM_AL_8_3"), Id = 3},
                        }),
                        CreateItemsWithTextures(4, 53, {
                            {Name = GetLabelText("CLO_EXM_AL_9_0"), Id = 0},
                        }),
                    }),
                },
            },
        },
        [3] = {
            Name = "Chaussures",
            Collections = {
                [1] = {
                    Name = "Derbies & Richelieus",
                    Price = 50,
                    Items = table.unpack({
                        CreateItemsWithTextures(6, 3, {
                            {Name = GetLabelText("F_FMM_3_0"), Id = 0},
                            {Name = GetLabelText("F_FMM_3_1"), Id = 1},
                            {Name = GetLabelText("F_FMM_3_2"), Id = 2},
                            {Name = GetLabelText("F_FMM_3_3"), Id = 3},
                            {Name = GetLabelText("F_FMM_3_4"), Id = 4},
                            {Name = GetLabelText("F_FMM_3_5"), Id = 5},
                            {Name = GetLabelText("F_FMM_3_6"), Id = 6},
                            {Name = GetLabelText("F_FMM_3_7"), Id = 7},
                            {Name = GetLabelText("F_FMM_3_8"), Id = 8},
                            {Name = GetLabelText("F_FMM_3_9"), Id = 9},
                            {Name = GetLabelText("F_FMM_3_10"), Id = 10},
                            {Name = GetLabelText("F_FMM_3_11"), Id = 11},
                            {Name = GetLabelText("F_FMM_3_12"), Id = 12},
                            {Name = GetLabelText("F_FMM_3_13"), Id = 13},
                            {Name = GetLabelText("F_FMM_3_14"), Id = 14},
                            {Name = GetLabelText("F_FMM_3_15"), Id = 15},
                        }),
                        CreateItemsWithTextures(6, 10, {
                            {Name = GetLabelText("F_FMM_10_0"), Id = 0},
                            {Name = GetLabelText("F_FMM_10_7"), Id = 7},
                            {Name = GetLabelText("F_FMM_10_12"), Id = 12},
                            {Name = GetLabelText("F_FMM_10_14"), Id = 14},
                        }),
                        CreateItemsWithTextures(6, 18, {
                            {Name = GetLabelText("CLO_VALM_F_0_0"), Id = 0},
                            {Name = GetLabelText("CLO_VALM_F_0_1"), Id = 1},
                        }),
                        CreateItemsWithTextures(6, 20, {
                            {Name = GetLabelText("CLO_BUSM_F_0_0"), Id = 0},
                            {Name = GetLabelText("CLO_BUSM_F_0_1"), Id = 1},
                            {Name = GetLabelText("CLO_BUSM_F_0_2"), Id = 2},
                            {Name = GetLabelText("CLO_BUSM_F_0_3"), Id = 3},
                            {Name = GetLabelText("CLO_BUSM_F_0_4"), Id = 4},
                            {Name = GetLabelText("CLO_BUSM_F_0_5"), Id = 5},
                            {Name = GetLabelText("CLO_BUSM_F_0_6"), Id = 6},
                            {Name = GetLabelText("CLO_BUSM_F_0_7"), Id = 7},
                            {Name = GetLabelText("CLO_BUSM_F_0_8"), Id = 8},
                            {Name = GetLabelText("CLO_BUSM_F_0_9"), Id = 9},
                            {Name = GetLabelText("CLO_BUSM_F_0_10"), Id = 10},
                            {Name = GetLabelText("CLO_BUSM_F_0_11"), Id = 11},
                        }),
                        CreateItemsWithTextures(6, 23, {
                            {Name = GetLabelText("CLO_HP_F_1_0"), Id = 0},
                            {Name = GetLabelText("CLO_HP_F_1_1"), Id = 1},
                            {Name = GetLabelText("CLO_HP_F_1_2"), Id = 2},
                            {Name = GetLabelText("CLO_HP_F_1_3"), Id = 3},
                            {Name = GetLabelText("CLO_HP_F_1_4"), Id = 4},
                            {Name = GetLabelText("CLO_HP_F_1_5"), Id = 5},
                            {Name = GetLabelText("CLO_HP_F_1_6"), Id = 6},
                            {Name = GetLabelText("CLO_HP_F_1_7"), Id = 7},
                            {Name = GetLabelText("CLO_HP_F_1_8"), Id = 8},
                            {Name = GetLabelText("CLO_HP_F_1_9"), Id = 9},
                            {Name = GetLabelText("CLO_HP_F_1_10"), Id = 10},
                            {Name = GetLabelText("CLO_HP_F_1_11"), Id = 11},
                            {Name = GetLabelText("CLO_HP_F_1_12"), Id = 12},
                            {Name = GetLabelText("CLO_HP_F_1_13"), Id = 13},
                            {Name = GetLabelText("CLO_HP_F_1_14"), Id = 14},
                            {Name = GetLabelText("CLO_HP_F_1_15"), Id = 15},
                        }),
                        CreateItemsWithTextures(6, 30, {
                            {Name = GetLabelText("CLO_L2M_F_0_0"), Id = 0},
                            {Name = GetLabelText("CLO_L2M_F_0_1"), Id = 1},
                        }),
                        CreateItemsWithTextures(6, 36, {
                            {Name = GetLabelText("CLO_EXM_AF_3_0"), Id = 0},
                            {Name = GetLabelText("CLO_EXM_AF_3_1"), Id = 1},
                            {Name = GetLabelText("CLO_EXM_AF_3_1"), Id = 2},
                            {Name = GetLabelText("CLO_EXM_AF_3_1"), Id = 3},
                        }),
                        CreateItemsWithTextures(6, 40, {
                            {Name = GetLabelText("CLO_V2M_F_0_0"), Id = 0},
                            {Name = GetLabelText("CLO_V2M_F_0_1"), Id = 1},
                            {Name = GetLabelText("CLO_V2M_F_0_2"), Id = 2},
                            {Name = GetLabelText("CLO_V2M_F_0_3"), Id = 3},
                            {Name = GetLabelText("CLO_V2M_F_0_4"), Id = 4},
                            {Name = GetLabelText("CLO_V2M_F_0_5"), Id = 5},
                            {Name = GetLabelText("CLO_V2M_F_0_6"), Id = 6},
                            {Name = GetLabelText("CLO_V2M_F_0_7"), Id = 7},
                            {Name = GetLabelText("CLO_V2M_F_0_8"), Id = 8},
                            {Name = GetLabelText("CLO_V2M_F_0_9"), Id = 9},
                            {Name = GetLabelText("CLO_V2M_F_0_10"), Id = 10},
                            {Name = GetLabelText("CLO_V2M_F_0_11"), Id = 11},
                        }),
                    }),
                },
                [2] = {
                    Name = "Chaussures basses",
                    Price = 50,
                    Items = table.unpack({
                        CreateItemsWithTextures(6, 11, {
                            {Name = GetLabelText("F_FMM_11_9"), Id = 9},
                            {Name = GetLabelText("F_FMM_11_12"), Id = 12},
                            {Name = GetLabelText("F_FMM_11_14"), Id = 14},
                            {Name = GetLabelText("F_FMM_11_15"), Id = 15},
                        }),
                        CreateItemsWithTextures(6, 21, {
                            {Name = GetLabelText("CLO_BUSM_F_1_0"), Id = 0},
                            {Name = GetLabelText("CLO_BUSM_F_1_1"), Id = 1},
                            {Name = GetLabelText("CLO_BUSM_F_1_2"), Id = 2},
                            {Name = GetLabelText("CLO_BUSM_F_1_3"), Id = 3},
                            {Name = GetLabelText("CLO_BUSM_F_1_4"), Id = 4},
                            {Name = GetLabelText("CLO_BUSM_F_1_5"), Id = 5},
                            {Name = GetLabelText("CLO_BUSM_F_1_6"), Id = 6},
                            {Name = GetLabelText("CLO_BUSM_F_1_7"), Id = 7},
                            {Name = GetLabelText("CLO_BUSM_F_1_8"), Id = 8},
                            {Name = GetLabelText("CLO_BUSM_F_1_9"), Id = 9},
                            {Name = GetLabelText("CLO_BUSM_F_1_10"), Id = 10},
                            {Name = GetLabelText("CLO_BUSM_F_1_11"), Id = 11},
                        }),
                        CreateItemsWithTextures(6, 51, {
                            {Name = GetLabelText("CLO_BIM_F_0_0"), Id = 0},
                            {Name = GetLabelText("CLO_BIM_F_0_1"), Id = 1},
                            {Name = GetLabelText("CLO_BIM_F_0_2"), Id = 2},
                            {Name = GetLabelText("CLO_BIM_F_0_3"), Id = 3},
                            {Name = GetLabelText("CLO_BIM_F_0_4"), Id = 4},
                            {Name = GetLabelText("CLO_BIM_F_0_5"), Id = 5},
                        }),
                        CreateItemsWithTextures(6, 54, {
                            {Name = GetLabelText("CLO_BIM_F_3_0"), Id = 0},
                            {Name = GetLabelText("CLO_BIM_F_3_1"), Id = 1},
                            {Name = GetLabelText("CLO_BIM_F_3_2"), Id = 2},
                            {Name = GetLabelText("CLO_BIM_F_3_3"), Id = 3},
                            {Name = GetLabelText("CLO_BIM_F_3_4"), Id = 4},
                            {Name = GetLabelText("CLO_BIM_F_3_5"), Id = 5},
                        }),
                        CreateItemsWithTextures(6, 56, {
                            {Name = GetLabelText("CLO_BIM_F_2_0"), Id = 0},
                            {Name = GetLabelText("CLO_BIM_F_2_1"), Id = 1},
                        }),
                    }),
                },
                [3] = {
                    Name = "Bottes",
                    Price = 50,
                    Items = table.unpack({
                        CreateItemsWithTextures(6, 19, {
                            {Name = GetLabelText("CLO_VALM_F_1_0"), Id = 0},
                        }),
                        CreateItemsWithTextures(6, 52, {
                            {Name = GetLabelText("CLO_BIM_F_2_0"), Id = 0},
                            {Name = GetLabelText("CLO_BIM_F_2_1"), Id = 1},
                        }),
                        --- TODO: trouver les bons labels
                        CreateItemsWithTextures(6, 88, {
                            {Name = GetLabelText("CLO_BUSM_F_1_0"), Id = 0},
                            {Name = GetLabelText("CLO_BUSM_F_1_1"), Id = 1},
                            {Name = GetLabelText("CLO_BUSM_F_1_2"), Id = 2},
                            {Name = GetLabelText("CLO_BUSM_F_1_3"), Id = 3},
                            {Name = GetLabelText("CLO_BUSM_F_1_4"), Id = 4},
                            {Name = GetLabelText("CLO_BUSM_F_1_5"), Id = 5},
                            {Name = GetLabelText("CLO_BUSM_F_1_6"), Id = 6},
                            {Name = GetLabelText("CLO_BUSM_F_1_7"), Id = 7},
                            {Name = GetLabelText("CLO_BUSM_F_1_8"), Id = 8},
                            {Name = GetLabelText("CLO_BUSM_F_1_9"), Id = 9},
                            {Name = GetLabelText("CLO_BUSM_F_1_10"), Id = 10},
                            {Name = GetLabelText("CLO_BUSM_F_1_11"), Id = 11},
                        }),
                    }),
                },
                [4] = {
                    Name = "Chaussons",
                    Price = 50,
                    Items = table.unpack({
                        CreateItemsWithTextures(6, 41, {
                            {Name = GetLabelText("CLO_S2M_F_0_0"), Id = 0},
                        }),
                        --- TODO: trouver les bons labels
                        CreateItemsWithTextures(6, 87, {
                            {Name = GetLabelText("F_FMM_3_0"), Id = 0},
                            {Name = GetLabelText("F_FMM_3_1"), Id = 1},
                            {Name = GetLabelText("F_FMM_3_2"), Id = 2},
                            {Name = GetLabelText("F_FMM_3_3"), Id = 3},
                            {Name = GetLabelText("F_FMM_3_4"), Id = 4},
                            {Name = GetLabelText("F_FMM_3_5"), Id = 5},
                            {Name = GetLabelText("F_FMM_3_6"), Id = 6},
                            {Name = GetLabelText("F_FMM_3_7"), Id = 7},
                            {Name = GetLabelText("F_FMM_3_8"), Id = 8},
                            {Name = GetLabelText("F_FMM_3_9"), Id = 9},
                            {Name = GetLabelText("F_FMM_3_10"), Id = 10},
                            {Name = GetLabelText("F_FMM_3_11"), Id = 11},
                            {Name = GetLabelText("F_FMM_3_12"), Id = 12},
                            {Name = GetLabelText("F_FMM_3_13"), Id = 13},
                            {Name = GetLabelText("F_FMM_3_14"), Id = 14},
                            {Name = GetLabelText("F_FMM_3_15"), Id = 15},
                            {Name = GetLabelText("F_FMM_3_16"), Id = 16},
                            {Name = GetLabelText("F_FMM_3_17"), Id = 17},
                        }),
                        CreateItemsWithTextures(6, 95, {
                            {Name = GetLabelText("CLO_H3M_F_0_0"), Id = 0},
                        }),
                    }),
                },
            },
        },
    },
    [GetHashKey("mp_f_freemode_01")] = {},
}

Config.Products["suburban"] = {[GetHashKey("mp_m_freemode_01")] = {}, [GetHashKey("mp_f_freemode_01")] = {}}

Config.Products["binco"] = Config.Products["suburban"]

Config.ClothingLocationsInShop = {
    ["ponsonbys1"] = vector4(-704.75, -151.61, 37.42, 200.16),
    ["ponsonbys2"] = vector4(-167.72, -299.38, 39.73, 336.42),
    ["ponsonbys3"] = vector4(-1447.86, -242.37, 49.82, 144.64),
    ["suburban1"] = vector4(118.16, -227.36, 54.56, 246.27),
    ["suburban2"] = vector4(620.16, 2769.12, 42.09, 93.65),
    ["suburban3"] = vector4(-1184.8, -769.37, 17.33, 40.76),
    ["suburban4"] = vector4(-3178.63, 1040.59, 20.86, 249.91),
    ["binco1"] = vector4(429.73, -811.43, 29.49, 355.47),
    ["binco2"] = vector4(-819.89, -1067.32, 11.33, 115.96),
    ["binco3"] = vector4(71.21, -1387.51, 29.38, 181.94),
    ["binco4"] = vector4(3.69, 6505.76, 31.88, 310.2),
    ["binco5"] = vector4(1698.71, 4818.05, 42.06, 6.41),
    ["binco6"] = vector4(1202.14, 2714.29, 38.22, 91.37),
    ["binco7"] = vector4(-1100.12, 2717.23, 19.11, 129.32),
}

Config.Locations["ponsonbys"] = {
    vector4(-708.9, -151.38, 37.42, 125.7),
    vector4(-165.28, -303.18, 39.73, 256.5),
    vector4(-1448.54, -238.02, 49.81, 50.99),
}

Config.Locations["suburban"] = {
    vector4(127.21, -224.29, 54.56, 71.99),
    vector4(612.77, 2762.72, 42.09, 273.74),
    vector4(-1193.98, -766.84, 17.32, 216.9),
    vector4(-3169.27, 1043.23, 20.86, 70.68),
}

Config.Locations["binco"] = {
    vector4(427.23, -807.14, 29.49, 87.53),
    vector4(-822.51, -1071.78, 11.33, 208.86),
    vector4(73.8, -1392.08, 29.38, 268.02),
    vector4(5.33, 6510.79, 31.88, 47.79),
    vector4(1695.52, 4822.3, 42.06, 114.62),
    vector4(1197.49, 2711.92, 38.22, 179.31),
    vector4(-1101.93, 2712.25, 19.11, 229.23),
}
