import { TetrisLeaderboard } from '@typings/app/tetris';

export const MockTetrisLeaderboard: TetrisLeaderboard[] = [
    {
        citizenid: '1',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1000,
        game_played: 10,
    },
    {
        citizenid: '2',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1001,
        game_played: 10,
    },
    {
        citizenid: '3',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1002,
        game_played: 10,
    },
    {
        citizenid: '4',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1003,
        game_played: 10,
    },
    {
        citizenid: '5',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1000,
        game_played: 10,
    },
    {
        citizenid: '6',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1000,
        game_played: 10,
    },
    {
        citizenid: '7',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1000,
        game_played: 10,
    },
    {
        citizenid: '8',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1000,
        game_played: 10,
    },
    {
        citizenid: '9',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1000,
        game_played: 10,
    },
    {
        citizenid: '10',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1000,
        game_played: 10,
    },
    {
        citizenid: '11',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1000,
        game_played: 10,
    },
    {
        citizenid: '12',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1000,
        game_played: 10,
    },
    {
        citizenid: '13',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1000,
        game_played: 10,
    },
    {
        citizenid: '14',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe not a long name',
        score: 1000,
        game_played: 10,
    },
    {
        citizenid: '15',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Doe',
        score: 1000,
        game_played: 10,
    },
    {
        citizenid: '1',
        avatar: 'https://placekitten.com/1920/1080',
        player_name: 'John Very long name Doe',
        score: 10000,
        game_played: 10,
    },
];
