blank_issues_enabled: false
contact_links:
  - name: SOZ Discord
    url: https://discord.gg/soz-pas-soz
    about: You can also visit the Official Discord, if you want to follow the development, the RoadMap and the many announcements to come !
