import { TwitchNewsMessage } from '@typings/twitch-news';

export const MockTwitchNewsMessages: TwitchNewsMessage[] = [
    {
        id: 1,
        type: 'annonce',
        message: 'Lorem ipsum dolor sit amet, conse ctetur adip iscing elit.',
        createdAt: '2022-01-14T09:58:18.000Z',
        job: 'news',
    },
    {
        id: 2,
        type: 'breaking-news',
        image: 'https://placekitten.com/1920/1080',
        message: 'Lorem ipsum dolor sit amet, conse ctetur adip iscing elit.',
        createdAt: '2022-01-14T09:58:18.000Z',
        job: 'you-news',
    },
    {
        id: 3,
        type: 'publicité',
        message: 'Lorem ipsum dolor sit amet, conse ctetur adip iscing elit.',
        createdAt: '2022-01-14T09:58:18.000Z',
        job: 'news',
    },
    {
        id: 4,
        type: 'fait-divers',
        image: 'https://placekitten.com/1920/1080',
        message: 'Lorem ipsum dolor sit amet, conse ctetur adip iscing elit.',
        createdAt: '2022-01-14T09:58:18.000Z',
        job: 'news',
    },
    {
        id: 5,
        type: 'info-trafic',
        image: 'https://placekitten.com/1920/1080',
        message: 'Lorem ipsum dolor sit amet, conse ctetur adip iscing elit.',
        createdAt: '2022-01-14T09:58:18.000Z',
        job: 'news',
    },
    {
        id: 6,
        type: 'lspd',
        message: 'Jean test',
        createdAt: '2022-01-14T09:58:18.000Z',
        job: 'lspd',
    },
    {
        id: 7,
        type: 'bcso',
        message: 'Jean test',
        createdAt: '2022-01-14T09:58:18.000Z',
        job: 'bcso',
    },
    {
        id: 8,
        type: 'lspd:end',
        message: 'Jean test',
        createdAt: '2022-01-14T09:58:18.000Z',
        job: 'lspd',
    },
    {
        id: 9,
        type: 'bcso:end',
        message: 'Jean test',
        createdAt: '2022-01-14T09:58:18.000Z',
        job: 'bcso',
    },
];
