SpringAutumnForecast = {
    extrasunny = {clearing = 50, overcast = 50},
    clear = {clearing = 5, overcast = 5, smog = 45, foggy = 45},
    neutral = {},
    smog = {clearing = 50, overcast = 50},
    foggy = {clearing = 50, overcast = 50},
    overcast = {clear = 33, clouds = 33, extrasunny = 34},
    clouds = {clearing = 50, overcast = 50},
    clearing = {clear = 10, clouds = 5, extrasunny = 5, thunder = 40, rain = 40},
    rain = {clearing = 50, overcast = 50},
    thunder = {},
    snow = {},
    blizzard = {},
    snowlight = {},
    xmas = {},
    halloween = {},
}
