SummerForecast = {
    extrasunny = {clearing = 25, overcast = 75},
    clear = {clearing = 25, overcast = 75},
    neutral = {},
    smog = {},
    foggy = {},
    overcast = {rain = 5, clearing = 20, clouds = 25, extrasunny = 25},
    clouds = {clearing = 25, overcast = 75},
    clearing = {rain = 5, clearing = 20, clouds = 25, extrasunny = 25},
    rain = {clearing = 100},
    thunder = {clearing = 100},
    snow = {},
    blizzard = {},
    snowlight = {},
    xmas = {},
    halloween = {},
}
