SummerForecast = {
    extrasunny = {clearing = 10, overcast = 90},
    clear = {clearing = 10, overcast = 90},
    neutral = {},
    smog = {},
    foggy = {},
    overcast = {rain = 5, clearing = 5, clouds = 10, extrasunny = 80},
    clouds = {clearing = 10, overcast = 90},
    clearing = {rain = 5, clearing = 5, clouds = 10, extrasunny = 80},
    rain = {clearing = 100},
    thunder = {clearing = 100},
    snow = {},
    blizzard = {},
    snowlight = {},
    xmas = {},
    halloween = {},
}
