SummerForecast = {
    extrasunny = {clearing = 5, overcast = 95},
    clear = {clearing = 5, overcast = 95},
    neutral = {},
    smog = {},
    foggy = {},
    overcast = {rain = 2, clearing = 3, clouds = 5, extrasunny = 80},
    clouds = {clearing = 25, overcast = 75},
    clearing = {rain = 2, clearing = 3, clouds = 5, extrasunny = 80},
    rain = {clearing = 100},
    thunder = {clearing = 100},
    snow = {},
    blizzard = {},
    snowlight = {},
    xmas = {},
    halloween = {},
}
