WinterForecast = {
    extrasunny = {clearing = 50, overcast = 50},
    clear = {clearing = 5, overcast = 5, smog = 45, foggy = 45},
    neutral = {},
    smog = {clearing = 50, overcast = 50},
    foggy = {clearing = 50, overcast = 50},
    overcast = {clear = 30, clouds = 30, extrasunny = 30, snow = 10},
    clouds = {clearing = 50, overcast = 50},
    clearing = {clear = 10, clouds = 5, extrasunny = 5, thunder = 40, rain = 40},
    rain = {clearing = 50, overcast = 50},
    thunder = {},
    snow = {clearing = 50, overcast = 50},
    blizzard = {},
    snowlight = {clearing = 50, overcast = 50},
    xmas = {snow = 100},
    halloween = {},
}
