QBShared = QBShared or {}

QBShared.Items = {
    -- WEAPONS
    -- Melee
    ['weapon_unarmed'] = {
        ['name'] = 'weapon_unarmed',
        ['label'] = 'Poings.',
        ['weight'] = 0,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Coups de poings.'
    },
    ['weapon_dagger'] = {
        ['name'] = 'weapon_dagger',
        ['label'] = 'Dague antique',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une large dague, semblable à une épée.'
    },
    ['weapon_bat'] = {
        ['name'] = 'weapon_bat',
        ['label'] = 'Batte de baseball',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Pour claquer ton plus beau home run !'
    },
    ['weapon_bottle'] = {
        ['name'] = 'weapon_bottle',
        ['label'] = 'Bouteille brisée',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une bouteille brisée'
    },
    ['weapon_crowbar'] = {
        ['name'] = 'weapon_crowbar',
        ['label'] = 'Pied de biche',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Barre de métal utilisée pour forcer des portes, ou forcer des crânes.'
    },
    ['weapon_flashlight'] = {
        ['name'] = 'weapon_flashlight',
        ['label'] = 'Lampe de poche',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Pour voir dans le noir !'
    },
    ['weapon_golfclub'] = {
        ['name'] = 'weapon_golfclub',
        ['label'] = 'Club de golf',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un club utilisé avant tout pour frapper la balle au golf.'
    },
    ['weapon_hammer'] = {
        ['name'] = 'weapon_hammer',
        ['label'] = 'Marteau',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Utilisé pour des travaux tels que casser des choses, planter des clous, ou supporter une équipe eSport...'
    },
    ['weapon_hatchet'] = {
        ['name'] = 'weapon_hatchet',
        ['label'] = 'Hachette',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une petite hache tenable à une main.'
    },
    ['weapon_knuckle'] = {
        ['name'] = 'weapon_knuckle',
        ['label'] = 'Poing americain',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un poing en métal.'
    },
    ['weapon_knife'] = {
        ['name'] = 'weapon_knife',
        ['label'] = 'Couteau',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Instrument composé d\'une lame fixée dans un manche, utilisé pour couper ou comme arme.'
    },
    ['weapon_machete'] = {
        ['name'] = 'weapon_machete',
        ['label'] = 'Machette',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un long couteau, lame assez lourde.'
    },
    ['weapon_switchblade'] = {
        ['name'] = 'weapon_switchblade',
        ['label'] = 'Cran d\'arrêt',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un couteau avec une lame rétractable.'
    },
    ['weapon_nightstick'] = {
        ['name'] = 'weapon_nightstick',
        ['label'] = 'Matraque',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Arme de prédilection des officiers de police.'
    },
    ['weapon_wrench'] = {
        ['name'] = 'weapon_wrench',
        ['label'] = 'Clé anglaise',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Idéal pour réparer la tuyauterie... ou casser des noix.'
    },
    ['weapon_battleaxe'] = {
        ['name'] = 'weapon_battleaxe',
        ['label'] = 'Hache de guerre',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Hache à une main pour combattre tel un Moyen-Ageux.'
    },
    ['weapon_poolcue'] = {
        ['name'] = 'weapon_poolcue',
        ['label'] = 'Queue de billard',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Utilisée pour jouer au billard, ou taper d\'autres trucs.'
    },
    ['weapon_briefcase'] = {
        ['name'] = 'weapon_briefcase',
        ['label'] = 'Porte-documents',
        ['weight'] = 1000,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une mallette pour ranger les documents importants.'
    },
    ['weapon_briefcase_02'] = {
        ['name'] = 'weapon_briefcase_02',
        ['label'] = 'Malette',
        ['weight'] = 1000,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Contient sûrement des infos top secrete.'
    },
    ['weapon_garbagebag'] = {
        ['name'] = 'weapon_garbagebag',
        ['label'] = 'Sac poubelle',
        ['weight'] = 2000,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Pour jeter tout type d\'ordures.'
    },
    ['weapon_handcuffs'] = {
        ['name'] = 'weapon_handcuffs',
        ['label'] = 'Menottes',
        ['weight'] = 100,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Menottes pour prisonniers.'
    },
    ['weapon_bread'] = {
        ['name'] = 'weapon_bread',
        ['label'] = 'Baguette',
        ['weight'] = 200,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Tu veux du pain ?'
    },
    ['weapon_stone_hatchet'] = {
        ['name'] = 'weapon_stone_hatchet',
        ['label'] = 'Hachette en pierre',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Retour à l\'âge de pierre.'
    },

    -- Handguns
    ['weapon_pistol'] = {
        ['name'] = 'weapon_pistol',
        ['label'] = 'Pistolet',
        ['weight'] = 2000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un pistolet très maniable, parfait pour assurer sa sécurité.'
    },
    ['weapon_pistol_mk2'] = {
        ['name'] = 'weapon_pistol_mk2',
        ['label'] = 'Pistolet Mk II',
        ['weight'] = 2000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une version amélioré du classique pistolet.'
    },
    ['weapon_combatpistol'] = {
        ['name'] = 'weapon_combatpistol',
        ['label'] = 'Pistolet de combat',
        ['weight'] = 1600,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un pistolet de petite taille, très maniable.'
    },
    ['weapon_appistol'] = {
        ['name'] = 'weapon_appistol',
        ['label'] = 'Pistolet perforant',
        ['weight'] = 1800,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Pistolet automatique à une main.'
    },
    ['weapon_stungun'] = {
        ['name'] = 'weapon_stungun',
        ['label'] = 'Taser',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Arme électrique de corps à corps, causant une paralysie.'
    },
    ['weapon_pistol50'] = {
        ['name'] = 'weapon_pistol50',
        ['label'] = 'Pistolet calibre .50',
        ['weight'] = 2000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une arme à feu de calibre 50 conçue pour être tenue à deux mains.'
    },
    ['weapon_snspistol'] = {
        ['name'] = 'weapon_snspistol',
        ['label'] = 'Pétoire',
        ['weight'] = 800,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un petit pistolet.'
    },
    ['weapon_heavypistol'] = {
        ['name'] = 'weapon_heavypistol',
        ['label'] = 'Pistolet lourd',
        ['weight'] = 2000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un pistolet puissant, maniement à deux mains conseillé.'
    },
    ['weapon_vintagepistol'] = {
        ['name'] = 'weapon_vintagepistol',
        ['label'] = 'Pistolet vintage',
        ['weight'] = 1400,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Pistolet pour ceux qui ont un coté Hypster.'
    },
    ['weapon_flaregun'] = {
        ['name'] = 'weapon_flaregun',
        ['label'] = 'Pistolet de détresse',
        ['weight'] = 800,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_FLARE',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Pour signaler ta position.'
    },
    ['weapon_marksmanpistol'] = {
        ['name'] = 'weapon_marksmanpistol',
        ['label'] = 'Pistolet de précision',
        ['weight'] = 7000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une arme de poing avec un canon un peu plus long, très précise.'
    },
    ['weapon_revolver'] = {
        ['name'] = 'weapon_revolver',
        ['label'] = 'Revolver',
        ['weight'] = 2000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un revolver classique, de quoi se sentir un peu cowboy.'
    },
    ['weapon_revolver_mk2'] = {
        ['name'] = 'weapon_revolver_mk2',
        ['label'] = 'Revolver lourd Mk II',
        ['weight'] = 2000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Un révolver lourd, lourd dégats.'
    },
    ['weapon_doubleaction'] = {
        ['name'] = 'weapon_doubleaction',
        ['label'] = 'Revolver double action',
        ['weight'] = 2000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Un révolver de luxe.'
    },
    ['weapon_snspistol_mk2'] = {
        ['name'] = 'weapon_snspistol_mk2',
        ['label'] = 'Pétoire Mk II',
        ['weight'] = 800,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Un tout petit pistolet.'
    },
    ['weapon_raypistol'] = {
        ['name'] = 'weapon_raypistol',
        ['label'] = 'Up\'n\'atomisateur',
        ['weight'] = 2000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Weapon Raypistol'
    },
    ['weapon_ceramicpistol'] = {
        ['name'] = 'weapon_ceramicpistol',
        ['label'] = 'Pistolet en céramique',
        ['weight'] = 1400,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Un pistolet en céramique, n\'active pos les détecteurs de métaux.'
    },
    ['weapon_navyrevolver'] = {
        ['name'] = 'weapon_navyrevolver',
        ['label'] = 'Revolver de la Navy',
        ['weight'] = 1200,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Révolver militaire.'
    },
    ['weapon_gadgetpistol'] = {
        ['name'] = 'weapon_gadgetpistol',
        ['label'] = 'Pistolet Perico',
        ['weight'] = 1500,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Arme Pistolet considérée par certains comme étant un gadget'
    },

    -- Submachine Guns
    ['weapon_microsmg'] = {
        ['name'] = 'weapon_microsmg',
        ['label'] = 'Pistolet mitrailleur',
        ['weight'] = 1400,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SMG',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une mitraillette tenable à une main.'
    },
    ['weapon_smg'] = {
        ['name'] = 'weapon_smg',
        ['label'] = 'Mitraillette',
        ['weight'] = 1500,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SMG',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une mitraillette basique au possible, efficacité prouvée.'
    },
    ['weapon_smg_mk2'] = {
        ['name'] = 'weapon_smg_mk2',
        ['label'] = 'SMG Mk II',
        ['weight'] = 3000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SMG',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'SMG MK2'
    },
    ['weapon_assaultsmg'] = {
        ['name'] = 'weapon_assaultsmg',
        ['label'] = 'Mitraillette d\'assaut',
        ['weight'] = 4200,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SMG',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une version plus lourde de la mitrailette.'
    },
    ['weapon_combatpdw'] = {
        ['name'] = 'weapon_combatpdw',
        ['label'] = 'ADP de combat',
        ['weight'] = 2400,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SMG',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une version de combat d\'une mitrailleuse légère de poche.'
    },
    ['weapon_machinepistol'] = {
        ['name'] = 'weapon_machinepistol',
        ['label'] = 'Tec-9',
        ['weight'] = 1200,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PISTOL',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un pistolet à chargement automatique capable de tirer en rafale ou en mode entièrement automatique.'
    },
    ['weapon_minismg'] = {
        ['name'] = 'weapon_minismg',
        ['label'] = 'Mitraillette légère',
        ['weight'] = 1600,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SMG',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Petite mitraileuse avec crosse pour épaule.'
    },
    ['weapon_raycarbine'] = {
        ['name'] = 'weapon_raycarbine',
        ['label'] = 'Dézingator Infernal',
        ['weight'] = 1500,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SMG',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Adapté pour dégommer tout ce qui passe à votre portée.'
    },

    -- Shotguns
    ['weapon_pumpshotgun'] = {
        ['name'] = 'weapon_pumpshotgun',
        ['label'] = 'Fusil à pompe',
        ['weight'] = 2500,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SHOTGUN',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un fusil à pompe, efficace à courte portée.'
    },
    ['weapon_sawnoffshotgun'] = {
        ['name'] = 'weapon_sawnoffshotgun',
        ['label'] = 'Fusil à canon scié',
        ['weight'] = 1800,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SHOTGUN',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un fusil à pompe avec canon racourci, pour de la courte distance.'
    },
    ['weapon_assaultshotgun'] = {
        ['name'] = 'weapon_assaultshotgun',
        ['label'] = 'Fusil d\'assaut',
        ['weight'] = 2500,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SHOTGUN',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Arme recommandée pour de courtes distances.'
    },
    ['weapon_bullpupshotgun'] = {
        ['name'] = 'weapon_bullpupshotgun',
        ['label'] = 'Fusil à pompe Bullpup',
        ['weight'] = 2400,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SHOTGUN',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un fusil à pompe compact.'
    },
    ['weapon_musket'] = {
        ['name'] = 'weapon_musket',
        ['label'] = 'Mousquet',
        ['weight'] = 2000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SHOTGUN',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Fusil léger d\'époque, idéal à moyenne distance.'
    },
    ['weapon_heavyshotgun'] = {
        ['name'] = 'weapon_heavyshotgun',
        ['label'] = 'Fusil à pompe lourd',
        ['weight'] = 2500,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SHOTGUN',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un fusil à pompe lourd, ravageur à courte distance.'
    },
    ['weapon_dbshotgun'] = {
        ['name'] = 'weapon_dbshotgun',
        ['label'] = 'Fusil à double canon',
        ['weight'] = 2400,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SHOTGUN',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Fusil à courte distance, permettant de tirer deux balles sans recharger.'
    },
    ['weapon_autoshotgun'] = {
        ['name'] = 'weapon_autoshotgun',
        ['label'] = 'Fusil à pompe d\'assaut',
        ['weight'] = 3600,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SHOTGUN',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Fusil à pompe avec grande cadence de tir.'
    },
    ['weapon_pumpshotgun_mk2'] = {
        ['name'] = 'weapon_pumpshotgun_mk2',
        ['label'] = 'Fusil à pompe Mk II',
        ['weight'] = 5200,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SHOTGUN',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Fusil à pompe, lourds dégats au corps à corps.'
    },
    ['weapon_combatshotgun'] = {
        ['name'] = 'weapon_combatshotgun',
        ['label'] = 'Fusil à pompe de combat',
        ['weight'] = 2600,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SHOTGUN',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Fusil à pompe, lourds dégats au corps à corps.'
    },

    -- Assault Rifles
    ['weapon_assaultrifle'] = {
        ['name'] = 'weapon_assaultrifle',
        ['label'] = 'Fusil d\'assaut',
        ['weight'] = 3000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_RIFLE',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un fusil d\'assaut, tout ce qu\'il y a de plus classique.'
    },
    ['weapon_assaultrifle_mk2'] = {
        ['name'] = 'weapon_assaultrifle_mk2',
        ['label'] = 'Fusil d\'assaut Mk II',
        ['weight'] = 3000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_RIFLE',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Un fusil d\'assaut, efficace.'
    },
    ['weapon_carbinerifle'] = {
        ['name'] = 'weapon_carbinerifle',
        ['label'] = 'Carabine',
        ['weight'] = 2000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_RIFLE',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Fusil d\'assaut très polyvalent en toute circonstance.'
    },
    ['weapon_carbinerifle_mk2'] = {
        ['name'] = 'weapon_carbinerifle_mk2',
        ['label'] = 'Carabine spéciale Mk II',
        ['weight'] = 4200,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_RIFLE',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Une carabine spéciale.'
    },
    ['weapon_advancedrifle'] = {
        ['name'] = 'weapon_advancedrifle',
        ['label'] = 'Fusil amélioré',
        ['weight'] = 4300,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_RIFLE',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une version amélioré d\'un fusil d\'assaut militaire.'
    },
    ['weapon_specialcarbine'] = {
        ['name'] = 'weapon_specialcarbine',
        ['label'] = 'Carabine spéciale',
        ['weight'] = 4000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_RIFLE',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un fusil d\'assaut extrêmement polyvalent pour toute situation de combat.'
    },
    ['weapon_bullpuprifle'] = {
        ['name'] = 'weapon_bullpuprifle',
        ['label'] = 'Fusil d\'assaut Bullpup',
        ['weight'] = 3600,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_RIFLE',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un fusil d\'assaut compact.'
    },
    ['weapon_compactrifle'] = {
        ['name'] = 'weapon_compactrifle',
        ['label'] = 'Fusil compact',
        ['weight'] = 2800,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_RIFLE',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Fusil d\'assaut compact.'
    },
    ['weapon_specialcarbine_mk2'] = {
        ['name'] = 'weapon_specialcarbine_mk2',
        ['label'] = 'Carabine Speciale Mk II',
        ['weight'] = 4000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_RIFLE',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Une arme de haute technologie.'
    },
    ['weapon_bullpuprifle_mk2'] = {
        ['name'] = 'weapon_bullpuprifle_mk2',
        ['label'] = 'Fusil d\'assaut Bullpup Mk II',
        ['weight'] = 3500,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_RIFLE',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Fusil d\'assaut militaire.'
    },
    ['weapon_militaryrifle'] = {
        ['name'] = 'weapon_militaryrifle',
        ['label'] = 'Fusil militaire',
        ['weight'] = 4000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_RIFLE',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Fusil d\'assaut de qualité militaire.'
    },

    -- Light Machine Guns
    ['weapon_mg'] = {
        ['name'] = 'weapon_mg',
        ['label'] = 'Mitrailleuse',
        ['weight'] = 7600,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_MG',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Grosse mitrailleuse avec grande capacité de munitions.'
    },
    ['weapon_combatmg'] = {
        ['name'] = 'weapon_combatmg',
        ['label'] = 'Mitrailleuse MG',
        ['weight'] = 8000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_MG',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Tire des balles en succession rapide tant que la gâchette est pressée.'
    },
    ['weapon_gusenberg'] = {
        ['name'] = 'weapon_gusenberg',
        ['label'] = 'Thompson',
        ['weight'] = 3000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_MG',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Pistollet mitrailleur, aussi appelé Tommygun'
    },
    ['weapon_combatmg_mk2'] = {
        ['name'] = 'weapon_combatmg_mk2',
        ['label'] = 'Mitrailleuse de combat Mk II',
        ['weight'] = 8400,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_MG',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Grosse mitrailleuse lourde avec grande capacité de munitions.'
    },

    -- Sniper Rifles
    ['weapon_sniperrifle'] = {
        ['name'] = 'weapon_sniperrifle',
        ['label'] = 'Fusil sniper',
        ['weight'] = 7000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SNIPER',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un fusil de haute précision et à longue portée.'
    },
    ['weapon_heavysniper'] = {
        ['name'] = 'weapon_heavysniper',
        ['label'] = 'Fusil de sniper lourd',
        ['weight'] = 7000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SNIPER',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un fusil à lunette de précision, idéal à longue distance.'
    },
    ['weapon_marksmanrifle'] = {
        ['name'] = 'weapon_marksmanrifle',
        ['label'] = 'Fusil à lunette',
        ['weight'] = 7000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SNIPER',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un fusil de précision.'
    },
    ['weapon_remotesniper'] = {
        ['name'] = 'weapon_remotesniper',
        ['label'] = 'Tourelle de précison',
        ['weight'] = 20000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SNIPER_REMOTE',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un fusil de précision monté sur une tourelle. Grande précision et puissance de feu.'
    },
    ['weapon_heavysniper_mk2'] = {
        ['name'] = 'weapon_heavysniper_mk2',
        ['label'] = 'Fusil de précision lourd',
        ['weight'] = 8000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SNIPER',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Un fusil de précision lourd, lourd dégats à longue distance.'
    },
    ['weapon_marksmanrifle_mk2'] = {
        ['name'] = 'weapon_marksmanrifle_mk2',
        ['label'] = 'Fusil à lunette Mk II',
        ['weight'] = 4500,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_SNIPER',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Un fusil à lunette.'
    },

    -- Heavy Weapons
    ['weapon_rpg'] = {
        ['name'] = 'weapon_rpg',
        ['label'] = 'RPG',
        ['weight'] = 6300,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_RPG',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Lance-roquettes'
    },
    ['weapon_grenadelauncher'] = {
        ['name'] = 'weapon_grenadelauncher',
        ['label'] = 'Lance-grenades',
        ['weight'] = 10000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_GRENADELAUNCHER',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un lance... grenades. BOUM!'
    },
    ['weapon_grenadelauncher_smoke'] = {
        ['name'] = 'weapon_grenadelauncher_smoke',
        ['label'] = 'Lanceur de fumigène',
        ['weight'] = 6000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_GRENADELAUNCHER',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Lance fumigène, libérant un épais nuage de fumée.'
    },
    ['weapon_minigun'] = {
        ['name'] = 'weapon_minigun',
        ['label'] = 'Minigun',
        ['weight'] = 12000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_MINIGUN',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Pour déchaîner les enfers, dans un bruit assourdissant.'
    },
    ['weapon_firework'] = {
        ['name'] = 'weapon_firework',
        ['label'] = 'Lanceur pyrotechnique',
        ['weight'] = 6000,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'De quoi fêter la nouvelle année.'
    },
    ['weapon_railgun'] = {
        ['name'] = 'weapon_railgun',
        ['label'] = 'Fusil à impulsion',
        ['weight'] = 14000,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une arme futuriste envoyant des onde électromagnétique'
    },
    ['weapon_hominglauncher'] = {
        ['name'] = 'weapon_hominglauncher',
        ['label'] = 'Lance-missiles',
        ['weight'] = 10000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_STINGER',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un lance missile, capable de suivre sa cible une fois verrouillée.'
    },
    ['weapon_compactlauncher'] = {
        ['name'] = 'weapon_compactlauncher',
        ['label'] = 'Lance-grenades compact',
        ['weight'] = 6000,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un lance-grenades dans un format très compacté.'
    },
    ['weapon_rayminigun'] = {
        ['name'] = 'weapon_rayminigun',
        ['label'] = 'Destructeur de l\'infini',
        ['weight'] = 14000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_MINIGUN',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Un minigun futuriste, tirant des lasers.'
    },

    -- Throwables
    ['weapon_grenade'] = {
        ['name'] = 'weapon_grenade',
        ['label'] = 'Grenade',
        ['weight'] = 200,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Un explosif portatif à lancer.'
    },
    ['weapon_bzgas'] = {
        ['name'] = 'weapon_bzgas',
        ['label'] = 'Grenade à lacrymogène',
        ['weight'] = 200,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une cartouche de gaz qui provoque une douleur extrême une fois inhalée.'
    },
    ['weapon_molotov'] = {
        ['name'] = 'weapon_molotov',
        ['label'] = 'Cocktail Molotov',
        ['weight'] = 1000,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Bouteille incendiaire... A ne surtout pas boire !'
    },
    ['weapon_stickybomb'] = {
        ['name'] = 'weapon_stickybomb',
        ['label'] = 'C4',
        ['weight'] = 1000,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une charge explosive recouverte d\'un adhésif qui, lorsqu\'elle est lancée contre un objet, reste collée jusqu\'à ce qu\'elle explose.'
    },
    ['weapon_proxmine'] = {
        ['name'] = 'weapon_proxmine',
        ['label'] = 'Mine de proximité',
        ['weight'] = 1000,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une bombe à placer au sol et qui explose dès que quelqu\'un approche.'
    },
    ['weapon_snowball'] = {
        ['name'] = 'weapon_snowball',
        ['label'] = 'Boule de neige',
        ['weight'] = 100,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une boule de neige, à lancer sur tout le monde.'
    },
    ['weapon_pipebomb'] = {
        ['name'] = 'weapon_pipebomb',
        ['label'] = 'Bombe artisanale',
        ['weight'] = 1000,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Une bombe faite maison ! Certain de l\'efficacité ?'
    },
    ['weapon_ball'] = {
        ['name'] = 'weapon_ball',
        ['label'] = 'Balle de baseball',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_BALL',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Lance la à ton pote qui a la batte !'
    },
    ['weapon_smokegrenade'] = {
        ['name'] = 'weapon_smokegrenade',
        ['label'] = 'Fumigène',
        ['weight'] = 500,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Grenade libérant un épais nuage de fumée.'
    },
    ['weapon_flare'] = {
        ['name'] = 'weapon_flare',
        ['label'] = 'Pistolet à fusées',
        ['weight'] = 800,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_FLARE',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'Petit dispositif pyrotechnique utilisés pour l\'éclairage et la signalisation.'
    },

    -- Miscellaneous
    ['weapon_petrolcan'] = {
        ['name'] = 'weapon_petrolcan',
        ['label'] = 'Bidon d\'essence',
        ['weight'] = 1000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PETROLCAN',
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'De quoi faire le plein de ta caisse !'
    },
    ['weapon_fireextinguisher'] = {
        ['name'] = 'weapon_fireextinguisher',
        ['label'] = 'Extincteur',
        ['weight'] = 1000,
        ['type'] = 'weapon',
        ['ammotype'] = nil,
        ['unique'] = true,
        ['useable'] = false,
        ['description'] = 'De quoi éteindre un feu !'
    },
    ['weapon_hazardcan'] = {
        ['name'] = 'weapon_hazardcan',
        ['label'] = 'Bidon chimique',
        ['weight'] = 1000,
        ['type'] = 'weapon',
        ['ammotype'] = 'AMMO_PETROLCAN',
        ['unique'] = true,
        ['useable'] = true,
        ['description'] = 'Bidon contenant une substance chimique dangereuse.'
    },

    -- ITEMS

    -- Ammo ITEMS
    ['pistol_ammo'] = {
        ['name'] = 'pistol_ammo',
        ['label'] = 'Munition de Pistolet',
        ['weight'] = 500,
        ['type'] = 'weapon_ammo',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Munitions pour pistolets.'
    },
    ['rifle_ammo'] = {
        ['name'] = 'rifle_ammo',
        ['label'] = 'Munitions de Fusil',
        ['weight'] = 500,
        ['type'] = 'weapon_ammo',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Munitions pour fusils automatiques.'
    },
    ['smg_ammo'] = {
        ['name'] = 'smg_ammo',
        ['label'] = 'Munitions SMG',
        ['weight'] = 500,
        ['type'] = 'weapon_ammo',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Munitions pour mitraillettes légères.'
    },
    ['shotgun_ammo'] = {
        ['name'] = 'shotgun_ammo',
        ['label'] = 'Munitions de Fusil à pompe',
        ['weight'] = 500,
        ['type'] = 'weapon_ammo',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Munitions pour fusils à pompe.'
    },
    ['mg_ammo'] = {
        ['name'] = 'mg_ammo',
        ['label'] = 'Munitions MG',
        ['weight'] = 500,
        ['type'] = 'weapon_ammo',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Munitions pour mitrailleuses lourdes.'
    },
    ['snp_ammo'] = {
        ['name'] = 'snp_ammo',
        ['label'] = 'Munitions de Sniper',
        ['weight'] = 500,
        ['type'] = 'weapon_ammo',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Munitions pour fusils de précision.'
    },

    -- Card ITEMS
    ['lawyerpass'] = {
        ['name'] = 'lawyerpass',
        ['label'] = 'Laissez-passer d\'avocat',
        ['weight'] = 100,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Pass exclusif aux avocats pour montrer qu\'ils peuvent représenter un suspect.'
    },

    -- Eat ITEMS
    ['tosti'] = {
        ['name'] = 'tosti',
        ['label'] = 'Panini fromage',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Hmmmm du fromage chauffé !'
    },
    ['twerks_candy'] = {
        ['name'] = 'twerks_candy',
        ['label'] = 'Twerks',
        ['weight'] = 100,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Oooooh, des bonbons !'
    },
    ['snikkel_candy'] = {
        ['name'] = 'snikkel_candy',
        ['label'] = 'Sniteuls',
        ['weight'] = 100,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Miam miam les sucreries !'
    },
    ['sandwich'] = {
        ['name'] = 'sandwich',
        ['label'] = 'Sandwich',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['durability'] = 2,
        ['combinable'] = nil,
        ['description'] = 'Avant tout du pain pour l\'estomac.'
    },

    -- Drink ITEMS
    ['water_bottle'] = {
        ['name'] = 'water_bottle',
        ['label'] = 'Bouteille d\'eau',
        ['weight'] = 300,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['durability'] = 31,
        ['combinable'] = nil,
        ['description'] = 'De l\'eau, merci.'
    },
    ['coffee'] = {
        ['name'] = 'coffee',
        ['label'] = 'Café',
        ['weight'] = 300,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Grande source de caféine.'
    },
    ['kurkakola'] = {
        ['name'] = 'kurkakola',
        ['label'] = 'Cola',
        ['weight'] = 300,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'De l\'eau, beaucoup de sucre et ça pétille !'
    },

    -- Alcohol
    ['beer'] = {
        ['name'] = 'beer',
        ['label'] = 'Bière',
        ['weight'] = 500,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Rien de mieux qu\'une bonne bière fraiche !'
    },
    ['whiskey'] = {
        ['name'] = 'whiskey',
        ['label'] = 'Whisky',
        ['weight'] = 1000,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['durability'] = 365,
        ['combinable'] = nil,
        ['description'] = 'Pour toutes les petites soifs !'
    },
    ['vodka'] = {
        ['name'] = 'vodka',
        ['label'] = 'Vodka',
        ['weight'] = 1000,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['durability'] = 365,
        ['combinable'] = nil,
        ['description'] = 'Pour toutes les petites soifs !'
    },
    ['grape1'] = {
        ['name'] = 'grape1',
        ['label'] = 'Grappe de Cardinal',
        ['weight'] = 400,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Raisin violet au goût légèrement sucré.'
    },
    ['grape2'] = {
        ['name'] = 'grape2',
        ['label'] = 'Grappe de Muscat',
        ['weight'] = 400,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Raisin blanc, assez sucré.'
    },
    ['grape3'] = {
        ['name'] = 'grape3',
        ['label'] = 'Grappe de Centennial',
        ['weight'] = 400,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Raisin vert, sucré, avec une pointe d\'acidité.'
    },
    ['grape4'] = {
        ['name'] = 'grape4',
        ['label'] = 'Grappe de Chasselas',
        ['weight'] = 400,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Raisin jaune avec un léger gout de miel.'
    },
    ['wine1'] = {
        ['name'] = 'wine1',
        ['label'] = 'Mandatorien',
        ['weight'] = 1000,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 3650,
        ['combinable'] = nil,
        ['description'] = 'Vin rouge avec une légère note sucrée !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['wine2'] = {
        ['name'] = 'wine2',
        ['label'] = 'Cuve Saint-Monnay',
        ['weight'] = 1000,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 3650,
        ['combinable'] = nil,
        ['description'] = 'Vin blanc assez sucré !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['wine3'] = {
        ['name'] = 'wine3',
        ['label'] = 'LaMano Blanc',
        ['weight'] = 1000,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 3650,
        ['combinable'] = nil,
        ['description'] = 'Vin blanc avec une note d\'acidité !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['wine4'] = {
        ['name'] = 'wine4',
        ['label'] = 'IndySpensable',
        ['weight'] = 1000,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 3650,
        ['combinable'] = nil,
        ['description'] = 'Vin blanc sirupeux au petit goût de miel !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['grapejuice1'] = {
        ['name'] = 'grapejuice1',
        ['label'] = 'Naples Gius',
        ['weight'] = 600,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Jus de raisins rouges !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['grapejuice2'] = {
        ['name'] = 'grapejuice2',
        ['label'] = 'JusKano',
        ['weight'] = 600,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Jus très sucré !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['grapejuice3'] = {
        ['name'] = 'grapejuice3',
        ['label'] = 'TropiCaMaK',
        ['weight'] = 600,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Jus de fruit légèrement acide !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['grapejuice4'] = {
        ['name'] = 'grapejuice4',
        ['label'] = 'FruitForSub',
        ['weight'] = 600,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Jus multifruits, pleins de vitamines !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['grapejuice5'] = {
        ['name'] = 'grapejuice5',
        ['label'] = 'OasClick',
        ['weight'] = 600,
        ['type'] = 'drink',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Jus de fruit au miel !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['tripe'] = {
        ['name'] = 'tripe',
        ['label'] = 'Tripe',
        ['weight'] = 200,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Ragoutant, mais vraiment bon !'
    },
    ['peau'] = {
        ['name'] = 'peau',
        ['label'] = 'Peau',
        ['weight'] = 300,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Bien grillé s\'il vous plaît !'
    },
    ['os'] = {
        ['name'] = 'os',
        ['label'] = 'Os',
        ['weight'] = 400,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'A ne pas avaler !'
    },
    ['viscere'] = {
        ['name'] = 'viscere',
        ['label'] = 'Viscère',
        ['weight'] = 300,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Un régal si bien assaisonné.'
    },
    ['viande'] = {
        ['name'] = 'viande',
        ['label'] = 'Viande',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Quel cuisson ?'
    },
    ['langue'] = {
        ['name'] = 'langue',
        ['label'] = 'Langue',
        ['weight'] = 200,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'A faire mijoter !'
    },
    ['abat'] = {
        ['name'] = 'abat',
        ['label'] = 'Abat',
        ['weight'] = 200,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Tout le monde n\'aime pas ça !'
    },
    ['rognon'] = {
        ['name'] = 'rognon',
        ['label'] = 'Rognon',
        ['weight'] = 200,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Rosé pour la cuisson !'
    },
    ['sausage1'] = {
        ['name'] = 'sausage1',
        ['label'] = 'Sans-Pareil',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Un gout inimaginable !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['sausage2'] = {
        ['name'] = 'sausage2',
        ['label'] = 'Solong',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Le saucisson le plus long jamais vu !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['sausage3'] = {
        ['name'] = 'sausage3',
        ['label'] = 'Lasbounou',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Un peu plus gras que la moyenne !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['sausage4'] = {
        ['name'] = 'sausage4',
        ['label'] = 'Soziflard',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Pour un apéro réussi entre amis !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['sausage5'] = {
        ['name'] = 'sausage5',
        ['label'] = 'Saucifion ',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Un gout très prononcé !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['milk'] = {
        ['name'] = 'milk',
        ['label'] = 'Pot de lait',
        ['weight'] = 3000,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Avant ou après avoir mis les céréales ?'
    },
    ['cheese1'] = {
        ['name'] = 'cheese1',
        ['label'] = 'Poveridou',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Idéal en tranche ou rapé !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['cheese2'] = {
        ['name'] = 'cheese2',
        ['label'] = 'Caprice du tchat',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Un amour du fromage !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['cheese3'] = {
        ['name'] = 'cheese3',
        ['label'] = 'Zaroilles',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Parait que c\'est bon avec du café !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['cheese4'] = {
        ['name'] = 'cheese4',
        ['label'] = 'MoMan-Tum',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Un fromage légèrement salé !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['cheese5'] = {
        ['name'] = 'cheese5',
        ['label'] = "P'tit Dashque",
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Très bon avec une confiture !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['cheese6'] = {
        ['name'] = 'cheese6',
        ['label'] = 'Tchat qui rit',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Le fromage des touts petits !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['cheese7'] = {
        ['name'] = 'cheese7',
        ['label'] = 'Cutmembert',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Dans une bonne baguette !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['cheese8'] = {
        ['name'] = 'cheese8',
        ['label'] = 'CHEHdar',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Idéal pour les burgers !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },
    ['cheese9'] = {
        ['name'] = 'cheese9',
        ['label'] = 'GorgonZera',
        ['weight'] = 300,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Un très bon fromage fondu en sauce !',
        ['resellPrice'] = 40,
        ['resellZone'] = 'Resell:LSPort:Food',
    },

    -- Drugs
    ['joint'] = {
        ['name'] = 'joint',
        ['label'] = 'Joint',
        ['weight'] = 100,
        ['type'] = 'drug',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Fait à la main !'
    },
    ['cokebaggy'] = {
        ['name'] = 'cokebaggy',
        ['label'] = 'Sachet de Cocaïne',
        ['weight'] = 600,
        ['type'] = 'drug',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Pour être heureux très vite.'
    },
    ['crack_baggy'] = {
        ['name'] = 'crack_baggy',
        ['label'] = 'Sachet de Crack',
        ['weight'] = 200,
        ['type'] = 'drug',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Pour devenir heureux encore plus rapidement.'
    },
    ['coke_small_brick'] = {
        ['name'] = 'coke_small_brick',
        ['label'] = 'Paquet de coke',
        ['weight'] = 300,
        ['type'] = 'drug',
        ['unique'] = true,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Petit paquet de cocaïne, utilisé principalement pour les transactions et prenant beaucoup de place.'
    },
    ['meth'] = {
        ['name'] = 'meth',
        ['label'] = 'Meth',
        ['weight'] = 100,
        ['type'] = 'drug',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Un pochon de meth.'
    },
    ['rolling_paper'] = {
        ['name'] = 'rolling_paper',
        ['label'] = 'Papier à rouler',
        ['weight'] = 100,
        ['type'] = 'drug',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = {
            accept = {
                'weed_white-widow', 'weed_skunk', 'weed_purple-haze', 'weed_og-kush', 'weed_amnesia', 'weed_ak47'
            },
            reward = 'joint',
            anim = {
                ['dict'] = 'anim@amb@business@weed@weed_inspecting_high_dry@',
                ['lib'] = 'weed_inspecting_high_base_inspector',
                ['text'] = 'Rolling joint',
                ['timeOut'] = 5000,
            }
        },
        ['description'] = 'Papier fabriqué spécifiquement pour envelopper et fumer du tabac ou du cannabis.'
    },

    -- Seed And Weed
    ['empty_weed_bag'] = {
        ['name'] = 'empty_weed_bag',
        ['label'] = 'Sachet d\'herbe vide',
        ['weight'] = 100,
        ['type'] = 'drug',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Un petit sachet vide.'
    },

    -- Material
    ['plastic'] = {
        ['name'] = 'plastic',
        ['label'] = 'Plastique',
        ['weight'] = 100,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'RECYCLEZ! - Greta Thunberg 2019.'
    },
    ['metalscrap'] = {
        ['name'] = 'metalscrap',
        ['label'] = 'Ferraille',
        ['weight'] = 300,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Il doit être possible d\'en faire quelque chose.'
    },
    ['copper'] = {
        ['name'] = 'copper',
        ['label'] = 'Cuivre',
        ['weight'] = 800,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Métal de couleur rouge ou orangée, le cuivre est ductile et malléable.'
    },
    ['aluminum'] = {
        ['name'] = 'aluminum',
        ['label'] = 'Aluminium',
        ['weight'] = 300,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Conserve les restes plus longtemps !'
    },
    ['aluminumoxide'] = {
        ['name'] = 'aluminumoxide',
        ['label'] = 'Poudre d\'Alluminium',
        ['weight'] = 100,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Un peu de poudre à mélanger.'
    },
    ['iron'] = {
        ['name'] = 'iron',
        ['label'] = 'Fer',
        ['weight'] = 800,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Métal pouuvant être travaillé pour avoir une forme particulière.'
    },
    ['ironoxide'] = {
        ['name'] = 'ironoxide',
        ['label'] = 'Poudre de fer',
        ['weight'] = 100,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = {
            accept = {
                'aluminumoxide'
            },
            reward = 'thermite',
            anim = {
                ['dict'] = 'anim@amb@business@weed@weed_inspecting_high_dry@',
                ['lib'] = 'weed_inspecting_high_base_inspector',
                ['text'] = 'Mixing powder..',
                ['timeOut'] = 10000
            }
        },
        ['description'] = 'Cette poudre devrait pouvoir servir à quelque chose..'
    },
    ['steel'] = {
        ['name'] = 'steel',
        ['label'] = 'Acier',
        ['weight'] = 300,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Élaboré pour résister à des sollicitations mécaniques et chimiques.'
    },
    ['rubber'] = {
        ['name'] = 'rubber',
        ['label'] = 'Caoutchouc',
        ['weight'] = 200,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Ça conduit pas l\'électricité.'
    },
    ['glass'] = {
        ['name'] = 'glass',
        ['label'] = 'Verre',
        ['weight'] = 300,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Très fragile, attention.'
    },

    -- Tools
    ['lockpick'] = {
        ['name'] = 'lockpick',
        ['label'] = 'Crochet',
        ['weight'] = 200,
        ['type'] = 'item_illegal',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Très utile quand on perd sa clé... Ou pour d\'autres choses...'
    },
    ['electronickit'] = {
        ['name'] = 'electronickit',
        ['label'] = 'Kit d\'électronique',
        ['weight'] = 300,
        ['type'] = 'item_illegal',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = {
            accept = {
                'gatecrack'
            },
            reward = 'trojan_usb',
            anim = nil
        },
        ['description'] = 'Envie de faire de la robotique ?'
    },
    ['trojan_usb'] = {
        ['name'] = 'trojan_usb',
        ['label'] = 'USB avec Virus',
        ['weight'] = 300,
        ['type'] = 'item_illegal',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'L\'outil parfait pour faire infecter un ordinateur'
    },
    -- Vehicle Tools
    ['repairkit'] = {
        ['name'] = 'repairkit',
        ['label'] = 'Kit de réparation',
        ['weight'] = 5000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Une belle boîte à outils avec des trucs pour réparer votre véhicule.'
    },
    ['cleaningkit'] = {
        ['name'] = 'cleaningkit',
        ['label'] = 'Kit de nettoyage',
        ['weight'] = 200,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Pour redonner une nouvelle jeunesse à votre voiture !'
    },
    -- Medication
    ['firstaid'] = {
        ['name'] = 'firstaid',
        ['label'] = 'Trousse de secours',
        ['weight'] = 600,
        ['type'] = 'item',
        ['image'] = 'Trousse de soin.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Pour remettre les gens sur pied.'
    },
    ['ifaks'] = {
        ['name'] = 'ifaks',
        ['label'] = 'IFAK',
        ['weight'] = 600,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Kits de traumatologie contenant du matériel essentiel pour sauver des vies, contrôler les hémorragies et traiter les principales blessures.'
    },
    ['painkiller'] = {
        ['name'] = 'painkiller',
        ['label'] = 'Anti-douleurs',
        ['weight'] = 100,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Quand la douleur est trop forte, une petite pillule et c\'est reparti !'
    },
    ['antibiotic'] = {
        ['name'] = 'antibiotic',
        ['label'] = 'Antibiotiques',
        ['weight'] = 100,
        ['type'] = 'item',
        ['image'] = 'antibiotic.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Quand on a la grippe, une petite pillule et c\'est reparti !'
    },
    ['walkstick'] = {
        ['name'] = 'walkstick',
        ['label'] = 'Bâton de marche',
        ['weight'] = 600,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Pour que les papys puissent taper sur les voitures.'
    },
    ['bloodbag'] = {
        ['name'] = 'bloodbag',
        ['label'] = 'Poche de sang',
        ['weight'] = 800,
        ['type'] = 'item',
        ['image'] = 'Pochedesang.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Utile pour réanimer'
    },
    ['empty_bloodbag'] = {
        ['name'] = 'empty_bloodbag',
        ['label'] = 'Poche vide',
        ['weight'] = 200,
        ['type'] = 'item',
        ['image'] = 'Pochevide.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Utile pour faire une prise de sang'
    },
    ['used_bloodbag'] = {
        ['name'] = 'used_bloodbag',
        ['label'] = 'Poche de sang usagée',
        ['weight'] = 300,
        ['type'] = 'item',
        ['image'] = 'used_bloodbag.png',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Pas très utile pour réanimer.'
    },
    ['tissue'] = {
        ['name'] = 'tissue',
        ['label'] = 'Mouchoirs',
        ['weight'] = 100,
        ['type'] = 'item',
        ['image'] = 'Mouchoir.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Utile en cas de rhume'
    },
    ['pommade'] = {
        ['name'] = 'pommade',
        ['label'] = 'Pommade',
        ['weight'] = 100,
        ['type'] = 'item',
        ['image'] = 'Pommade.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Utile en cas de rougeur'
    },
    ['defibrillator'] = {
        ['name'] = 'defibrillator',
        ['label'] = 'Défibrillateur',
        ['weight'] = 5000,
        ['type'] = 'item',
        ['image'] = 'Défibrillateur.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Utile pour réanimer'
    },
    ['poumon'] = {
        ['name'] = 'poumon',
        ['label'] = 'Poumon',
        ['weight'] = 1000,
        ['type'] = 'organ',
        ['image'] = 'poumon.png',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['durability'] = 60,
        ['combinable'] = nil,
        ['description'] = 'Utile pour respirer.'
    },
    ['foie'] = {
        ['name'] = 'foie',
        ['label'] = 'Foie',
        ['weight'] = 1000,
        ['type'] = 'organ',
        ['image'] = 'foie.png',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['durability'] = 60,
        ['combinable'] = nil,
        ['description'] = 'Attention à la crise.'
    },
    ['rein'] = {
        ['name'] = 'rein',
        ['label'] = 'Rein',
        ['weight'] = 1000,
        ['type'] = 'organ',
        ['image'] = 'rein.png',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['durability'] = 60,
        ['combinable'] = nil,
        ['description'] = 'Ca pourrait t\'en couter un.'
    },

    ['garbagebag'] = {
        ['name'] = 'garbagebag',
        ['label'] = 'Sac poubelle',
        ['weight'] = 2000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['description'] = 'Pour jeter tout type d\'ordures.'
    },
    ['cardbord'] = {
        ['name'] = 'cardbord',
        ['label'] = 'Mon carton',
        ['weight'] = 200,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['description'] = 'Une jolie maison !'
    },

    -- Communication
    ['phone'] = {
        ['name'] = 'phone',
        ['label'] = 'ZPhone',
        ['weight'] = 300,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Outil qui zert à communiquer.'
    },
    ['radio'] = {
        ['name'] = 'radio',
        ['label'] = 'Radio',
        ['weight'] = 500,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Alooo ?'
    },
    ['megaphone'] = {
        ['name'] = 'megaphone',
        ['label'] = 'Mégaphone',
        ['weight'] = 1000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Peut servir pour parler a une foule... A déjà permis de faire plusieurs exploits mondiaux'
    },
    ['microphone'] = {
        ['name'] = 'microphone',
        ['label'] = 'Microphone',
        ['weight'] = 800,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Poupipou, il est l\'heure de CHANTER !'
    },
    ['laptop'] = {
        ['name'] = 'laptop',
        ['label'] = 'Ordinateur portable volé',
        ['weight'] = 1800,
        ['type'] = 'item_illegal',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Ordinateur portable très cher.'
    },
    ['tablet'] = {
        ['name'] = 'tablet',
        ['label'] = 'Tablette volée',
        ['weight'] = 500,
        ['type'] = 'item_illegal',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Tablette qui coûte cher.'
    },
    ['gps'] = {
        ['name'] = 'gps',
        ['label'] = 'GPS',
        ['weight'] = 200,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Trouve ton chemin facilement !'
    },
    ['compass'] = {
        ['name'] = 'compass',
        ['label'] = 'Boussole',
        ['weight'] = 100,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Pour ne jamais perdre le Nord !'
    },

    -- Theft and Jewelry
    ['rolex'] = {
        ['name'] = 'rolex',
        ['label'] = 'Montre en Or',
        ['weight'] = 300,
        ['type'] = 'item_illegal',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Cette montre en Or indique que vous êtes à l\'aise financièrement.'
    },
    ['diamond_ring'] = {
        ['name'] = 'diamond_ring',
        ['label'] = 'Bague en diamant',
        ['weight'] = 300,
        ['type'] = 'item_illegal',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Un bijou magnifique.'
    },
    ['goldchain'] = {
        ['name'] = 'goldchain',
        ['label'] = 'Chaîne en or',
        ['weight'] = 300,
        ['type'] = 'item_illegal',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'C\'est du vrai or ?'
    },
    ['10kgoldchain'] = {
        ['name'] = '10kgoldchain',
        ['label'] = 'Chaîne en or volée',
        ['weight'] = 500,
        ['type'] = 'item_illegal',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Chaîne en or volée à son propriétaire !'
    },
    ['goldbar'] = {
        ['name'] = 'goldbar',
        ['label'] = 'Lingot d\'or',
        ['weight'] = 1000,
        ['type'] = 'item_illegal',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Ça semble valoir son pesant... d\'or.'
    },

    -- Cops Tools
    ['armor'] = {
        ['name'] = 'armor',
        ['label'] = 'Gilet pare-balles',
        ['weight'] = 5000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Il faut parfois se protéger avant de sortir.'
    },
    ['outfit'] = {
        ['name'] = 'outfit',
        ['label'] = 'Tenue',
        ['weight'] = 1000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['handcuffs'] = {
        ['name'] = 'handcuffs',
        ['label'] = 'Menottes de police',
        ['weight'] = 100,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Pour les criminels. Peut avoir d\'autres utilités...'
    },
    ['handcuffs_key'] = {
        ['name'] = 'handcuffs_key',
        ['label'] = 'Clé de menottes',
        ['weight'] = 100,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Pour ouvrir des menottes fermées'
    },
    ['spike'] = {
        ['name'] = 'spike',
        ['label'] = 'Herse',
        ['weight'] = 1200,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Meilleur outil pour réduire la vitesse !'
    },
    ['cone'] = {
        ['name'] = 'cone',
        ['label'] = 'Cône de circulation',
        ['weight'] = 800,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Rien à voir avec un cône VLC.'
    },
    ['police_barrier'] = {
        ['name'] = 'police_barrier',
        ['label'] = 'Barrière de circulation',
        ['weight'] = 1000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'VOUS NE PASSEREZ PAAAAAAAAAS !'
    },

    -- Firework Tools
    ['firework1'] = {
        ['name'] = 'firework1',
        ['label'] = 'Feu d\'artifice',
        ['weight'] = 2000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Cela fait de jolies lumières dans le ciel !'
    },
    ['firework2'] = {
        ['name'] = 'firework2',
        ['label'] = 'Feu d\'artifice POPPER',
        ['weight'] = 2000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Feu d\'artifice de la marque POPPER !'
    },
    ['firework3'] = {
        ['name'] = 'firework3',
        ['label'] = 'Feu d\'artifice WIPEOUT',
        ['weight'] = 2000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Feu d\'artifice de la marque WIPEOUT !'
    },
    ['firework4'] = {
        ['name'] = 'firework4',
        ['label'] = 'Feu d\'artifice WILLOW',
        ['weight'] = 2000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Feu d\'artifice de la marque WILLOW !'
    },

    -- Sea Tools
    ['diving_gear'] = {
        ['name'] = 'diving_gear',
        ['label'] = 'Tenue de plongée',
        ['weight'] = 4000,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Tout ce qu\'il faut pour aller visiter Nemo'
    },

    -- Other Tools
    ['moneybag'] = {
        ['name'] = 'moneybag',
        ['label'] = 'Sac d\'argent',
        ['weight'] = 2500,
        ['type'] = 'item',
        ['image'] = 'moneybag.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Un sac plein de THUNES.'
    },
    ['parachute'] = {
        ['name'] = 'parachute',
        ['label'] = 'Parachute',
        ['weight'] = 3000,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Le ciel est la limite ! Woohoo !'
    },
    ['binoculars'] = {
        ['name'] = 'binoculars',
        ['label'] = 'Jumelles',
        ['weight'] = 2000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Pour surveiller des oiseaux... Ou espionner des voisins.'
    },
    ['snowball'] = {
        ['name'] = 'snowball',
        ['label'] = 'Boule de neige',
        ['weight'] = 0,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Elle est froide'
    },
    ['lighter'] = {
        ['name'] = 'lighter',
        ['label'] = 'Briquet défaillant',
        ['weight'] = 100,
        ['type'] = 'item_illegal',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Ooooh, jolie flamme !'
    },
    ['certificate'] = {
        ['name'] = 'certificate',
        ['label'] = 'Certificat',
        ['weight'] = 100,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Certificat attestant d\'une preuve.'
    },
    ['printerdocument'] = {
        ['name'] = 'printerdocument',
        ['label'] = 'Document',
        ['weight'] = 100,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Un document'
    },
    ['newspaper'] = {
        ['name'] = 'newspaper',
        ['label'] = 'Journal',
        ['weight'] = 300,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Peut être utile pour se culturer'
    },

    --- News items
    ['n_fix_greenscreen'] = {
        ['name'] = 'n_fix_greenscreen',
        ['label'] = 'Kit d\'installation fond vert',
        ['weight'] = 5000,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['n_fix_camera'] = {
        ['name'] = 'n_fix_camera',
        ['label'] = 'Kit d\'installation camera fixe',
        ['weight'] = 8000,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['n_fix_light'] = {
        ['name'] = 'n_fix_light',
        ['label'] = 'Kit d\'installation lumière fixe',
        ['weight'] = 4000,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['n_fix_mic'] = {
        ['name'] = 'n_fix_mic',
        ['label'] = 'Kit d\'installation micro fixe',
        ['weight'] = 3000,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['n_camera'] = {
        ['name'] = 'n_camera',
        ['label'] = 'Caméra épaule',
        ['weight'] = 3000,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['n_mic'] = {
        ['name'] = 'n_mic',
        ['label'] = 'Micro main',
        ['weight'] = 800,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['n_bmic'] = {
        ['name'] = 'n_bmic',
        ['label'] = 'Micro perche',
        ['weight'] = 1500,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = ''
    },

    -- mtp
    ['petroleum'] = {
        ['name'] = 'petroleum',
        ['label'] = 'Pétrole brut',
        ['weight'] = 5000,
        ['type'] = 'oil',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Le pétrole brut est raffiné en toutes sortes de ressources à base de pétrole, telles que le carburant.'
    },
    ['petroleum_refined'] = {
        ['name'] = 'petroleum_refined',
        ['label'] = 'Pétrole conditionné',
        ['weight'] = 1500,
        ['type'] = 'oil',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Pétrole brut, conditionné pour le transport ou pour être utilisé comme carburant.'
    },
    ['petroleum_residue'] = {
        ['name'] = 'petroleum_residue',
        ['label'] = 'Résidus de pétrole lourd conditionnés',
        ['weight'] = 300,
        ['type'] = 'oil_and_item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Du résidus polluants prêt à être livré à BlueBird.'
    },
    ['essence'] = {
        ['name'] = 'essence',
        ['label'] = 'Carburant conditionné',
        ['weight'] = 1000,
        ['type'] = 'oil',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Du carburant conditionné servant à remplir les différentes stations services.'
    },
    ['essence_jerrycan'] = {
        ['name'] = 'essence_jerrycan',
        ['label'] = 'Bidon de carburant conditionné',
        ['weight'] = 1000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Du carburant conditionné servant à remplir les différents véhicules à la main.'
    },
    ['oil_jerrycan'] = {
        ['name'] = 'oil_jerrycan',
        ['label'] = 'Bidon d\'huile',
        ['weight'] = 1000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'De l\'huile servant à remplir les différents véhicules à la main.'
    },
    ['kerosene'] = {
        ['name'] = 'kerosene',
        ['label'] = 'Kérosène conditionné',
        ['weight'] = 1000,
        ['type'] = 'oil',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Du carburant conditionné servant à remplir les différentes stations services.'
    },
    ['kerosene_jerrycan'] = {
        ['name'] = 'kerosene_jerrycan',
        ['label'] = 'Bidon de kérosène conditionné',
        ['weight'] = 1000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'Du carburant conditionné servant à remplir les différents véhicules à la main.'
    },

    -- UPW
    ['energy_cell_hydro'] = {
        ['name'] = 'energy_cell_hydro',
        ['label'] = "Cellule d'énergie hydraulique",
        ['weight'] = 5000,
        ['type'] = 'energy',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['energy_cell_fossil'] = {
        ['name'] = 'energy_cell_fossil',
        ['label'] = "Cellule d'énergie fossile",
        ['weight'] = 5000,
        ['type'] = 'energy',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['energy_cell_wind'] = {
        ['name'] = 'energy_cell_wind',
        ['label'] = "Cellule d'énergie éolienne",
        ['weight'] = 5000,
        ['type'] = 'energy',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['seeweed_acid'] = {
        ['name'] = 'seeweed_acid',
        ['label'] = "Acide d’algue conditionnée",
        ['weight'] = 1000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = ''
    },

    -- zkea
    ['house_map'] = {
        ['name'] = 'house_map',
        ['label'] = 'Carte des habitations',
        ['weight'] = 100,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = false,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Pour retrouver ton chez toi !'
    },

    -- other
    ['welcome_book'] = {
        ['name'] = 'welcome_book',
        ['label'] = 'Dépliant Touristique',
        ['weight'] = 100,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Bienvenue sur SOZ !'
    },

    -- Benny's
    ['diagnostic_pad'] = {
        ['name'] = 'diagnostic_pad',
        ['label'] = 'Tablette diagnostic',
        ['weight'] = 5000,
        ['type'] = 'item',
        ['unique'] = true,
        ['useable'] = true,
        ['shouldClose'] = true,
        ['combinable'] = nil,
        ['description'] = 'Pour faire des diagnostics sur les véhicules.'
    },

    -- PAWL
    ['tree_trunk'] = {
        ['name'] = 'tree_trunk',
        ['label'] = "Tronc d'arbre",
        ['weight'] = 40000,
        ['type'] = 'log',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['wood_plank'] = {
        ['name'] = 'wood_plank',
        ['label'] = "Planche de bois",
        ['weight'] = 1000,
        ['type'] = 'plank',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = '',
        ['resellPrice'] = 2,
        ['resellZone'] = 'Resell:LSPort:Pawl',
    },
    ['sawdust'] = {
        ['name'] = 'sawdust',
        ['label'] = "Sciure de bois",
        ['weight'] = 20,
        ['type'] = 'sawdust',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['paper'] = {
        ['name'] = 'paper',
        ['label'] = "Feuille de papier",
        ['weight'] = 30,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = ''
    },
    ['cabinet_zkea'] = {
        ['name'] = 'cabinet_zkea',
        ['label'] = "Meuble ZKEA",
        ['weight'] = 4000,
        ['type'] = 'item',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = '',
        ['resellPrice'] = {
            [1] = 60,
            [2] = 200,
            [3] = 500,
            [4] = 2600,
        },
        ['resellZone'] = 'Resell:Zkea',
    },

    --- Deprecated
    ['milkbucket'] = {
        ['name'] = 'milkbucket',
        ['label'] = 'Bidon archéologique',
        ['weight'] = 1000,
        ['type'] = 'food',
        ['unique'] = false,
        ['useable'] = false,
        ['shouldClose'] = false,
        ['durability'] = 14,
        ['combinable'] = nil,
        ['description'] = 'Bidon archéologique, autrefois utilisé pour produire du lait'
    },
}
