QBShared       = QBShared or {}

QBShared.Items = {
    -- WEAPONS
    -- Melee
    ['weapon_unarmed']               = { ['name'] = 'weapon_unarmed', ['label'] = 'Fists', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'placeholder.png', ['unique'] = true, ['useable'] = false, ['description'] = 'Fisticuffs' },
    ['weapon_dagger']                = { ['name'] = 'weapon_dagger', ['label'] = 'Dagger', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_dagger.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A short knife with a pointed and edged blade, used as a weapon' },
    ['weapon_bat']                   = { ['name'] = 'weapon_bat', ['label'] = 'Bat', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_bat.png', ['unique'] = true, ['useable'] = false, ['description'] = 'Used for hitting a ball in sports (or other things)' },
    ['weapon_bottle']                = { ['name'] = 'weapon_bottle', ['label'] = 'Broken Bottle', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_bottle.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A broken bottle' },
    ['weapon_crowbar']               = { ['name'] = 'weapon_crowbar', ['label'] = 'Crowbar', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_crowbar.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An iron bar with a flattened end, used as a lever' },
    ['weapon_flashlight']            = { ['name'] = 'weapon_flashlight', ['label'] = 'Flashlight', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_flashlight.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A battery-operated portable light' },
    ['weapon_golfclub']              = { ['name'] = 'weapon_golfclub', ['label'] = 'Golfclub', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_golfclub.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A club used to hit the ball in golf' },
    ['weapon_hammer']                = { ['name'] = 'weapon_hammer', ['label'] = 'Hammer', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_hammer.png', ['unique'] = true, ['useable'] = false, ['description'] = 'Used for jobs such as breaking things (legs) and driving in nails' },
    ['weapon_hatchet']               = { ['name'] = 'weapon_hatchet', ['label'] = 'Hatchet', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_hatchet.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A small axe with a short handle for use in one hand' },
    ['weapon_knuckle']               = { ['name'] = 'weapon_knuckle', ['label'] = 'Knuckle', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_knuckle.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A metal guard worn over the knuckles in fighting, especially to increase the effect of the blows' },
    ['weapon_knife']                 = { ['name'] = 'weapon_knife', ['label'] = 'Knife', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_knife.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An instrument composed of a blade fixed into a handle, used for cutting or as a weapon' },
    ['weapon_machete']               = { ['name'] = 'weapon_machete', ['label'] = 'Machete', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_machete.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A broad, heavy knife used as a weapon' },
    ['weapon_switchblade']           = { ['name'] = 'weapon_switchblade', ['label'] = 'Switchblade', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_switchblade.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A knife with a blade that springs out from the handle when a button is pressed' },
    ['weapon_nightstick']            = { ['name'] = 'weapon_nightstick', ['label'] = 'Nightstick', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_nightstick.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A police officer\'s club or billy' },
    ['weapon_wrench']                = { ['name'] = 'weapon_wrench', ['label'] = 'Wrench', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_wrench.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A tool used for gripping and turning nuts, bolts, pipes, etc' },
    ['weapon_battleaxe']             = { ['name'] = 'weapon_battleaxe', ['label'] = 'Battle Axe', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_battleaxe.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A large broad-bladed axe used in ancient warfare' },
    ['weapon_poolcue']               = { ['name'] = 'weapon_poolcue', ['label'] = 'Poolcue', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_poolcue.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A stick used to strike a ball, usually the cue ball (or other things)' },
    ['weapon_briefcase']             = { ['name'] = 'weapon_briefcase', ['label'] = 'Briefcase', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_briefcase.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A briefcase for storing important documents' },
    ['weapon_briefcase_02']          = { ['name'] = 'weapon_briefcase_02', ['label'] = 'Suitcase', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_briefcase2.png', ['unique'] = true, ['useable'] = false, ['description'] = 'Wonderfull for nice vacation to Liberty City' },
    ['weapon_garbagebag']            = { ['name'] = 'weapon_garbagebag', ['label'] = 'Garbage Bag', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_garbagebag.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A garbage bag' },
    ['weapon_handcuffs']             = { ['name'] = 'weapon_handcuffs', ['label'] = 'Handcuffs', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_handcuffs.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A pair of lockable linked metal rings for securing a prisoner\'s wrists' },
    ['weapon_bread']                 = { ['name'] = 'weapon_bread', ['label'] = 'Baquette', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'baquette.png', ['unique'] = true, ['useable'] = false, ['description'] = 'Bread...?' },
    ['weapon_stone_hatchet']         = { ['name'] = 'weapon_stone_hatchet', ['label'] = 'Stone Hatchet', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_stone_hatchet.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Stone ax' },

    -- Handguns
    ['weapon_pistol']                = { ['name'] = 'weapon_pistol', ['label'] = 'Walther P99', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_pistol.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A small firearm designed to be held in one hand' },
    ['weapon_pistol_mk2']            = { ['name'] = 'weapon_pistol_mk2', ['label'] = 'Pistol Mk II', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_pistol_mk2.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An upgraded small firearm designed to be held in one hand' },
    ['weapon_combatpistol']          = { ['name'] = 'weapon_combatpistol', ['label'] = 'Combat Pistol', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_combatpistol.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A combat version small firearm designed to be held in one hand' },
    ['weapon_appistol']              = { ['name'] = 'weapon_appistol', ['label'] = 'AP Pistol', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_appistol.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A small firearm designed to be held in one hand that is automatic' },
    ['weapon_stungun']               = { ['name'] = 'weapon_stungun', ['label'] = 'Taser', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_stungun.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A weapon firing barbs attached by wires to batteries, causing temporary paralysis' },
    ['weapon_pistol50']              = { ['name'] = 'weapon_pistol50', ['label'] = 'Pistol .50', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_pistol50.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A .50 caliber firearm designed to be held with both hands' },
    ['weapon_snspistol']             = { ['name'] = 'weapon_snspistol', ['label'] = 'SNS Pistol', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_snspistol.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A very small firearm designed to be easily concealed' },
    ['weapon_heavypistol']           = { ['name'] = 'weapon_heavypistol', ['label'] = 'Heavy Pistol', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_heavypistol.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A hefty firearm designed to be held in one hand (or attempted)' },
    ['weapon_vintagepistol']         = { ['name'] = 'weapon_vintagepistol', ['label'] = 'Vintage Pistol', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_vintagepistol.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An antique firearm designed to be held in one hand' },
    ['weapon_flaregun']              = { ['name'] = 'weapon_flaregun', ['label'] = 'Flare Gun', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_FLARE', ['image'] = 'weapon_flaregun.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A handgun for firing signal rockets' },
    ['weapon_marksmanpistol']        = { ['name'] = 'weapon_marksmanpistol', ['label'] = 'Marksman Pistol', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_marksmanpistol.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A very accurate small firearm designed to be held in one hand' },
    ['weapon_revolver']              = { ['name'] = 'weapon_revolver', ['label'] = 'Revolver', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_revolver.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A pistol with revolving chambers enabling several shots to be fired without reloading' },
    ['weapon_revolver_mk2']          = { ['name'] = 'weapon_revolver_mk2', ['label'] = 'Violence', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_revolver_mk2.png', ['unique'] = true, ['useable'] = true, ['description'] = 'da Violence' },
    ['weapon_doubleaction']          = { ['name'] = 'weapon_doubleaction', ['label'] = 'Double Action Revolver', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_doubleaction.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Double Action Revolver' },
    ['weapon_snspistol_mk2']         = { ['name'] = 'weapon_snspistol_mk2', ['label'] = 'SNS Pistol Mk II', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_snspistol_mk2.png', ['unique'] = true, ['useable'] = true, ['description'] = 'SNS Pistol MK2' },
    ['weapon_raypistol']             = { ['name'] = 'weapon_raypistol', ['label'] = 'Up-n-Atomizer', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_raypistol.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Raypistol' },
    ['weapon_ceramicpistol']         = { ['name'] = 'weapon_ceramicpistol', ['label'] = 'Ceramic Pistol', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_ceramicpistol.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Ceramicpistol' },
    ['weapon_navyrevolver']          = { ['name'] = 'weapon_navyrevolver', ['label'] = 'Navy Revolver', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_navyrevolver.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Navyrevolver' },
    ['weapon_gadgetpistol']          = { ['name'] = 'weapon_gadgetpistol', ['label'] = 'Perico Pistol', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_gadgetpistol.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Gadgetpistol' },

    -- Submachine Guns
    ['weapon_microsmg']              = { ['name'] = 'weapon_microsmg', ['label'] = 'Micro SMG', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SMG', ['image'] = 'weapon_microsmg.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A handheld lightweight machine gun' },
    ['weapon_smg']                   = { ['name'] = 'weapon_smg', ['label'] = 'SMG', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SMG', ['image'] = 'weapon_smg.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A handheld lightweight machine gun' },
    ['weapon_smg_mk2']               = { ['name'] = 'weapon_smg_mk2', ['label'] = 'SMG Mk II', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SMG', ['image'] = 'weapon_smg_mk2.png', ['unique'] = true, ['useable'] = true, ['description'] = 'SMG MK2' },
    ['weapon_assaultsmg']            = { ['name'] = 'weapon_assaultsmg', ['label'] = 'Assault SMG', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SMG', ['image'] = 'weapon_assaultsmg.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An assault version of a handheld lightweight machine gun' },
    ['weapon_combatpdw']             = { ['name'] = 'weapon_combatpdw', ['label'] = 'Combat PDW', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SMG', ['image'] = 'weapon_combatpdw.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A combat version of a handheld lightweight machine gun' },
    ['weapon_machinepistol']         = { ['name'] = 'weapon_machinepistol', ['label'] = 'Tec-9', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PISTOL', ['image'] = 'weapon_machinepistol.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A self-loading pistol capable of burst or fully automatic fire' },
    ['weapon_minismg']               = { ['name'] = 'weapon_minismg', ['label'] = 'Mini SMG', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SMG', ['image'] = 'weapon_minismg.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A mini handheld lightweight machine gun' },
    ['weapon_raycarbine']            = { ['name'] = 'weapon_raycarbine', ['label'] = 'Unholy Hellbringer', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SMG', ['image'] = 'weapon_raycarbine.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Raycarbine' },

    -- Shotguns
    ['weapon_pumpshotgun']           = { ['name'] = 'weapon_pumpshotgun', ['label'] = 'Pump Shotgun', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN', ['image'] = 'weapon_pumpshotgun.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A pump-action smoothbore gun for firing small shot at short range' },
    ['weapon_sawnoffshotgun']        = { ['name'] = 'weapon_sawnoffshotgun', ['label'] = 'Sawn-off Shotgun', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN', ['image'] = 'weapon_sawnoffshotgun.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A sawn-off smoothbore gun for firing small shot at short range' },
    ['weapon_assaultshotgun']        = { ['name'] = 'weapon_assaultshotgun', ['label'] = 'Assault Shotgun', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN', ['image'] = 'weapon_assaultshotgun.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An assault version of asmoothbore gun for firing small shot at short range' },
    ['weapon_bullpupshotgun']        = { ['name'] = 'weapon_bullpupshotgun', ['label'] = 'Bullpup Shotgun', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN', ['image'] = 'weapon_bullpupshotgun.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A compact smoothbore gun for firing small shot at short range' },
    ['weapon_musket']                = { ['name'] = 'weapon_musket', ['label'] = 'Musket', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN', ['image'] = 'weapon_musket.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An infantryman\'s light gun with a long barrel, typically smooth-bored, muzzleloading, and fired from the shoulder' },
    ['weapon_heavyshotgun']          = { ['name'] = 'weapon_heavyshotgun', ['label'] = 'Heavy Shotgun', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN', ['image'] = 'weapon_heavyshotgun.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A large smoothbore gun for firing small shot at short range' },
    ['weapon_dbshotgun']             = { ['name'] = 'weapon_dbshotgun', ['label'] = 'Double-barrel Shotgun', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN', ['image'] = 'weapon_dbshotgun.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A shotgun with two parallel barrels, allowing two single shots to be fired in quick succession' },
    ['weapon_autoshotgun']           = { ['name'] = 'weapon_autoshotgun', ['label'] = 'Auto Shotgun', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN', ['image'] = 'weapon_autoshotgun.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A shotgun capable of rapid continous fire' },
    ['weapon_pumpshotgun_mk2']       = { ['name'] = 'weapon_pumpshotgun_mk2', ['label'] = 'Pumpshotgun Mk II', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN', ['image'] = 'weapon_pumpshotgun_mk2.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Pumpshotgun MK2' },
    ['weapon_combatshotgun']         = { ['name'] = 'weapon_combatshotgun', ['label'] = 'Combat Shotgun', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SHOTGUN', ['image'] = 'weapon_combatshotgun.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Combatshotgun' },

    -- Assault Rifles
    ['weapon_assaultrifle']          = { ['name'] = 'weapon_assaultrifle', ['label'] = 'Assault Rifle', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_assaultrifle.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A rapid-fire, magazine-fed automatic rifle designed for infantry use' },
    ['weapon_assaultrifle_mk2']      = { ['name'] = 'weapon_assaultrifle_mk2', ['label'] = 'Assault Rifle Mk II', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_assaultrifle_mk2.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Assault Rifle MK2' },
    ['weapon_carbinerifle']          = { ['name'] = 'weapon_carbinerifle', ['label'] = 'Carbine Rifle', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_carbinerifle.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A lightweight automatic rifle' },
    ['weapon_carbinerifle_mk2']      = { ['name'] = 'weapon_carbinerifle_mk2', ['label'] = 'Carbine Rifle Mk II', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_carbinerifle_mk2.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Carbine Rifle MK2' },
    ['weapon_advancedrifle']         = { ['name'] = 'weapon_advancedrifle', ['label'] = 'Advanced Rifle', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_advancedrifle.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An assault version of a rapid-fire, magazine-fed automatic rifle designed for infantry use' },
    ['weapon_specialcarbine']        = { ['name'] = 'weapon_specialcarbine', ['label'] = 'Special Carbine', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_specialcarbine.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An extremely versatile assault rifle for any combat situation' },
    ['weapon_bullpuprifle']          = { ['name'] = 'weapon_bullpuprifle', ['label'] = 'Bullpup Rifle', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_bullpuprifle.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A compact automatic assault rifle' },
    ['weapon_compactrifle']          = { ['name'] = 'weapon_compactrifle', ['label'] = 'Compact Rifle', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_compactrifle.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A compact version of an assault rifle' },
    ['weapon_specialcarbine_mk2']    = { ['name'] = 'weapon_specialcarbine_mk2', ['label'] = 'Special Carbine Mk II', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_specialcarbine_mk2.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Wpecialcarbine MK2' },
    ['weapon_bullpuprifle_mk2']      = { ['name'] = 'weapon_bullpuprifle_mk2', ['label'] = 'Bullpup Rifle Mk II', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_bullpuprifle_mk2.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Bull Puprifle MK2' },
    ['weapon_militaryrifle']         = { ['name'] = 'weapon_militaryrifle', ['label'] = 'Military Rifle', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RIFLE', ['image'] = 'weapon_militaryrifle.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Militaryrifle' },

    -- Light Machine Guns
    ['weapon_mg']                    = { ['name'] = 'weapon_mg', ['label'] = 'Machinegun', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_MG', ['image'] = 'weapon_mg.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An automatic gun that fires bullets in rapid succession for as long as the trigger is pressed' },
    ['weapon_combatmg']              = { ['name'] = 'weapon_combatmg', ['label'] = 'Combat MG', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_MG', ['image'] = 'weapon_combatmg.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A combat version of an automatic gun that fires bullets in rapid succession for as long as the trigger is pressed' },
    ['weapon_gusenberg']             = { ['name'] = 'weapon_gusenberg', ['label'] = 'Thompson SMG', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_MG', ['image'] = 'weapon_gusenberg.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An automatic rifle commonly referred to as a tommy gun' },
    ['weapon_combatmg_mk2']          = { ['name'] = 'weapon_combatmg_mk2', ['label'] = 'Combat MG Mk II', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_MG', ['image'] = 'weapon_combatmg_mk2.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Combatmg MK2' },

    -- Sniper Rifles
    ['weapon_sniperrifle']           = { ['name'] = 'weapon_sniperrifle', ['label'] = 'Sniper Rifle', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SNIPER', ['image'] = 'weapon_sniperrifle.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A high-precision, long-range rifle' },
    ['weapon_heavysniper']           = { ['name'] = 'weapon_heavysniper', ['label'] = 'Heavy Sniper', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SNIPER', ['image'] = 'weapon_heavysniper.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An upgraded high-precision, long-range rifle' },
    ['weapon_marksmanrifle']         = { ['name'] = 'weapon_marksmanrifle', ['label'] = 'Marksman Rifle', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SNIPER', ['image'] = 'weapon_marksmanrifle.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A very accurate single-fire rifle' },
    ['weapon_remotesniper']          = { ['name'] = 'weapon_remotesniper', ['label'] = 'Remote Sniper', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SNIPER_REMOTE', ['image'] = 'weapon_remotesniper.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A portable high-precision, long-range rifle' },
    ['weapon_heavysniper_mk2']       = { ['name'] = 'weapon_heavysniper_mk2', ['label'] = 'Heavy Sniper Mk II', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SNIPER', ['image'] = 'weapon_heavysniper_mk2.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Heavysniper MK2' },
    ['weapon_marksmanrifle_mk2']     = { ['name'] = 'weapon_marksmanrifle_mk2', ['label'] = 'Marksman Rifle Mk II', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_SNIPER', ['image'] = 'weapon_marksmanrifle_mk2.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Marksmanrifle MK2' },

    -- Heavy Weapons
    ['weapon_rpg']                   = { ['name'] = 'weapon_rpg', ['label'] = 'RPG', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_RPG', ['image'] = 'weapon_rpg.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A rocket-propelled grenade launcher' },
    ['weapon_grenadelauncher']       = { ['name'] = 'weapon_grenadelauncher', ['label'] = 'Grenade Launcher', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_GRENADELAUNCHER', ['image'] = 'weapon_grenadelauncher.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A weapon that fires a specially-designed large-caliber projectile, often with an explosive, smoke or gas warhead' },
    ['weapon_grenadelauncher_smoke'] = { ['name'] = 'weapon_grenadelauncher_smoke', ['label'] = 'Smoke Grenade Launcher', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_GRENADELAUNCHER', ['image'] = 'weapon_smokegrenade.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A bomb that produces a lot of smoke when it explodes' },
    ['weapon_minigun']               = { ['name'] = 'weapon_minigun', ['label'] = 'Minigun', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_MINIGUN', ['image'] = 'weapon_minigun.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A portable machine gun consisting of a rotating cluster of six barrels and capable of variable rates of fire of up to 6,000 rounds per minute' },
    ['weapon_firework']              = { ['name'] = 'weapon_firework', ['label'] = 'Firework Launcher', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_firework.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A device containing gunpowder and other combustible chemicals that causes a spectacular explosion when ignited' },
    ['weapon_railgun']               = { ['name'] = 'weapon_railgun', ['label'] = 'Railgun', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_railgun.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A weapon that uses electromagnetic force to launch high velocity projectiles' },
    ['weapon_hominglauncher']        = { ['name'] = 'weapon_hominglauncher', ['label'] = 'Homing Launcher', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_STINGER', ['image'] = 'weapon_hominglauncher.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A weapon fitted with an electronic device that enables it to find and hit a target' },
    ['weapon_compactlauncher']       = { ['name'] = 'weapon_compactlauncher', ['label'] = 'Compact Launcher', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_compactlauncher.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A compact grenade launcher' },
    ['weapon_rayminigun']            = { ['name'] = 'weapon_rayminigun', ['label'] = 'Widowmaker', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_MINIGUN', ['image'] = 'weapon_rayminigun.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Rayminigun' },

    -- Throwables
    ['weapon_grenade']               = { ['name'] = 'weapon_grenade', ['label'] = 'Grenade', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_grenade.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A handheld throwable bomb' },
    ['weapon_bzgas']                 = { ['name'] = 'weapon_bzgas', ['label'] = 'BZ Gas', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_bzgas.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A cannister of gas that causes extreme pain' },
    ['weapon_molotov']               = { ['name'] = 'weapon_molotov', ['label'] = 'Molotov', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_molotov.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A crude bomb made of a bottle filled with a flammable liquid and fitted with a wick for lighting' },
    ['weapon_stickybomb']            = { ['name'] = 'weapon_stickybomb', ['label'] = 'C4', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_stickybomb.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An explosive charge covered with an adhesive that when thrown against an object sticks until it explodes' },
    ['weapon_proxmine']              = { ['name'] = 'weapon_proxmine', ['label'] = 'Proxmine Grenade', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_proximitymine.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A bomb placed on the ground that detonates when going within its proximity' },
    ['weapon_snowball']              = { ['name'] = 'weapon_snowball', ['label'] = 'Snowball', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_snowball.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A ball of packed snow, especially one made for throwing at other people for fun' },
    ['weapon_pipebomb']              = { ['name'] = 'weapon_pipebomb', ['label'] = 'Pipe Bomb', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_pipebomb.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A homemade bomb, the components of which are contained in a pipe' },
    ['weapon_ball']                  = { ['name'] = 'weapon_ball', ['label'] = 'Ball', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_BALL', ['image'] = 'weapon_ball.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A solid or hollow spherical or egg-shaped object that is kicked, thrown, or hit in a game' },
    ['weapon_smokegrenade']          = { ['name'] = 'weapon_smokegrenade', ['label'] = 'Smoke Grenade', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_c4.png', ['unique'] = true, ['useable'] = false, ['description'] = 'An explosive charge that can be remotely detonated' },
    ['weapon_flare']                 = { ['name'] = 'weapon_flare', ['label'] = 'Flare pistol', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_FLARE', ['image'] = 'weapon_flare.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A small pyrotechnic devices used for illumination and signalling' },

    -- Miscellaneous
    ['weapon_petrolcan']             = { ['name'] = 'weapon_petrolcan', ['label'] = 'Petrol Can', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PETROLCAN', ['image'] = 'weapon_petrolcan.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A robust liquid container made from pressed steel' },
    ['weapon_fireextinguisher']      = { ['name'] = 'weapon_fireextinguisher', ['label'] = 'Fire Extinguisher', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = nil, ['image'] = 'weapon_fireextinguisher.png', ['unique'] = true, ['useable'] = false, ['description'] = 'A portable device that discharges a jet of water, foam, gas, or other material to extinguish a fire' },
    ['weapon_hazardcan']             = { ['name'] = 'weapon_hazardcan', ['label'] = 'Hazardous Jerry Can', ['weight'] = 1000, ['type'] = 'weapon', ['ammotype'] = 'AMMO_PETROLCAN', ['image'] = 'weapon_hazardcan.png', ['unique'] = true, ['useable'] = true, ['description'] = 'Weapon Hazardcan' },

    -- ITEMS

    -- Ammo ITEMS
    ['pistol_ammo']                  = { ['name'] = 'pistol_ammo', ['label'] = 'Pistol ammo', ['weight'] = 200, ['type'] = 'weapon_ammo', ['image'] = 'pistol_ammo.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Ammo for Pistols' },
    ['rifle_ammo']                   = { ['name'] = 'rifle_ammo', ['label'] = 'Rifle ammo', ['weight'] = 1000, ['type'] = 'weapon_ammo', ['image'] = 'rifle_ammo.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Ammo for Rifles' },
    ['smg_ammo']                     = { ['name'] = 'smg_ammo', ['label'] = 'SMG ammo', ['weight'] = 500, ['type'] = 'weapon_ammo', ['image'] = 'smg_ammo.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Ammo for Sub Machine Guns' },
    ['shotgun_ammo']                 = { ['name'] = 'shotgun_ammo', ['label'] = 'Shotgun ammo', ['weight'] = 500, ['type'] = 'weapon_ammo', ['image'] = 'shotgun_ammo.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Ammo for Shotguns' },
    ['mg_ammo']                      = { ['name'] = 'mg_ammo', ['label'] = 'MG ammo', ['weight'] = 1000, ['type'] = 'weapon_ammo', ['image'] = 'mg_ammo.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Ammo for Machine Guns' },
    ['snp_ammo']                     = { ['name'] = 'snp_ammo', ['label'] = 'Sniper ammo', ['weight'] = 1000, ['type'] = 'weapon_ammo', ['image'] = 'rifle_ammo.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Ammo for Sniper Rifles' },

    -- Card ITEMS
    ['lawyerpass']                   = { ['name'] = 'lawyerpass', ['label'] = 'Lawyer Pass', ['weight'] = 0, ['type'] = 'item', ['image'] = 'lawyerpass.png', ['unique'] = true, ['useable'] = true, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Pass exclusive to lawyers to show they can represent a suspect' },

    -- Eat ITEMS
    ['tosti']                        = { ['name'] = 'tosti', ['label'] = 'Grilled Cheese Sandwich', ['weight'] = 200, ['type'] = 'food', ['image'] = 'tosti.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Nice to eat' },
    ['twerks_candy']                 = { ['name'] = 'twerks_candy', ['label'] = 'Twerks', ['weight'] = 100, ['type'] = 'food', ['image'] = 'twerks_candy.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Some delicious candy :O' },
    ['snikkel_candy']                = { ['name'] = 'snikkel_candy', ['label'] = 'Snikkel', ['weight'] = 100, ['type'] = 'food', ['image'] = 'snikkel_candy.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Some delicious candy :O' },
    ['sandwich']                     = { ['name'] = 'sandwich', ['label'] = 'Sandwich', ['weight'] = 200, ['type'] = 'food', ['image'] = 'sandwich.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Nice bread for your stomach' },

    -- Drink ITEMS
    ['water_bottle']                 = { ['name'] = 'water_bottle', ['label'] = 'Bottle of Water', ['weight'] = 500, ['type'] = 'drink', ['image'] = 'water_bottle.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'For all the thirsty out there' },
    ['coffee']                       = { ['name'] = 'coffee', ['label'] = 'Coffee', ['weight'] = 200, ['type'] = 'drink', ['image'] = 'coffee.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Pump 4 Caffeine' },
    ['kurkakola']                    = { ['name'] = 'kurkakola', ['label'] = 'Cola', ['weight'] = 500, ['type'] = 'drink', ['image'] = 'cola.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'For all the thirsty out there' },

    -- Alcohol
    ['beer']                         = { ['name'] = 'beer', ['label'] = 'Beer', ['weight'] = 500, ['type'] = 'drink', ['image'] = 'beer.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Nothing like a good cold beer!' },
    ['whiskey']                      = { ['name'] = 'whiskey', ['label'] = 'Whiskey', ['weight'] = 500, ['type'] = 'drink', ['image'] = 'whiskey.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'For all the thirsty out there' },
    ['vodka']                        = { ['name'] = 'vodka', ['label'] = 'Vodka', ['weight'] = 500, ['type'] = 'drink', ['image'] = 'vodka.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'For all the thirsty out there' },
    ['grape']                        = { ['name'] = 'grape', ['label'] = 'Grape', ['weight'] = 100, ['type'] = 'drink', ['image'] = 'grape.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Mmmmh yummie, grapes' },
    ['wine']                         = { ['name'] = 'wine', ['label'] = 'Wine', ['weight'] = 300, ['type'] = 'drink', ['image'] = 'wine.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Some good wine to drink on a fine evening' },
    ['grapejuice']                   = { ['name'] = 'grapejuice', ['label'] = 'Grape Juice', ['weight'] = 200, ['type'] = 'drink', ['image'] = 'grapejuice.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Grape juice is said to be healthy' },

    -- Drugs
    ['joint']                        = { ['name'] = 'joint', ['label'] = 'Joint', ['weight'] = 0, ['type'] = 'drug', ['image'] = 'joint.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Sidney would be very proud at you' },
    ['cokebaggy']                    = { ['name'] = 'cokebaggy', ['label'] = 'Bag of Coke', ['weight'] = 0, ['type'] = 'drug', ['image'] = 'cocaine_baggy.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'To get happy real quick' },
    ['crack_baggy']                  = { ['name'] = 'crack_baggy', ['label'] = 'Bag of Crack', ['weight'] = 0, ['type'] = 'drug', ['image'] = 'crack_baggy.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'To get happy faster' },
    ['xtcbaggy']                     = { ['name'] = 'xtcbaggy', ['label'] = 'Bag of XTC', ['weight'] = 0, ['type'] = 'drug', ['image'] = 'xtc_baggy.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Pop those pills baby' },
    ['coke_small_brick']             = { ['name'] = 'coke_small_brick', ['label'] = 'Coke Package', ['weight'] = 350, ['type'] = 'drug', ['image'] = 'coke_small_brick.png', ['unique'] = true, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Small package of cocaine, mostly used for deals and takes a lot of space' },
    ['meth']                         = { ['name'] = 'meth', ['label'] = 'Meth', ['weight'] = 100, ['type'] = 'drug', ['image'] = 'meth_baggy.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'A baggie of Meth' },
    ['rolling_paper']                = { ['name'] = 'rolling_paper', ['label'] = 'Rolling Paper', ['weight'] = 0, ['type'] = 'drug', ['image'] = 'rolling_paper.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = { accept = { 'weed_white-widow', 'weed_skunk', 'weed_purple-haze', 'weed_og-kush', 'weed_amnesia', 'weed_ak47' }, reward = 'joint', anim = { ['dict'] = 'anim@amb@business@weed@weed_inspecting_high_dry@', ['lib'] = 'weed_inspecting_high_base_inspector', ['text'] = 'Rolling joint', ['timeOut'] = 5000, } }, ['description'] = 'Paper made specifically for encasing and smoking tobacco or cannabis.' },

    -- Seed And Weed
    ['empty_weed_bag']               = { ['name'] = 'empty_weed_bag', ['label'] = 'Empty Weed Bag', ['weight'] = 0, ['type'] = 'drug', ['image'] = 'weed_baggy_empty.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'A small empty bag' },

    -- Material
    ['plastic']                      = { ['name'] = 'plastic', ['label'] = 'Plastic', ['weight'] = 100, ['type'] = 'item', ['image'] = 'plastic.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'RECYCLE! - Greta Thunberg 2019' },
    ['metalscrap']                   = { ['name'] = 'metalscrap', ['label'] = 'Metal Scrap', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'metalscrap.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'You can probably make something nice out of this' },
    ['copper']                       = { ['name'] = 'copper', ['label'] = 'Copper', ['weight'] = 100, ['type'] = 'item', ['image'] = 'copper.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Nice piece of metal that you can probably use for something' },
    ['aluminum']                     = { ['name'] = 'aluminum', ['label'] = 'Aluminium', ['weight'] = 100, ['type'] = 'item', ['image'] = 'aluminum.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Nice piece of metal that you can probably use for something' },
    ['aluminumoxide']                = { ['name'] = 'aluminumoxide', ['label'] = 'Aluminium Powder', ['weight'] = 100, ['type'] = 'item', ['image'] = 'aluminumoxide.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Some powder to mix with' },
    ['iron']                         = { ['name'] = 'iron', ['label'] = 'Iron', ['weight'] = 100, ['type'] = 'item', ['image'] = 'iron.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Handy piece of metal that you can probably use for something' },
    ['ironoxide']                    = { ['name'] = 'ironoxide', ['label'] = 'Iron Powder', ['weight'] = 100, ['type'] = 'item', ['image'] = 'ironoxide.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = { accept = { 'aluminumoxide' }, reward = 'thermite', anim = { ['dict'] = 'anim@amb@business@weed@weed_inspecting_high_dry@', ['lib'] = 'weed_inspecting_high_base_inspector', ['text'] = 'Mixing powder..', ['timeOut'] = 10000 } }, ['description'] = 'Some powder to mix with.' },
    ['steel']                        = { ['name'] = 'steel', ['label'] = 'Steel', ['weight'] = 100, ['type'] = 'item', ['image'] = 'steel.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Nice piece of metal that you can probably use for something' },
    ['rubber']                       = { ['name'] = 'rubber', ['label'] = 'Rubber', ['weight'] = 100, ['type'] = 'item', ['image'] = 'rubber.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Rubber, I believe you can make your own rubber ducky with it :D' },
    ['glass']                        = { ['name'] = 'glass', ['label'] = 'Glass', ['weight'] = 100, ['type'] = 'item', ['image'] = 'glass.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'It is very fragile, watch out' },

    -- Tools
    ['lockpick']                     = { ['name'] = 'lockpick', ['label'] = 'Lockpick', ['weight'] = 300, ['type'] = 'item', ['image'] = 'lockpick.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = { accept = { 'screwdriverset' }, reward = 'advancedlockpick', anim = { ['dict'] = 'anim@amb@business@weed@weed_inspecting_high_dry@', ['lib'] = 'weed_inspecting_high_base_inspector', ['text'] = 'Crafting lockpick', ['timeOut'] = 7500, } }, ['description'] = 'Very useful if you lose your keys a lot.. or if you want to use it for something else...' },
    ['electronickit']                = { ['name'] = 'electronickit', ['label'] = 'Electronic Kit', ['weight'] = 100, ['type'] = 'item', ['image'] = 'electronickit.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = { accept = { 'gatecrack' }, reward = 'trojan_usb', anim = nil }, ['description'] = 'If you\'ve always wanted to build a robot you can maybe start here. Maybe you\'ll be the new Elon Musk?' },
    ['trojan_usb']                   = { ['name'] = 'trojan_usb', ['label'] = 'Trojan USB', ['weight'] = 0, ['type'] = 'item', ['image'] = 'usb_device.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Handy software to shut down some systems' },
    ['screwdriverset']               = { ['name'] = 'screwdriverset', ['label'] = 'Toolkit', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'screwdriverset.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Very useful to screw... screws...' },

    -- Vehicle Tools
    ['repairkit']                    = { ['name'] = 'repairkit', ['label'] = 'Repairkit', ['weight'] = 2500, ['type'] = 'item', ['image'] = 'repairkit.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'A nice toolbox with stuff to repair your vehicle' },
    ['advancedrepairkit']            = { ['name'] = 'advancedrepairkit', ['label'] = 'Advanced Repairkit', ['weight'] = 4000, ['type'] = 'item', ['image'] = 'advancedkit.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'A nice toolbox with stuff to repair your vehicle' },
    ['cleaningkit']                  = { ['name'] = 'cleaningkit', ['label'] = 'Cleaning Kit', ['weight'] = 250, ['type'] = 'item', ['image'] = 'cleaningkit.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'A microfiber cloth with some soap will let your car sparkle again!' },
    ['jerry_can']                    = { ['name'] = 'jerry_can', ['label'] = 'Jerrycan 20L', ['weight'] = 20000, ['type'] = 'item', ['image'] = 'jerry_can.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'A can full of Fuel' },

    -- Medication
    ['firstaid']                     = { ['name'] = 'firstaid', ['label'] = 'First Aid', ['weight'] = 2500, ['type'] = 'item', ['image'] = 'firstaid.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'You can use this First Aid kit to get people back on their feet' },
    ['bandage']                      = { ['name'] = 'bandage', ['label'] = 'Bandage', ['weight'] = 0, ['type'] = 'item', ['image'] = 'bandage.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'A bandage works every time' },
    ['ifaks']                        = { ['name'] = 'ifaks', ['label'] = 'ifaks', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ifaks.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'ifaks for healing and a complete stress remover.' },
    ['painkillers']                  = { ['name'] = 'painkillers', ['label'] = 'Painkillers', ['weight'] = 0, ['type'] = 'item', ['image'] = 'painkillers.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'For pain you can\'t stand anymore, take this pill that\'d make you feel great again' },
    ['walkstick']                    = { ['name'] = 'walkstick', ['label'] = 'Walking Stick', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'walkstick.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Walking stick for ya\'ll grannies out there.. HAHA' },

    -- Communication
    ['phone']                        = { ['name'] = 'phone', ['label'] = 'ZPhone', ['weight'] = 700, ['type'] = 'item', ['image'] = 'zphone.png', ['unique'] = true, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Outil qui zert à communiquer' },
    ['radio']                        = { ['name'] = 'radio', ['label'] = 'Radio', ['weight'] = 2000, ['type'] = 'item', ['image'] = 'radio.png', ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'You can communicate with this through a signal' },
    ['laptop']                       = { ['name'] = 'laptop', ['label'] = 'Laptop', ['weight'] = 4000, ['type'] = 'item', ['image'] = 'laptop.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Expensive laptop' },
    ['tablet']                       = { ['name'] = 'tablet', ['label'] = 'Tablet', ['weight'] = 2000, ['type'] = 'item', ['image'] = 'tablet.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Expensive tablet' },
    ['gps']                          = { ['name'] = 'gps', ['label'] = 'GPS', ['weight'] = 500, ['type'] = 'item', ['image'] = 'gps.png', ['unique'] = true, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Trouve ton chemin facilement !' },
    ['compass']                      = { ['name'] = 'compass', ['label'] = 'Boussole', ['weight'] = 500, ['type'] = 'item', ['image'] = 'compass.png', ['unique'] = true, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Pour ne jamais perdre le nord !' },

    -- Theft and Jewelry
    ['rolex']                        = { ['name'] = 'rolex', ['label'] = 'Golden Watch', ['weight'] = 1500, ['type'] = 'item', ['image'] = 'rolex.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'A golden watch seems like the jackpot to me!' },
    ['diamond_ring']                 = { ['name'] = 'diamond_ring', ['label'] = 'Diamond Ring', ['weight'] = 1500, ['type'] = 'item', ['image'] = 'diamond_ring.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'A diamond ring seems like the jackpot to me!' },
    ['goldchain']                    = { ['name'] = 'goldchain', ['label'] = 'Golden Chain', ['weight'] = 1500, ['type'] = 'item', ['image'] = 'goldchain.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'A golden chain seems like the jackpot to me!' },
    ['10kgoldchain']                 = { ['name'] = '10kgoldchain', ['label'] = '10k Gold Chain', ['weight'] = 2000, ['type'] = 'item', ['image'] = '10kgoldchain.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = '10 carat golden chain' },
    ['goldbar']                      = { ['name'] = 'goldbar', ['label'] = 'Gold Bar', ['weight'] = 7000, ['type'] = 'item', ['image'] = 'goldbar.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Looks pretty expensive to me' },

    -- Cops Tools
    ['armor']                        = { ['name'] = 'armor', ['label'] = 'Armor', ['weight'] = 5000, ['type'] = 'item', ['image'] = 'armor.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Some protection won\'t hurt... right?' },
    ['handcuffs']                    = { ['name'] = 'handcuffs', ['label'] = 'Menottes', ['weight'] = 100, ['type'] = 'item', ['image'] = 'handcuffs.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Comes in handy when people misbehave. Maybe it can be used for something else?' },
    ['handcuffs_key']                = { ['name'] = 'handcuffs_key', ['label'] = 'Clé de menottes', ['weight'] = 100, ['type'] = 'item', ['image'] = 'handcuffs.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Comes in handy when people misbehave. Maybe it can be used for something else?' },
    ['spike']                        = { ['name'] = 'spike', ['label'] = 'Herse', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'spike.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = '' },
    ['cone']                         = { ['name'] = 'cone', ['label'] = 'Cone de circulation', ['weight'] = 500, ['type'] = 'item', ['image'] = 'cone.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = '' },
    ['police_barrier']               = { ['name'] = 'police_barrier', ['label'] = 'Barrière de circulation', ['weight'] = 750, ['type'] = 'item', ['image'] = 'police_barrier.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = '' },

    -- Firework Tools
    ['firework1']                    = { ['name'] = 'firework1', ['label'] = '2Brothers', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'firework1.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Fireworks' },
    ['firework2']                    = { ['name'] = 'firework2', ['label'] = 'Poppelers', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'firework2.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Fireworks' },
    ['firework3']                    = { ['name'] = 'firework3', ['label'] = 'WipeOut', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'firework3.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Fireworks' },
    ['firework4']                    = { ['name'] = 'firework4', ['label'] = 'Weeping Willow', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'firework4.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Fireworks' },

    -- Sea Tools
    ['diving_gear']                  = { ['name'] = 'diving_gear', ['label'] = 'Diving Gear', ['weight'] = 30000, ['type'] = 'item', ['image'] = 'diving_gear.png', ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'An oxygen tank and a rebreather' },

    -- Other Tools
    ['moneybag']                     = { ['name'] = 'moneybag', ['label'] = 'Money Bag', ['weight'] = 0, ['type'] = 'item', ['image'] = 'moneybag.png', ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'A bag with money' },
    ['parachute']                    = { ['name'] = 'parachute', ['label'] = 'Parachute', ['weight'] = 30000, ['type'] = 'item', ['image'] = 'parachute.png', ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'The sky is the limit! Woohoo!' },
    ['binoculars']                   = { ['name'] = 'binoculars', ['label'] = 'Binoculars', ['weight'] = 600, ['type'] = 'item', ['image'] = 'binoculars.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Sneaky Breaky...' },
    ['snowball']                     = { ['name'] = 'snowball', ['label'] = 'Snowball', ['weight'] = 0, ['type'] = 'item', ['image'] = 'snowball.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Should have catched it :D' },
    ['lighter']                      = { ['name'] = 'lighter', ['label'] = 'Lighter', ['weight'] = 0, ['type'] = 'item', ['image'] = 'lighter.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'On new years eve a nice fire to stand next to' },
    ['certificate']                  = { ['name'] = 'certificate', ['label'] = 'Certificate', ['weight'] = 0, ['type'] = 'item', ['image'] = 'certificate.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Certificate that proves you own certain stuff' },
    ['printerdocument']              = { ['name'] = 'printerdocument', ['label'] = 'Document', ['weight'] = 500, ['type'] = 'item', ['image'] = 'printerdocument.png', ['unique'] = true, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'A nice document' },
}
