QBShared = QBShared or {}

QBShared.Vehicles = {
    --- Sports Classic
    ['ardent']       = {
        ['name']     = 'Ardent',
        ['brand']    = 'Ocelot',
        ['model']    = 'ardent',
        ['price']    = 30000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('ardent'),
        ['shop']     = 'pdm',
    },
    ['btype']        = {              --meme car that goes pretty fast
        ['name']     = 'Roosevelt',
        ['brand']    = 'Albany',
        ['model']    = 'btype',
        ['price']    = 75000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('btype'),
        ['shop']     = 'pdm',
    },
    ['btype2']       = {
        ['name']     = 'Franken Stange',
        ['brand']    = 'Albany',
        ['model']    = 'btype2',
        ['price']    = 87000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('btype2'),
        ['shop']     = 'pdm',
    },
    ['btype3']       = {
        ['name']     = 'Roosevelt Valor',
        ['brand']    = 'Albany',
        ['model']    = 'btype3',
        ['price']    = 63000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('btype3'),
        ['shop']     = 'pdm',
    },
    ['casco']        = {
        ['name']     = 'Casco',
        ['brand']    = 'Lampadati',
        ['model']    = 'casco',
        ['price']    = 100000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('casco'),
        ['shop']     = 'pdm',
    },
    ['cheetah2']     = {
        ['name']     = 'Cheetah Classic',
        ['brand']    = 'Grotti',
        ['model']    = 'cheetah2',
        ['price']    = 195000,
        ['category'] = 'Sports',
        ['hash']     = GetHashKey('cheetah2'),
        ['shop']     = 'luxury',
    },
    ['deluxo']       = {
        ['name']     = 'Deluxo',
        ['brand']    = 'Imponte',
        ['model']    = 'deluxo',
        ['price']    = 55000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('deluxo'),
        ['shop']     = 'pdm',
    },
    ['dynasty']      = {
        ['name']     = 'Dynasty',
        ['brand']    = 'Weeny',
        ['model']    = 'dynasty',
        ['price']    = 25000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('dynasty'),
        ['shop']     = 'pdm',
    },
    ['fagaloa']      = {
        ['name']     = 'Fagaloa',
        ['brand']    = 'Vulcar',
        ['model']    = 'fagaloa',
        ['price']    = 13000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('fagaloa'),
        ['shop']     = 'pdm',
    },
    ['feltzer3']     = {
        ['name']     = 'Stirling GT',
        ['brand']    = 'Benefactor',
        ['model']    = 'feltzer3',
        ['price']    = 115000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('feltzer3'),
        ['shop']     = 'pdm',
    },
    ['gt500']        = {
        ['name']     = 'GT500',
        ['brand']    = 'Grotti',
        ['model']    = 'gt500',
        ['price']    = 130000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('gt500'),
        ['shop']     = 'pdm',
    },
    ['infernus2']    = {
        ['name']     = 'Infernus Classic',
        ['brand']    = 'Pegassi',
        ['model']    = 'infernus2',
        ['price']    = 245000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('infernus2'),
        ['shop']     = 'pdm',
    },
    ['jb700']        = {
        ['name']     = 'JB 700',
        ['brand']    = 'Dewbauchee',
        ['model']    = 'jb700',
        ['price']    = 240000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('jb700'),
        ['shop']     = 'pdm',
    },
    ['jb7002']       = {
        ['name']     = 'JB 700W',
        ['brand']    = 'Dewbauchee',
        ['model']    = 'jb7002',
        ['price']    = 40000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('jb7002'),
        ['shop']     = 'pdm',
    },
    ['mamba']        = {
        ['name']     = 'Mamba',
        ['brand']    = 'Declasse',
        ['model']    = 'mamba',
        ['price']    = 140000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('mamba'),
        ['shop']     = 'pdm',
    },
    ['michelli']     = {
        ['name']     = 'Michelli GT',
        ['brand']    = 'Lampadati',
        ['model']    = 'michelli',
        ['price']    = 30000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('michelli'),
        ['shop']     = 'pdm',
    },
    ['monroe']       = {
        ['name']     = 'Monroe',
        ['brand']    = 'Pegassi',
        ['model']    = 'monroe',
        ['price']    = 115000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('monroe'),
        ['shop']     = 'pdm',
    },
    ['nebula']       = {
        ['name']     = 'Nebula',
        ['brand']    = 'Vulcar',
        ['model']    = 'nebula',
        ['price']    = 22000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('nebula'),
        ['shop']     = 'pdm',
    },
    ['peyote']       = {
        ['name']     = 'Peyote',
        ['brand']    = 'Vapid',
        ['model']    = 'peyote',
        ['price']    = 23500,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('peyote'),
        ['shop']     = 'pdm',
    },
    ['peyote3']      = {
        ['name']     = 'Peyote Custom',
        ['brand']    = 'Vapid',
        ['model']    = 'peyote3',
        ['price']    = 48000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('peyote3'),
        ['shop']     = 'pdm',
    },
    ['pigalle']      = {
        ['name']     = 'Pigalle',
        ['brand']    = 'Lampadati',
        ['model']    = 'pigalle',
        ['price']    = 92000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('pigalle'),
        ['shop']     = 'pdm',
    },
    ['rapidgt3']     = {
        ['name']     = 'Rapid GT',
        ['brand']    = 'Dewbauchee',
        ['model']    = 'rapidgt3',
        ['price']    = 90000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('rapidgt3'),
        ['shop']     = 'pdm',
    },
    ['retinue']      = {
        ['name']     = 'Retinue',
        ['brand']    = 'Vapid',
        ['model']    = 'retinue',
        ['price']    = 32000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('retinue'),
        ['shop']     = 'pdm',
    },
    ['retinue2']     = {
        ['name']     = 'Retinue MKII',
        ['brand']    = 'Vapid',
        ['model']    = 'retinue2',
        ['price']    = 38000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('retinue2'),
        ['shop']     = 'pdm',
    },
    ['savestra']     = {
        ['name']     = 'Savestra',
        ['brand']    = 'Annis',
        ['model']    = 'savestra',
        ['price']    = 67000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('savestra'),
        ['shop']     = 'pdm',
    },
    ['stinger']      = {
        ['name']     = 'Stinger',
        ['brand']    = 'Grotti',
        ['model']    = 'stinger',
        ['price']    = 39500,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('stinger'),
        ['shop']     = 'pdm',
    },
    ['stingergt']    = {
        ['name']     = 'Stinger GT',
        ['brand']    = 'Grotti',
        ['model']    = 'stingergt',
        ['price']    = 70000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('stingergt'),
        ['shop']     = 'pdm',
    },
    ['stromberg']    = {
        ['name']     = 'Stromberg',
        ['brand']    = 'Ocelot',
        ['model']    = 'stromberg',
        ['price']    = 80000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('stromberg'),
        ['shop']     = 'pdm',
    },
    ['swinger']      = {
        ['name']     = 'Swinger',
        ['brand']    = 'Ocelot',
        ['model']    = 'swinger',
        ['price']    = 221000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('swinger'),
        ['shop']     = 'pdm',
    },
    ['torero']       = {
        ['name']     = 'Torero',
        ['brand']    = 'Pegassi',
        ['model']    = 'torero',
        ['price']    = 84000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('torero'),
        ['shop']     = 'pdm',
    },
    ['tornado']      = {
        ['name']     = 'Tornado',
        ['brand']    = 'Declasse',
        ['model']    = 'tornado',
        ['price']    = 21000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('tornado'),
        ['shop']     = 'pdm',
    },
    ['tornado2']     = {
        ['name']     = 'Tornado Gang',
        ['brand']    = 'Declasse',
        ['model']    = 'tornado2',
        ['price']    = 22000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('tornado2'),
        ['shop']     = 'pdm',
    },
    ['tornado5']     = {
        ['name']     = 'Tornado Custom',
        ['brand']    = 'Declasse',
        ['model']    = 'tornado5',
        ['price']    = 22000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('tornado5'),
        ['shop']     = 'pdm',
    },
    ['turismo2']     = {
        ['name']     = 'Turismo Classic',
        ['brand']    = 'Grotti',
        ['model']    = 'turismo2',
        ['price']    = 170000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('turismo2'),
        ['shop']     = 'pdm',
    },
    ['viseris']      = {
        ['name']     = 'Viseris',
        ['brand']    = 'Lampadati',
        ['model']    = 'viseris',
        ['price']    = 210000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('viseris'),
        ['shop']     = 'pdm',
    },
    ['z190']         = {
        ['name']     = '190Z',
        ['brand']    = 'Karin',
        ['model']    = 'z190',
        ['price']    = 78000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('z190'),
        ['shop']     = 'pdm',
    },
    ['ztype']        = {
        ['name']     = 'Z-Type',
        ['brand']    = 'Truffade',
        ['model']    = 'ztype',
        ['price']    = 270000,
        ['category'] = 'Sportsclassics',
        ['hash']     = GetHashKey('ztype'),
        ['shop']     = 'pdm',
    },
    ['zion3']        = {
        ['name']     = 'Zion Classic',
        ['brand']    = 'Übermacht',
        ['model']    = 'zion3',
        ['price']    = 45000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('zion3'),
        ['shop']     = 'pdm',
    },
    ['cheburek']     = {
        ['name']     = 'Cheburek',
        ['brand']    = 'Rune',
        ['model']    = 'cheburek',
        ['price']    = 7000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('cheburek'),
        ['shop']     = 'pdm',
    },
    ['toreador']     = {
        ['name']     = 'Toreador',
        ['brand']    = 'Pegassi',
        ['model']    = 'toreador',
        ['price']    = 50000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('toreador'),
        ['shop']     = 'pdm',
    },
    --- Super
    ['adder']        = {
        ['name']     = 'Adder',
        ['brand']    = 'Truffade',
        ['model']    = 'adder',
        ['price']    = 280000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('adder'),
        ['shop']     = 'luxury',
    },
    ['autarch']      = {
        ['name']     = 'Autarch',
        ['brand']    = 'Överflöd',
        ['model']    = 'autarch',
        ['price']    = 224000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('autarch'),
        ['shop']     = 'luxury',
    },
    ['banshee2']     = {
        ['name']     = 'Banshee 900R',
        ['brand']    = 'Bravado',
        ['model']    = 'banshee2',
        ['price']    = 120000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('banshee2'),
        ['shop']     = 'luxury',
    },
    ['bullet']       = {
        ['name']     = 'Bullet',
        ['brand']    = 'Vapid',
        ['model']    = 'bullet',
        ['price']    = 120000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('bullet'),
        ['shop']     = 'luxury',
    },
    ['cheetah']      = {
        ['name']     = 'Cheetah',
        ['brand']    = 'Grotti',
        ['model']    = 'cheetah',
        ['price']    = 214000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('cheetah'),
        ['shop']     = 'luxury',
    },
    ['cyclone']      = {         --might be too overpowered
        ['name']     = 'Cyclone',
        ['brand']    = 'Coil',
        ['model']    = 'cyclone',
        ['price']    = 300000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('cyclone'),
        ['shop']     = 'luxury',
    },
    ['entity2']      = {
        ['name']     = 'Entity XXR',
        ['brand']    = 'Överflöd',
        ['model']    = 'entity2',
        ['price']    = 164000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('entity2'),
        ['shop']     = 'luxury',
    },
    ['entityxf']     = {
        ['name']     = 'Entity XF',
        ['brand']    = 'Överflöd',
        ['model']    = 'entityxf',
        ['price']    = 180000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('entityxf'),
        ['shop']     = 'luxury',
    },
    ['emerus']       = {
        ['name']     = 'Emerus',
        ['brand']    = 'Progen',
        ['model']    = 'emerus',
        ['price']    = 220000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('emerus'),
        ['shop']     = 'luxury',
    },
    ['fmj']          = {
        ['name']     = 'FMJ',
        ['brand']    = 'Vapid',
        ['model']    = 'fmj',
        ['price']    = 125000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('fmj'),
        ['shop']     = 'luxury',
    },
    ['furia']        = {
        ['name']     = 'Furia',
        ['brand']    = 'Grotti',
        ['model']    = 'furia',
        ['price']    = 230000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('furia'),
        ['shop']     = 'luxury',
    },
    ['gp1']          = {
        ['name']     = 'GP1',
        ['brand']    = 'Progen',
        ['model']    = 'gp1',
        ['price']    = 110000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('gp1'),
        ['shop']     = 'luxury',
    },
    ['infernus']     = {
        ['name']     = 'Infernus',
        ['brand']    = 'Pegassi',
        ['model']    = 'infernus',
        ['price']    = 235000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('infernus'),
        ['shop']     = 'luxury',
    },
    ['italigtb']     = {
        ['name']     = 'Itali GTB',
        ['brand']    = 'Progen',
        ['model']    = 'italigtb',
        ['price']    = 170000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('italigtb'),
        ['shop']     = 'luxury',
    },
    ['italigtb2']    = {
        ['name']     = 'Itali GTB',
        ['brand']    = 'Progen',
        ['model']    = 'italigtb2',
        ['price']    = 250000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('italigtb2'),
        ['shop']     = 'luxury',
    },
    ['krieger']      = {
        ['name']     = 'Krieger',
        ['brand']    = 'Benefactor',
        ['model']    = 'krieger',
        ['price']    = 222000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('krieger'),
        ['shop']     = 'luxury',
    },
    ['le7b']         = {
        ['name']     = 'RE-7B',
        ['brand']    = 'Annis',
        ['model']    = 'le7b',
        ['price']    = 260000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('le7b'),
        ['shop']     = 'luxury',
    },
    ['nero']         = {
        ['name']     = 'Nero',
        ['brand']    = 'Truffade',
        ['model']    = 'nero',
        ['price']    = 200000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('nero'),
        ['shop']     = 'luxury',
    },
    ['nero2']        = {
        ['name']     = 'Nero Custom',
        ['brand']    = 'Truffade',
        ['model']    = 'nero2',
        ['price']    = 260000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('nero2'),
        ['shop']     = 'luxury',
    },
    ['osiris']       = {
        ['name']     = 'Osiris',
        ['brand']    = 'Pegassi',
        ['model']    = 'osiris',
        ['price']    = 220000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('osiris'),
        ['shop']     = 'luxury',
    },
    ['penetrator']   = {
        ['name']     = 'Penetrator',
        ['brand']    = 'Ocelot',
        ['model']    = 'penetrator',
        ['price']    = 130000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('penetrator'),
        ['shop']     = 'luxury',
    },
    ['pfister811']   = {
        ['name']     = '811',
        ['brand']    = 'Pfister',
        ['model']    = 'pfister811',
        ['price']    = 220000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('pfister811'),
        ['shop']     = 'luxury',
    },
    ['prototipo']    = {
        ['name']     = 'X80 Proto',
        ['brand']    = 'Grotti',
        ['model']    = 'prototipo',
        ['price']    = 235000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('prototipo'),
        ['shop']     = 'luxury',
    },
    ['reaper']       = {
        ['name']     = 'Reaper',
        ['brand']    = 'Pegassi',
        ['model']    = 'reaper',
        ['price']    = 100000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('reaper'),
        ['shop']     = 'luxury',
    },
    ['s80']          = {
        ['name']     = 'S80RR',
        ['brand']    = 'Annis',
        ['model']    = 's80',
        ['price']    = 205000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('s80'),
        ['shop']     = 'luxury',
    },
    ['sc1']          = {
        ['name']     = 'SC1',
        ['brand']    = 'Übermacht',
        ['model']    = 'sc1',
        ['price']    = 90000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('sc1'),
        ['shop']     = 'luxury',
    },
    ['sheava']       = {
        ['name']     = 'ETR1',
        ['brand']    = 'Emperor',
        ['model']    = 'sheava',
        ['price']    = 220000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('sheava'),
        ['shop']     = 'luxury',
    },
    ['sultanrs']     = {
        ['name']     = 'Sultan RS',
        ['brand']    = 'Karin',
        ['model']    = 'sultanrs',
        ['price']    = 76500,
        ['category'] = 'Sports',
        ['hash']     = GetHashKey('sultanrs'),
        ['shop']     = 'luxury',
    },
    ['t20']          = {
        ['name']     = 'T20',
        ['brand']    = 'Progen',
        ['model']    = 't20',
        ['price']    = 1650000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('t20'),
        ['shop']     = 'luxury',
    },
    ['taipan']       = {
        ['name']     = 'Taipan',
        ['brand']    = 'Cheval',
        ['model']    = 'taipan',
        ['price']    = 1850000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('taipan'),
        ['shop']     = 'luxury',
    },
    ['tempesta']     = {
        ['name']     = 'Tempesta',
        ['brand']    = 'Pegassi',
        ['model']    = 'tempesta',
        ['price']    = 120000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('tempesta'),
        ['shop']     = 'luxury',
    },
    ['tezeract']     = {
        ['name']     = 'Tezeract',
        ['brand']    = 'Pegassi',
        ['model']    = 'tezeract',
        ['price']    = 220000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('tezeract'),
        ['shop']     = 'luxury',
    },
    ['thrax']        = {
        ['name']     = 'Thrax',
        ['brand']    = 'Truffade',
        ['model']    = 'thrax',
        ['price']    = 180000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('thrax'),
        ['shop']     = 'luxury',
    },
    ['tigon']        = {
        ['name']     = 'Tigon',
        ['brand']    = 'Lampadati',
        ['model']    = 'tigon',
        ['price']    = 240000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('tigon'),
        ['shop']     = 'luxury',
    },
    ['turismor']     = {
        ['name']     = 'Turismo R',
        ['brand']    = 'Grotti',
        ['model']    = 'turismor',
        ['price']    = 140000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('turismor'),
        ['shop']     = 'luxury',
    },
    ['tyrant']       = {
        ['name']     = 'Tyrant',
        ['brand']    = ' Överflöd',
        ['model']    = 'tyrant',
        ['price']    = 2100000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('tyrant'),
        ['shop']     = 'luxury',
    },
    ['tyrus']        = {
        ['name']     = 'Tyrus',
        ['brand']    = 'Progen',
        ['model']    = 'tyrus',
        ['price']    = 230000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('tyrus'),
        ['shop']     = 'luxury',
    },
    ['vacca']        = {
        ['name']     = 'Vacca',
        ['brand']    = 'Pegassi',
        ['model']    = 'vacca',
        ['price']    = 105000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('vacca'),
        ['shop']     = 'luxury',
    },
    ['vagner']       = {
        ['name']     = 'Vagner',
        ['brand']    = 'Dewbauchee',
        ['model']    = 'vagner',
        ['price']    = 1660000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('vagner'),
        ['shop']     = 'luxury',
    },
    ['visione']      = {
        ['name']     = 'Visione',
        ['brand']    = 'Grotti',
        ['model']    = 'visione',
        ['price']    = 750000,
        ['category'] = 'Sports',
        ['hash']     = GetHashKey('visione'),
        ['shop']     = 'luxury',
    },
    ['voltic']       = {
        ['name']     = 'Voltic',
        ['brand']    = 'Coil',
        ['model']    = 'voltic',
        ['price']    = 120000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('voltic'),
        ['shop']     = 'luxury',
    },
    ['voltic2']      = {
        ['name']     = 'Rocket Voltic',
        ['brand']    = 'Coil',
        ['model']    = 'voltic2',
        ['price']    = 9830400,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('voltic2'),
        ['shop']     = 'luxury',
    },
    ['xa21']         = {
        ['name']     = 'XA-21',
        ['brand']    = 'Ocelot',
        ['model']    = 'xa21',
        ['price']    = 180000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('xa21'),
        ['shop']     = 'luxury',
    },
    ['zentorno']     = {
        ['name']     = 'Zentorno',
        ['brand']    = 'Pegassi',
        ['model']    = 'zentorno',
        ['price']    = 340000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('zentorno'),
        ['shop']     = 'luxury',
    },
    ['zorrusso']     = {
        ['name']     = 'Zorrusso',
        ['brand']    = 'Pegassi',
        ['model']    = 'zorrusso',
        ['price']    = 277000,
        ['category'] = 'Super',
        ['hash']     = GetHashKey('zorrusso'),
        ['shop']     = 'luxury',
    },
    -- Vans
    ['bison']        = {
        ['name']     = 'Bison',
        ['brand']    = 'Bravado',
        ['model']    = 'bison',
        ['price']    = 33750,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('bison'),
        ['shop']     = 'pdm',
    },
    ['bobcatxl']     = {
        ['name']     = 'Bobcat XL Open',
        ['brand']    = 'Vapid',
        ['model']    = 'bobcatxl',
        ['price']    = 26280,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('bobcatxl'),
        ['shop']     = 'pdm',
    },
    ['burrito']     = {
        ['name']     = 'Burrito',
        ['brand']    = 'Declasse',
        ['model']    = 'burrito3',
        ['price']    = 23760,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('burrito3'),
        ['shop']     = 'pdm',
    },
    ['gburrito2']    = {
        ['name']     = 'Burrito Custom',
        ['brand']    = 'Declasse',
        ['model']    = 'gburrito2',
        ['price']    = 50580,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('gburrito2'),
        ['shop']     = 'pdm',
    },
    ['rumpo']        = {
        ['name']     = 'Rumpo',
        ['brand']    = 'Bravado',
        ['model']    = 'rumpo',
        ['price']    = 9000,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('rumpo'),
        ['shop']     = 'pdm',
    },
    ['journey']      = {
        ['name']     = 'Journey',
        ['brand']    = 'Zirconium',
        ['model']    = 'journey',
        ['price']    = 6500,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('journey'),
        ['shop']     = 'pdm',
    },
    ['minivan']      = {
        ['name']     = 'Minivan',
        ['brand']    = 'Vapid',
        ['model']    = 'minivan',
        ['price']    = 11160,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('minivan'),
        ['shop']     = 'pdm',
    },
    ['minivan2']     = {
        ['name']     = 'Minivan Custom',
        ['brand']    = 'Vapid',
        ['model']    = 'minivan2',
        ['price']    = 10000,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('minivan2'),
        ['shop']     = 'pdm',
    },
    ['paradise']     = {
        ['name']     = 'Paradise',
        ['brand']    = 'Bravado',
        ['model']    = 'paradise',
        ['price']    = 18990,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('paradise'),
        ['shop']     = 'pdm',
    },
    ['rumpo3']       = {
        ['name']     = 'Rumpo Custom',
        ['brand']    = 'Bravado',
        ['model']    = 'rumpo3',
        ['price']    = 19500,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('rumpo3'),
        ['shop']     = 'pdm',
    },
    ['speedo']       = {
        ['name']     = 'Speedo',
        ['brand']    = 'Vapid',
        ['model']    = 'speedo',
        ['price']    = 10000,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('speedo'),
        ['shop']     = 'pdm',
    },
    ['speedo4']      = {
        ['name']     = 'Speedo Custom',
        ['brand']    = 'Vapid',
        ['model']    = 'speedo4',
        ['price']    = 15000,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('speedo4'),
        ['shop']     = 'pdm',
    },
    ['surfer']       = {
        ['name']     = 'Surfer',
        ['brand']    = 'BF',
        ['model']    = 'surfer',
        ['price']    = 22680,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('surfer'),
        ['shop']     = 'pdm',
    },
    ['youga3']       = {
        ['name']     = 'Youga Classic 4x4',
        ['brand']    = 'Bravado',
        ['model']    = 'youga3',
        ['price']    = 15000,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('youga3'),
        ['shop']     = 'pdm',
    },
    ['youga']        = {
        ['name']     = 'Youga',
        ['brand']    = 'Bravado',
        ['model']    = 'youga',
        ['price']    = 25290,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('youga'),
        ['shop']     = 'pdm',
    },
    ['youga2']       = {
        ['name']     = 'Youga Classic',
        ['brand']    = 'Bravado',
        ['model']    = 'youga2',
        ['price']    = 52290,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('youga2'),
        ['shop']     = 'pdm',
    },
    ['youga4']       = {
        ['name']     = 'Youga',
        ['brand']    = 'Bravado',
        ['model']    = 'youga4',
        ['price']    = 85000,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('youga4'),
        ['shop']     = 'pdm',
    },
    ['mule5']        = {
        ['name']     = 'Mule',
        ['brand']    = 'Box Truck',
        ['model']    = 'mule5',
        ['price']    = 221000,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('mule5'),
        ['shop']     = 'pdm',
    },
    -- Utility
    ['sadler']       = {
        ['name']     = 'Sadler',
        ['brand']    = 'Vapid',
        ['model']    = 'sadler',
        ['price']    = 20000,
        ['category'] = 'Off-road',
        ['hash']     = GetHashKey('sadler'),
        ['shop']     = 'pdm',
    },
    ['guardian']     = {
        ['name']     = 'Guardian',
        ['brand']    = 'Annis',
        ['model']    = 'guardian',
        ['price']    = 21000,
        ['category'] = 'Off-road',
        ['hash']     = GetHashKey('guardian'),
        ['shop']     = 'pdm',
    },
    ['warrener2']    = {
        ['name']     = 'Warrener HKR',
        ['brand']    = 'Vulcar',
        ['model']    = 'warrener2',
        ['price']    = 30000,
        ['category'] = 'Sedans',
        ['hash']     = GetHashKey('warrener2'),
        ['shop']     = 'pdm',
    },
    --- Custom
    ['ambcar']       = {
        ['name']     = 'Granger',
        ['brand']    = 'LSMC',
        ['model']    = 'ambcar',
        ['price']    = 35000,
        ['category'] = 'suvs',
        ['hash']     = GetHashKey('ambcar'),
        ['shop']     = 'na',
    },
    ['firetruk']     = {
        ['name']     = 'Camion de pompier',
        ['brand']    = 'LSMC',
        ['model']    = 'firetruk',
        ['price']    = 35000,
        ['category'] = 'suvs',
        ['hash']     = GetHashKey('firetruk'),
        ['shop']     = 'na',
        ['size']     = 3,
    },
    ['police5']      = {
        ['name']     = 'STX',
        ['brand']    = 'Bravado',
        ['model']    = 'police5',
        ['price']    = 35000,
        ['category'] = 'Muscle',
        ['hash']     = GetHashKey('police5'),
        ['shop']     = 'na',
    },
    ['police6']      = {
        ['name']     = 'Scout',
        ['brand']    = 'Vapid',
        ['model']    = 'police6',
        ['price']    = 45000,
        ['category'] = 'suvs',
        ['hash']     = GetHashKey('police6'),
        ['shop']     = 'na',
    },
    ['sheriff3']     = {
        ['name']     = 'Charger',
        ['brand']    = 'Bravado',
        ['model']    = 'sheriff3',
        ['price']    = 35000,
        ['category'] = 'Muscle',
        ['hash']     = GetHashKey('sheriff3'),
        ['shop']     = 'na',
    },
    ['sheriff4']     = {
        ['name']     = 'Tahoe',
        ['brand']    = 'Albany',
        ['model']    = 'sheriff4',
        ['price']    = 45000,
        ['category'] = 'svus',
        ['hash']     = GetHashKey('sheriff4'),
        ['shop']     = 'na',
    },
    ['sheriffb']     = {
        ['name']     = 'Moto Sheriff',
        ['brand']    = 'Western',
        ['model']    = 'sheriffb',
        ['price']    = 25000,
        ['category'] = 'Motorcycles',
        ['hash']     = GetHashKey('sheriffb'),
        ['shop']     = 'na',
    },
    ['paragonfbi']   = {
        ['name']     = 'Paragon FBI',
        ['brand']    = 'Enus',
        ['model']    = 'paragonfbi',
        ['price']    = 60000,
        ['category'] = 'Sports',
        ['hash']     = GetHashKey('paragonfbi'),
        ['shop']     = 'na',
    },
    ['cogfbi']       = {
        ['name']     = 'Cognoscenti FBI',
        ['brand']    = 'Enus',
        ['model']    = 'cogfbi',
        ['price']    = 22000,
        ['category'] = 'Sedans',
        ['hash']     = GetHashKey('cogfbi'),
        ['shop']     = 'na',
    },
    ['dynasty2']     = {
        ['name']     = 'Dynasty',
        ['brand']    = 'Weeny',
        ['model']    = 'dynasty2',
        ['price']    = 24000,
        ['category'] = 'Sportsclassic',
        ['hash']     = GetHashKey('dynasty2'),
        ['shop']     = 'na',
    },
    ['burrito6']     = {
        ['name']     = 'Burrito',
        ['brand']    = 'Declasse',
        ['model']    = 'burrito6',
        ['price']    = 26000,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('burrito6'),
        ['shop']     = 'na',
    },
    ['baller8']      = {
        ['name']     = 'Baller ST',
        ['brand']    = 'Gallivanter',
        ['model']    = 'baller8',
        ['price']    = 45000,
        ['category'] = 'Sedans',
        ['hash']     = GetHashKey('baller8'),
        ['shop']     = 'na',
    },
    ['flatbed']      = {
        ['name']     = 'Flatbed',
        ['brand']    = 'MTL',
        ['model']    = 'flatbed3',
        ['price']    = 45000,
        ['category'] = 'Industrial',
        ['hash']     = GetHashKey('flatbed3'),
        ['shop']     = 'na',
    },
    ['mule']         = {
        ['name']     = 'Mule',
        ['brand']    = 'Box Truck',
        ['model']    = 'mule6',
        ['price']    = 26000,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('mule6'),
        ['shop']     = 'na',
    },
    ['newsvan']      = {
        ['name']     = 'Rumpo',
        ['brand']    = 'Bravado',
        ['model']    = 'newsvan',
        ['price']    = 26000,
        ['category'] = 'Vans',
        ['hash']     = GetHashKey('newsvan'),
        ['shop']     = 'na',
    },
    ['packer']       = {
        ['name']     = 'Packer',
        ['brand']    = 'MTL',
        ['model']    = 'packer2',
        ['price']    = 27000,
        ['category'] = 'Industrial',
        ['hash']     = GetHashKey('packer2'),
        ['shop']     = 'na',
    },
    ['trailer']       = {
        ['name']     = 'Trailer',
        ['brand']    = 'MTL',
        ['model']    = 'tanker',
        ['price']    = 10000,
        ['category'] = 'Industrial',
        ['hash']     = GetHashKey('tanker'),
        ['shop']     = 'na',
        ['size']     = 3, -- 1 = S, 2 = M, 3 = L
    },
    ['stockade']     = {
        ['name']     = 'Securicar',
        ['brand']    = 'MTL',
        ['model']    = 'stockade',
        ['price']    = 30000,
        ['category'] = 'Commercial',
        ['hash']     = GetHashKey('stockade'),
        ['shop']     = 'na',
    },
    ['utiltruc']     = {
        ['name']     = 'Utility Truck',
        ['brand']    = 'Brute',
        ['model']    = 'utillitruck4',
        ['price']    = 20000,
        ['category'] = 'Utility',
        ['hash']     = GetHashKey('utillitruck4'),
        ['shop']     = 'na',
    },
    ['polmav']       = {
        ['name']     = 'Maverick',
        ['brand']    = 'Los Santos',
        ['model']    = 'polmav',
        ['price']    = 65000,
        ['category'] = 'Emergency',
        ['hash']     = GetHashKey('polmav'),
        ['shop']     = 'na',
        ['type']     = 'air',
        ['job_name'] = {
            ['lspd'] = 'Police Polmav',
            ['lsmc'] = 'Ambulance Polmav',
        }
    },
    ['ambulan']      = {
        ['name']     = 'Ambulance',
        ['brand']    = 'Los Santos',
        ['model']    = 'ambulance',
        ['price']    = 25000,
        ['category'] = 'Emergency',
        ['hash']     = GetHashKey('ambulance'),
        ['shop']     = 'na',
    },
    ['frogger']      = {
        ['name']     = 'Frogger',
        ['brand']    = 'Los Santos',
        ['model']    = 'frogger3',
        ['price']    = 65000,
        ['category'] = 'Emergency',
        ['hash']     = GetHashKey('frogger3'),
        ['shop']     = 'na',
        ['type']     = 'air',
    },
    ['trash']        = {
        ['name']     = 'Trashmaster',
        ['brand']    = 'Los Santos',
        ['model']    = 'trash',
        ['price']    = 18000,
        ['category'] = 'Utility',
        ['hash']     = GetHashKey('trash'),
        ['shop']     = 'na',
    },
    ['maverick2']    = {
        ['name']     = 'Maverick',
        ['brand']    = 'Los Santos',
        ['model']    = 'maverick2',
        ['price']    = 65000,
        ['category'] = 'Emergency',
        ['hash']     = GetHashKey('maverick2'),
        ['shop']     = 'na',
        ['type']     = 'air',
        ['job_name'] = {
            ['bcso'] = 'Police Maverick',
        }
    },
    ['policeb']      = {
        ['name']     = 'Moto de police',
        ['brand']    = 'Los Santos',
        ['model']    = 'policeb',
        ['price']    = 25000,
        ['category'] = 'Emergency',
        ['hash']     = GetHashKey('policeb'),
        ['shop']     = 'na',
    },
    ['buzzard2']      = {
        ['name']     = 'Buzzard',
        ['brand']    = 'Nagasaki',
        ['model']    = 'buzzard2',
        ['price']    = 100000,
        ['category'] = 'Helicopters',
        ['hash']     = GetHashKey('buzzard2'),
        ['shop']     = 'air',
        ['type']     = 'air',
    },
    ['sparrow']      = {
        ['name']     = 'Sea Sparrow',
        ['brand']    = 'Los Santos',
        ['model']    = 'seasparrow',
        ['price']    = 115000,
        ['category'] = 'Helicopters',
        ['hash']     = GetHashKey('seasparrow'),
        ['shop']     = 'air',
        ['type']     = 'air',
    },
    ['svolito']      = {
        ['name']     = 'SuperVolito',
        ['brand']    = 'Buckingham',
        ['model']    = 'supervolito',
        ['price']    = 260000,
        ['category'] = 'Helicopters',
        ['hash']     = GetHashKey('supervolito'),
        ['shop']     = 'air',
        ['type']     = 'air',
    },
    ['supervolito1']      = {
        ['name']     = 'SuperVolito',
        ['brand']    = 'Buckingham',
        ['model']    = 'supervolito1',
        ['price']    = 60000,
        ['category'] = 'Helicopters',
        ['hash']     = GetHashKey('supervolito'),
        ['shop']     = 'na',
        ['type']     = 'air',
    },
    ['svolito2']      = {
        ['name']     = 'SuperVolito Carbon',
        ['brand']    = 'Buckingham',
        ['model']    = 'supervolito2',
        ['price']    = 340000,
        ['category'] = 'Helicopters',
        ['hash']     = GetHashKey('supervolito2'),
        ['shop']     = 'air',
        ['type']     = 'air',
    },
    ['swift']      = {
        ['name']     = 'Swift',
        ['brand']    = 'Volatus',
        ['model']    = 'swift',
        ['price']    = 450000,
        ['category'] = 'Helicopters',
        ['hash']     = GetHashKey('swift'),
        ['shop']     = 'air',
        ['type']     = 'air',
    },
    ['swift2']      = {
        ['name']     = 'Swift Deluxe',
        ['brand']    = 'Volatus',
        ['model']    = 'swift2',
        ['price']    = 520000,
        ['category'] = 'Helicopters',
        ['hash']     = GetHashKey('swift2'),
        ['shop']     = 'air',
        ['type']     = 'air',
    },
    ['volatus']      = {
        ['name']     = 'Volatus',
        ['brand']    = 'Buckingham',
        ['model']    = 'volatus',
        ['price']    = 600000,
        ['category'] = 'Helicopters',
        ['hash']     = GetHashKey('volatus'),
        ['shop']     = 'air',
        ['type']     = 'air',
    },
    ['cargobob']      = {
        ['name']     = 'Cargobob',
        ['brand']    = 'Jetsam',
        ['model']    = 'cargobob2',
        ['price']    = 65000,
        ['category'] = 'Helicopters',
        ['hash']     = GetHashKey('cargobob2'),
        ['shop']     = 'na',
        ['type']     = 'air'
    },
    --- PAWL
    ['sadler1']     = {
        ['name']     = 'Sadler',
        ['brand']    = 'Vapid',
        ['model']    = 'sadler1',
        ['price']    = 25000,
        ['category'] = 'Utility',
        ['hash']     = GetHashKey('sadler1'),
        ['shop']     = 'na',
        ['type']     = 'car'
    },
    ['hauler1']     = {
        ['name']     = 'Hauler',
        ['brand']    = 'Jobuilt',
        ['model']    = 'hauler1',
        ['price']    = 25000,
        ['category'] = 'Commercial',
        ['hash']     = GetHashKey('hauler1'),
        ['shop']     = 'na',
        ['type']     = 'truck'
    },
    ['trailerlogs']     = {
        ['name']     = 'Remorque',
        ['brand']    = '',
        ['model']    = 'trailerlogs',
        ['price']    = 25000,
        ['category'] = 'Utility',
        ['hash']     = GetHashKey('trailerlogs'),
        ['shop']     = 'na',
        ['type']     = 'truck'
    },
    -- UPW
    ['brickade1']     = {
        ['name']     = 'Brickade',
        ['brand']    = '',
        ['model']    = 'brickade1',
        ['price']    = 35000,
        ['category'] = 'Utility',
        ['hash']     = GetHashKey('brickade1'),
        ['shop']     = 'na',
        ['type']     = 'truck'
    },
    ['boxville']     = {
        ['name']     = 'Boxville',
        ['brand']    = '',
        ['model']    = 'boxville',
        ['price']    = 24000,
        ['category'] = 'Utility',
        ['hash']     = GetHashKey('boxville'),
        ['shop']     = 'na',
        ['type']     = 'truck'
    },
    ['openwheel1']     = {
        ['name']     = 'BR8',
        ['brand']    = 'Benefactor',
        ['model']    = 'openwheel1',
        ['price']    = 666666,
        ['category'] = 'Openwheel',
        ['hash']     = GetHashKey('openwheel1'),
        ['shop']     = 'na',
        ['type']     = 'car'
    },
    ['openwheel2']     = {
        ['name']     = 'DR1',
        ['brand']    = 'Declasse',
        ['model']    = 'openwheel2',
        ['price']    = 666666,
        ['category'] = 'Openwheel',
        ['hash']     = GetHashKey('openwheel2'),
        ['shop']     = 'na',
        ['type']     = 'car'
    },
    ['formula']     = {
        ['name']     = 'PR4',
        ['brand']    = 'Progen',
        ['model']    = 'formula',
        ['price']    = 666666,
        ['category'] = 'Openwheel',
        ['hash']     = GetHashKey('formula'),
        ['shop']     = 'na',
        ['type']     = 'car'
    },
    ['formula2']     = {
        ['name']     = 'R88',
        ['brand']    = 'Ocelot',
        ['model']    = 'formula2',
        ['price']    = 666666,
        ['category'] = 'Openwheel',
        ['hash']     = GetHashKey('formula2'),
        ['shop']     = 'na',
        ['type']     = 'car',
    },
    -- Boats
    ['dinghy']     = {
        ['name']     = 'Dinghy 4 Places',
        ['brand']    = 'Nagasaki',
        ['model']    = 'dinghy',
        ['price']    = 50000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('dinghy'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['dinghy2']     = {
        ['name']     = 'Dinghy 2 Places',
        ['brand']    = 'Nagasaki',
        ['model']    = 'dinghy2',
        ['price']    = 48000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('dinghy2'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['dinghy3']     = {
        ['name']     = 'Dinghy',
        ['brand']    = 'Nagasaki',
        ['model']    = 'dinghy3',
        ['price']    = 50000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('dinghy3'),
        ['shop']     = 'na',
        ['type']     = 'boat'
    },
    ['dinghy4']     = {
        ['name']     = 'Dinghy Premium',
        ['brand']    = 'Nagasaki',
        ['model']    = 'dinghy4',
        ['price']    = 60000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('dinghy4'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['jetmax']     = {
        ['name']     = 'Jetmax',
        ['brand']    = 'Shitzu',
        ['model']    = 'jetmax',
        ['price']    = 60000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('jetmax'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['marquis']     = {
        ['name']     = 'Marquis',
        ['brand']    = 'Dinka',
        ['model']    = 'marquis',
        ['price']    = 120000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('marquis'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['seashark']     = {
        ['name']     = 'Seashark',
        ['brand']    = 'Speedophile',
        ['model']    = 'seashark',
        ['price']    = 15000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('seashark'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['seashark2']     = {
        ['name']     = 'Seashark Premium',
        ['brand']    = 'Speedophile',
        ['model']    = 'seashark2',
        ['price']    = 20000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('seashark2'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['speeder']     = {
        ['name']     = 'Speeder',
        ['brand']    = 'Pegassi',
        ['model']    = 'speeder',
        ['price']    = 65000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('speeder'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['speeder2']     = {
        ['name']     = 'Speeder Premium',
        ['brand']    = 'Pegassi',
        ['model']    = 'speeder',
        ['price']    = 65000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('speeder'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['squalo']     = {
        ['name']     = 'Squalo',
        ['brand']    = 'Shitzu',
        ['model']    = 'squalo',
        ['price']    = 135000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('squalo'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['submersible']     = {
        ['name']     = 'Submersible',
        ['brand']    = 'Kraken',
        ['model']    = 'submersible',
        ['price']    = 200000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('submersible'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['submersible2']     = {
        ['name']     = 'Kraken',
        ['brand']    = 'Kraken',
        ['model']    = 'submersible2',
        ['price']    = 230000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('submersible2'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['avisa']     = {
        ['name']     = 'Avisa',
        ['brand']    = 'Kraken',
        ['model']    = 'avisa',
        ['price']    = 290000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('avisa'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['suntrap']     = {
        ['name']     = 'Suntrap',
        ['brand']    = 'Shitzu',
        ['model']    = 'suntrap',
        ['price']    = 80000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('suntrap'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['toro']     = {
        ['name']     = 'Toro',
        ['brand']    = 'Lampadati',
        ['model']    = 'toro',
        ['price']    = 165000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('toro'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['toro2']     = {
        ['name']     = 'Toro Premium',
        ['brand']    = 'Lampadati',
        ['model']    = 'toro2',
        ['price']    = 165000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('toro2'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['tropic']     = {
        ['name']     = 'Tropic',
        ['brand']    = 'Shitzu',
        ['model']    = 'tropic',
        ['price']    = 125000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('tropic'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['tropic2']     = {
        ['name']     = 'Tropic Premium',
        ['brand']    = 'Shitzu',
        ['model']    = 'tropic2',
        ['price']    = 145000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('tropic2'),
        ['shop']     = 'boat',
        ['type']     = 'boat'
    },
    ['longfin']     = {
        ['name']     = 'Longfin',
        ['brand']    = 'Shitzu',
        ['model']    = 'longfin',
        ['price']    = 260000,
        ['category'] = 'Boats',
        ['hash']     = GetHashKey('longfin'),
        ['shop']     = 'boat',
        ['type']     = 'boat',
    },
}
