import { InventoryType } from '../inventory';
import { JobType } from '../job';
import { Zone } from '../polyzone/box.zone';

export type JobInventory = {
    storage: string;
    type: InventoryType;
};

export const JOB_INVENTORIES: Partial<Record<JobType, Zone<JobInventory>[]>> = {
    [JobType.Baun]: [
        {
            center: [106.36, -1299.08, 28.77],
            length: 0.4,
            width: 2.3,
            minZ: 27.82,
            maxZ: 30.27,
            heading: 30,
            data: {
                storage: 'baun_unicorn_cloakroom_1',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [109.05, -1304.24, 28.77],
            length: 2.25,
            width: 0.4,
            minZ: 27.87,
            maxZ: 30.27,
            heading: 30,
            data: {
                storage: 'baun_unicorn_cloakroom_2',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [-1381.38, -602.26, 30.32],
            length: 2.0,
            width: 6.4,
            minZ: 29.92,
            maxZ: 31.92,
            heading: 303,
            data: {
                storage: 'baun_bahama_cloakroom_1',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [-1383.92, -608.42, 30.32],
            length: 2.0,
            width: 6.4,
            minZ: 29.92,
            maxZ: 31.92,
            heading: 303,
            data: {
                storage: 'baun_bahama_cloakroom_2',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [1983.94, 3050.51, 47.22],
            length: 0.4,
            width: 3.2,
            minZ: 46.22,
            maxZ: 48.22,
            heading: -31.96,
            data: {
                storage: 'baun_yellowjack_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [-1385.25, -632.97, 30.81],
            length: 2.8,
            width: 0.6,
            minZ: 29.81,
            maxZ: 32.61,
            heading: 309,
            data: {
                storage: 'baun_bahama_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [92.05, -1292.26, 29.27],
            length: 1.05,
            width: 0.4,
            minZ: 28.27,
            maxZ: 29.27,
            heading: 30,
            data: {
                storage: 'baun_unicorn_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [-1386.24, -609.34, 30.32],
            length: 1.0,
            width: 0.9,
            minZ: 29.32,
            maxZ: 31.52,
            heading: 32,
            data: {
                storage: 'baun_bahama_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [132.44, -1287.82, 29.27],
            length: 1.0,
            width: 1.0,
            minZ: 28.27,
            maxZ: 30.47,
            heading: 30.13,
            data: {
                storage: 'baun_unicorn_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [1984.86, 3048.1, 47.22],
            length: 1.0,
            width: 0.8,
            minZ: 46.22,
            maxZ: 48.22,
            heading: 327.65,
            data: {
                storage: 'baun_yellowjack_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-1393.41, -601.61, 30.47],
            length: 0.8,
            width: 1.3,
            minZ: 28.42,
            maxZ: 30.27,
            heading: 266.56,
            data: {
                storage: 'baun_bahama_snack_storage',
                type: InventoryType.SnackStorage,
            },
        },
        {
            center: [127.87, -1282.88, 28.22],
            length: 1.0,
            width: 0.65,
            minZ: 27.22,
            maxZ: 29.22,
            heading: 300.37,
            data: {
                storage: 'baun_unicorn_snack_storage',
                type: InventoryType.SnackStorage,
            },
        },
        {
            center: [1983.08, 3049.19, 47.22],
            length: 0.4,
            width: 3.2,
            minZ: 46.22,
            maxZ: 47.07,
            heading: 327.35,
            data: {
                storage: 'baun_yellowjack_snack_storage',
                type: InventoryType.SnackStorage,
            },
        },
        {
            center: [132.34, -1285.02, 29.27],
            length: 3.6,
            width: 0.6,
            minZ: 28.27,
            maxZ: 29.27,
            heading: 30,
            data: {
                storage: 'baun_unicorn_liquor_storage_1',
                type: InventoryType.LiquorStorage,
            },
        },
        {
            center: [129.87, -1280.56, 29.27],
            length: 2.8,
            width: 0.8,
            minZ: 28.27,
            maxZ: 29.27,
            heading: 30,
            data: {
                storage: 'baun_unicorn_liquor_storage_2',
                type: InventoryType.LiquorStorage,
            },
        },
        {
            center: [133.31, -1286.06, 29.27],
            length: 0.7,
            width: 0.7,
            minZ: 29.27,
            maxZ: 30.17,
            heading: 30,
            data: {
                storage: 'baun_unicorn_flavor_storage_1',
                type: InventoryType.FlavorStorage,
            },
        },
        {
            center: [128.97, -1284.42, 29.27],
            length: 0.5,
            width: 0.35,
            minZ: 29.27,
            maxZ: 29.67,
            heading: 30,
            data: {
                storage: 'baun_unicorn_furniture_storage_1',
                type: InventoryType.FurnitureStorage,
            },
        },
        {
            center: [-1375.53, -629.32, 30.82],
            length: 6.8,
            width: 0.2,
            minZ: 29.82,
            maxZ: 30.77,
            heading: 303,
            data: {
                storage: 'baun_bahama_fridge_storage_1',
                type: InventoryType.LiquorStorage,
            },
        },
        {
            center: [-1391.91, -606.7, 30.27],
            length: 0.8,
            width: 2.8,
            minZ: 29.07,
            maxZ: 30.27,
            heading: 305.35,
            data: {
                storage: 'baun_bahama_fridge_storage_2',
                type: InventoryType.LiquorStorage,
            },
        },
        {
            center: [-1389.55, -599.86, 30.32],
            length: 0.75,
            width: 0.7,
            minZ: 30.32,
            maxZ: 31.12,
            heading: 302,
            data: {
                storage: 'baun_bahama_flavor_storage_1',
                type: InventoryType.FlavorStorage,
            },
        },
        {
            center: [-1378.66, -631.6, 30.82],
            length: 0.65,
            width: 0.6,
            minZ: 30.82,
            maxZ: 31.62,
            heading: 34,
            data: {
                storage: 'baun_bahama_flavor_storage_2',
                type: InventoryType.FlavorStorage,
            },
        },
        {
            center: [-1389.54, -606.59, 30.38],
            length: 0.55,
            width: 0.35,
            minZ: 30.33,
            maxZ: 30.73,
            heading: 38,
            data: {
                storage: 'baun_bahama_furniture_storage_1',
                type: InventoryType.FurnitureStorage,
            },
        },
        {
            center: [-1375.82, -627.51, 30.82],
            length: 0.55,
            width: 0.3,
            minZ: 30.77,
            maxZ: 31.17,
            heading: 301,
            data: {
                storage: 'baun_bahama_furniture_storage_2',
                type: InventoryType.FurnitureStorage,
            },
        },
        {
            center: [1981.83, 3053.12, 47.22],
            length: 0.1,
            width: 2.4,
            minZ: 46.22,
            maxZ: 47.02,
            heading: 237.68,
            data: {
                storage: 'baun_yellowjack_fridge_storage_1',
                type: InventoryType.LiquorStorage,
            },
        },
        {
            center: [1982.59, 3054.93, 47.22],
            length: 1.2,
            width: 0.8,
            minZ: 46.22,
            maxZ: 47.02,
            heading: 146.98,
            data: {
                storage: 'baun_yellowjack_flavor_storage_1',
                type: InventoryType.FlavorStorage,
            },
        },
        {
            center: [1982.58, 3054.94, 47.22],
            length: 1.0,
            width: 0.6,
            minZ: 47.22,
            maxZ: 48.22,
            heading: 326.85,
            data: {
                storage: 'baun_yellowjack_furniture_storage_1',
                type: InventoryType.FurnitureStorage,
            },
        },
        {
            center: [127.81, -1281.97, 28.32],
            length: 1.2,
            width: 0.8,
            minZ: 27.32,
            maxZ: 29.32,
            heading: 299.97,
            data: {
                storage: 'baun_unicorn_ice_machine',
                type: InventoryType.IceMachine,
            },
        },
        {
            center: [-1389.45, -599.76, 30.32],
            length: 1.4,
            width: 0.8,
            minZ: 29.32,
            maxZ: 30.32,
            heading: 123.19,
            data: {
                storage: 'baun_bahama_ice_machine_1',
                type: InventoryType.IceMachine,
            },
        },
        {
            center: [-1378.7, -631.53, 30.82],
            length: 1.2,
            width: 1.0,
            minZ: 29.32,
            maxZ: 30.32,
            heading: 33.34,
            data: {
                storage: 'baun_bahama_ice_machine_2',
                type: InventoryType.IceMachine,
            },
        },
        {
            center: [1983.46, 3052.34, 46.22],
            length: 1.2,
            width: 0.8,
            minZ: 45.22,
            maxZ: 47.22,
            heading: 58.99,
            data: {
                storage: 'baun_yellowjack_ice_machine',
                type: InventoryType.IceMachine,
            },
        },
        {
            center: [-1387.14, -606.22, 30.32],
            length: 3.8,
            width: 0.8,
            minZ: 29.32,
            maxZ: 30.12,
            heading: 303,
            data: {
                storage: 'baun_bahama_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [131.23, -1282.6, 29.27],
            length: 1.0,
            width: 1.2,
            minZ: 28.27,
            maxZ: 29.22,
            heading: 120.28,
            data: {
                storage: 'baun_unicorn_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [1983.94, 3050.51, 47.22],
            length: 0.4,
            width: 3.2,
            minZ: 46.22,
            maxZ: 47.22,
            heading: -31.96,
            data: {
                storage: 'baun_yellowjack_storage',
                type: InventoryType.Stash,
            },
        },
    ],
    [JobType.BCSO]: [
        {
            center: [1856.79, 3693.02, 37.97],
            length: 1.5,
            width: 1.5,
            minZ: 36.97,
            maxZ: 38.97,
            heading: 302.0,
            data: {
                storage: 'bcso_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [1859.58, 3690.44, 34.27],
            length: 2.5,
            width: 1.5,
            minZ: 33.27,
            maxZ: 35.27,
            heading: 245.0,
            data: {
                storage: 'bcso_armory',
                type: InventoryType.Armory,
            },
        },
        {
            center: [1849.4, 3694.2, 30.27],
            length: 3.8,
            width: 5.2,
            minZ: 29.27,
            maxZ: 31.27,
            heading: 120.0,
            data: {
                storage: 'bcso_seizure1',
                type: InventoryType.Seizure,
            },
        },
        {
            center: [1842.5, 3689.75, 30.27],
            length: 6.2,
            width: 3.2,
            minZ: 29.27,
            maxZ: 31.27,
            heading: 30.0,
            data: {
                storage: 'bcso_seizure2',
                type: InventoryType.Seizure,
            },
        },
        {
            center: [1840.28, 3694.13, 30.27],
            length: 3.4,
            width: 3.5,
            minZ: 29.27,
            maxZ: 31.27,
            heading: 30.0,
            data: {
                storage: 'bcso_seizure3',
                type: InventoryType.Seizure,
            },
        },
        {
            center: [1853.46, 3687.07, 38.2],
            length: 1.5,
            width: 1.5,
            minZ: 37.2,
            maxZ: 39.2,
            heading: 125.0,
            data: {
                storage: 'bcso_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [1854.96, 3695.17, 30.08],
            length: 1.5,
            width: 3.0,
            minZ: 29.08,
            maxZ: 31.08,
            heading: 28.0,
            data: {
                storage: 'bcso_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [1847.09, 3691.61, 34.27],
            length: 2.0,
            width: 1.8,
            minZ: 33.27,
            maxZ: 35.27,
            heading: 208.54,
            data: {
                storage: 'bcso_evidence_storage',
                type: InventoryType.EvidenceStorage,
            },
        },
        {
            center: [1858.19, 3699.86, 30.27],
            length: 2.8,
            width: 0.4,
            minZ: 29.27,
            maxZ: 31.27,
            heading: 30.0,
            data: {
                storage: 'bcso_ammo',
                type: InventoryType.Ammo,
            },
        },
        {
            center: [1847.27, 3693.85, 34.27],
            length: 8.0,
            width: 3.6,
            minZ: 33.27,
            maxZ: 35.27,
            heading: 300,
            data: {
                storage: 'bcso_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.CashTransfer]: [
        {
            center: [-10.0, -700.62, 46.25],
            length: 1.5,
            width: 1.5,
            minZ: 45.25,
            maxZ: 47.25,
            heading: 204.6,
            data: {
                storage: 'stonk_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-6.17, -706.95, 40.72],
            length: 1.0,
            width: 3.0,
            minZ: 39.72,
            maxZ: 41.72,
            heading: 235.7,
            data: {
                storage: 'stonk_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [-3.38, -703.02, 40.7],
            length: 1.0,
            width: 3.0,
            minZ: 39.7,
            maxZ: 41.7,
            heading: 235.7,
            data: {
                storage: 'stonk_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [-17.64, -716.12, 46.02],
            length: 2.2,
            width: 3.8,
            minZ: 45.02,
            maxZ: 47.02,
            heading: 25.0,
            data: {
                storage: 'stonk_armory',
                type: InventoryType.Armory,
            },
        },
        {
            center: [-16.0, -714.38, 46.02],
            length: 2.0,
            width: 0.6,
            minZ: 45.02,
            maxZ: 47.02,
            heading: 25.0,
            data: {
                storage: 'stonk_ammo',
                type: InventoryType.Ammo,
            },
        },
        {
            center: [-24.1, -708.6, 46.0],
            length: 0.8,
            width: 8.0,
            minZ: 45.0,
            maxZ: 47.2,
            heading: 295,
            data: {
                storage: 'stonk_cloakroom_1',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [-20.75, -706.325, 46.0],
            length: 0.8,
            width: 8.0,
            minZ: 45.0,
            maxZ: 47.2,
            heading: 295,
            data: {
                storage: 'stonk_cloakroom_2',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.DMC]: [
        {
            center: [1079.02, -1978.35, 31.47],
            length: 4.2,
            width: 1.0,
            minZ: 30.47,
            maxZ: 33.27,
            heading: 55,
            data: {
                storage: 'dmc_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [1075.59, -2010.84, 32.08],
            length: 1.2,
            width: 2.8,
            minZ: 31.08,
            maxZ: 33.08,
            heading: 55,
            data: {
                storage: 'dmc_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [1085.6, -2016.04, 41.48],
            length: 1.0,
            width: 1.8,
            minZ: 40.48,
            maxZ: 42.88,
            heading: 145,
            data: {
                storage: 'dmc_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [1111.87, -2009.54, 31.01],
            length: 3.4,
            width: 3.2,
            minZ: 30.01,
            maxZ: 32.81,
            heading: 55,
            data: {
                storage: 'dmc_converter',
                type: InventoryType.MetalConverter,
            },
        },
        {
            center: [1086.27, -2003.68, 31.28],
            length: 4.2,
            width: 2.8,
            minZ: 30.28,
            maxZ: 32.08,
            heading: 318,
            data: {
                storage: 'dmc_incinerator',
                type: InventoryType.MetalIncinerator,
            },
        },
        {
            center: [1083.18, -2014.34, 41.48],
            length: 1.0,
            width: 3.8,
            minZ: 40.48,
            maxZ: 43.08,
            heading: 145,
            data: {
                storage: 'dmc_cloackroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.FBI]: [
        {
            center: [134.23, -770.05, 242.15],
            length: 0.6,
            width: 2.8,
            minZ: 241.15,
            maxZ: 243.55,
            heading: 250,
            data: {
                storage: 'fbi_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [144.18, -764.65, 242.15],
            length: 2.8,
            width: 0.4,
            minZ: 241.15,
            maxZ: 243.7,
            heading: 340,
            data: {
                storage: 'fbi_armory',
                type: InventoryType.Armory,
            },
        },
        {
            center: [145.13, -762.08, 242.15],
            length: 2.7,
            width: 0.4,
            minZ: 241.15,
            maxZ: 243.65,
            heading: 340,
            data: {
                storage: 'fbi_ammo',
                type: InventoryType.Ammo,
            },
        },
    ],
    [JobType.FDF]: [
        {
            center: [2437.57, 5013.32, 46.99],
            length: 0.6,
            width: 2.2,
            minZ: 45.99,
            maxZ: 47.99,
            heading: 314.41,
            data: {
                storage: 'fdf_cloakroom_2',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [2439.95, 4974.12, 46.81],
            length: 1.0,
            width: 1.0,
            minZ: 45.81,
            maxZ: 47.81,
            heading: 225.3,
            data: {
                storage: 'fdf_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [2441.24, 4980.16, 46.81],
            length: 1.0,
            width: 1.0,
            minZ: 45.81,
            maxZ: 47.81,
            heading: 223.53,
            data: {
                storage: 'fdf_fridge2',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [2529.21, 4980.51, 45.36],
            length: 3.8,
            width: 7.8,
            minZ: 44.36,
            maxZ: 46.36,
            heading: 224.77,
            data: {
                storage: 'fdf_stash',
                type: InventoryType.Stash,
            },
        },
        {
            center: [2438.33, 4966.09, 46.81],
            length: 1.0,
            width: 2.4,
            minZ: 45.81,
            maxZ: 47.81,
            heading: 47.37,
            data: {
                storage: 'fdf_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [2434.21, 5011.35, 46.99],
            length: 0.6,
            width: 2.2,
            minZ: 45.99,
            maxZ: 47.99,
            heading: 314.41,
            data: {
                storage: 'fdf_cloakroom_1',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.Ffs]: [
        {
            center: [710.75, -962.72, 30.4],
            length: 1.4,
            width: 0.8,
            minZ: 29.4,
            maxZ: 30.65,
            heading: 0,
            data: {
                storage: 'ffs_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [708.85, -963.2, 30.41],
            length: 0.2,
            width: 1.6,
            minZ: 29.41,
            maxZ: 30.86,
            heading: 0,
            data: {
                storage: 'ffs_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [705.28, -961.63, 30.4],
            length: 0.25,
            width: 1.1,
            minZ: 29.4,
            maxZ: 31.4,
            heading: 0,
            data: {
                storage: 'ffs_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [706.41, -959.03, 30.4],
            length: 0.5,
            width: 4.25,
            minZ: 29.4,
            maxZ: 31.6,
            heading: 0,
            data: {
                storage: 'ffs_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.Food]: [
        {
            center: [-1878.76, 2066.86, 141.02],
            length: 0.5,
            width: 1.5,
            minZ: 140.02,
            maxZ: 142.52,
            heading: 251.1,
            data: {
                storage: 'food_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-1927.72, 2042.2, 140.73],
            length: 1.0,
            width: 3.4,
            minZ: 139.73,
            maxZ: 142.23,
            heading: 257.32,
            data: {
                storage: 'food_fridge2',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-1926.27, 2048.37, 140.73],
            length: 1.0,
            width: 3.6,
            minZ: 139.73,
            maxZ: 142.23,
            heading: 256.38,
            data: {
                storage: 'food_fridge3',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-1924.85, 2054.54, 140.73],
            length: 1.5,
            width: 3.4,
            minZ: 139.73,
            maxZ: 142.23,
            heading: 256.22,
            data: {
                storage: 'food_fridge4',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-1888.19, 2060.61, 141.0],
            length: 1.25,
            width: 1.0,
            minZ: 140.0,
            maxZ: 142.3,
            heading: 340.0,
            data: {
                storage: 'food_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [-1890.94, 2065.11, 140.97],
            length: 0.5,
            width: 1.25,
            minZ: 139.97,
            maxZ: 142.22,
            heading: 160.2,
            data: {
                storage: 'food_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [-1866.8, 2059.98, 141.0],
            length: 0.5,
            width: 1.5,
            minZ: 140.0,
            maxZ: 142.5,
            heading: 340.76,
            data: {
                storage: 'food_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.Garbage]: [
        {
            center: [-594.91, -1620.31, 33.01],
            length: 0.8,
            width: 1.6,
            minZ: 32.01,
            maxZ: 35.01,
            heading: 355,
            data: {
                storage: 'garbage_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-615.57, -1624.62, 33.01],
            length: 0.6,
            width: 1.4,
            minZ: 32.01,
            maxZ: 35.01,
            heading: 355,
            data: {
                storage: 'garbage_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [-596.23, -1616.31, 33.01],
            length: 0.8,
            width: 10.8,
            minZ: 32.01,
            maxZ: 35.01,
            heading: 355,
            data: {
                storage: 'garbage_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.Gouv]: [
        {
            center: [-533.09, -592.43, 34.68],
            length: 0.8,
            width: 0.8,
            minZ: 33.68,
            maxZ: 35.68,
            heading: 0,
            data: {
                storage: 'gouv_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-530.99, -596.52, 34.68],
            length: 0.8,
            width: 2.6,
            minZ: 33.68,
            maxZ: 35.68,
            heading: 270.0,
            data: {
                storage: 'gouv_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [-530.6, -591.2, 34.68],
            length: 3.2,
            width: 0.2,
            minZ: 33.68,
            maxZ: 35.68,
            heading: 180,
            data: {
                storage: 'gouv_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [-538.53, -582.2, 34.68],
            length: 0.8,
            width: 3.2,
            minZ: 33.68,
            maxZ: 35.68,
            heading: 180,
            data: {
                storage: 'gouv_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.LSCS]: [
        {
            center: [443.83, -974.49, 30.69],
            length: 0.8,
            width: 3.2,
            minZ: 29.69,
            maxZ: 31.69,
            heading: 180.77,
            data: {
                storage: 'lscs_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [451.38, -994.47, 30.69],
            length: 1.2,
            width: 5.0,
            minZ: 29.69,
            maxZ: 31.69,
            heading: -0.1,
            data: {
                storage: 'lscs_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.LSMC]: [
        {
            center: [387.78, -1402.0, 37.99],
            length: 6.8,
            width: 0.8,
            minZ: 36.99,
            maxZ: 38.99,
            heading: 320,
            data: {
                storage: 'lsmc_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [1820.94, 3677.6, 38.28],
            length: 1.0,
            width: 1.6,
            minZ: 37.28,
            maxZ: 39.28,
            heading: 300,
            data: {
                storage: 'lsmc_north_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [391.75, -1427.29, 29.43],
            length: 1.0,
            width: 4.6,
            minZ: 28.43,
            maxZ: 30.43,
            heading: 320,
            data: {
                storage: 'lsmc_armory',
                type: InventoryType.Armory,
            },
        },
        {
            center: [377.0, -1391.75, 37.99],
            length: 1.1,
            width: 5.6,
            minZ: 36.99,
            maxZ: 38.99,
            heading: 320,
            data: {
                storage: 'lsmc_stash',
                type: InventoryType.Stash,
            },
        },
        {
            center: [374.06, -1412.06, 38.04],
            length: 2.6,
            width: 0.8,
            minZ: 37.04,
            maxZ: 39.04,
            heading: 51.07,
            data: {
                storage: 'lsmc_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [1826.23, 3674.01, 37.18],
            length: 1.0,
            width: 1.2,
            minZ: 36.18,
            maxZ: 38.18,
            heading: 29.75,
            data: {
                storage: 'lsmc_north_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [367.9, -1417.04, 32.51],
            length: 0.8,
            width: 3.2,
            minZ: 31.51,
            maxZ: 32.51,
            heading: 230,
            data: {
                storage: 'lsmc_organ',
                type: InventoryType.Organ,
            },
        },
        {
            center: [1821.94, 3681.11, 34.38],
            length: 1.0,
            width: 2.4,
            minZ: 33.38,
            maxZ: 34.18,
            heading: 120,
            data: {
                storage: 'lsmc_north_organ',
                type: InventoryType.Organ,
            },
        },
        {
            center: [365.05, -1391.05, 37.99],
            length: 0.8,
            width: 4.0,
            minZ: 36.99,
            maxZ: 38.99,
            heading: 49.35,
            data: {
                storage: 'lsmc_male_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [356.14, -1384.64, 37.99],
            length: 0.8,
            width: 5.6,
            minZ: 36.99,
            maxZ: 38.99,
            heading: 49.61,
            data: {
                storage: 'lsmc_female_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [1837.87, 3682.32, 34.28],
            length: 0.75,
            width: 2.55,
            minZ: 33.28,
            maxZ: 35.28,
            heading: 299.58,
            data: {
                storage: 'lsmc_north_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.LSPD]: [
        {
            center: [625.466919, -31.86854, 90.308548],
            length: 2.5,
            width: 1.0,
            minZ: 89.308548,
            maxZ: 91.308548,
            heading: 255,
            data: {
                storage: 'lspd_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [608.31, -6.02, 76.63],
            length: 0.6,
            width: 2.8,
            minZ: 75.63,
            maxZ: 77.63,
            heading: 350,
            data: {
                storage: 'lspd_ammo',
                type: InventoryType.Ammo,
            },
        },
        {
            center: [616.57, -7.69, 90.51],
            length: 2.0,
            width: 2.8,
            minZ: 89.51,
            maxZ: 91.51,
            heading: 158.27,
            data: {
                storage: 'lspd_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [615.95, -15.24, 90.5],
            length: 2.5,
            width: 6.5,
            minZ: 89.5,
            maxZ: 91.5,
            heading: 160,
            data: {
                storage: 'lspd_evidence_storage',
                type: InventoryType.EvidenceStorage,
            },
        },
        {
            center: [618.06, -9.32, 76.63],
            length: 7.8,
            width: 1.0,
            minZ: 75.63,
            maxZ: 77.63,
            heading: 80,
            data: {
                storage: 'lspd_seizure1',
                type: InventoryType.Seizure,
            },
        },
        {
            center: [618.29, -12.1, 76.63],
            length: 1.0,
            width: 6.2,
            minZ: 75.63,
            maxZ: 77.63,
            heading: -10,
            data: {
                storage: 'lspd_seizure2',
                type: InventoryType.Seizure,
            },
        },
        {
            center: [617.14, -15.0, 76.63],
            length: 7.6,
            width: 1.75,
            minZ: 75.63,
            maxZ: 77.63,
            heading: 260,
            data: {
                storage: 'lspd_seizure3',
                type: InventoryType.Seizure,
            },
        },
        {
            center: [599.230713, -10.196113, 81.767494],
            length: 1.5,
            width: 1.5,
            minZ: 80.767494,
            maxZ: 82.767494,
            heading: 160.0,
            data: {
                storage: 'lspd_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [609.05, -15.12, 76.81],
            length: 2.0,
            width: 2.5,
            minZ: 75.81,
            maxZ: 77.81,
            heading: 170.0,
            data: {
                storage: 'lspd_armory',
                type: InventoryType.Armory,
            },
        },
        {
            center: [626.93, 2.18, 76.63],
            length: 7.0,
            width: 8.4,
            minZ: 75.62,
            maxZ: 78.62,
            heading: 350,
            data: {
                storage: 'lspd_male_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [624.58, -5.48, 76.63],
            length: 6.8,
            width: 6.4,
            minZ: 75.62,
            maxZ: 78.62,
            heading: 350,
            data: {
                storage: 'lspd_female_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.MDR]: [
        {
            center: [-540.74, -201.78, 47.66],
            length: 1.0,
            width: 2.0,
            minZ: 46.66,
            maxZ: 48.66,
            heading: 30,
            data: {
                storage: 'mdr_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [-561.21, -210.28, 38.17],
            length: 2.35,
            width: 1.0,
            minZ: 37.17,
            maxZ: 39.17,
            heading: 30,
            data: {
                storage: 'mdr_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [-569.05, -196.28, 47.66],
            length: 1.1,
            width: 1.1,
            minZ: 46.66,
            maxZ: 48.66,
            heading: 30.0,
            data: {
                storage: 'mdr_fridge1',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-570.33, -194.09, 47.66],
            length: 1.1,
            width: 1.1,
            minZ: 46.66,
            maxZ: 48.66,
            heading: 30.0,
            data: {
                storage: 'mdr_fridge2',
                type: InventoryType.Fridge,
            },
        },
    ],
    [JobType.Bennys]: [
        {
            center: [1904.47, 3089.13, 46.93],
            length: 1.0,
            width: 1.0,
            minZ: 45.93,
            maxZ: 46.932,
            heading: 331.0,
            data: {
                storage: 'bennys_cloakroom_north',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [-224.16, -1318.89, 30.63],
            length: 1.5,
            width: 3.0,
            minZ: 29.63,
            maxZ: 31.63,
            heading: 0,
            data: {
                storage: 'bennys_stash',
                type: InventoryType.Stash,
            },
        },
        {
            center: [1901.15, 3071.08, 46.92],
            length: 1.8,
            width: 0.8,
            minZ: 45.92,
            maxZ: 47.92,
            heading: 0,
            data: {
                storage: 'bennys_stash_north',
                type: InventoryType.Stash,
            },
        },
        {
            center: [-196.99, -1314.76, 31.09],
            length: 1.5,
            width: 3.0,
            minZ: 30.09,
            maxZ: 32.09,
            heading: 0,
            data: {
                storage: 'bennys_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [1908.63, 3092.91, 46.93],
            length: 1.2,
            width: 1.6,
            minZ: 45.93,
            maxZ: 47.93,
            heading: 0,
            data: {
                storage: 'bennys_boss_storage_north',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [-204.2, -1340.54, 34.89],
            length: 2.0,
            width: 2.0,
            minZ: 33.89,
            maxZ: 35.89,
            heading: 0,
            data: {
                storage: 'bennys_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [1916.05, 3085.72, 51.75],
            length: 2.4,
            width: 3.2,
            minZ: 50.75,
            maxZ: 52.75,
            heading: 0,
            data: {
                storage: 'bennys_fridge_north',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-204.44, -1330.74, 34.89],
            length: 3.0,
            width: 2.8,
            minZ: 33.89,
            maxZ: 37.89,
            heading: 0,
            data: {
                storage: 'bennys_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.News]: [
        {
            center: [-562.0, -937.72, 32.32],
            length: 0.6,
            width: 1.5,
            minZ: 31.32,
            maxZ: 33.32,
            heading: 270.0,
            data: {
                storage: 'news_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-556.57, -915.31, 33.22],
            length: 5.0,
            width: 0.5,
            minZ: 32.22,
            maxZ: 34.22,
            heading: 0,
            data: {
                storage: 'news_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [-572.0, -939.91, 28.82],
            length: 1.0,
            width: 2.5,
            minZ: 27.82,
            maxZ: 29.82,
            heading: 0,
            data: {
                storage: 'news_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [-568.22, -935.54, 33.76],
            length: 0.65,
            width: 3.75,
            minZ: 32.76,
            maxZ: 35.76,
            heading: 90,
            data: {
                storage: 'news_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.Oil]: [
        {
            center: [-240.68, 6076.91, 40.57],
            length: 1.1,
            width: 1.0,
            minZ: 39.57,
            maxZ: 41.57,
            heading: 315,
            data: {
                storage: 'oil_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-247.7, 6066.21, 40.57],
            length: 0.6,
            width: 2.45,
            minZ: 39.57,
            maxZ: 41.57,
            heading: 315,
            data: {
                storage: 'oil_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [-235.35, 6075.13, 40.57],
            length: 0.6,
            width: 3.05,
            minZ: 39.57,
            maxZ: 41.57,
            heading: 45,
            data: {
                storage: 'oil_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [-283.67, 6054.67, 31.35],
            length: 17.2,
            width: 4.4,
            minZ: 30.35,
            maxZ: 33.35,
            heading: 225,
            data: {
                storage: 'oil_tank_1',
                type: InventoryType.StorageTank,
            },
        },
        {
            center: [-289.25, 6048.79, 31.35],
            length: 17.2,
            width: 4.8,
            minZ: 30.35,
            maxZ: 33.35,
            heading: 225,
            data: {
                storage: 'oil_tank_2',
                type: InventoryType.StorageTank,
            },
        },
        {
            center: [-236.93, 6085.69, 31.39],
            length: 6.4,
            width: 4.2,
            minZ: 30.39,
            maxZ: 33.39,
            heading: 315,
            data: {
                storage: 'oil_male_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [-233.61, 6082.43, 31.39],
            length: 6.4,
            width: 4.2,
            minZ: 30.39,
            maxZ: 33.39,
            heading: 315,
            data: {
                storage: 'oil_female_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.Pawl]: [
        {
            center: [-532.21, 5308.37, 76.37],
            length: 0.6,
            width: 7.2,
            minZ: 75.37,
            maxZ: 78.37,
            heading: 250,
            data: {
                storage: 'pawl_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [-545.98, 5299.32, 76.37],
            length: 1.6,
            width: 1.0,
            minZ: 75.37,
            maxZ: 78.37,
            heading: 340,
            data: {
                storage: 'pawl_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-541.46, 5311.12, 76.37],
            length: 0.8,
            width: 2.85,
            minZ: 75.37,
            maxZ: 78.37,
            heading: 70,
            data: {
                storage: 'pawl_armory',
                type: InventoryType.Armory,
            },
        },
        {
            center: [-537.1, 5304.83, 76.37],
            length: 1,
            width: 1.2,
            minZ: 75.37,
            maxZ: 78.37,
            heading: 340,
            data: {
                storage: 'pawl_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [-537.49, 5387.45, 70.54],
            length: 16.6,
            width: 12.0,
            minZ: 69.54,
            maxZ: 73.54,
            heading: 337,
            data: {
                storage: 'pawl_log_storage',
                type: InventoryType.LogStorage,
            },
        },
        {
            center: [-500.79, 5269.62, 80.61],
            length: 35.0,
            width: 6.2,
            minZ: 79.61,
            maxZ: 81.61,
            heading: 340,
            data: {
                storage: 'pawl_plank_storage',
                type: InventoryType.PlankStorage,
            },
        },
        {
            center: [-574.83, 5284.21, 70.27],
            length: 23.0,
            width: 11.2,
            minZ: 69.27,
            maxZ: 71.27,
            heading: 332,
            data: {
                storage: 'pawl_sawdust_storage',
                type: InventoryType.SawdustStorage,
            },
        },
        {
            center: [-582.54, 5352.34, 70.21],
            length: 14.8,
            width: 33.6,
            minZ: 69.21,
            maxZ: 73.21,
            heading: 70,
            data: {
                storage: 'pawl_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [-551.98, 5348.3, 74.74],
            length: 0.35,
            width: 1.4,
            minZ: 73.74,
            maxZ: 75.74,
            heading: 72,
            data: {
                storage: 'pawl_log_processing',
                type: InventoryType.LogProcessing,
            },
        },
    ],
    [JobType.SASP]: [
        {
            center: [-572.34, -592.5, 34.68],
            length: 0.8,
            width: 0.8,
            minZ: 33.68,
            maxZ: 35.68,
            heading: 0,
            data: {
                storage: 'sasp_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-572.87, -608.43, 34.68],
            length: 0.6,
            width: 2.4,
            minZ: 33.68,
            maxZ: 35.68,
            heading: 180.0,
            data: {
                storage: 'sasp_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [-580.18, -590.11, 34.68],
            length: 0.4,
            width: 2.4,
            minZ: 33.68,
            maxZ: 35.68,
            heading: 270,
            data: {
                storage: 'sasp_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [-580.25, -609.74, 34.68],
            length: 0.4,
            width: 3.0,
            minZ: 33.68,
            maxZ: 35.68,
            heading: 270.0,
            data: {
                storage: 'sasp_armory',
                type: InventoryType.Armory,
            },
        },
        {
            center: [-579.57, -607.16, 34.68],
            length: 1.2,
            width: 0.6,
            minZ: 33.68,
            maxZ: 35.68,
            heading: 0.0,
            data: {
                storage: 'sasp_ammo',
                type: InventoryType.Ammo,
            },
        },
        {
            center: [-577.76, -582.41, 34.68],
            length: 0.6,
            width: 3.2,
            minZ: 33.68,
            maxZ: 35.68,
            heading: 180,
            data: {
                storage: 'sasp_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.Taxi]: [
        {
            center: [889.1, -178.53, 74.7],
            length: 0.4,
            width: 6.8,
            minZ: 73.75,
            maxZ: 75.75,
            heading: 330,
            data: {
                storage: 'taxi_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [891.46, -173.37, 74.7],
            length: 1.4,
            width: 0.8,
            minZ: 73.7,
            maxZ: 75.7,
            heading: 328,
            data: {
                storage: 'taxi_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [899.6, -169.36, 74.17],
            length: 0.6,
            width: 6.0,
            minZ: 73.17,
            maxZ: 75.17,
            heading: 238,
            data: {
                storage: 'taxi_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [910.45, -152.13, 74.17],
            length: 0.2,
            width: 2.6,
            minZ: 73.17,
            maxZ: 75.17,
            heading: 328,
            data: {
                storage: 'taxi_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
    ],
    [JobType.Upw]: [
        {
            center: [592.62, 2770.33, 41.86],
            length: 1.0,
            width: 1.0,
            minZ: 40.86,
            maxZ: 42.86,
            heading: 274,
            data: {
                storage: 'upw_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [599.6, 2757.35, 41.86],
            length: 2.4,
            width: 0.4,
            minZ: 40.86,
            maxZ: 42.86,
            heading: 4,
            data: {
                storage: 'upw_stash',
                type: InventoryType.Stash,
            },
        },
        {
            center: [600.66, 2760.11, 47.76],
            length: 0.6,
            width: 2.55,
            minZ: 46.76,
            maxZ: 48.76,
            heading: 4,
            data: {
                storage: 'upw_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [585.13, 2747.34, 41.86],
            length: 1.2,
            width: 4.4,
            minZ: 40.86,
            maxZ: 43.86,
            heading: 4,
            data: {
                storage: 'upw_cloakroom_1',
                type: InventoryType.Cloakroom,
            },
        },
        {
            center: [577.8, 2747.03, 41.86],
            length: 1.0,
            width: 5.0,
            minZ: 40.86,
            maxZ: 43.86,
            heading: 4,
            data: {
                storage: 'upw_cloakroom_2',
                type: InventoryType.Cloakroom,
            },
        },
    ],
    [JobType.YouNews]: [
        {
            center: [-1066.73, -240.5, 39.73],
            length: 1.4,
            width: 2.2,
            minZ: 38.73,
            maxZ: 40.73,
            heading: 207.15,
            data: {
                storage: 'you_news_fridge',
                type: InventoryType.Fridge,
            },
        },
        {
            center: [-1046.41, -241.9, 37.96],
            length: 1.2,
            width: 6.0,
            minZ: 36.96,
            maxZ: 38.96,
            heading: 207.26,
            data: {
                storage: 'you_news_storage',
                type: InventoryType.Stash,
            },
        },
        {
            center: [-1051.65, -233.71, 44.02],
            length: 1.0,
            width: 3.0,
            minZ: 43.02,
            maxZ: 45.02,
            heading: 209.16,
            data: {
                storage: 'you_news_boss_storage',
                type: InventoryType.BossStorage,
            },
        },
        {
            center: [-1040.75, -233.07, 37.96],
            length: 1.0,
            width: 1.0,
            minZ: 36.96,
            maxZ: 38.96,
            heading: 293.44,
            data: {
                storage: 'you_news_cloakroom',
                type: InventoryType.Cloakroom,
            },
        },
    ],
};
