Config = {}

Config.AttachedVehicle = nil

Config.Locations = {
    ["bennys"] = vector3(-211.91, -1323.98, 30.89),
    ["vehicle"] = vector4(-162.15, -1302.58, 31.32, 85.0),
    ["cass"] = vector3(2405.98, 3127.11, 48.17),
}

Config.ValuesLabels = {["engine"] = "Moteur", ["body"] = "Carrosserie", ["fuel"] = "Réservoir"}

Config.vehicleResprayCategories = {
    {category = "Couleur Principale", id = 0},
    {category = "Couleur Secondaire", id = 1},
    {category = "Couleur Nacré", id = 2},
    {category = "Couleur des Roues", id = 3},
    {category = "Couleur du Tableau de bord", id = 4},
    {category = "Couleur Intérieure", id = 5},
}

Config.vehicleWindowTintOptions = {
    {name = "Aucun", id = 0},
    {name = "Noir pure", id = 1},
    {name = "Fumé foncé", id = 2},
    {name = "Fumé léger", id = 3},
}

Config.vehicleXenonOptions = {
    xenonColours = {
        {name = "Stock", id = 255},
        {name = "Blanc", id = 0},
        {name = "Bleu", id = 1},
        {name = "Bleu électrique", id = 2},
        {name = "Vert menthe", id = 3},
        {name = "Citron vert", id = 4},
        {name = "Jaune", id = 5},
        {name = "Douche dorée", id = 6},
        {name = "Orange", id = 7},
        {name = "Rouge", id = 8},
        {name = "Rose poney", id = 9},
        {name = "Rose chaud", id = 10},
        {name = "Violet", id = 11},
        {name = "Noir léger", id = 12},
    },
}

Config.vehicleWheelOptions = {
    {category = "Roues personalisées", id = -1, wheelID = 23},
    {category = "Fumée de roues", id = 20, wheelID = 23},
    {category = "Sport", id = 0, wheelID = 23},
    {category = "Muscle", id = 1, wheelID = 23},
    {category = "Lowrider", id = 2, wheelID = 23},
    {category = "SUV", id = 3, wheelID = 23},
    {category = "Offroad", id = 4, wheelID = 23},
    {category = "Tuner", id = 5, wheelID = 23},
    {category = "Motorcycle", id = 6, wheelID = 23},
    {category = "Highend", id = 7, wheelID = 23},
}

Config.vehicleTyreSmokeOptions = {
    {name = "Fumée blanche", r = 254, g = 254, b = 254},
    {name = "Fumée noire", r = 1, g = 1, b = 1},
    {name = "Fumée bleue", r = 0, g = 150, b = 255},
    {name = "Fumée jaune", r = 255, g = 255, b = 50},
    {name = "Fumée orange", r = 255, g = 153, b = 51},
    {name = "Fumée rouge", r = 255, g = 10, b = 10},
    {name = "Fumée verte", r = 10, g = 255, b = 10},
    {name = "Fumée violette", r = 153, g = 10, b = 153},
    {name = "Fumée rose", r = 255, g = 102, b = 178},
    {name = "Fumée grise", r = 128, g = 128, b = 128},
}

Config.vehicleNeonOptions = {
    category = "Néons",
    neonTypes = {
        {name = "Néon avant", id = 2},
        {name = "Néon arrière", id = 3},
        {name = "Néon gauche", id = 0},
        {name = "Néon droit", id = 1},
    },
    neonColours = {
        {name = "Blanc", r = 222, g = 222, b = 255},
        {name = "Bleu", r = 2, g = 21, b = 255},
        {name = "Bleu électrique", r = 3, g = 83, b = 255},
        {name = "Vert menthe", r = 0, g = 255, b = 140},
        {name = "Citron vert", r = 94, g = 255, b = 1},
        {name = "Jaune", r = 255, g = 255, b = 0},
        {name = "Douche dorée", r = 255, g = 150, b = 0},
        {name = "Orange", r = 255, g = 62, b = 0},
        {name = "Rouge", r = 255, g = 1, b = 1},
        {name = "Rose poney", r = 255, g = 50, b = 100},
        {name = "Rose chaud", r = 255, g = 5, b = 190},
        {name = "Violet", r = 35, g = 1, b = 255},
        {name = "Noir léger", r = 15, g = 3, b = 255},
    },
}

Config.vehicleCustomisationBannedMods = {
    "Unité de contrôle à distance",
    "Brouilleur de verr. (missile)",
    "Mitrailleuses",
}

Config.vehicleCustomisationMechanic = {
    {category = "Spoiler", id = 0},
    {category = "Pare-choc avant", id = 1},
    {category = "Pare-choc arrière", id = 2},
    {category = "Bas de caisse", id = 3},
    {category = "Pot d'échappement", id = 4},
    {category = "Cage de protection", id = 5},
    {category = "Grille", id = 6},
    {category = "Capot", id = 7},
    {category = "Aile gauche", id = 8},
    {category = "Aile droite", id = 9},
    {category = "Toit", id = 10},
    {category = "Style Immatriculation", id = 25},
    {category = "Finitions A", id = 27},
    {category = "Décorations", id = 28},
    {category = "Tableau de bord", id = 29},
    {category = "Compteur", id = 30},
    {category = "Enceintes de porte", id = 31},
    {category = "Sièges", id = 32},
    {category = "Volant", id = 33},
    {category = "Levier de vitesse", id = 34},
    {category = "Plaque", id = 35},
    {category = "Enceinte", id = 36},
    {category = "Coffre", id = 37},
    {category = "Hydraulique", id = 38},
    {category = "Bloc moteur", id = 39},
    {category = "Filtration air", id = 40},
    {category = "Entretoise", id = 41},
    {category = "Arch Cover", id = 42},
    {category = "Antenne", id = 43},
    {category = "Finitions B", id = 44},
    {category = "Réservoir", id = 45},
    {category = "Fenêtre", id = 46},
    {category = "Sticker", id = 48},
    {
        category = "Klaxon",
        id = 14,
        hornNames = {
            {name = "Camion", id = 0},
            {name = "Flic", id = 1},
            {name = "Clown", id = 2},
            {name = "Musique 1", id = 3},
            {name = "Musique 2", id = 4},
            {name = "Musique 3", id = 5},
            {name = "Musique 4", id = 6},
            {name = "Musique 5", id = 7},
            {name = "Trombone triste", id = 8},
            {name = "Classique 1", id = 9},
            {name = "Classique 2", id = 10},
            {name = "Classique 3", id = 11},
            {name = "Classique 4", id = 12},
            {name = "Classique 5", id = 13},
            {name = "Classique 6", id = 14},
            {name = "Classique 7", id = 15},
            {name = "Classique 8", id = 35},
            {name = "Classique 8 Loop", id = 32},
            {name = "Classique 9", id = 36},
            {name = "Classique 9 Loop", id = 33},
            {name = "Classique 10", id = 37},
            {name = "Classique 10 Loop", id = 34},
            {name = "Gamme - Do", id = 16},
            {name = "Gamme - Re", id = 17},
            {name = "Gamme - Mi", id = 18},
            {name = "Gamme - Fa", id = 19},
            {name = "Gamme - Sol", id = 20},
            {name = "Gamme - La", id = 21},
            {name = "Gamme - Ti", id = 22},
            {name = "Gamme - Do", id = 23},
            {name = "Jazz 1", id = 24},
            {name = "Jazz 2", id = 25},
            {name = "Jazz 3", id = 26},
            {name = "Jazz Loop", id = 27},
            {name = "Star Spangled Banner 1", id = 28},
            {name = "Star Spangled Banner 2", id = 29},
            {name = "Star Spangled Banner 3", id = 30},
            {name = "Star Spangled Banner 4", id = 31},
            {name = "Funéraire", id = 39},
            {name = "Funéraire Loop", id = 38},
            {name = "Effrayant", id = 41},
            {name = "Effrayant Loop", id = 40},
            {name = "San Andreas", id = 43},
            {name = "San Andreas Loop", id = 42},
            {name = "Liberty City Loop", id = 44},
            {name = "Liberty City", id = 45},
            {name = "Festif 1", id = 47},
            {name = "Festif 1 Loop", id = 46},
            {name = "Festif 2", id = 49},
            {name = "Festif 2 Loop", id = 48},
            {name = "Festif 3", id = 51},
            {name = "Festif 3 Loop", id = 50},
        },
    },
}

Config.vehicleResprayOptions = {
    {
        category = "Classique",
        id = 0,
        colours = {
            {name = "Black", id = 0},
            {name = "Carbon Black", id = 147},
            {name = "Graphite", id = 1},
            {name = "Anhracite Black", id = 11},
            {name = "Black Steel", id = 11},
            {name = "Dark Steel", id = 3},
            {name = "Silver", id = 4},
            {name = "Bluish Silver", id = 5},
            {name = "Rolled Steel", id = 6},
            {name = "Shadow Silver", id = 7},
            {name = "Stone Silver", id = 8},
            {name = "Midnight Silver", id = 9},
            {name = "Cast Iron Silver", id = 10},
            {name = "Red", id = 27},
            {name = "Torino Red", id = 28},
            {name = "Formula Red", id = 29},
            {name = "Lava Red", id = 150},
            {name = "Blaze Red", id = 30},
            {name = "Grace Red", id = 31},
            {name = "Garnet Red", id = 32},
            {name = "Sunset Red", id = 33},
            {name = "Cabernet Red", id = 34},
            {name = "Wine Red", id = 143},
            {name = "Candy Red", id = 35},
            {name = "Hot Pink", id = 135},
            {name = "Pfsiter Pink", id = 137},
            {name = "Salmon Pink", id = 136},
            {name = "Sunrise Orange", id = 36},
            {name = "Orange", id = 38},
            {name = "Bright Orange", id = 138},
            {name = "Gold", id = 99},
            {name = "Bronze", id = 90},
            {name = "Yellow", id = 88},
            {name = "Race Yellow", id = 89},
            {name = "Dew Yellow", id = 91},
            {name = "Dark Green", id = 49},
            {name = "Racing Green", id = 50},
            {name = "Sea Green", id = 51},
            {name = "Olive Green", id = 52},
            {name = "Bright Green", id = 53},
            {name = "Gasoline Green", id = 54},
            {name = "Lime Green", id = 92},
            {name = "Midnight Blue", id = 141},
            {name = "Galaxy Blue", id = 61},
            {name = "Dark Blue", id = 62},
            {name = "Saxon Blue", id = 63},
            {name = "Blue", id = 64},
            {name = "Mariner Blue", id = 65},
            {name = "Harbor Blue", id = 66},
            {name = "Diamond Blue", id = 67},
            {name = "Surf Blue", id = 68},
            {name = "Nautical Blue", id = 69},
            {name = "Racing Blue", id = 73},
            {name = "Ultra Blue", id = 70},
            {name = "Light Blue", id = 74},
            {name = "Chocolate Brown", id = 96},
            {name = "Bison Brown", id = 101},
            {name = "Creeen Brown", id = 95},
            {name = "Feltzer Brown", id = 94},
            {name = "Maple Brown", id = 97},
            {name = "Beechwood Brown", id = 103},
            {name = "Sienna Brown", id = 104},
            {name = "Saddle Brown", id = 98},
            {name = "Moss Brown", id = 100},
            {name = "Woodbeech Brown", id = 102},
            {name = "Straw Brown", id = 99},
            {name = "Sandy Brown", id = 105},
            {name = "Bleached Brown", id = 106},
            {name = "Schafter Purple", id = 71},
            {name = "Spinnaker Purple", id = 72},
            {name = "Midnight Purple", id = 142},
            {name = "Bright Purple", id = 145},
            {name = "Cream", id = 107},
            {name = "Ice White", id = 111},
            {name = "Frost White", id = 112},
        },
    },
    {
        category = "Metallic",
        id = 1,
        colours = {
            {name = "Black", id = 0},
            {name = "Carbon Black", id = 147},
            {name = "Graphite", id = 1},
            {name = "Anhracite Black", id = 11},
            {name = "Black Steel", id = 11},
            {name = "Dark Steel", id = 3},
            {name = "Silver", id = 4},
            {name = "Bluish Silver", id = 5},
            {name = "Rolled Steel", id = 6},
            {name = "Shadow Silver", id = 7},
            {name = "Stone Silver", id = 8},
            {name = "Midnight Silver", id = 9},
            {name = "Cast Iron Silver", id = 10},
            {name = "Red", id = 27},
            {name = "Torino Red", id = 28},
            {name = "Formula Red", id = 29},
            {name = "Lava Red", id = 150},
            {name = "Blaze Red", id = 30},
            {name = "Grace Red", id = 31},
            {name = "Garnet Red", id = 32},
            {name = "Sunset Red", id = 33},
            {name = "Cabernet Red", id = 34},
            {name = "Wine Red", id = 143},
            {name = "Candy Red", id = 35},
            {name = "Hot Pink", id = 135},
            {name = "Pfsiter Pink", id = 137},
            {name = "Salmon Pink", id = 136},
            {name = "Sunrise Orange", id = 36},
            {name = "Orange", id = 38},
            {name = "Bright Orange", id = 138},
            {name = "Gold", id = 99},
            {name = "Bronze", id = 90},
            {name = "Yellow", id = 88},
            {name = "Race Yellow", id = 89},
            {name = "Dew Yellow", id = 91},
            {name = "Dark Green", id = 49},
            {name = "Racing Green", id = 50},
            {name = "Sea Green", id = 51},
            {name = "Olive Green", id = 52},
            {name = "Bright Green", id = 53},
            {name = "Gasoline Green", id = 54},
            {name = "Lime Green", id = 92},
            {name = "Midnight Blue", id = 141},
            {name = "Galaxy Blue", id = 61},
            {name = "Dark Blue", id = 62},
            {name = "Saxon Blue", id = 63},
            {name = "Blue", id = 64},
            {name = "Mariner Blue", id = 65},
            {name = "Harbor Blue", id = 66},
            {name = "Diamond Blue", id = 67},
            {name = "Surf Blue", id = 68},
            {name = "Nautical Blue", id = 69},
            {name = "Racing Blue", id = 73},
            {name = "Ultra Blue", id = 70},
            {name = "Light Blue", id = 74},
            {name = "Chocolate Brown", id = 96},
            {name = "Bison Brown", id = 101},
            {name = "Creeen Brown", id = 95},
            {name = "Feltzer Brown", id = 94},
            {name = "Maple Brown", id = 97},
            {name = "Beechwood Brown", id = 103},
            {name = "Sienna Brown", id = 104},
            {name = "Saddle Brown", id = 98},
            {name = "Moss Brown", id = 100},
            {name = "Woodbeech Brown", id = 102},
            {name = "Straw Brown", id = 99},
            {name = "Sandy Brown", id = 105},
            {name = "Bleached Brown", id = 106},
            {name = "Schafter Purple", id = 71},
            {name = "Spinnaker Purple", id = 72},
            {name = "Midnight Purple", id = 142},
            {name = "Bright Purple", id = 145},
            {name = "Cream", id = 107},
            {name = "Ice White", id = 111},
            {name = "Frost White", id = 112},
        },
    },
    {
        category = "Matte",
        id = 2,
        colours = {
            {name = "Black", id = 12},
            {name = "Gray", id = 13},
            {name = "Light Gray", id = 14},
            {name = "Ice White", id = 131},
            {name = "Blue", id = 83},
            {name = "Dark Blue", id = 82},
            {name = "Midnight Blue", id = 84},
            {name = "Midnight Purple", id = 149},
            {name = "Schafter Purple", id = 148},
            {name = "Red", id = 39},
            {name = "Dark Red", id = 40},
            {name = "Orange", id = 41},
            {name = "Yellow", id = 42},
            {name = "Lime Green", id = 55},
            {name = "Green", id = 128},
            {name = "Forest Green", id = 151},
            {name = "Foliage Green", id = 155},
            {name = "Olive Darb", id = 152},
            {name = "Dark Earth", id = 153},
            {name = "Desert Tan", id = 154},
        },
    },
    {
        category = "Metals",
        id = 3,
        colours = {
            {name = "Brushed Steel", id = 117},
            {name = "Brushed Black Steel", id = 118},
            {name = "Brushed Aluminium", id = 119},
            {name = "Pure Gold", id = 158},
            {name = "Brushed Gold", id = 159},
            {name = "Chrome", id = 120},
        },
    },
}

Config.Cloakroom = {
    ["Patron"] = {
        [GetHashKey("mp_m_freemode_01")] = {
            ["Tenue de service"] = {
                Components = {
                    [1] = {Drawable = 0, Texture = 0, Palette = 0},
                    [3] = {Drawable = 0, Texture = 0, Palette = 0},
                    [4] = {Drawable = 98, Texture = 17, Palette = 0},
                    [6] = {Drawable = 46, Texture = 3, Palette = 0},
                    [7] = {Drawable = 0, Texture = 0, Palette = 0},
                    [8] = {Drawable = 15, Texture = 0, Palette = 0},
                    [9] = {Drawable = 0, Texture = 0, Palette = 0},
                    [10] = {Drawable = 0, Texture = 0, Palette = 0},
                    [11] = {Drawable = 351, Texture = 9, Palette = 0},
                },
                Props = {},
            },
        },
        [GetHashKey("mp_f_freemode_01")] = {
            ["Tenue de service"] = {
                Components = {
                    [1] = {Drawable = 0, Texture = 0, Palette = 0},
                    [3] = {Drawable = 14, Texture = 0, Palette = 0},
                    [4] = {Drawable = 101, Texture = 17, Palette = 0},
                    [6] = {Drawable = 47, Texture = 3, Palette = 0},
                    [7] = {Drawable = 0, Texture = 0, Palette = 0},
                    [8] = {Drawable = 2, Texture = 0, Palette = 0},
                    [9] = {Drawable = 0, Texture = 0, Palette = 0},
                    [10] = {Drawable = 0, Texture = 0, Palette = 0},
                    [11] = {Drawable = 377, Texture = 5, Palette = 0},
                },
                Props = {},
            },
        },
    },
    ["Chef d'atelier"] = {
        [GetHashKey("mp_m_freemode_01")] = {
            ["Tenue de service"] = {
                Components = {
                    [1] = {Drawable = 0, Texture = 0, Palette = 0},
                    [3] = {Drawable = 19, Texture = 0, Palette = 0},
                    [4] = {Drawable = 98, Texture = 2, Palette = 0},
                    [6] = {Drawable = 46, Texture = 3, Palette = 0},
                    [7] = {Drawable = 0, Texture = 0, Palette = 0},
                    [8] = {Drawable = 15, Texture = 0, Palette = 0},
                    [9] = {Drawable = 0, Texture = 0, Palette = 0},
                    [10] = {Drawable = 0, Texture = 0, Palette = 0},
                    [11] = {Drawable = 146, Texture = 2, Palette = 0},
                },
                Props = {},
            },
        },
        [GetHashKey("mp_f_freemode_01")] = {
            ["Tenue de service"] = {
                Components = {
                    [1] = {Drawable = 0, Texture = 0, Palette = 0},
                    [3] = {Drawable = 14, Texture = 0, Palette = 0},
                    [4] = {Drawable = 101, Texture = 2, Palette = 0},
                    [6] = {Drawable = 47, Texture = 3, Palette = 0},
                    [7] = {Drawable = 0, Texture = 0, Palette = 0},
                    [8] = {Drawable = 3, Texture = 0, Palette = 0},
                    [9] = {Drawable = 0, Texture = 0, Palette = 0},
                    [10] = {Drawable = 0, Texture = 0, Palette = 0},
                    [11] = {Drawable = 338, Texture = 7, Palette = 0},
                },
                Props = {},
            },
        },
    },
    ["Mécano confirmé"] = {
        [GetHashKey("mp_m_freemode_01")] = {
            ["Tenue de service"] = {
                Components = {
                    [1] = {Drawable = 0, Texture = 0, Palette = 0},
                    [3] = {Drawable = 19, Texture = 0, Palette = 0},
                    [4] = {Drawable = 98, Texture = 4, Palette = 0},
                    [6] = {Drawable = 46, Texture = 3, Palette = 0},
                    [7] = {Drawable = 0, Texture = 0, Palette = 0},
                    [8] = {Drawable = 15, Texture = 0, Palette = 0},
                    [9] = {Drawable = 0, Texture = 0, Palette = 0},
                    [10] = {Drawable = 0, Texture = 0, Palette = 0},
                    [11] = {Drawable = 0, Texture = 3, Palette = 0},
                },
                Props = {},
            },
        },
        [GetHashKey("mp_f_freemode_01")] = {
            ["Tenue de service"] = {
                Components = {
                    [1] = {Drawable = 0, Texture = 0, Palette = 0},
                    [3] = {Drawable = 14, Texture = 0, Palette = 0},
                    [4] = {Drawable = 101, Texture = 4, Palette = 0},
                    [6] = {Drawable = 47, Texture = 3, Palette = 0},
                    [7] = {Drawable = 0, Texture = 0, Palette = 0},
                    [8] = {Drawable = 3, Texture = 0, Palette = 0},
                    [9] = {Drawable = 0, Texture = 0, Palette = 0},
                    [10] = {Drawable = 0, Texture = 0, Palette = 0},
                    [11] = {Drawable = 338, Texture = 5, Palette = 0},
                },
                Props = {},
            },
        },
    },
    ["Mécano"] = {
        [GetHashKey("mp_m_freemode_01")] = {
            ["Tenue de service"] = {
                Components = {
                    [1] = {Drawable = 0, Texture = 0, Palette = 0},
                    [3] = {Drawable = 19, Texture = 0, Palette = 0},
                    [4] = {Drawable = 98, Texture = 3, Palette = 0},
                    [6] = {Drawable = 46, Texture = 3, Palette = 0},
                    [7] = {Drawable = 0, Texture = 0, Palette = 0},
                    [8] = {Drawable = 15, Texture = 0, Palette = 0},
                    [9] = {Drawable = 0, Texture = 0, Palette = 0},
                    [10] = {Drawable = 0, Texture = 0, Palette = 0},
                    [11] = {Drawable = 0, Texture = 2, Palette = 0},
                },
                Props = {},
            },
        },
        [GetHashKey("mp_f_freemode_01")] = {
            ["Tenue de service"] = {
                Components = {
                    [1] = {Drawable = 0, Texture = 0, Palette = 0},
                    [3] = {Drawable = 14, Texture = 0, Palette = 0},
                    [4] = {Drawable = 101, Texture = 3, Palette = 0},
                    [6] = {Drawable = 47, Texture = 3, Palette = 0},
                    [7] = {Drawable = 0, Texture = 0, Palette = 0},
                    [8] = {Drawable = 3, Texture = 0, Palette = 0},
                    [9] = {Drawable = 0, Texture = 0, Palette = 0},
                    [10] = {Drawable = 0, Texture = 0, Palette = 0},
                    [11] = {Drawable = 338, Texture = 1, Palette = 0},
                },
                Props = {},
            },
        },
    },
    ["Mécano novice"] = {
        [GetHashKey("mp_m_freemode_01")] = {
            ["Tenue de service"] = {
                Components = {
                    [1] = {Drawable = 0, Texture = 0, Palette = 0},
                    [3] = {Drawable = 0, Texture = 0, Palette = 0},
                    [4] = {Drawable = 98, Texture = 3, Palette = 0},
                    [6] = {Drawable = 89, Texture = 0, Palette = 0},
                    [7] = {Drawable = 0, Texture = 0, Palette = 0},
                    [8] = {Drawable = 15, Texture = 0, Palette = 0},
                    [9] = {Drawable = 0, Texture = 0, Palette = 0},
                    [10] = {Drawable = 0, Texture = 0, Palette = 0},
                    [11] = {Drawable = 212, Texture = 18, Palette = 0},
                },
                Props = {},
            },
        },
        [GetHashKey("mp_f_freemode_01")] = {
            ["Tenue de service"] = {
                Components = {
                    [1] = {Drawable = 0, Texture = 0, Palette = 0},
                    [3] = {Drawable = 14, Texture = 0, Palette = 0},
                    [4] = {Drawable = 101, Texture = 3, Palette = 0},
                    [6] = {Drawable = 47, Texture = 1, Palette = 0},
                    [7] = {Drawable = 0, Texture = 0, Palette = 0},
                    [8] = {Drawable = 15, Texture = 0, Palette = 0},
                    [9] = {Drawable = 0, Texture = 0, Palette = 0},
                    [10] = {Drawable = 0, Texture = 0, Palette = 0},
                    [11] = {Drawable = 212, Texture = 18, Palette = 0},
                },
                Props = {},
            },
        },
    },
    ["Apprenti"] = {
        [GetHashKey("mp_m_freemode_01")] = {
            ["Tenue de service"] = {
                Components = {
                    [1] = {Drawable = 0, Texture = 0, Palette = 0},
                    [3] = {Drawable = 4, Texture = 0, Palette = 0},
                    [4] = {Drawable = 39, Texture = 1, Palette = 0},
                    [6] = {Drawable = 46, Texture = 3, Palette = 0},
                    [7] = {Drawable = 0, Texture = 0, Palette = 0},
                    [8] = {Drawable = 15, Texture = 0, Palette = 0},
                    [9] = {Drawable = 0, Texture = 0, Palette = 0},
                    [10] = {Drawable = 0, Texture = 0, Palette = 0},
                    [11] = {Drawable = 66, Texture = 1, Palette = 0},
                },
                Props = {},
            },
        },
        [GetHashKey("mp_f_freemode_01")] = {
            ["Tenue de service"] = {
                Components = {
                    [1] = {Drawable = 0, Texture = 0, Palette = 0},
                    [3] = {Drawable = 3, Texture = 0, Palette = 0},
                    [4] = {Drawable = 39, Texture = 1, Palette = 0},
                    [6] = {Drawable = 47, Texture = 3, Palette = 0},
                    [7] = {Drawable = 0, Texture = 0, Palette = 0},
                    [8] = {Drawable = 3, Texture = 0, Palette = 0},
                    [9] = {Drawable = 0, Texture = 0, Palette = 0},
                    [10] = {Drawable = 0, Texture = 0, Palette = 0},
                    [11] = {Drawable = 60, Texture = 1, Palette = 0},
                },
                Props = {},
            },
        },
    },
}

Config.BossShop = {
    [1] = {name = "repairkit", metadata = {}, price = 50, amount = 1},
    [2] = {name = "cleaningkit", metadata = {}, price = 20, amount = 1},
    [3] = {name = "diagnostic_pad", metadata = {}, price = 260, amount = 1},
    [4] = {name = "oil_jerrycan", metadata = {}, price = 20, amount = 1},
}

Config.DisableRoofModificationOnVehicles = {"savestra", "comet4", "jb7002", "revolter", "viseris"}

Config.DisableArmoringModificationOnVehicles = {"buffalo4", "champion", "deity", "granger2", "jubilee"}
