import { JobType } from '../shared/job';

export const SocietyNumberList: Record<JobType, string> = {
    [JobType.FBI]: '555-FBI',
    [JobType.LSPD]: '555-LSPD',
    [JobType.LSMC]: '555-LSMC',
    [JobType.BCSO]: '555-BCSO',
    [JobType.News]: '555-NEWS',
    [JobType.YouNews]: '555-YOUN',
    [JobType.Garbage]: '555-BLUEBIRD',
    [JobType.Taxi]: '555-CARLJR',
    [JobType.Food]: '555-MARIUS',
    [JobType.Oil]: '555-MTP',
    [JobType.CashTransfer]: '555-STONK',
    [JobType.Bennys]: '555-NEWGAHRAY',
    [JobType.Upw]: '555-UPW',
    [JobType.Pawl]: '555-PAWL',
    [JobType.Baun]: '555-BAUN',
    [JobType.Ffs]: '555-FFS',
    [JobType.MDR]: '555-MDR',
    [JobType.SASP]: '555-SASP',
    [JobType.FDF]: '555-FDF',
    [JobType.Gouv]: '555-GOUV',
    [JobType.DMC]: '555-DMC',
    [JobType.LSCS]: '555-LSCS',
    [JobType.Casino]: '555-DIAMOND',
    [JobType.Unemployed]: '',
    [JobType.Adsl]: '',
    [JobType.Delivery]: '',
    [JobType.Religious]: '',
    [JobType.Scrapper]: '',
};
