export const RadarAllowedVehicle: number[] = [
    //LSMC
    GetHashKey('ambulance'),
    GetHashKey('ambulance2'),
    GetHashKey('ambcar'),
    GetHashKey('lguard'),
    GetHashKey('seashark2'),
    GetHashKey('blazer2'),
    GetHashKey('firetruk'),
    // LSPD
    GetHashKey('police'),
    GetHashKey('police2'),
    GetHashKey('police3'),
    GetHashKey('police4'),
    GetHashKey('police5'),
    GetHashKey('policeb'),
    GetHashKey('lspd10'),
    GetHashKey('lspd11'),
    GetHashKey('lspd12'),
    GetHashKey('lspd20'),
    GetHashKey('lspd21'),
    GetHashKey('lspd30'),
    GetHashKey('lspd40'),
    GetHashKey('lspd41'),
    GetHashKey('lspd50'),
    GetHashKey('lspd51'),
    // BCSO
    GetHashKey('sheriff'),
    GetHashKey('sheriff2'),
    GetHashKey('sheriff3'),
    GetHashKey('sheriff4'),
    GetHashKey('sheriffb'),
    GetHashKey('bcso10'),
    GetHashKey('bcso11'),
    GetHashKey('bcso12'),
    GetHashKey('bcso20'),
    GetHashKey('bcso21'),
    GetHashKey('bcso30'),
    GetHashKey('bcso40'),
    GetHashKey('bcso41'),
    GetHashKey('bcso50'),
    GetHashKey('bcso51'),
    // LSPD / BCSO
    GetHashKey('pbus'),
    //SASP
    GetHashKey('sasp1'),
    // FBI
    GetHashKey('fbi'),
    GetHashKey('fbi2'),
    GetHashKey('cogfbi'),
    GetHashKey('paragonfbi'),
    GetHashKey('paragonsfbi'),
    GetHashKey('dodgebana'),
    GetHashKey('polgauntlet'),
    // Gouv
    GetHashKey('xls2'),
    GetHashKey('schafter6'),
    // policeold
    GetHashKey('policeold1'),
    GetHashKey('policeold2'),
];

export const RadarInformedVehicle: number[] = [
    GetHashKey('police'),
    GetHashKey('police2'),
    GetHashKey('police3'),
    GetHashKey('police4'),
    GetHashKey('police5'),
    GetHashKey('policeb'),
    GetHashKey('lspd10'),
    GetHashKey('lspd11'),
    GetHashKey('lspd12'),
    GetHashKey('lspd20'),
    GetHashKey('lspd21'),
    GetHashKey('lspd30'),
    GetHashKey('lspd40'),
    GetHashKey('lspd41'),
    GetHashKey('lspd50'),
    GetHashKey('lspd51'),
    // BCSO
    GetHashKey('sheriff'),
    GetHashKey('sheriff2'),
    GetHashKey('sheriff3'),
    GetHashKey('sheriff4'),
    GetHashKey('sheriffb'),
    GetHashKey('bcso10'),
    GetHashKey('bcso11'),
    GetHashKey('bcso12'),
    GetHashKey('bcso20'),
    GetHashKey('bcso21'),
    GetHashKey('bcso30'),
    GetHashKey('bcso40'),
    GetHashKey('bcso41'),
    GetHashKey('bcso50'),
    GetHashKey('bcso51'),
    // Both
    GetHashKey('predator'),
    //SASP
    GetHashKey('sasp1'),
    // policeold
    GetHashKey('policeold1'),
    GetHashKey('policeold2'),
];
