-- CreateTable
CREATE TABLE `loot_item` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type` VARCHAR(100) NOT NULL,
    `item` VARCHAR(100) NOT NULL,
    `metadata` TEXT,
    `max` INTEGER NOT NULL,
    `chance` INTEGER NOT NULL,

    INDEX `loot_item_type_idx`(`type`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `loot_item` (`id`, `type`, `item`, `metadata`, `max`, `chance`) VALUES
	(1, 'smuggling_container_tier1', 'weapon_knife', NULL, 10, 10),
	(2, 'smuggling_container_tier1', 'zip', NULL, 100, 10),
	(3, 'smuggling_container_tier1', 'lockpick_low', NULL, 100, 10),
	(4, 'smuggling_container_tier1', 'parking_ticket_fake', NULL, 100, 10),
	(5, 'smuggling_container_tier1', 'cigarette_pack', NULL, 100, 10),
	(6, 'smuggling_container_tier1', 'clothing_job_low', NULL, 100, 10),
	(7, 'smuggling_container_tier1', 'antistress_diy', NULL, 100, 10),
	(8, 'smuggling_container_tier1', 'ammo_01', NULL, 100, 10),
	(9, 'smuggling_container_tier1', 'ammo_08', NULL, 100, 10),
	(10, 'smuggling_container_tier1', 'weapon_pistol', NULL, 10, 10),
	(11, 'smuggling_container_tier1', 'weapon_dbshotgun', NULL, 10, 10),
	(12, 'smuggling_container_tier2', 'bulletproof_vest_low', NULL, 50, 10),
	(13, 'smuggling_container_tier2', 'clothing_job_medium', NULL, 100, 10),
	(14, 'smuggling_container_tier2', 'paycrimi_card', NULL, 100, 10),
	(15, 'smuggling_container_tier2', 'lockpick_medium', NULL, 100, 10),
	(16, 'smuggling_container_tier2', 'mre_zera', NULL, 100, 10),
	(17, 'smuggling_container_tier2', 'mre_peach', NULL, 100, 10),
	(18, 'smuggling_container_tier2', 'essence_jerrycan_low', NULL, 100, 10),
	(19, 'smuggling_container_tier2', 'kerozene_jerrycan_low', NULL, 100, 10),
	(20, 'smuggling_container_tier2', 'antistress_pro', NULL, 100, 10),
	(21, 'smuggling_container_tier2', 'weapon_combatpistol', NULL, 10, 10),
	(22, 'smuggling_container_tier3', 'weapon_microsmg', NULL, 10, 10),
	(23, 'smuggling_container_tier2', 'weapon_flaregun', NULL, 10, 10),
	(24, 'smuggling_container_tier2', 'ammo_03', NULL, 100, 10),
	(25, 'smuggling_container_tier2', 'weapon_molotov', '{"ammo": 1}', 10, 10),
	(26, 'smuggling_container_tier3', 'bulletproof_vest_medium', NULL, 100, 10),
	(27, 'smuggling_container_tier3', 'remote_crafting_kit', NULL, 10, 10),
	(28, 'smuggling_container_tier3', 'weapon_switchblade', NULL, 10, 10),
	(29, 'smuggling_container_tier3', 'clothing_job_high', NULL, 100, 10),
	(30, 'smuggling_container_tier3', 'lockpick_high', NULL, 100, 10),
	(31, 'smuggling_container_tier3', 'special_drill', NULL, 100, 10),
	(32, 'smuggling_container_tier3', 'weapon_sawnoffshotgun', NULL, 10, 10),
	(33, 'smuggling_container_tier2', 'weapon_machinepistol', NULL, 10, 10),
	(34, 'smuggling_container_tier3', 'weapon_stickybomb', '{"ammo": 1}', 10, 10),
	(35, 'smuggling_container_tier3', 'artisanal_jammer', NULL, 100, 10),
	(36, 'smuggling_container_tier4', 'injector_morphine', NULL, 100, 10),
	(37, 'smuggling_container_tier4', 'injector_adrenaline', NULL, 100, 10),
	(38, 'smuggling_container_tier4', 'injector_propital', NULL, 100, 10),
	(39, 'smuggling_container_tier4', 'injector_mule', NULL, 100, 10),
	(40, 'smuggling_container_tier4', 'injector_etgc', NULL, 100, 10);