GarbageConfig = {}

GarbageConfig.SellPrice = {["default"] = 25, ["sawdust"] = 2, ["petroleum_residue"] = 6, ["seeweed_acid"] = 30}

GarbageConfig.RecycleItem = {
    ["plastic"] = 5,
    ["metalscrap"] = 5,
    ["aluminum"] = 5,
    ["rubber"] = 5,
    ["electronickit"] = 5,
    ["rolex"] = 5,
    ["diamond_ring"] = 5,
    ["goldchain"] = 5,
    ["10kgoldchain"] = 5,
    ["goldbar"] = 5,
    ["garbagebag"] = 5,
    ["petroleum_residue"] = 20,
    ["os"] = 5,
    ["viscere"] = 5,
    ["sawdust"] = 300,
    ["used_bloodbag"] = 5,
    ["seeweed_acid"] = 3,
}

GarbageConfig.Cloakroom = {
    [GetHashKey("mp_m_freemode_01")] = {
        ["En essai"] = {
            Components = {
                [1] = {Drawable = 0, Texture = 0, Palette = 0},
                [3] = {Drawable = 39, Texture = 0, Palette = 0},
                [4] = {Drawable = 98, Texture = 11, Palette = 0},
                [5] = {Drawable = 82, Texture = 0, Palette = 0},
                [6] = {Drawable = 71, Texture = 11, Palette = 0},
                [7] = {Drawable = 0, Texture = 0, Palette = 0},
                [8] = {Drawable = 15, Texture = 0, Palette = 0},
                [9] = {Drawable = 0, Texture = 0, Palette = 0},
                [10] = {Drawable = 0, Texture = 0, Palette = 0},
                [11] = {Drawable = 251, Texture = 11, Palette = 0},
            },
            Props = {},
        },
        ["Employé"] = {
            Components = {
                [1] = {Drawable = 0, Texture = 0, Palette = 0},
                [3] = {Drawable = 39, Texture = 0, Palette = 0},
                [4] = {Drawable = 98, Texture = 8, Palette = 0},
                [5] = {Drawable = 82, Texture = 0, Palette = 0},
                [6] = {Drawable = 71, Texture = 8, Palette = 0},
                [7] = {Drawable = 0, Texture = 0, Palette = 0},
                [8] = {Drawable = 15, Texture = 0, Palette = 0},
                [9] = {Drawable = 0, Texture = 0, Palette = 0},
                [10] = {Drawable = 0, Texture = 0, Palette = 0},
                [11] = {Drawable = 251, Texture = 8, Palette = 0},
            },
            Props = {},
        },
        ["Confirmé(e)"] = {
            Components = {
                [1] = {Drawable = 0, Texture = 0, Palette = 0},
                [3] = {Drawable = 39, Texture = 0, Palette = 0},
                [4] = {Drawable = 98, Texture = 8, Palette = 0},
                [5] = {Drawable = 82, Texture = 0, Palette = 0},
                [6] = {Drawable = 71, Texture = 8, Palette = 0},
                [7] = {Drawable = 0, Texture = 0, Palette = 0},
                [8] = {Drawable = 15, Texture = 0, Palette = 0},
                [9] = {Drawable = 0, Texture = 0, Palette = 0},
                [10] = {Drawable = 0, Texture = 0, Palette = 0},
                [11] = {Drawable = 248, Texture = 4, Palette = 0},
            },
            Props = {},
        },
    },
    [GetHashKey("mp_f_freemode_01")] = {
        ["En essai"] = {
            Components = {
                [1] = {Drawable = 0, Texture = 0, Palette = 0},
                [3] = {Drawable = 33, Texture = 0, Palette = 0},
                [4] = {Drawable = 101, Texture = 11, Palette = 0},
                [5] = {Drawable = 82, Texture = 0, Palette = 0},
                [6] = {Drawable = 74, Texture = 11, Palette = 0},
                [7] = {Drawable = 0, Texture = 0, Palette = 0},
                [8] = {Drawable = 0, Texture = 0, Palette = 0},
                [9] = {Drawable = 0, Texture = 0, Palette = 0},
                [10] = {Drawable = 0, Texture = 0, Palette = 0},
                [11] = {Drawable = 259, Texture = 11, Palette = 0},
            },
            Props = {},
        },
        ["Employé"] = {
            Components = {
                [1] = {Drawable = 0, Texture = 0, Palette = 0},
                [3] = {Drawable = 33, Texture = 0, Palette = 0},
                [4] = {Drawable = 101, Texture = 8, Palette = 0},
                [5] = {Drawable = 82, Texture = 0, Palette = 0},
                [6] = {Drawable = 74, Texture = 8, Palette = 0},
                [7] = {Drawable = 0, Texture = 0, Palette = 0},
                [8] = {Drawable = 0, Texture = 0, Palette = 0},
                [9] = {Drawable = 0, Texture = 0, Palette = 0},
                [10] = {Drawable = 0, Texture = 0, Palette = 0},
                [11] = {Drawable = 259, Texture = 8, Palette = 0},
            },
            Props = {},
        },
        ["Confirmé(e)"] = {
            Components = {
                [1] = {Drawable = 0, Texture = 0, Palette = 0},
                [3] = {Drawable = 33, Texture = 0, Palette = 0},
                [4] = {Drawable = 101, Texture = 8, Palette = 0},
                [5] = {Drawable = 82, Texture = 0, Palette = 0},
                [6] = {Drawable = 74, Texture = 8, Palette = 0},
                [7] = {Drawable = 0, Texture = 0, Palette = 0},
                [8] = {Drawable = 2, Texture = 0, Palette = 0},
                [9] = {Drawable = 0, Texture = 0, Palette = 0},
                [10] = {Drawable = 0, Texture = 0, Palette = 0},
                [11] = {Drawable = 256, Texture = 4, Palette = 0},
            },
            Props = {},
        },
    },
}
