AddTextEntry("PM_PANE_CFX", "SO~g~Z~w~~italic~ ~s~(FiveM)")
AddTextEntry("FE_THDR_GTAO", "SO~g~Z~w~~italic~ - Serveur GTA RP Communautaire")
AddTextEntry("PM_SCR_MAP", "CARTE DE L'ÎLE")
AddTextEntry("PM_SCR_GAM", "ACTIONS FIVEM")
AddTextEntry("PM_PANE_LEAVE", "Retourner au menu")
AddTextEntry("PM_PANE_QUIT", "Retourner au bureau")
AddTextEntry("PM_SCR_SET", "PARAMÈTRES")
