export enum ClientEvent {
    ADMIN_OPEN_MENU = 'soz-core:client:admin:openMenu',
    ADMIN_MAPPER_OPEN_MENU = 'soz-core:client:admin:mapper:openMenu',
    ADMIN_SHOW_GPS = 'soz-core:client:admin:show-gps',
    ADMIN_SPECTATE_PLAYER = 'soz-core:client:admin:spectate-player',
    ADMIN_KILL_PLAYER = 'soz-core:client:admin:kill-player',
    ANIMATION_SURRENDER = 'soz-core:client:animation:surrender',
    ANIMATION_GIVE = 'soz-core:client:animation:give',

    BASE_ENTERED_VEHICLE = 'baseevents:enteredVehicle',
    BASE_ENTERING_VEHICLE = 'baseevents:enteringVehicle',
    BASE_LEFT_VEHICLE = 'baseevents:leftVehicle',
    BASE_CHANGE_VEHICLE_SEAT = 'baseevents:changedVehicleSeat',

    BAUN_ICE_CUBE = 'soz-core:client:baun:create-ice-cubes',

    BANK_SAFE_OPEN = 'banking:client:qTargetOpenSafe',

    BENNYS_OPEN_CLOAKROOM = 'soz-core:client:job:bennys:open-cloakroom',
    BENNYS_FLATBED_DETACH_VEHICLE = 'soz-core:client:job:bennys:flatbed:detach-vehicle',

    CHARACTER_REQUEST_CHARACTER_WIZARD = 'soz-character:client:RequestCharacterWizard',

    CORE_CLOSE_MENU = 'soz-core:client:menu:close',

    GET_CLOTHES = 'soz-core:client:get-clothes',

    AUDIO_PLAY = 'soz-core:client:audio:play',
    AUDIO_STOP = 'soz-core:client:audio:stop',
    CRIMI_USE_CLOAKROOM = 'soz-core:client:crimi:use-cloakroom',
    CRIMI_USE_FAKE_CARD = 'soz-core:client:crimi:use-fake-card',
    CRIMI_USE_JAMMER = 'soz-core:client:crimi:use-jammer',
    CRIMI_REMOVE_CLOTH = 'soz-core:client:crimi:remove-cloth',
    CRIMI_ASK_REMOTE_WORKSHOP = 'soz-core:client:crimi:ask-remote-workshop',
    CRIMI_ADD_REMOTE_WORKSHOP = 'soz-core:client:crimi:add-remote-workshop',
    CRIMI_REMOVE_REMOTE_WORKSHOP = 'soz-core:client:crimi:remove-remote-workshop',
    CRIMI_SET_TEMP_ADDITIONAL_WEIGHT = 'soz-core:client:crimi:set-temp-additional-weight',
    CRIMI_SET_TEMP_UNLIMITED_SPRINT = 'soz-core:client:crimi:set-temp-unlimited-sprint',
    CRIMI_USE_INJECTOR = 'soz-core:client:crimi:use-injector',
    CRIMI_HEAL_OVER_TIME = 'soz-core:client:crimi:heal-over-time',

    DRIVING_SCHOOL_START_EXAM = 'soz-core:client:driving-school:start-exam',
    DRIVING_SCHOOL_SETUP_EXAM = 'soz-core:client:driving-school:spawn-veh',

    FOOD_UPDATE_ORDER = 'soz-core:client:food:update-order',
    FOOD_HUNT_SYNC = 'soz-core:client:food:hunt-sync',

    HOUSING_OPEN_UPGRADES_MENU = 'soz-core:client:housing:open-upgrades-menu',
    HOUSING_REQUEST_ENTER = 'soz-core:client:housing:request-enter',
    HOUSING_ADD_TEMPORARY_ACCESS = 'soz-core:client:housing:add-temporary-access',
    HOUSING_TELEPORT = 'soz-core:client:housing:teleport',
    HOUSING_DELETE_FOURNITURE = 'soz-core:client:housing:delete',
    HOUSING_SYNC_FOURNITURE = 'soz-core:client:housing:sync',
    HOUSING_SYNC_LIGHT = 'soz-core:client:housing:sync-light',

    HALLOWEEN_HAT_TOOGLE = 'soz-core:client:halloween:hat-toggle',
    HALLOWEEN_DEGUISEMENT_USE = 'soz-core:client:halloween:use-deguisement',
    HALLOWEEN_DEMON_ANALISYS = 'soz-core:client:halloween:use-demon-analysis',
    HALLOWEEN_VAMPIRE_UPDATE_STATE = 'soz-core:client:halloween:vampire-update-state',
    HALLOWEEN_VAMPIRE_UPDATE_OBJECTIVE_PART1 = 'soz-core:client:halloween:vampire-update-objective-part1',
    HALLOWEEN_VAMPIRE_UPDATE_OBJECTIVE_PART2 = 'soz-core:client:halloween:vampire-update-objective-part2',
    HALLOWEEN_VAMPIRE_UPDATE_POSITION = 'soz-core:client:halloween:vampire-update-position',
    HALLOWEEN_VAMPIRE_PLAYER_CONVERTED = 'soz-core:client:halloween:vampire-player-converted',
    HALLOWEEN_VAMPIRE_START_GAME = 'soz-core:client:halloween:vampire-start-game',

    HALLOWEEN_SUCK_PLAYER_START = 'soz-core:client:halloween:halloween:player-suck-start',
    HALLOWEEN_SUCK_PLAYER_END = 'soz-core:client:halloween:player-suck-end',

    INVENTORY_OPEN = 'soz-core:client:inventory:open',
    INVENTORY_OPEN_KEYS = 'soz-core:client:inventory:open-keys',
    INVENTORY_OPEN_WALLET = 'soz-core:client:inventory:open-wallet',
    INVENTORY_UPDATE = 'soz-core:client:inventory:update',
    INVENTORY_CLOSE = 'soz-core:client:inventory:close',

    ITEM_USE = 'soz-core:client:item:use',
    ITEM_ALBUM_USE = 'soz-core:client:item:album:toggle',
    ITEM_PROTEST_SIGN_TOGGLE = 'soz-core:client:item:protest-sign:toggle',
    ITEM_UMBRELLA_TOGGLE = 'soz-core:client:item:umbrella:toggle',
    ITEM_WALK_STICK_TOGGLE = 'soz-core:client:item:walk-stick:toggle',
    ITEM_BOOK_USE = 'soz-core:client:item:book:use',
    ITEM_CAMERA_TOGGLE = 'soz-core:client:item:camera:toggle',
    ITEM_MICROPHONE_TOGGLE = 'soz-core:client:item:microphone:toggle',
    ITEM_SCIENTIST_CAMERA_TOGGLE = 'soz-core:client:item:scientist-camera:toggle',
    ITEM_SCIENTIST_PHOTO_TOGGLE = 'soz-core:client:item:scientist-photo:toggle',
    ITEM_SCUBA_TOOGLE = 'soz-core:client:item:scuba:toggle',
    ITEM_DETECTIVE_BOARD_TOGGLE = 'soz-core:client:item:detective-board:toggle',
    ITEM_RADAR_USE = 'soz-core:client:item:radar:use',
    ITEM_WATCH_USE = 'soz-core:client:item:watch:use',

    HELICO_UPDATE_LIGHT = 'soz-core:client:police:update-light',

    JOBS_FFS_OPEN_SOCIETY_MENU = 'soz-jobs:client:ffs:OpenSocietyMenu',
    JOBS_BAUN_OPEN_SOCIETY_MENU = 'soz-jobs:client:baun:OpenSocietyMenu',
    JOBS_FOOD_OPEN_SOCIETY_MENU = 'jobs:client:food:OpenSocietyMenu',
    JOBS_STONK_OPEN_SOCIETY_MENU = 'soz-jobs:client:stonk:OpenSocietyMenu',
    JOBS_MDR_OPEN_SOCIETY_MENU = 'soz-jobs:client:mdr:OpenSocietyMenu',
    JOBS_TAXI_OPEN_SOCIETY_MENU = 'soz-jobs:client:taxi:OpenSocietyMenu',
    JOBS_LSMC_OPEN_SOCIETY_MENU = 'soz-jobs:client:lsmc:OpenSocietyMenu',
    JOBS_GARBAGE_OPEN_SOCIETY_MENU = 'jobs:client:garbage:OpenSocietyMenu',
    JOBS_FDF_OPEN_SOCIETY_MENU = 'soz-jobs:client:fdf:OpenSocietyMenu',
    JOBS_GOUV_OPEN_SOCIETY_MENU = 'soz-jobs:client:gouv:OpenSocietyMenu',
    JOBS_TWITCH_NEWS_OPEN_SOCIETY_MENU = 'soz-jobs:client:twitch-news:OpenSocietyMenu',
    JOBS_YOU_NEWS_OPEN_SOCIETY_MENU = 'soz-jobs:client:you-news:OpenSocietyMenu',
    JOBS_DMC_OPEN_SOCIETY_MENU = 'soz-jobs:client:dmc:OpenSocietyMenu',
    JOBS_POLICE_OPEN_SOCIETY_MENU = 'soz-jobs:client:police:OpenSocietyMenu',
    JOBS_OIL_OPEN_SOCIETY_MENU = 'soz-jobs:client:oil:OpenSocietyMenu',

    JOBS_CHECK_CLOAKROOM_STORAGE = 'soz-jobs:client:check-cloakroom-storage',
    JOB_OPEN_MENU = 'soz-core:client:job:open-menu',
    JOB_DUTY_CHANGE = 'QBCore:Client:SetDuty',
    JOB_OPEN_CLOAKROOM = 'soz-core:client:job::OpenCloakroomMenu',
    JOB_OPEN_ON_DUTY_MENU = 'soz-job:client:OpenOnDutyMenu',

    LSMC_DISEASE_APPLY_CURRENT_EFFECT = 'lsmc:maladie:client:ApplyCurrentDiseaseEffect',
    LSMC_SET_DEATH = 'soz-core:client:lsmc:set-death',
    LSMC_REVIVE = 'soz-core:lsmc:client:revive',
    LSMC_REVIVE_DOC = 'soz-core:lsmc:client:revive-doc',
    LSMC_CALL = 'soz-core:lsmc:client:call',
    LSMC_APPLY_PATIENT_CLOTHING = 'soz-core:client:lsmc:applyPatientClothing',
    LSMC_REMOVE_PATIENT_CLOTHING = 'soz-core:client:lsmc:removePatientClothing',
    LSMC_APPLY_OUTFIT = 'soz-core:client:lsmc:ApplyDutyClothing',
    LSMC_TELEPORTATION = 'soz-core:lsmc:client:teleportation',
    LSMC_HEAL = 'soz-core:lsmc:client:heal',
    LSMC_NEW_URGENCY = 'soz-core:lsmc:client:new-urgency',
    LSMC_END_URGENCY = 'soz-core:lsmc:client:end-urgency',
    LSMC_STRETCHER_USE = 'soz-core:lsmc:client:stretcher-use',
    LSMC_STRETCHER_PUT_ON = 'soz-core:lsmc:client:stretcher-put-on',
    LSMC_WHEELCHAIR_USE = 'soz-core:lsmc:client:wheelchair-use',
    LSMC_SHOW_MEDICAL_DIAG = 'soz-core:lsmc:client:show-medical-diag',
    LSMC_BED_PUT_ON = 'soz-core:client:job:lsmc:bed-put-on',
    LSMC_VEH_PUT_ON = 'soz-core:client:job:lsmc:veh-put-on',

    MISSIVE_SHOW_ITEM = 'soz-core:client:missive:show-item',
    MONITOR_START_TRACING = 'soz-core:client:monitor:start-tracing',

    NEWS_DRAW = 'soz-core:client:news:draw',
    NEWS_NEWSPAPER_SELL = 'soz-core:client:news:newspaper-sell',
    NEWS_NEWSPAPER_SOLD = 'soz-core:client:news:newspaper-sold',

    NOTIFICATION_DRAW = 'soz-core:client:notification:draw',
    NOTIFICATION_DRAW_ADVANCED = 'soz-core:client:notification:draw-advanced',
    NUI_SHOW_PANEL = 'soz-core:client:nui:show-panel',

    NUI_HIDE_PANEL = 'soz-core:client:nui:hide-panel',

    OBJECT_CREATE = 'soz-core:client:object:create',
    OBJECT_DELETE = 'soz-core:client:object:delete',
    OBJECT_EDIT = 'soz-core:client:object:edit',
    OBJECT_PLACE_ITEM = 'soz-core:client:object:place',
    OBJECT_PLACE_JOB = 'soz-core:client:job-object:place',

    PROP_OPEN_MENU = 'soz-core:client:prop:open-menu',

    OIL_REFILL_ESSENCE_STATION = 'soz-core:client:oil:refill-essence-station',
    OIL_REFILL_KEROSENE_STATION = 'soz-core:client:oil:refill-kerosene-station',

    PHONE_APP_WEATHER_UPDATE_FORECASTS = 'phone:app:weather:updateForecasts',
    PHONE_APP_WEATHER_UPDATE_STORM_ALERT = 'phone:app:weather:updateStormAlert',
    PHONE_APP_BANK_UPDATE_BALANCE = 'phone:client:app:bank:updateBalance',

    STONK_DELIVER_LOCATION = 'stonk:client:DeliverLocation',
    STONK_APPLY_OUTFIT = 'soz-core:client:stonk:ApplyDutyClothing',

    SHOP_OPEN_MENU = 'soz-core:client:shops:open-menu',
    SHOP_UPDATE_STOCKS = 'soz-core:client:shops:update-stocks',

    // Temp event which should be internally used by a service when only soz core
    CHARACTER_SET_TEMPORARY_CLOTH = 'soz-character:Client:ApplyTemporaryClothSet',

    PLAYER_DISABLE_SPRINT = 'soz-core:client:player:disable-sprint',
    PLAYER_FORCE_ALCOHOL_EFFECT = 'soz-core:client:player:force-alcohol-effect',
    PLAYER_FORCE_DRUG_EFFECT = 'soz-core:client:player:force-drug-effect',
    PLAYER_HEALTH_DO_PUSH_UP = 'soz-core:client:player:health:push-up',
    PLAYER_HEALTH_DO_YOGA = 'soz-core:client:player:health:yoga',
    PLAYER_HEALTH_DO_SIT_UP = 'soz-core:client:player:health:sit-up',
    PLAYER_HEALTH_DO_FREE_WEIGHT = 'soz-core:client:player:health:free-weight',
    PLAYER_SET_JOB_OUTFIT = 'soz-core:client:player:set-job-outfit',
    PLAYER_SET_UNLIMITED_SPRINT = 'soz-core:client:player:set-unlimited-sprint',
    PLAYER_SHOW_IDENTITY = 'soz-core:client:player:show-identity',
    PLAYER_UPDATE_CROSSHAIR = 'soz-core:client:player:update-crosshair',
    PLAYER_UPDATE_STATE = 'soz-core:client:player:update-state',
    PLAYER_UPDATE_LIST_STATE = 'soz-core:client:player:update-list-state',
    PLAYER_ON_DEATH = 'ems:client:onDeath',
    PLAYER_ZOMBIE_TRANSFORM = 'soz-core:client:player:zombie:transform',
    PLAYER_ZOMBIE_REMOVE = 'soz-core:client:player:zombie:remove',
    PLAYER_ZOMBIE_SET_POSITIONS = 'soz-core:client:player:zombie:set-positions',
    PLAYER_CARD_SHOW = 'soz-core:client:player:card:show',
    PLAYER_CARD_SEE = 'soz-core:client:player:card:see',

    PROGRESS_START = 'soz-core:client:progress:start',
    PROGRESS_STOP = 'soz-core:client:progress:stop',

    REPOSITORY_SYNC_DATA = 'soz-core:client:repository:sync-data',
    REPOSITORY_SET_DATA = 'soz-core:client:repository:set-data',
    REPOSITORY_PATCH_DATA = 'soz-core:client:repository:patch-data',
    REPOSITORY_DELETE_DATA = 'soz-core:client:repository:delete-data',

    SCENE_LOAD = 'soz-core:client:scene:load',
    SCENE_UNLOAD = 'soz-core:client:scene:unload',

    STATE_UPDATE_GLOBAL = 'soz-core:client:state:update-global',
    STATE_UPDATE_TIME = 'soz-core:client:state:update-time',

    VEHICLE_CONDITION_REGISTER = 'soz-core:client:vehicle:condition:register',
    VEHICLE_CONDITION_UNREGISTER = 'soz-core:client:vehicle:condition:unregister',
    VEHICLE_CONDITION_APPLY = 'soz-core:client:vehicle:condition:apply',
    VEHICLE_CONDITION_SYNC = 'soz-core:client:vehicle:condition:sync',
    VEHICLE_CLOSE_TRUNK = 'soz-core:client:vehicle:close-trunk',
    VEHICLE_DELETE = 'soz-core:client:vehicle:delete',
    VEHICLE_FUEL_START = 'soz-core:client:vehicle:fuel:start',
    VEHICLE_CHARGE_START = 'soz-core:client:vehicle:charge:start',
    VEHICLE_FUEL_STOP = 'soz-core:client:vehicle:fuel:stop',
    VEHICLE_CHARGE_STOP = 'soz-core:client:vehicle:charge:stop',
    VEHICLE_GET_CLOSEST = 'soz-core:client:vehicle:get-closest',
    VEHICLE_GARAGE_HOUSE_OPEN_MENU = 'soz-core:client:vehicle:garage:house:open-menu',
    VEHICLE_GARAGE_HOUSE_SHOW_PARKING = 'soz-core:client:vehicle:garage:house:show-parking',
    VEHICLE_GARAGE_UPDATE = 'soz-core:client:vehicle:garage:update',
    VEHICLE_ROUTE_EJECTION = 'soz-core:client:vehicle:route-ejection',
    VEHICLE_SET_TRUNK_STATE = 'soz-core:client:vehicle:set-trunk-state',
    VEHICLE_RADAR_FLASHED = 'soz-core:client:vehicle:radar:flashed',
    VEHICLE_RADAR_TRIGGER = 'soz-core:client:radar:trigger',
    VEHICLE_UPDATE_STATE = 'soz-core:client:vehicle:update-state',
    VEHICLE_DELETE_STATE = 'soz-core:client:vehicle:delete-state',
    VEHICLE_LOCKPICK = 'soz-core:client:vehicle:lockpick',
    VEHICLE_SET_OPEN_LIST = 'soz-core:client:vehicle:set-open-list',
    VEHICLE_DAMAGE_BLUR = 'soz-core:client:vehicle:damage-blur',
    VEHICLE_NOS_START = 'soz-core:client:vehicle:nos-start',
    VEHICLE_RELEASE = 'soz-core:client:vehicle:release',
    VEH_FEATURE_SURFACE_RESET = 'reset-feature-surface',
    VEH_HAS_BEEN_TPM = 'soz-core:client:offroad:setTpm',
    VEHICLE_SYNC_DOOR_TRAIN = 'soz-core:client:vehicle:train-door-sync',

    VEHICLE_SYNC_PUSHING_STATE = 'soz-core:client:vehicle:sync-pushing-state',

    VOIP_DEBUG = 'soz-core:client:voip:debug',
    VOIP_SET_MEGAPHONE = 'soz-core:client:voip:set-megaphone',
    VOIP_ITEM_RADIO_TOGGLE = 'soz-core:client:voip:item-radio:toggle',
    VOIP_ITEM_MEGAPHONE_TOGGLE = 'soz-core:client:voip:item-megaphone:toggle',
    VOIP_ITEM_MICROPHONE_TOGGLE = 'soz-core:client:voip:item-microphone:toggle',
    VOIP_RADIO_VEHICLE_ENABLE = 'soz-core:client:voip:radio-vehicle-enable',
    VOIP_RADIO_VEHICLE_UPDATE = 'soz-core:client:voip:radio-vehicle-update',

    VOIP_VOICE_START_CALL = 'soz-core:client:voip:voice:start-call',
    VOIP_VOICE_END_CALL = 'soz-core:client:voip:voice:end-call',
    VOIP_VOICE_MUTE_CALL = 'soz-core:client:voip:voice:mute-call',
    VOIP_VOICE_RADIO_PLAYER_START_TRANSMITTING = 'soz-core:client:voip:voice:radio:player-start-transmitting',
    VOIP_VOICE_RADIO_PLAYER_STOP_TRANSMITTING = 'soz-core:client:voip:voice:radio:player-stop-transmitting',

    UPW_OPEN_CLOAKROOM = 'soz-core:client:job:upw:open-cloakroom',
    UPW_CREATE_CHARGER = 'soz-core:client:job:upw:create-charger',

    PAWL_FAST_HARVEST_TREE = 'soz-core:client:job:pawl:fast-harvest-tree',

    RADAR_TOGGLE_BLIP = 'soz-core:client:radar:toggle-blip',

    ZEVENT_TOGGLE_TSHIRT = 'soz-core:client:zevent:toggle-tshirt',

    WEAPON_USE_WEAPON = 'soz-core:client:weapon:use-weapon',
    WEAPON_USE_WEAPON_NAME = 'soz-core:client:weapon:use-weapon-name',
    WEAPON_USE_AMMO = 'soz-core:client:weapon:use-ammo',
    WEAPON_OPEN_GUNSMITH = 'soz-core:client:weapon:open-gunsmith',
    WEAPON_EXPLOSION = 'soz-core:client:weapon:explosion',
    WEAPON_CLEAR_WEAPON = 'soz-core:client:weapon:clear',
    WEAPON_PICK_SNOWBALL = 'soz-core:client:weapon:pick-snowball',

    MDR_USE_TICKET = 'soz-core:client:mdr:use-ticket',
    HEIST_GUARD = 'soz-core:client:heist:guard',
    HEIST_PLAY_ANIM = 'soz-core:client:heist:play-anim',

    NPC_DENSITY_UPDATE = 'soz-core:client:npc:density-update',

    INJURY_DEATH = 'soz-core:client:injury:death',

    TAKE_DOWN = 'soz-core:client:player:animation:takedown',
    TAKE_DOWN_TARGET = 'soz-core:client:player:animation:takedown-target',

    TOGGLE_CRAWLING = 'soz-core:client:player:animation:crawling',

    POLICE_OPEN_CLOAKROOM = 'soz-core:client:police:OpenCloakroomMenu',
    POLICE_APPLY_OUTFIT = 'soz-core:client:police:ApplyDutyClothing',
    POLICE_SET_PRISONER_CLOTHES = 'soz-core:client:police:SetPrisonerClothes',
    POLICE_SETUP_ARMOR = 'soz-core:client:police:setup-armor',
    POLICE_SETUP_ARMOR_PLATE = 'soz-core:client:police:setup-armor-plate',
    POLICE_ANIMATE_ARMOR_PLATE = 'soz-core:client:police:animate-armor-plate',
    POLICE_SETUP_MAX_ARMOR_PLATE = 'soz-core:client:police:setup-max-armor-plate',
    POLICE_MOBILE_RADAR = 'soz-core:client:police:mobile-radar',
    POLICE_BREATHANALYZER_TARGET = 'soz-core:client:police:breathanalyzer-target',
    POLICE_HANDCUFF_ANIMATION = 'soz-core:client:police:handcuff-animation',
    POLICE_UNCUFF_ANIMATION = 'soz-core:client:police:uncuff-animation',
    POLICE_GET_UNCUFFED = 'soz-core:client:police:get-uncuffed',
    POLICE_GET_CUFFED = 'soz-core:client:police:get-cuffed',
    POLICE_REQUEST_ADD_SPIKE = 'soz-core:client:police:request-add-spike',
    POLICE_SYNC_SPIKE = 'soz-core:client:police:sync-spikes',
    POLICE_REQUEST_ADD_SPEEDZONE = 'soz-core:client:police:request-add-speedzone',
    POLICE_SYNC_SPEEDZONE = 'soz-core:client:police:sync-speedzone',
    POLICE_IDENTIFIED_CLUE = 'soz-core:client:police:identified-clue',
    POLICE_GATHERED_CLUE = 'soz-core:client:police:cleaned-clue',
    POLICE_DESTROYED_CLUE = 'soz-core:client:police:destroyed-clue',
    POLICE_DRUG_IN_TRUNK = 'soz-core:client:police:drug-in-trunk',
    POLICE_PLACE_SPEED_ZONE = 'soz-core:client:police:place-speed-zone',

    SET_ESCORTING = 'soz-core:client:police:set-escorting',
    GET_ESCORTED = 'soz-core:client:police:get-escorted',
    REMOVE_ESCORTED = 'soz-core:client:police:remove-escorted',

    HELICO_ADD_LIGHT = 'soz-core:client:police:add-light',
    HELICO_REMOVE_LIGHT = 'soz-core:client:police:del-light',

    TALENT_TREE_DISABLE_CRIMI = 'soz-core:client:talent:disable-crimi',
    TALENT_NEW_CRIMI = 'soz-core:client:talent:new-crimi',

    PLAYER_TELEPORT = 'soz-core:client:player:teleport',

    HUB_ENTER = 'soz-core:client:hub:enter',
    HUB_REMOVE_STATUS = 'soz-core:client:hub:remove-status',
    HUB_ENTRY_REFRESH = 'soz-core:client:hub:entry-refresh',

    CRIMI_HOOD = 'soz-core:client:crimi:hood',
    CRIMI_SMOKE = 'soz-core:client:crimi:smoke',

    FISHING_ROD_TOGGLE = 'soz-core:server:fishing:toggle-rod',
    FISHING_BAIT_TOGGLE = 'soz-core:server:fishing:toggle-bait',

    EASTER_EAR_TOGGLE = 'soz-core:client:easter:toogle-ear',
    FULL_SCARF_TOGGLE = 'soz-core:client:easter:toggle-full-scarf',

    BINOCULARS_TOGGLE = 'items:binoculars:toggle',
    BINOCULARS_SET = 'items:binoculars:set',

    RACKET_START_PHASE = 'soz-core:client:racket:start-phase',

    // Not core
    LOCATION_ENTER = 'locations:zone:enter',
    LOCATION_EXIT = 'locations:zone:exit',

    // Sozedex
    NUI_SHOW_SOZEDEX = 'soz-core:client:nui:show-sozedex',
    NUI_HIDE_SOZEDEX = 'soz-core:client:nui:hide-sozedex',

    DRUGS_SHOW_CONTRACT = 'soz-core:client:drug:show-contract',
    DRUGS_HARVEST_CHAMPI = 'soz-core:client:drugs:harvest-champi',
    DRUGS_HARVEST_ZEED = 'soz-core:client:drugs:harvest-zeed',
    DRUGS_HARVEST_URANIUM = 'soz-core:client:drugs:harvest-uranium',
    DRUGS_DELETE = 'soz-core:client:drugs:delete',
    DRUGS_ADD = 'soz-core:client:drugs:add',
    DRUGS_UPDATE_SEED = 'soz-core:client:drugs:update-seed',
    DRUGS_CONSUME = 'soz-core:client:drugs:consume',
    DRUGS_ZONE_ADD_UPDATE = 'soz-core:client:drugs:zone-add',
    DRUGS_ZONE_DELETE = 'soz-core:client:drugs:zone-delete',

    BILLBOARD_UPDATE = 'soz-core:client:billboard:update',
    BILLBOARD_DELETE = 'soz-core:client:billboard:delete',

    VANDALISM_ABORT = 'soz-core:client:vandalism:abort',
    VANDALISM_STEP = 'soz-core:client:vandalism:step',
    VANDALISM_UPDATE_PROP = 'soz-core:client:vandalism:update-prop',

    ANIMATION_FX = 'soz-core:client:animation:fx',
    ANIMATION_FX_POSITION = 'soz-core:client:animation:fx-position',
    ANIMATION_OBJECT_WORLD = 'soz-core:client:animation:world-object',
    ANIMATION_OBJECT_GRID = 'soz-core:client:animation:grid-object',

    METEOR_START = 'soz-core:client:meteor:start',
    METEOR_MUSIC = 'soz-core:client:meteor:music',
    METEOR_SIREN = 'soz-core:client:meteor:siren',
    METEOR_CHONOS_MUSIC = 'soz-core:client:meteor:chronos-music',
    METEOR_SANDSTORM_MUSIC = 'soz-core:client:meteor:sandstorm-music',

    OCEAN_WATER_LEVEL = 'soz-core:client:ocean:water-level',
    OCEAN_WATER_HIGH_WAVE = 'soz-core:client:ocean:high-wave',
    EARTHQUAKE = 'soz-core:client:eathquake',

    BANK_ATM_CREATED = 'soz-core:client:bank:atm:created',
    BANK_SAFE_OPEN_UI = 'soz-core:client:bank:safe:openui',
    BANK_SAFE_HOUSE_OPEN_UI = 'soz-core:client:bank:safe:house:openui',
    BANK_PHONE_INVOICE_PAID = 'banking:client:invoicePaid',
    BANK_PHONE_INVOICE_REJECTED = 'banking:client:invoiceRejected',
    BANK_PHONE_INVOICE_RECEIVED = 'banking:client:invoiceReceived',
    BANK_PHONE_NEW_STATEMENT = 'phone:app:bank-statements:newStatement',
    BANK_PHONE_NEW_CONTACT = 'phone:app:bank-contacts:addContact',
    BANK_PHONE_REMOVE_CONTACT = 'phone:app:bank-contacts:removeContact',

    BLIP_CREATE = 'soz-core:client:blip:create',
    BLIP_DELETE = 'soz-core:client:blip:delete',

    GANG_VEHBIZ_CONTAINER = 'soz-core:client:gang:veh:container',
    GANG_VEHBIZ_HACK = 'soz-core:client:gang:veh:hack',
    GANG_VEHBIZ_APPLY_MOD = 'soz-core:client:gang:veh:apply-mod',
    GANG_VEHBIZ_STRIP_WHEEL = 'soz-core:client:gang:veh:strip-wheel',
    GANG_VEHBIZ_STRIP_ENGINE = 'soz-core:client:gang:veh:strip-engine',
    GANG_VEHBIZ_BOX_RESELL_ZONE = 'soz-core:client:gang:veh:box-resell-zone',
    GANG_VEHBIZ_NPC = 'soz-core:client:gang:veh:npc',
    GANG_VEHBIZ_NPC_RELEASE = 'soz-core:client:gang:veh:npc-release',
    GANG_VEHBIZ_NPC_CHASE = 'soz-core:client:gang:veh:npc-chase',
    GANG_VEHBIZ_BOX_RESELL_ZONE_HIGHLIGHT = 'soz-core:client:gang:veh:resell-hightlight',

    GANG_SMUGGLING_CONNECTED_REFRESH = 'soz-core:client:gang:smuggling:connected-refresh',
    GANG_SMUGGLING_EXPORT_POSITION = 'soz-core:client:gang:smuggling:export-position',
    GANG_SMUGGLING_MINE_DETONATION = 'soz-core:client:gang:smuggling:mine-c4-detonation',
    GANG_SMUGGLING_ELECTRONIC_DETONATION = 'soz-core:client:gang:smuggling:electronic-c4-detonation',
    GANG_SMUGGLING_CONVOY_TASK = 'soz-core:client:gang:smuggling:convoy-task',
    GANG_SMUGGLING_UPDATE_OPENED_RESALERS = 'soz-core:client:gang:smuggling:update-resalers',
    GANG_SMUGGLING_SPAWN_GUARD_RESALER = 'soz-core:client:gang:smuggling:spawn-guard-resalers',

    GANG_CYBER_HACK_VEHICLE = 'soz-core:server:gang:cyber:hack-vehicle',
    GANG_CYBER_ALERT_INJECTOR_USE = 'soz-core:server:gang:cyber:use-alert-injector',
    GANG_CYBER_SCANNER_USE = 'soz-core:server:gang:cyber:use-scanner',
    GANG_CYBER_TRACKER_UPDATE = 'soz-core:server:gang:cyber:tracker-update',
    GANG_CYBER_VISION_USE = 'soz-core:server:gang:cyber:vision-use',
    GANG_CYBER_REPORT_USE = 'soz-core:server:gang:cyber:report-use',
    GANG_CYBER_ALERT = 'soz-core:server:gang:cyber:alert',
    GANG_CYBER_ENTRER_HEIST_INIT_PED = 'soz-core:server:gang:cyber:heist-init-ped',

    GANG_CARTEL_CONTAINER_USE = 'soz-core:client:gang:container-use',

    WORLD_EVENT_START = 'soz-core:client:world-event:start',
    WORLD_EVENT_END = 'soz-core:client:world-event:end',
    WORLD_EVENT_SIGNAL_INVENTORY = 'soz-core:client:world-event:signal-inventory',
    WORLD_EVENT_UNLOCK_INVENTORY = 'soz-core:client:world-event:unlock-inventory',
    WORLD_EVENT_INIT_PED = 'soz-core:client:world-event:ped-init',

    PED_RELEASE = 'soz-core:client:ped:release',

    DRONE_USE = 'soz-core:client:drone-use',
    DRONE_ADD_REMOTE = 'soz-core:client:drone-add-remote',
    DRONE_REMOVE_REMOTE = 'soz-core:client:drone-remove-remote',

    WEATHER_UPDATE_FORECASTS = 'soz-core:client:weather:update-forecasts',
    UPDATE_MINIMAP_POSITION = 'soz-core:client:update-minimap-position',

    OILRIG_HEIST_UPDATE = 'soz-core:server:oilrig-heist:update',
    OILRIG_HEIST_RESET = 'soz-core:server:oilrig-heist:reset',

    GIFT_PLAY_JOKER_ANIM = 'soz-core:server:gift:joker',
    GIFT_PLAY_BOUQUET_ANIM = 'soz-core:server:gift:bouquet',
    GIFT_PLAY_TOKEN_ANIM = 'soz-core:server:gift:token',
    GIFT_PLAY_GIFT_ANIM = 'soz-core:server:gift:gift',
}
