export enum ServerEvent {
    PHONE_APP_NEWS_CREATE_BROADCAST = 'phone:app:news:createNewsBroadcast',

    ADMIN_RESET_HALLOWEEN = 'soz-core:server:admin:reset-halloween',
    ADMIN_ADD_MONEY = 'soz-core:server:admin:add-money',
    ADMIN_ADD_LICENSE = 'soz-core:server:admin:add-license',
    ADMIN_SET_AIO = 'soz-core:server:admin:set-aio',
    ADMIN_SET_METADATA = 'soz-core:server:admin:set-metadata',
    ADMIN_SET_DISEASE = 'soz-core:server:admin:set-disease',
    ADMIN_SET_STAMINA = 'soz-core:server:admin:set-stamina',
    ADMIN_SET_STRENGTH = 'soz-core:server:admin:set-strength',
    ADMIN_SET_STRESS_LEVEL = 'soz-core:server:admin:set-stress-level',
    ADMIN_SET_INJURIES_COUNT = 'soz-core:server:admin:set-injuries-count',
    ADMIN_SET_REPUTATION = 'soz-core:server:admin:set-reputation',
    ADMIN_SET_DRUG_EFFECT = 'soz-core:server:admin:set-drug-effect',
    ADMIN_SET_ALCOHOL_EFFECT = 'soz-core:server:admin:set-alcohol-effect',
    ADMIN_SET_JOB = 'soz-core:server:admin:set-job',
    ADMIN_SET_CLOTHES = 'soz-core:server:admin:set-clothes',
    ADMIN_SET_GOD_MODE = 'soz-core:server:admin:set-god-mode',
    ADMIN_KILL_PLAYER = 'soz-core:server:admin:kill-player',
    ADMIN_RESET_EFFECT = 'soz-core:server:admin:reset-effect',
    ADMIN_FREEZE_PLAYER = 'soz-core:server:admin:freeze-player',
    ADMIN_UNFREEZE_PLAYER = 'soz-core:server:admin:unfreeze-player',
    ADMIN_SPECTATE_PLAYER = 'soz-core:server:admin:spectate-player',
    ADMIN_TELEPORT_TO_PLAYER = 'soz-core:server:admin:teleport-to-player',
    ADMIN_TELEPORT_PLAYER_TO_ME = 'soz-core:server:admin:teleport-player-to-me',
    ADMIN_UNCUFF_PLAYER = 'soz-core:server:admin:uncuff-player',
    ADMIN_RESET_SKIN = 'soz-core:server:admin:reset-skin',
    ADMIN_RESET_CRIMI = 'soz-core:server:admin:reset-crimi',
    ADMIN_RESET_CLIENT_STATE = 'soz-core:server:admin:reset-client-state',
    ADMIN_VEHICLE_SEE_CAR_PRICE = 'soz-core:server:admin:vehicle:see-car-price',
    ADMIN_VEHICLE_CHANGE_CAR_PRICE = 'soz-core:server:admin:vehicle:change-car-price',
    ADMIN_VEHICLE_SPAWN = 'soz-core:server:admin:vehicle:spawn',
    ADMIN_VEHICLE_DELETE = 'soz-core:server:admin:vehicle:delete',
    ADMIN_VEHICLE_NOS = 'soz-core:server:admin:vehicle:nos',
    ADMIN_CREATE_CHARACTER = 'soz-core:server:admin:create-character',
    ADMIN_SWITCH_CHARACTER = 'soz-core:server:admin:switch-character',
    ADMIN_ADD_PERSISTENT_PROP = 'soz-core:server:admin:add-persistent-prop',
    ADMIN_ADD_VEHICLE = 'soz-core:server:admin:add-vehicle',
    ADMIN_PLAYER_SET_ZOMBIE = 'soz-core:server:admin:player:set-zombie',
    ADMIN_PLAYER_SET_SENATE_PARTY = 'soz-core:server:admin:player:set-senate-party',
    ADMIN_PLAYER_SET_VOIP_DEBUG = 'soz-core:server:admin:player:set-voip-debug',
    ADMIN_PLAYER_SET_PLATE = 'soz-core:server:admin:player:set-plate',
    ADMIN_METEOR_SIREN = 'soz-core:server:admin:meteor:siren',
    ADMIN_METEOR_ACTIVATE = 'soz-core:server:admin:meteor:activate',
    ADMIN_METEOR_CHONOS_MUSIC = 'soz-core:server:admin:meteor:chonos-music',
    ADMIN_METEOR_MUSIC = 'soz-core:server:admin:meteor:music',
    ADMIN_SANDSTORM_MUSIC = 'soz-core:server:admin:meteor:sandsorm-music',
    ADMIN_METEOR_DISABLE_NPC = 'soz-core:server:admin:meteor:disble-npc',
    ADMIN_METEOR_KICK_PLAYERS = 'soz-core:server:admin:meteor:players-kick',
    ADMIN_OCEAN_WATER_CURRENT_LEVEL = 'soz-core:server:admin:ocean:water-current-level',
    ADMIN_OCEAN_WATER_LEVEL = 'soz-core:server:admin:ocean:water-level',
    ADMIN_OCEAN_WATER_HIGH_WAVE = 'soz-core:server:admin:ocean:high-wave',
    ADMIN_EARTHQUAKE = 'soz-core:server:admin:earthquake',
    ADMIN_EVENT_CREATE = 'soz-core:server:admin:event:create',
    ADMIN_EVENT_DELETE = 'soz-core:server:admin:event:delete',
    ADMIN_EVENT_ADD_REWARD = 'soz-core:server:admin:event:add-reward',
    ADMIN_EVENT_REMOVE_REWARD = 'soz-core:server:admin:event:remove-reward',
    ADMIN_EVENT_SET_REWARD_CHANCE = 'soz-core:server:admin:event:set-reward-chance',
    ADMIN_EVENT_SET_REWARD_MIN = 'soz-core:server:admin:event:set-reward-min',
    ADMIN_EVENT_SET_REWARD_MAX = 'soz-core:server:admin:event:set-reward-max',
    ADMIN_EVENT_SET_START_SOUND = 'soz-core:server:admin:event:set-start-sound',
    ADMIN_HALLOWEEN_MOON_UPDATE = 'soz-core:server:admin:halloween:moon-update',
    ADMIN_HALLOWEEN_START_GAME = 'soz-core:server:admin:halloween:launch-game',
    ADMIN_HALLOWEEN_STOP_GAME = 'soz-core:server:admin:halloween:stop-game',
    ADMIN_HALLOWEEN_UPDATE_GAME_DURATION = 'soz-core:server:admin:halloween:update-game-duration',
    ADMIN_HALLOWEEN_UPDATE_GAME_PLAYER_EXCLUSION = 'soz-core:server:admin:halloween:update-game-staff-enabled',
    ADMIN_HALLOWEEN_FOCE_TRANSFORM_PLAYER = 'soz-core:server:admin:halloween:force-transform-player',
    ADMIN_HALLOWEEN_UPDATE_ROLE = 'soz-core:server:admin:halloween:update-role',
    ADMIN_HALLOWEEN_UPDATE_MORTAL_OBJECTIVE_PART1 = 'soz-core:server:admin:halloween:update-mortal-objective-part1',
    ADMIN_HALLOWEEN_UPDATE_MORTAL_OBJECTIVE_PART2 = 'soz-core:server:admin:halloween:update-mortal-objective-part2',
    ADMIN_HALLOWEEN_UPDATE_MORTAL_OBJECTIVE_PART3 = 'soz-core:server:admin:halloween:update-mortal-objective-part3',
    ADMIN_CEREMONY_PUBLIC_PART_START = 'soz-core:server:admin:ceremony:start:public',
    ADMIN_CEREMONY_FINAL_PART_START = 'soz-core:server:admin:ceremony:start:final',
    ADMIN_CEREMONY_TIME = 'soz-core:server:admin:ceremony:time',
    ADMIN_PARADE_START = 'soz-core:server:admin:parade:start',

    BASE_ENTERED_VEHICLE = 'baseevents:enteredVehicle',
    BASE_LEFT_VEHICLE = 'baseevents:leftVehicle',
    BASE_CHANGE_VEHICLE_SEAT = 'baseevents:changeVehicleSeat',

    BAUN_CREATE_COCKTAIL_BOX = 'soz-core:server:job:baun:create-cocktail-box',
    BAUN_CREATE_ICE_CUBES = 'soz-core:server:job:baun:create-ice-cubes',
    BAUN_HARVEST = 'soz-core:server:job:baun:harvest',
    BAUN_RESELL = 'soz-core:server:job:baun:resell',
    BAUN_ICE_CUBE = 'soz-core:server:job:baun:ice-cube',
    BAUN_RESTOCK = 'soz-core:server:job:baun:restock',

    BENNYS_ESTIMATE_VEHICLE = 'soz-core:server:job:bennys:estimate-vehicle',
    BENNYS_SELL_VEHICLE = 'soz-core:server:job:bennys:sell-vehicle',
    BENNYS_SET_SPECIAL_VEHICLES = 'soz-core:server:bennys:set-special-vehicles',
    BENNYS_REPAIR_VEHICLE_ENGINE = 'soz-core:server:job:bennys:repair-vehicle-engine',
    BENNYS_REPAIR_VEHICLE_BODY = 'soz-core:server:job:bennys:repair-vehicle-body',
    BENNYS_REPAIR_VEHICLE_TANK = 'soz-core:server:job:bennys:repair-vehicle-tank',
    BENNYS_REPAIR_VEHICLE_WHEEL = 'soz-core:server:job:bennys:repair-vehicle-wheel',
    BENNYS_WASH_VEHICLE = 'soz-core:server:job:bennys:wash-vehicle',
    BENNYS_FLATBED_ATTACH_VEHICLE = 'soz-core:server:job:bennys:flatbed:attach-vehicle',
    BENNYS_FLATBED_DETACH_VEHICLE = 'soz-core:server:job:bennys:flatbed:detach-vehicle',
    BENNYS_FLATBED_ASK_DETACH_VEHICLE = 'soz-core:server:job:bennys:flatbed:ask-detach-vehicle',

    CRIMI_CONFIRM_REMOTE_WORKSHOP = 'soz-core:server:job:crimi:confirm-remote-workshop',

    DRIVING_SCHOOL_PLAYER_PAY = 'soz-core:server:driving-school:player-pay',
    DRIVING_SCHOOL_UPDATE_LICENSE = 'soz-core:server:driving-school:update-license',
    DRIVING_SCHOOL_UPDATE_VEHICLE_LIMIT = 'soz-core:server:driving-school:update-vehicle-limit',

    DMC_HARVEST = 'soz-core:server:job:dmc:harvest',
    DMC_TOGGLE_CONVERTER = 'soz-core:server:job:dmc:toggle-converter',
    DMC_SET_CONVERTER_TARGET_TEMPERATURE = 'soz-core:server:job:dmc:set-converter-target-temperature',
    DMC_RESTOCK = 'soz-core:server:job:dmc:restock',

    FIVEM_PLAYER_CONNECTING = 'playerConnecting',
    FIVEM_WEAPON_DAMAGE_EVENT = 'weaponDamageEvent',

    FOOD_ORDER_MEALS = 'soz-core:server:job:food:order-meals',
    FOOD_RETRIEVE_ORDER = 'soz-core:server:job:food:retrieve-order',
    FOOD_RETRIEVE_STATE = 'soz-core:server:job:food:retrieve-state',
    FOOD_EASTER_HARVEST = 'soz-core:server:job:food:easter-harvest',
    FOOD_HUNT = 'soz-core:client:food:hunt',
    FOOD_HUNT_RESPAWN = 'soz-core:server:food:hunt-respawn',
    FOOD_COLLECT = 'soz-core:server:job:food:collect',
    FOOD_MILK_COLLECT = 'soz-core:server:job:food:milk-collect',
    FOOD_FISH_PREPARATION = 'soz-core:server:job:food:fish-preparation',

    EASTER_HUNT = 'soz-core:server:easter:hunt',

    FFS_HARVEST = 'soz-core:server:job:ffs:harvest',
    FFS_RESTOCK = 'soz-core:server:job:ffs:restock',
    FFS_TRANSFORM = 'soz-core:server:job:ffs:transform',

    HOUSING_ADD_TEMPORARY_ACCESS = 'soz-core:server:housing:add-temporary-access',
    HOUSING_ADD_ROOMMATE = 'soz-core:server:housing:add-roommate',
    HOUSING_BELL_APARTMENT = 'soz-core:server:housing:bell-apartment',
    HOUSING_BUY_APARTMENT = 'soz-core:server:housing:buy-apartment',
    HOUSING_ENTER_APARTMENT = 'soz-core:server:housing:enter-apartment',
    HOUSING_EXIT_APARTMENT = 'soz-core:server:housing:exit-apartment',
    HOUSING_REMOVE_ROOMMATE = 'soz-core:server:housing:remove-roommate',
    HOUSING_SELL_APARTMENT = 'soz-core:server:housing:sell-apartment',
    HOUSING_VISIT_APARTMENT = 'soz-core:server:housing:visit-apartment',
    HOUSING_UPGRADE_APARTMENT_TIER = 'soz-core:server:housing:upgrade-apartment-tier',
    HOUSING_ADD_PARKING_PLACE = 'soz-core:server:housing:add-parking-place',
    HOUSING_STORE_FOURNITURE = 'soz-core:server:housing:store-fourniture',
    HOUSING_TOGGLE_LIGHTS = 'soz-core:server:housing:toggle-lights',

    STONK_RESELL = 'soz-core:server:job:stonk:resell',
    STONK_COLLECT = 'soz-core:server:job:stonk:collect',
    STONK_FILL_IN = 'soz-core:server:job:stonk:fill-in',
    STONK_DELIVERY_TAKE = 'soz-core:server:job:stonk:delivery-take',
    STONK_DELIVERY_END = 'soz-core:server:job:stonk:delivery-end',

    JOBS_PLACE_PROPS = 'job:server:placeProps',

    JOB_TEMPORARY_SET_JOB = 'soz-core:server:job:temporary:set-job',
    JOB_TEMPORARY_UNEMPLOYED = 'soz-core:server:job:temporary:unemployed',
    JOB_TEMPORARY_PAYOUT = 'soz-core:server:job:temporary:payout',
    JOB_RECRUIT = 'soz-core:server:job:recruit',
    JOB_FIRE = 'soz-core:server:job:fire',
    JOB_PROMOTE = 'soz-core:server:job:promote',
    JOB_GRADE_ADD = 'soz-core:server:job:grade:add',
    JOB_GRADE_REMOVE = 'soz-core:server:job:grade:remove',
    JOB_GRADE_SET_DEFAULT = 'soz-core:server:job:grade:set-default',
    JOB_GRADE_SET_SALARY = 'soz-core:server:job:grade:set-salary',
    JOB_GRADE_SET_WEIGHT = 'soz-core:server:job:grade:set-weight',
    JOB_GRADE_SET_NAME = 'soz-core:server:job:grade:set-name',
    JOB_GRADE_SET_PERMISSION = 'soz-core:server:job:grade:set-permission',
    JOB_RESELL_ITEM = 'soz-core:server:job:resell-item',

    LSMC_BLOOD_FILL_FLASK = 'soz-core:server:job:lsmc:blood-fill-flask',
    LSMC_BLOOD_ANALYZE = 'soz-core:server:job:lsmc:blood-analyze',
    LSMC_BUY_ITEM = 'soz-core:server:job:lsmc:buy-item',
    LSMC_HEAL = 'soz-core:server:job:lsmc:heal',
    LSMC_NPC_HEAL = 'soz-core:server:job:lsmc:npc-heal',
    LSMC_PEE_ANALYZE = 'soz-core:server:job:lsmc:pee-analyze',
    LSMC_HEALTH_CHECK = 'soz-core:server:job:lsmc:health-check',
    LSMC_SET_HEALTH_BOOK = 'soz-core:server:job:lsmc:set-health-book',
    LSMC_TOOGLE_ITT = 'soz-core:server:job:lsmc:toggle-itt',
    LSMC_SET_HAZMAT = 'soz-core:server:job:lsmc:set-hazmat',
    LSMC_SET_CURRENT_ORGAN = 'soz-core:server:job:lsmc:set-organ',
    LSMC_SET_PATIENT_OUTFIT = 'soz-core:server:job:lsmc:set-patient-outfit',
    LSMC_DAMAGE_ADD = 'soz-core:server:job:lsmc:add-damage',
    LSMC_STRETCHER_RETRIEVE = 'soz-core:server:job:lsmc:stretcher-retrieve',
    LSMC_STRETCHER_PUT_ON = 'soz-core:server:job:lsmc:stretcher-put-on',
    LSMC_STRETCHER_ON_AMBULANCE = 'soz-core:server:job:lsmc:stretcher-ambulance-put',
    LSMC_STRETCHER_RETRIEVE_AMBULANCE = 'soz-core:server:job:lsmc:stretcher-ambulance-retrieve',
    LSMC_WHEELCHAIR_RETRIEVE = 'soz-core:server:job:lsmc:wheelchair-retrieve',
    LSMC_SCAN = 'soz-core:server:job:lsmc:scan',
    LSMC_PLASTER = 'soz-core:server:job:lsmc:plaster',
    LSMC_NALOXONE = 'soz-core:server:job:lsmc:nolaxone',
    LSMC_MORPHINE = 'soz-core:server:job:lsmc:morphine',
    LSMC_BED_PUT_ON = 'soz-core:server:job:lsmc:bed-put-on',
    LSMC_VEH_PUT_ON = 'soz-core:server:job:lsmc:veh-put-on',

    LSC_CHECK_STOCK = 'soz-core:server:job:lsc:check-stock',

    MISSIVE_CREATE_ITEM = 'soz-core:server:missive:create-item',
    MISSIVE_DELETE_ITEM = 'soz-core:server:missive:delete-item',
    MISSIVE_COMPLETE = 'soz-core:server:missive:complete',

    MONITOR_ADD_EVENT = 'soz-core:server:monitor:add-event',
    MONITOR_TRACE_EVENT = 'soz-core:server:monitor:trace-event',
    MONITOR_LOG = 'soz-core:server:monitor:log',

    NEWS_ADD_FLASH = 'soz-core:server:news:add-flash',
    NEWS_NEWSPAPER_SOLD = 'soz-core:server:job:news:newspaper-sold',
    NEWS_NEWSPAPER_FARM = 'soz-core:server:job:news:newspaper-farm',

    OBJECT_PLACE = 'soz-core:server:object:place',
    OBJECT_COLLECT = 'soz-core:server:object:collect',
    OBJECT_ATTACHED_REGISTER = 'soz-core:client:object:attached:register',
    OBJECT_ATTACHED_UNREGISTER = 'soz-core:client:object:attached:unregister',
    OBJECT_DELETE = 'soz-core:server:object:delete',

    OIL_CRAFT_ESSENCE = 'soz-core:server:oil:craft-essence',
    OIL_CRAFT_ESSENCE_JERRYCAN = 'soz-core:server:oil:craft-essence-jerrycan',
    OIL_CRAFT_KEROSENE = 'soz-core:server:oil:craft-kerosene',
    OIL_CRAFT_KEROSENE_JERRYCAN = 'soz-core:server:oil:craft-kerosene-jerrycan',
    OIL_REFILL_ESSENCE_STATION = 'soz-core:server:oil:refill-essence-station',
    OIL_REFILL_KEROSENE_STATION = 'soz-core:server:oil:refill-kerosene-station',
    OIL_SET_STATION_PRICE = 'soz-core:server:oil:set-station-price',
    OIL_DECREMENT_STATION = 'soz-core:server:oil:decrement',
    OIL_REFILL_TANKER = 'soz-core:server:oil:refill-tanker',
    OIL_REFINE_TANKER = 'soz-core:server:oil:refine-tanker',
    OIL_RESELL_TANKER = 'soz-core:server:oil:resell-tanker',
    OIL_UNLOCK_TANKER = 'soz-core:server:oil:unlock-tanker',

    PLAYER_LOADED = 'soz-core:server:player:loaded',
    PLAYER_INCREASE_STRENGTH = 'soz-core:server:player:increase-strength',
    PLAYER_SET_CURRENT_DISEASE = 'soz-core:server:server:set-current-disease',
    PLAYER_INCREASE_RUN_TIME = 'soz-core:server:player:health:increase-run-time',
    PLAYER_DO_YOGA = 'soz-core:server:player:do-yoga',
    PLAYER_SET_CURRENT_WALKSTYLE = 'soz-core:server:player:set-current-walkstyle',
    PLAYER_UPDATE_HAT_VEHICLE = 'soz-core:server:player:update-hat-vehicle',
    PLAYER_UPDATE_STATE = 'soz-core:server:player:update-state',

    PLAYER_NUTRITION_LOOP = 'soz-core:server:player:nutrition:loop',
    PLAYER_NUTRITION_CHECK = 'soz-core:server:player:nutrition:check',
    PLAYER_HEALTH_SET_EXERCISE_COMPLETED = 'soz-core:server:player:health:set-exercise-completed',
    PLAYER_HEALTH_GYM_SUBSCRIBE = 'soz-core:server:player:health:gym-subscribe',

    PLAYER_APPEARANCE_SET_JOB_OUTFIT = 'soz-core:server:appearance:set-job-outfit',
    PLAYER_APPEARANCE_REMOVE_JOB_OUTFIT = 'soz-core:server:appearance:remove-job-outfit',
    PLAYER_APPEARANCE_SET_TEMP_OUTFIT = 'soz-core:server:appearance:set-temp-outfit',
    PLAYER_APPEARANCE_REMOVE_TEMP_OUTFIT = 'soz-core:server:appearance:remove-temp-outfit',

    PLAYER_ZIP = 'soz-core:server:player:zip',
    PLAYER_UNZIP = 'soz-core:server:player:unzip',

    PLAYER_ZOMBIE_CONVERT = 'soz-core:server:player:zombie:convert',
    PLAYER_ZOMBIE_REMOVE = 'soz-core:server:player:zombie:remove',
    PLAYER_ZOMBIE_TP = 'soz-core:server:player:zombie:tp',

    PLAYER_OPEN_WALLET = 'soz-core:server:player:open-wallet',

    PROGRESS_FINISH = 'soz-core:server:progress:finish',

    PROP_REQUEST_DELETE_PROP = 'soz-core:server:prop:request-delete',
    PROP_REQUEST_EDIT_PROP = 'soz-core:server:prop:request-edit',

    SCENE_CREATE = 'soz-core:server:scene:create',
    SCENE_DELETE = 'soz-core:server:scene:delete',
    SCENE_LOAD = 'soz-core:server:scene:load',
    SCENE_UNLOAD = 'soz-core:server:scene:unload',
    SCENE_ADD_ENTITY = 'soz-core:server:scene:add-entity',
    SCENE_REMOVE_ENTITY = 'soz-core:server:scene:remove-entity',
    SCENE_UPDATE_ENTITY = 'soz-core:server:scene:update-entity',
    SCENE_SET_ENTITY_INVENTORY = 'soz-core:server:scene:set-entity-inventory',
    SCENE_ADD_PED = 'soz-core:server:scene:add-ped',
    SCENE_REMOVE_PED = 'soz-core:server:scene:remove-ped',
    SCENE_UPDATE_PED = 'soz-core:server:scene:update-ped',
    SCENE_SET_PERSISTENT = 'soz-core:server:scene:set-persistent',
    SCENE_SET_NAME = 'soz-core:server:scene:set-name',

    STORY_HALLOWEEN_2023_SCENARIO_1 = 'soz-core:server:halloween:scenario1',
    STORY_HALLOWEEN_2023_SCENARIO_2 = 'soz-core:server:halloween:scenario2',
    STORY_HALLOWEEN_2023_SCENARIO_3 = 'soz-core:server:halloween:scenario3',
    STORY_HALLOWEEN_2023_SCENARIO_4 = 'soz-core:server:halloween:scenario4',

    HALLOWEEN_SUCK_NPC = 'soz-core:server:halloween:npc-suck',
    HALLOWEEN_SUCK_PLAYER_START = 'soz-core:server:halloween:player-suck-start',
    HALLOWEEN_SUCK_PLAYER_END = 'soz-core:server:halloween:player-suck-end',
    HALLOWEEN_BLOOD_HARVEST = 'soz-core:server:halloween:blood-harvest',

    STORAGE_REMOVE_ITEM = 'soz-core:server:storage:remove-item',
    SHOP_BOSS_ORDER = 'soz-core:server:shop:boss:order',
    SHOP_EASTER_BUY = 'soz-core:server:shop:easter:buy',

    UPW_CREATE_CHARGER = 'soz-core:server:job:upw:create-charger',
    UPW_REFILL_STATION = 'soz-core:server:job:upw:refill-station',
    UPW_CHANGE_BATTERY = 'soz-core:server:job:upw:change-battery',
    UPW_SET_CHARGER_PRICE = 'soz-core:server:job:upw:set-charger-price',
    UPW_GET_BLESSED_WATER = 'soz-core:server:job:upw:get-blessed-water',

    PAWL_DECREASE_CHAINSAW_FUEL = 'soz-core:server:job:pawl:decrease-chainsaw-fuel',
    PAWL_PROCESSING_STATUS = 'soz-core:server:job:pawl:processing-status',
    PAWL_PROCESSING_START = 'soz-core:server:job:pawl:processing-start',
    PAWL_PROCESSING_STOP = 'soz-core:server:job:pawl:processing-stop',

    SHOP_BUY = 'soz-core:server:shop:buy',
    SHOP_TATTOO_RESET = 'soz-core:server:shop:tattoo-reset',
    ZKEA_CHECK_STOCK = 'soz-core:client:shop:zkea:check-stock',
    ZKEA_RENT_MULE = 'soz-core:client:shop:zkea:rent-mule',
    ZKEA_RETURN_MULE = 'soz-core:client:shop:zkea:return-mule',

    AFK_KICK = 'soz-core:server:afk:kick',

    // not core
    CHARACTER_SET_JOB_CLOTHES = 'soz-character:server:SetPlayerJobClothes',
    CHARACTER_SET_CLOTHES = 'soz-character:server:SetPlayerClothes',
    QBCORE_CALL_COMMAND = 'QBCore:CallCommand',
    QBCORE_TOGGLE_DUTY = 'QBCore:ToggleDuty',
    QBCORE_SET_DUTY = 'QBCore:Server:SetDuty',
    QBCORE_SET_METADATA = 'QBCore:Server:SetMetaData',

    LSMC_CLEAR_DISEASE = 'lsmc:maladie:ClearDisease',
    LSMC_SET_CURRENT_DISEASE = 'lsmc:maladie:server:SetCurrentDisease',
    LSMC_REVIVE = 'soz-core:lsmc:server:revive',
    LSMC_FREE_BED = 'soz-core:lsmc:server:free-bed',
    LSMC_ON_DEATH = 'soz-core:lsmc:server:on-death',
    LSMC_ON_DEATH2 = 'soz-core:lsmc:server:on-death2',
    LSMC_SET_DEATH_REASON = 'soz-core:lsmc:server:set-death-reason',
    LSMC_NEW_URGENCY = 'soz-core:lsmc:server:new-urgency',
    LSMC_GIVE_BLOOD = 'soz-core:lsmc:server:give-blood',
    LSMC_TELEPORTATION = 'soz-core:lsmc:server:teleportation',

    METRICS_UPDATE = 'soz-core:server:metrics:update',

    REPOSITORY_REFRESH_DATA = 'soz-core:server:repository:refresh-data',

    TAXI_NPC_PAY = 'soz-core:server:taxi:taxi-npc-pay',
    BUS_NPC_PAY = 'soz-core:server:taxi:bus-npc-pay',

    VEHICLE_USE_REPAIR_KIT = 'soz-core:server:vehicle:use-repair-kit',
    VEHICLE_USE_BODY_REPAIR_KIT = 'soz-core:server:vehicle:use-body-repair-kit',
    VEHICLE_USE_CLEANING_KIT = 'soz-core:server:vehicle:use-cleaning-kit',
    VEHICLE_USE_WHEEL_KIT = 'soz-core:server:vehicle:use-wheel-kit',
    VEHICLE_FORCE_OPEN = 'soz-core:server:vehicle:force-open',
    VEHICLE_COLLECT_FINGERPRINT = 'soz-core:server:vehicle:collect-fingerprint',
    VEHICLE_COLLECT_DRUG = 'soz-core:server:vehicle:collect-drug',
    VEHICLE_SET_CLOSEST = 'soz-core:server:vehicle:set-closest',
    VEHICLE_DELETED = 'soz-core:server:vehicle:deleted',
    VEHICLE_GARAGE_STORE = 'soz-core:server:vehicle:garage:store',
    VEHICLE_GARAGE_RETRIEVE = 'soz-core:server:vehicle:garage:retrieve',
    VEHICLE_GARAGE_RENAME = 'soz-core:server:vehicle:garage:rename',
    VEHICLE_GARAGE_TRANSFER = 'soz-core:server:vehicle:garage:transfer',
    VEHICLE_SET_DEAD = 'soz-core:server:vehicle:set-dead',
    VEHICLE_WASH = 'soz-core:server:vehicle:wash',
    VEHICLE_FUEL_START = 'soz-core:server:vehicle:fuel:start',
    VEHICLE_CHARGE_START = 'soz-core:server:vehicle:charge:start',
    VEHICLE_OPEN_KEYS = 'soz-core:server:vehicle:open-keys',
    VEHICLE_GIVE_KEY = 'soz-core:server:vehicle:give-key',
    VEHICLE_ROUTE_EJECTION = 'soz-core:server:vehicle:route-ejection',
    VEHICLE_TAKE_OWNER = 'soz-core:server:vehicle:take-owner',
    VEHICLE_SET_TRUNK_STATE = 'soz-core:server:vehicle:set-trunk-state',
    VEHICLE_UPDATE_STATE = 'soz-core:server:vehicle:update-state',
    VEHICLE_UPDATE_CONDITION = 'soz-core:server:vehicle:update-condition',
    VEHICLE_UPDATE_CONDITION_FROM_OWNER = 'soz-core:server:vehicle:update-condition-from-owner',
    VEHICLE_UPDATE_MILEAGE = 'soz-core:server:vehicle:update-mileage',
    VEHICLE_SET_OPEN = 'soz-core:server:vehicle:set-open',
    VEHICLE_PITSTOP = 'soz-core:server:vehicle:pitstop',
    VEHICLE_TOW_ROPE_ADD = 'soz-core:server:vehicle:tow-rope-add',
    VEHICLE_TOW_ROPE_DELETE = 'soz-core:server:vehicle:tow-rope-delete',
    VEHICLE_DAMAGE_BLUR = 'soz-core:server:vehicle:damage-blur',
    VEHICLE_LOCKPICK = 'soz-core:server:vehicle:lockpick',
    VEHICLE_BREAK_DOOR = 'soz-core:server:vehicle:break-door',
    VEHICLE_NOS_START = 'soz-core:server:vehicle:nos-start',
    VEHICLE_NOS_END = 'soz-core:server:vehicle:nos-end',
    VEHICLE_HANDLING_BASE_SAVE = 'soz-core:server:vehicle:handling-base-save',
    VEHICLE_RESET_SURFACE_STATE_TO_OWNER = 'soz-core:server:vehicle:reset-surface-effect-to-owner',
    VEHICLE_SYNC_DOOR_TRAIN = 'soz-core:server:vehicle:train-door-sync',

    VEHICLE_UPDATE_PUSHING_OWNER = 'soz-core:server:vehicle:update-pushing-owner',
    VEHICLE_START_PUSHING = 'soz-core:server:vehicle:start-pushing',
    VEHICLE_STOP_PUSHING = 'soz-core:server:vehicle:stop-pushing',
    VEHICLE_CHANGE_DIRECTION = 'soz-core:server:vehicle:change-direction',

    VOIP_SET_MEGAPHONE = 'soz-core:server:voip:set-megaphone',
    VOIP_RADIO_VEHICLE_ENABLE = 'soz-core:server:voip:radio-vehicle-enable',
    VOIP_RADIO_VEHICLE_UPDATE = 'soz-core:server:voip:radio-vehicle-update',
    VOIP_PHONE_CALL_START = 'soz-core:server:voip:phone-call-start',
    VOIP_PHONE_CALL_END = 'soz-core:server:voip:phone-call-end',
    VOIP_RADIO_JOIN_CHANNEL = 'soz-core:server:voip:radio-join-channel',
    VOIP_RADIO_LEAVE_CHANNEL = 'soz-core:server:voip:radio-leave-channel',

    HALLOWEEN2022_HUNT = 'halloween2022:server:hunt',
    LSMC_HALLOWEEN_LOOT_PLAYER = 'lsmc:halloween:lootPlayer',
    VEHICLE_FREE_JOB_SPAWN = 'soz-core:server:vehicle:free-job-spawn',

    INVENTORY_USE_ITEM = 'soz-core:server:inventory:use-item',
    INVENTORY_SET_ITEM_SHORTCUT = 'soz-core:server:inventory:set-item-usage',
    INVENTORY_REMOVE_ITEM_SHORTCUT = 'soz-core:server:inventory:remove-item-usage',
    INVENTORY_MOVE_ITEM_SHORTCUT = 'soz-core:server:inventory:move-item-usage',
    INVENTORY_ITEM_SHOW = 'soz-core:server:inventory:item-show',
    INVENTORY_UNSUBSCRIBE = 'soz-core:server:inventory:unsubscribe',
    INVENTORY_OPEN = 'soz-core:server:inventory:open',
    INVENTORY_OPEN_TRUNK = 'soz-core:server:inventory:open_trunk',
    INVENTORY_OPEN_TARGET = 'soz-core:server:inventory:open-target',
    INVENTORY_OPEN_SUB_INVENTORY = 'soz-core:server:inventory:open-sub-inventory',
    INVENTORY_MOVE_ITEM = 'soz-core:server:inventory:move-item',
    INVENTORY_SORT = 'soz-core:server:inventory:sort',
    INVENTORY_RENAME_ITEM = 'soz-core:server:inventory:rename-item',
    INVENTORY_ENGRAVE_ITEM = 'soz-core:server:inventory:engrave-item',
    INVENTORY_GIVE_ITEM = 'soz-core:server:inventory:give-item',
    INVENTORY_GIVE_MONEY = 'soz-core:server:inventory:give-money',
    INVENTORY_TRANSFER_MONEY = 'soz-core:server:inventory:transfer-money',
    INVENTORY_DROP_ITEM = 'soz-core:server:inventory:drop-item',
    INVENTORY_FORCE_CONSUME = 'soz-core:server:inventory:force-consume',
    INVENTORY_REMOVE_PLAYER_ITEM = 'soz-core:server:inventory:remove-player-item',
    INVENTORY_BIN_VANDALISM = 'soz-core:server:inventory:bin-vandalism',

    WEAPON_SHOOTING = 'soz-core:server:weapon:shooting',
    WEAPON_SHOOTING_ALERT = 'soz-core:server:weapon:shooting-alert',
    WEAPON_GET_SNOW = 'soz-core:server:weapon:get-dnow',

    VANDALISM_ABORT = 'soz-core:server:vandalism:abort',
    VANDALISM_REPAIR = 'soz-core:server:vandalism:repair',
    VANDALISM_STATION_EXPLOSION = 'soz-core:server:vandalism:station-explosion',

    MDR_SHOW_TICKET = 'soz-core:server:mdr:show-ticket',
    MDR_MONEY_CLEANING = 'soz-core:server:mdr:money-cleaning',

    RACKET = 'soz-core:server:racket',
    RACKET_RELEASE_PED = 'soz-core:server:racket:release-ped',
    RACKET_START_PHASE = 'soz-core:server:racket:start-phase',

    HEIST_ADD_ITEM = 'soz-core:server:heist:add-item',
    HEIST_JEWELRY_UNLOCK = 'soz-core:server:heist:unlock',
    HEIST_JEWELRY_ALARM_STOP = 'soz-core:server:heist:alarm-stop',
    HEIST_JEWELRY_START_ROBBERY = 'soz-core:server:heist:start-robbery',
    HEIST_PLAY_ANIM = 'soz-core:server:heist:play-anim',
    HEIST_PLAY_ANIM_INIT = 'soz-core:server:heist:init',
    HEIST_RETRIEVE_ITEM = 'soz-core:server:heist:retrieve',
    HEIST_RETRIEVE_JEWEL = 'soz-core:server:heist:jewelry-retrieve-jewel',
    HEIST_JEWELRY_STOP_ROBBERY = 'soz-core:server:heist:jewelry-stop-robbery',

    SOUND_GLOBAL_INIT = 'soz-core:server:sound:init',

    PLAYER_SHOW_IDENTITY = 'soz-core:server:player:show-identity',
    POLICE_TAKE_DOWN = 'soz-core:server:takedown',
    POLICE_REMOVE_POINT = 'soz-core:server:police:remove-point',
    POLICE_REMOVE_LICENCE = 'soz-core:server:police:remove-licence',
    POLICE_GIVE_LICENCE = 'soz-core:server:police:give-licence',
    POLICE_CONFISCATE_MONEY = 'soz-core:server:police:confiscate-money',
    POLICE_PLACE_SPIKE = 'soz-core:server:police:place-spike',
    POLICE_ADD_SPIKE = 'soz-core:server:police:add-spike',
    POLICE_REMOVE_SPIKE = 'soz-core:server:police:remove-spike',
    POLICE_INIT_SPIKE = 'soz-core:server:police:init-spike',
    POLICE_PLACE_SPEEDZONE = 'soz-core:server:police:place-speedzone',
    POLICE_ADD_SPEEDZONE = 'soz-core:server:police:add-speedzone',
    POLICE_REMOVE_SPEEDZONE = 'soz-core:server:police:remove-speedzone',
    POLICE_INIT_SPEEDZONE = 'soz-core:server:police:init-speedzone',
    POLICE_IDENTIFY_CLUE = 'soz-core:server:police:identify',
    POLICE_GATHER_CLUE = 'soz-core:server:police:clean',
    POLICE_GATHER_DRUG_ON_PERSON = 'soz-core:server:police:clean-drug-on-person',
    POLICE_GATHER_FINGERPRINT_ON_PERSON = 'soz-core:server:police:clean-fingerprint-on-person',
    POLICE_GATHER_POWDER_ON_PERSON = 'soz-core:server:police:clean-powder-on-person',
    POLICE_ANALYZE_EVIDENCE = 'soz-core:server:police:analyze-evidence',
    POLICE_EDIT_DETECTIVE_BOARD = 'soz-core:server:police:edit-detective-board',
    POLICE_COPY_DETECTIVE_BOARD = 'soz-core:server:police:make-copy-detective-board',
    POLICE_CREATE_PHOTO = 'soz-core:server:police:create-photo',
    POLICE_ADD_PHOTO_DETECTIVE_BOARD = 'soz-core:server:police:add-photo-detective-board',
    POLICE_DESTROY_CLUE = 'soz-core:server:police:destroy-clue',
    POLICE_DRUG_IN_TRUNK = 'soz-core:server:police:drug-in-trunk',
    POLICE_GET_VEHICLE_OWNER = 'soz-core:server:police:get-vehicule-owner',

    ESCORT_PLAYER = 'soz-core:server:escort',
    REMOVE_ESCORT_PLAYER = 'soz-core:server:remove-escort',
    CUFF_PLAYER = 'soz-core:server:cuff',
    UNCUFF_PLAYER = 'soz-core:server:uncuff',

    HELICO_ADD_LIGHT = 'soz-core:server:police:add-light',
    HELICO_REMOVE_LIGHT = 'soz-core:server:police:del-light',
    HELICO_UPDATE_LIGHT = 'soz-core:server:police:update-light',

    HUB_TELEPORT_ENTER = 'soz-core:server:hub:teleport:enter',
    HUB_TELEPORT_EXIT = 'soz-core:server:hub:teleport:exit',
    HUB_WASH = 'soz-core:server:hub:wash',
    HUB_SHOP_BUY = 'soz-core:server:hub:shop-buy',
    HUB_EXIT = 'soz-core:server:hub:exit',
    HUB_RESELL = 'soz-core:server:hub:resell',
    HUB_SHOP_RESELL = 'soz-core:server:hub:shop-resell',
    HUB_ENTRY_DELETE = 'soz-core:server:hub:entry:delete',
    HUB_ENTRY_ADD = 'soz-core:server:hub:entry:add',
    HUB_ENTRY_UPDATE = 'soz-core:server:hub:entry:update',

    CRIMI_HOOD = 'soz-core:server:crimi:hood',
    CRIMI_UNHOOD = 'soz-core:server:crimi:unhood',
    CRIMI_NAKED = 'soz-core:server:crimi:naked',
    CRIMI_UNNAKED = 'soz-core:server:crimi:unnaked',
    CRIMI_SMOKE_STRESS = 'soz-core:server:crimi:smoke-stress',
    CRIMI_USE_JAMMER = 'soz-core:server:crimi:use-jammer',
    CRIMI_SIPHON = 'soz-core:server:crimi:siphon',

    TALENT_TREE_DISABLE_CRIMI = 'soz-core:server:talent:disable-crimi',

    CRAFTING_TRAINING = 'soz-core:crafting:craft-training',

    ALERT_POLICE = 'soz-core:alert:notification:draw-police',
    ALERT_MESSAGE = 'phone:createSocietyMessagesBroadcast',

    FISHING_SUCCESS = 'soz-core:server:fishing:success',
    FISHING_ROTTEN = 'soz-core:server:fishing:rotten',
    FISHING_GARBAGE = 'soz-core:server:fishing:garbage',
    FISHING_RESELL = 'soz-core:server:fishing:resell',
    FISHING_RENT_BOAT = 'soz-core:server:fishing:rent-boat',
    FISHING_REMOVE_BAIT = 'soz-core:server:fishing:remove-bait',
    FISHING_RETURN_BOAT = 'soz-core:server:fishing:return-boat',

    SOZEDEX_CLAIM_REWARD = 'soz-core:server:sozedex:claim-reward',

    DRUGS_SHOP_BUY = 'soz-core:server:drug:shop-buy',
    DRUGS_ADD_SKILL = 'soz-core:server:drug:add-skill',
    DRUGS_HARVEST_FIELDS = 'soz-core:server:drugs:harvest-fields',
    DRUGS_WATER = 'soz-core:server:drugs:water',
    DRUGS_CHECK = 'soz-core:server:drugs:check',
    DRUGS_HARVEST = 'soz-core:server:drugs:harvest',
    DRUGS_DESTROY = 'soz-core:server:drugs:destroy',
    DRUGS_SELL_PED = 'soz-core:server:drugs:sell-ped',
    DRUGS_SELL_CONTRACT = 'soz-core:server:drugs:sell-contract',
    DRUGS_STOLEN = 'soz-core:server:drugs:stolen',
    DRUGS_GARDEN_ADD = 'soz-core:server:drugs:garden-add',
    DRUGS_GARDEN_REMOVE = 'soz-core:server:drugs:garden-remove',
    DRUGS_ZONE_ADD = 'soz-core:server:drugs:zone-add',
    DRUGS_ZONE_DELETE = 'soz-core:server:drugs:zone-delete',
    DRUGS_ZONE_UPDATE = 'soz-core:server:drugs:zone-update',
    DRUGS_SEARCH_FINGERPRINT = 'soz-core:server:drugs:search-fingerprint',

    RACE_ADD = 'soz-core:server:race:add',
    RACE_UPDATE = 'soz-core:server:race:update',
    RACE_DELETE = 'soz-core:server:race:delete',
    RACE_FINISH = 'soz-core:server:race:finish',
    RACE_CLEAR_RANKING = 'soz-core:server:race:clear-ranking',

    FDF_TREE_CUT = 'soz-core:server:fdf:tree-cut',
    FDF_TREE_WATER = 'soz-core:server:fdf:tree-water',
    FDF_TREE_CHECK = 'soz-core:server:fdf:tree-check',
    FDF_FIELD_HILLING = 'soz-core:server:fdf:field-hilling',
    FDF_FIELD_HARVEST = 'soz-core:server:fdf:field-harvest',
    FDF_FIELD_DESTROY = 'soz-core:server:fdf:field-destroy',
    FDF_FIELD_PLOW = 'soz-core:server:fdf:field-plow',
    FDF_FIELD_PLANT = 'soz-core:server:fdf:field-plant',
    FDF_FIELD_CHECK = 'soz-core:server:fdf:field-check',
    FDF_TRACTOR_HARVEST = 'soz-core:server:fdf:field-tractor-harvest',
    FDF_GARLIC_HARVEST = 'soz-core:server:fdf:garlic-harvest',
    FDF_MILK_COLLECT = 'soz-core:server:fdf:cow-milk-collect',

    ANIMATION_FX = 'soz-core:server:animation:fx',
    ANIMATION_FX_POSITION = 'soz-core:server:animation:fx-position',
    ANIMATION_OBJECT_WORLD = 'soz-core:server:animation:world-object',
    ANIMATION_OBJECT_GRID = 'soz-core:server:animation:grid-object',

    DISPENSER_BUY = 'soz-core:server:dispenser:buy',

    GOUV_UPDATE_TAX = 'soz-core:server:gouv:update-tax',
    GOUV_UPDATE_JOB_TIER_TAX = 'soz-core:server:gouv:update-job-tier-tax',
    GOUV_UPDATE_JOB_TIER_TAX_PERCENTAGE = 'soz-core:server:gouv:update-job-tier-tax-percentage',
    GOUV_FINE_ADD = 'soz-core:server:gouv:fine-add',
    GOUV_FINE_SET_MIN_PRICE = 'soz-core:server:gouv:fine-set-min-price',
    GOUV_FINE_SET_MAX_PRICE = 'soz-core:server:gouv:fine-set-max-price',
    GOUV_FINE_SET_LABEL = 'soz-core:server:gouv:fine-set-label',
    GOUV_FINE_REMOVE = 'soz-core:server:gouv:fine-remove',
    GOUV_RADAR_ADD = 'soz-core:server:gouv:radar-add',
    GOUV_RADAR_SET_SPEED = 'soz-core:server:gouv:radar-set-speed',
    GOUV_RADAR_SET_DISABLED = 'soz-core:server:gouv:radar-set-disabled',
    GOUV_RADAR_REMOVE = 'soz-core:server:gouv:radar-remove',
    GOUV_VALIDATE_IDENTITY = 'soz-core:server:gouv:validate-identity',

    LUXURY_DELETE_GUARD = 'soz-core:server:luxury:delete-guard',
    LUXURY_CREATED_GUARD = 'soz-core:server:luxury:created-guard',

    BANK_INVOICE_PAY = 'soz-core:server:bank:invoice-pay',
    BANK_INVOICE_REJECT = 'soz-core:server:bank:invoice-reject',
    BANK_REMOVE_ATM_LIQUIDITY_RATIO = 'soz-core:server:bank:remove-atm-liquidity-ratio',
    BANK_REFRESH_ACCOUNT = 'soz-core:server:bank:refresh-account',

    GANG_ADMIN_CREATE = 'soz-core:server:gang:admin-create',
    GANG_ADMIN_QUIT = 'soz-core:server:gang:admin-quit',
    GANG_ADMIN_ASSIGN = 'soz-core:server:gang:admin-assign',
    GANG_ADMIN_UPDATE = 'soz-core:server:gang:admin-update',
    GANG_ADMIN_DELETE = 'soz-core:server:gang:admin-delete',
    GANG_SKILL_ADD = 'soz-core:server:gang:skill-add',
    GANG_INFLUENCE_ZONE_UPDATE = 'soz-core:server:gang:influence:update',
    GANG_CARTEL_CONTAINER_TAKE = 'soz-core:server:gang:container-take',
    GANG_CARTEL_CONTAINER_USE = 'soz-core:server:gang:container-use',
    GANG_UPGRADE = 'soz-core:server:gang:upgrade',
    GANG_PARKING_UPDATE = 'soz-core:server:gang:parking-update',

    GANG_VEHBIZ_GET_POSITION = 'soz-core:server:gang:veh:position',
    GANG_VEHBIZ_UNLOCK = 'soz-core:server:gang:veh:unlock',
    GANG_VEHBIZ_RESELL = 'soz-core:server:gang:veh:resell',
    GANG_VEHBIZ_HACK = 'soz-core:server:gang:veh:hack',
    GANG_VEHBIZ_STRIP_DOOR = 'soz-core:server:gang:veh:strip-door',
    GANG_VEHBIZ_STRIP_WHEEL = 'soz-core:server:gang:veh:strip-wheel',
    GANG_VEHBIZ_STRIP_ENGINE = 'soz-core:server:gang:veh:strip-engine',
    GANG_VEHBIZ_STRIP_BODY = 'soz-core:server:gang:veh:strip-body',
    GANG_VEHBIZ_BOX_RESELL = 'soz-core:server:gang:veh:box-resell',
    GANG_VEHBIZ_BOX_RESELL_ZONE = 'soz-core:server:gang:veh:box-resell-zone',
    GANG_VEHBIZ_SECRET_STORAGE = 'soz-core:server:gang:veh:secret-storage',
    GANG_VEHBIZ_ADD_NOS = 'soz-core:server:gang:veh:nos-add',
    GANG_VEHBIZ_UNIQUE_SPAWN = 'soz-core:server:gang:veh:unique-spawn',
    GANG_VEHBIZ_NPC_REGISTER = 'soz-core:server:gang:veh:npc-register',
    GANG_VEHBIZ_PLATE_CHANGE = 'soz-core:server:gang:veh:plate-change',
    GANG_VEHBIZ_REFRESH_LIST = 'soz-core:server:gang:vehbiz:refresh-list',
    GANG_VEHBIZ_COMMAND = 'soz-core:server:gang:veh:command',
    GANG_VEHBIZ_MAPPING_APPLY = 'soz-core:server:gang:veh:mapping-apply',
    GANG_VEHBIZ_GARAGE_UPGRADE = 'soz-core:server:gang:veh:garage-upgrade',
    GANG_VEHBIZ_REPAIR_ENGINE = 'soz-core:server:gang:veh:repair-engine',
    GANG_VEHBIZ_REPAIR_BODY = 'soz-core:server:gang:veh:repair-body',

    GANG_SMUGGLING_BLACK_MARKET_BOX_USE = 'soz-core:server:gang:smuggling:black-market-box-use',
    GANG_SMUGGLING_BLACK_MARKET_PRICE_UPDATE = 'soz-core:server:gang:smuggling:black-market-price',
    GANG_SMUGGLING_BLACK_MARKET_BOX_LOCK = 'soz-core:server:gang:smuggling:black-market-lock',
    GANG_SMUGGLING_BLACK_MARKET_BOX_TAKE = 'soz-core:server:gang:smuggling:black-market-box-take',
    GANG_SMUGGLING_CONTAINER_OPEN = 'soz-core:server:gang:smuggling:container-open',
    GANG_SMUGGLING_HARVEST_TAKE = 'soz-core:server:gang:smuggling:harvest-take',
    GANG_SMUGGLING_HARVEST_SIGNAL = 'soz-core:server:gang:smuggling:harvest-signal',
    GANG_SMUGGLING_TOBACCO_STIR = 'soz-core:server:gang:smuggling:tobacco-stir',
    GANG_SMUGGLING_TOBACCO_CHECK = 'soz-core:server:gang:smuggling:tobacco-check',
    GANG_SMUGGLING_TOBACCO_HARVEST = 'soz-core:server:gang:smuggling:tobacco-harvest',
    GANG_SMUGGLING_TOBACCO_DESTROY = 'soz-core:server:gang:smuggling:tobacco-destroy',
    GANG_SMUGGLING_ALCOHOL_DISTILLERY_SWITCH = 'soz-core:server:gang:smuggling:distillery-switch',
    GANG_SMUGGLING_ALCOHOL_DISTILLERY_DESTROY = 'soz-core:server:gang:smuggling:distillery-destroy',
    GANG_SMUGGLING_ALCOHOL_DISTILLERY_SETUP = 'soz-core:server:gang:smuggling:distillery-setup',
    GANG_SMUGGLING_EXPORT = 'soz-core:server:gang:smuggling:export',
    GANG_SMUGGLING_EXPORT_CLOSE = 'soz-core:server:gang:smuggling:export-close',
    GANG_SMUGGLING_SECRET_STASH_USE = 'soz-core:server:gang:smuggling:secret-stash-use',
    GANG_SMUGGLING_SECRET_STASH_REMOVE = 'soz-core:server:gang:smuggling:secret-stash-remove',
    GANG_SMUGGLING_PRINTER_USE = 'soz-core:server:gang:smuggling:printer-use',
    GANG_SMUGGLING_PRINTER_INSERT = 'soz-core:server:gang:smuggling:printer-insert',
    GANG_SMUGGLING_PRINTER_START = 'soz-core:server:gang:smuggling:printer-start',
    GANG_SMUGGLING_PRINTER_STOP = 'soz-core:server:gang:smuggling:printer-stop',
    GANG_SMUGGLING_PRINTER_CANCEL = 'soz-core:server:gang:smuggling:printer-cancel',
    GANG_SMUGGLING_PRINTER_RETRIEVE = 'soz-core:server:gang:smuggling:printer-retrieve',
    GANG_SMUGGLING_PRINTER_REMOVE = 'soz-core:server:gang:smuggling:printer-remove',
    GANG_SMUGGLING_MINE_PUT_C4 = 'soz-core:server:gang:smuggling:mine-putting-c4',
    GANG_SMUGGLING_GETTING_ORE = 'soz-core:server:gang:smuggling:mine-getting-ore',
    GANG_SMUGGLING_ZONE_EDIT_CREATE = 'soz-core:server:gang:smuggling:zone-edit:create',
    GANG_SMUGGLING_ZONE_EDIT_DELETE = 'soz-core:server:gang:smuggling:zone-edit:delete',
    GANG_SMUGGLING_ZONE_EDIT_UPDATE = 'soz-core:server:gang:smuggling:zone-edit:update',
    GANG_SMUGGLING_CONVOY_START = 'soz-core:server:gang:smuggling:convoy:start',
    GANG_SMUGGLING_MINE_ESTIMATION = 'soz-core:server:gang:smuggling:mine-estimation',
    GANG_SMUGGLING_MINE_ESTIMATION_FAILED = 'soz-core:server:gang:smuggling:mine-estimation-failed',
    GANG_SMUGGLING_ELECTRONIC_ESTIMATION = 'soz-core:server:gang:smuggling:electronic-estimation',
    GANG_SMUGGLING_ElECTRONIC_ESTIMATION_FAILED = 'soz-core:server:gang:smuggling:electronic-estimation-failed',
    GANG_SMUGGLING_DELETE_GUARD = 'soz-core:server:gang:smuggling:delete-guard',
    GANG_SMUGGLING_MINE_CLOSING_JEWELRY_RESALER = 'soz-core:server:gang:smuggling:delete-jewelry-resaler',
    GANG_SMUGGLING_MINE_CLOSING_ELECTRONIC_RESALER = 'soz-core:server:gang:smuggling:delete-electronic-resaler',
    GANG_SMUGGLING_ELECTRONIC_PUT_C4 = 'soz-core:server:gang:smuggling:electronic-putting-c4',
    GANG_SMUGGLING_GETTING_ELECTRONIC_PARTS = 'soz-core:server:gang:smuggling:getting-electronic-parts',
    GANG_SMUGGLING_CONTAINER_SIGNAL = 'soz-core:server:gang:smuggling:container-signal',

    GANG_CYBER_HACK_VEHICLE = 'soz-core:server:gang:cyber:hack-vehicle',
    GANG_CYBER_HACK_PED = 'soz-core:server:gang:cyber:hack-ped',
    GANG_CYBER_HACK_RADAR = 'soz-core:server:gang:cyber:hack-radar',
    GANG_CYBER_JAMMER_USE = 'soz-core:server:gang:cyber:jammer-use',
    GANG_CYBER_TRACKER_SETUP = 'soz-core:server:gang:cyber:tracker-setup',
    GANG_CYBER_RETRIEVE_DRONE = 'soz-core:server:gang:cyber:drone-retieve',
    GANG_CYBER_CRYPTO_PROP_USE = 'soz-core:server:gang:cyber:prop-use',
    GANG_CYBER_CRYPO_MAINTENANCE = 'soz-core:server:gang:cyber:maintenance',
    GANG_CYBER_CRYPTO_DESTROY = 'soz-core:server:gang:cyber:destroy',
    GANG_CYBER_CRYPTO_DESTROY_FDO = 'soz-core:server:gang:cyber:destroy-fdo',
    GANG_CYBER_CRYPTO_STEAL = 'soz-core:server:gang:cyber:steal',
    GANG_CYBER_CRYPTO_ALERT = 'soz-core:server:gang:cyber:alert',
    GANG_CYBER_EXIT_HEIST = 'soz-core:server:gang:cyber:heist-exit',
    GANG_CYBER_UNLOCK_HEIST = 'soz-core:server:gang:cyber:heist-unlock',
    GANG_CYBER_COMPUTER_HEIST = 'soz-core:server:gang:cyber:heist-computer',
    GANG_CYBER_COMPUTER_HEIST_INIT = 'soz-core:server:gang:cyber:heist-computer-init',
    GANG_CYBER_ZCOIN_HEIST = 'soz-core:server:gang:cyber:heist-computer-zcoin',
    GANG_CYBER_LEVER_HEIST = 'soz-core:server:gang:cyber:heist-lever',
    GANG_CYBER_STORAGE_HEIST = 'soz-core:server:gang:cyber:heist-storage',

    DOOR_ADD_UPDATE = 'soz-core:server:door:add-update',
    DOOR_DELETE = 'soz-core:server:door:delete',

    ADMIN_MAPPER_ADD_ZONE = 'soz-core:admin:mapper:add-zone',
    ADMIN_MAPPER_REMOVE_ZONE = 'soz-core:admin:mapper:remove-zone',
    ADMIN_MAPPER_RENAME_ZONE = 'soz-core:admin:mapper:rename-zone',
    ADMIN_MAPPER_UPDATE_ZONE = 'soz-core:admin:mapper:update-zone',

    WORLD_EVENT_STOP = 'soz-core:server:world-event:stop',
    WORLD_EVENT_SIGNAL_INVENTORY = 'soz-core:server:world-event:signal-inventory',
    WORLD_EVENT_UNLOCK_INVENTORY = 'soz-core:server:world-event:unlock-inventory',

    HALLOWEEN_VAMPIRE_GAME_KNOCK_PLAYER = 'soz-core:server:halloween:vampire-game-knock-player',
    HALLOWEEN_VAMPIRE_GAME_TAKE_OBJECTIVE_PART1 = 'soz-core:server:halloween:vampire-game-take-objective-part1',
    HALLOWEEN_VAMPIRE_GAME_TAKE_OBJECTIVE_PART2 = 'soz-core:server:halloween:vampire-game-take-objective-part2',
    HALLOWEEN_VAMPIRE_GAME_CONVERT_PLAYER = 'soz-core:server:halloween:vampire-game-convert-player',
    HALLOWEEN_VAMPIRE_GAME_PLAYER_KNOCKED_OUT = 'soz-core:server:halloween:vampire-game-player-knocked-out',
    HALLOWEEN_VAMPIRE_GAME_CANCEL_VAMPIRE_KNOCKOUT = 'soz-core:server:halloween:vampire-game-cancel-vampire-knockout',
    HALLOWEEN_VAMPIRE_NEW_PLAYER = 'soz-core:server:halloween:vampire-new-player',

    DRONE_NEW = 'soz-core:server:drone-new',
    DRONE_DELETE = 'soz-core:server:drone-delete',

    OILRIG_HEIST_THERMITE = 'soz-core:server:oilrig-heist:thermite',
    OILRIG_HEIST_PIPELINE_HARVEST = 'soz-core:server:oilrig-heist:pipeline-harvest',
    OILRIG_HEIST_ELEC = 'soz-core:server:oilrig-heist:elec',
    OILRIG_HEIST_COMPUTER = 'soz-core:server:oilrig-heist:computer',
    OILRIG_HEIST_PHONE = 'soz-core:server:oilrig-heist:phone',
    OILRIG_HEIST_FINALPHONE = 'soz-core:server:oilrig-heist:final-phone',
    OILRIG_HEIST_BOSS_COMPUTER = 'soz-core:server:oilrig-heist:boss-computer',
    OILRIG_HEIST_WC = 'soz-core:server:oilrig-heist:wc',
    OILRIG_HEIST_SHELF = 'soz-core:server:oilrig-heist:shelf',
    OILRIG_HEIST_BOSS_SAFE = 'soz-core:server:oilrig-heist:boss-safe',
    OILRIG_HEIST_PRINTER = 'soz-core:server:oilrig-heist:printer',
    OILRIG_HEIST_TANK = 'soz-core:server:oilrig-heist:tank',
    OILRIG_HEIST_INIT = 'soz-core:server:oilrig-heist:init',
    OILRIG_HEIST_CAMERA_SPOTTED = 'soz-core:server:oilrig-heist:camera-spotted',
    OILRIG_HEIST_STOP_ALARM = 'soz-core:server:oilrig-heist:alarm-stop',

    PLAYER_MORTAL_TP = 'soz-core:server:player:mortal-tp',

    GIFT_TOSS_COIN = 'soz-core:server:gift:toss-coin',
    GIFT_OPEN_GIFT = 'soz-core:server:gift:open-gift',
    GIFT_GIVE_ZRT_BLIZZARD = 'soz-core:server:gift:give-zrt-blizzard',
}
