import { ShopConfig } from '../shop';

export const BossShop: (ShopConfig & { job: string })[] = [
    {
        name: 'pawl',
        job: 'pawl',
        zone: {
            center: [-538.07, 5304.91, 76.37],
            length: 0.55,
            width: 0.65,
            heading: 340,
            minZ: 75.37,
            maxZ: 77.37,
        },
        targets: [],
        products: [{ id: 'weapon_hatchet', type: 'weapon', price: 100 }],
    },
    {
        name: 'stonk',
        job: 'cash-transfer',
        zone: {
            center: [-15.5, -708.83, 45.02],
            length: 0.6,
            width: 2.6,
            heading: 25,
            minZ: 45.02,
            maxZ: 48.02,
        },
        targets: [],
        products: [
            { id: 'outfit', type: 'item', metadata: { label: 'STONK', type: 'stonk' }, price: 100 },
            { id: 'armor', type: 'item', metadata: { label: 'STONK', type: 'stonk' }, price: 150 },
            { id: 'weapon_pistol', type: 'weapon', price: 300 },
            { id: 'pistol_ammo', type: 'weapon_ammo', price: 10 },
        ],
    },
    {
        name: 'news',
        job: 'news',
        zone: {
            center: [-567.59, -922.01, 28.82],
            length: 0.4,
            width: 2.8,
            heading: 0,
            minZ: 27.82,
            maxZ: 30.82,
        },
        targets: [],
        products: [
            { id: 'armor', type: 'item', metadata: { label: 'Twitch News', type: 'news' }, price: 150 },
            { id: 'n_fix_camera', type: 'item', price: 250 },
            { id: 'n_fix_greenscreen', type: 'item', price: 150 },
            { id: 'n_fix_light', type: 'item', price: 80 },
            { id: 'n_fix_mic', type: 'item', price: 60 },
            { id: 'n_mic', type: 'item', price: 50 },
            { id: 'n_camera', type: 'item', price: 250 },
            { id: 'n_bmic', type: 'item', price: 100 },
        ],
    },
    {
        name: 'food',
        job: 'food',
        zone: {
            center: [-1881.68, 2058.03, 140.0],
            length: 0.8,
            width: 2.15,
            heading: 70,
            minZ: 140.0,
            maxZ: 143.0,
        },
        targets: [],
        products: [
            { id: 'weapon_machete', type: 'weapon', price: 45 },
            { id: 'weapon_musket', type: 'weapon', price: 125 },
            { id: 'shotgun_ammo', type: 'weapon_ammo', price: 10 },
        ],
    },
    {
        name: 'bennys',
        job: 'bennys',
        zone: {
            center: [-216.94, -1318.97, 30.89],
            length: 0.8,
            width: 1.6,
            heading: 90,
            minZ: 29.89,
            maxZ: 32.89,
        },
        targets: [],
        products: [
            { id: 'repairkit', type: 'item', price: 50 },
            { id: 'cleaningkit', type: 'item', price: 20 },
            { id: 'diagnostic_pad', type: 'item', price: 260 },
            { id: 'oil_jerrycan', type: 'item', price: 20 },
        ],
    },
    {
        name: 'lsmc',
        job: 'lsmc',
        zone: {
            center: [309.79, -1417.49, 32.51],
            length: 0.6,
            width: 1.25,
            heading: 50,
            minZ: 31.51,
            maxZ: 32.51,
        },
        targets: [],
        products: [
            { id: 'outfit', type: 'item', metadata: { label: 'LSMC', type: 'lsmc' }, price: 100 },
            { id: 'armor', type: 'item', metadata: { label: 'LSMC', type: 'lsmc' }, price: 150 },
            { id: 'antibiotic', type: 'item', price: 15 },
            { id: 'painkiller', type: 'item', price: 15 },
            { id: 'defibrillator', type: 'item', price: 25 },
            { id: 'empty_bloodbag', type: 'item', price: 5 },
            { id: 'firstaid', type: 'item', price: 10 },
            { id: 'pommade', type: 'item', price: 15 },
            { id: 'tissue', type: 'item', price: 5 },
            { id: 'weapon_fireextinguisher', type: 'weapon', metadata: { ammo: 400 }, price: 5 },
            { id: 'walkstick', type: 'item', price: 15 },
            { id: 'poumon', type: 'item', price: 2000 },
            { id: 'rein', type: 'item', price: 2000 },
            { id: 'foie', type: 'item', price: 2000 },
            { id: 'flask_pee_empty', type: 'item', price: 15 },
            { id: 'flask_blood_empty', type: 'item', price: 15 },
            { id: 'antidepressant', type: 'item', price: 15 },
            { id: 'health_book', type: 'item', price: 30 },
            { id: 'antiacide', type: 'item', price: 15 },
        ],
    },
];
