import { Society } from '@typings/society';

export const SocietyContactsState: Society[] = [
    {
        id: 1,
        display: 'FIB',
        number: '555-FBI',
        avatar: 'media/society_icon/fbi.webp',
        type: 'Entreprise Publique',
        order: 7,
    },
    {
        id: 2,
        display: 'LSPD',
        number: '555-LSPD',
        avatar: 'media/society_icon/lspd.webp',
        type: 'Entreprise Publique',
        order: 1,
    },
    {
        id: 3,
        display: 'LSMC',
        number: '555-LSMC',
        avatar: 'media/society_icon/lsmc.webp',
        type: 'Entreprise Publique',
        order: 0,
    },
    {
        id: 4,
        display: 'BCSO',
        number: '555-BCSO',
        avatar: 'media/society_icon/bcso.webp',
        type: 'Entreprise Publique',
        order: 2,
    },
    {
        id: 5,
        display: 'Twitch News',
        number: '555-NEWS',
        avatar: 'media/society_icon/news.webp',
        type: 'Entreprise Privée',
    },
    {
        id: 6,
        display: 'BlueBird',
        number: '555-BLUEBIRD',
        avatar: 'media/society_icon/garbage.webp',
        type: 'Entreprise Privée',
    },
    {
        id: 7,
        display: 'Carl Jr Services',
        number: '555-CARLJR',
        avatar: 'media/society_icon/taxi.webp',
        type: 'Entreprise Privée',
    },
    {
        id: 8,
        display: 'Château Marius',
        number: '555-MARIUS',
        avatar: 'media/society_icon/food.webp',
        type: 'Entreprise Privée',
    },
    {
        id: 9,
        display: 'Michel Transport Petrol',
        number: '555-MTP',
        avatar: 'media/society_icon/oil.webp',
        type: 'Entreprise Privée',
    },
    {
        id: 10,
        display: 'STONK Security',
        number: '555-STONK',
        avatar: 'media/society_icon/cash-transfer.webp',
        type: 'Entreprise Publique',
        order: 4,
    },
    {
        id: 11,
        display: 'New Gahray',
        number: '555-NEWGAHRAY',
        avatar: 'media/society_icon/bennys.webp',
        type: 'Entreprise Privée',
    },
    {
        id: 12,
        display: 'UPW',
        number: '555-UPW',
        avatar: 'media/society_icon/upw.webp',
        type: 'Entreprise Privée',
    },
    {
        id: 13,
        display: 'PAWL',
        number: '555-PAWL',
        avatar: 'media/society_icon/pawl.webp',
        type: 'Entreprise Privée',
    },
    {
        id: 14,
        display: 'Bahama Unicorn',
        number: '555-BAUN',
        avatar: 'media/society_icon/baun.webp',
        type: 'Entreprise Privée',
    },
    /*
    {
        id: 15,
        display: 'Fight For Style',
        number: '555-FFS',
        avatar: 'media/society_icon/ffs.webp',
        type: 'Entreprise Privée',
    },
    */
    {
        id: 16,
        display: 'Mandatory',
        number: '555-MDR',
        avatar: 'media/society_icon/mdr.webp',
        type: 'Entreprise Publique',
        order: 5,
    },
    {
        id: 17,
        display: "Force de l'ordre",
        number: '555-POLICE',
        avatar: 'media/society_icon/fdo.webp',
        type: 'Urgence',
    },
    {
        id: 18,
        display: 'SASP',
        number: '555-SASP',
        avatar: 'media/society_icon/sasp.webp',
        type: 'Entreprise Publique',
        order: 3,
    },
    {
        id: 19,
        display: 'Gouvernement',
        number: '555-GOUV',
        avatar: 'media/society_icon/gouv.webp',
        type: 'Entreprise Publique',
        order: 6,
    },
    /*
    {
        id: 20,
        display: 'Ferme de Fou',
        number: '555-FDF',
        avatar: 'media/society_icon/fdf.webp',
        type: 'Entreprise Privée',
    },
    */
    {
        id: 21,
        display: 'YouNews',
        number: '555-YOUN',
        avatar: 'media/society_icon/you-news.webp',
        type: 'Entreprise Privée',
    },
    {
        id: 22,
        display: 'DeMetal Company',
        number: '555-DMC',
        avatar: 'media/society_icon/dmc.webp',
        type: 'Entreprise Privée',
    },
];
