name: "Check Typescript"

on:
    pull_request: ~

jobs:
    check-typescript:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                resource: ["soz-core", "soz-phone"]

        steps:
            - uses: actions/checkout@v3
            - uses: bahmutov/npm-install@v1
              with:
                  working-directory: "resources/[soz]/${{ matrix.resource }}"
            - name: "check-typescript"
              working-directory: "resources/[soz]/${{ matrix.resource }}"
              run: yarn run tsc -p tsconfig.json --noEmit
